### ISSUE TITLE
Label Referencing Problem

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#1000]
After reading some code, I have some questions being listed below:

1. `Label` should not be directly used to make references, so we don't want Label to be the instance of `HasLabel` and `Referable`? But now the `label` of `GenDef` is used to make references in SSP case. Like https://github.com/JacquesCarette/Drasil/blob/3d5c8e5fe924ddc0010d51347abcc50526431e5d/code/drasil-example/Drasil/SSP/DataDefs.hs#L366

So I don't think that only making `Section` has the label still doesn't help to remove `Referable` class for 'label'. 

2. As the last comment in #235, does that mean that
Chunks are "Referable" "HasLabel";
We were expecting "HasLabel" would help Chunks to be somehow easily make all chunks be reached to make references in anywhere, when we first designed `Label`. But it turns out that we finally make `Label` "Referable" and "HasLabel" to make references happen. And this implementation is kind of bad, since "HasLabel" and "Referable" doesn't make sense for `Label`.

**Comment by halonazhao** [comment]
Didn't realize this is the No.1000 issue. Should have left this spot for you @JacquesCarette.

**Comment by JacquesCarette** [comment]
For a true geek, the next nice round number is 1024... 😈 

1. Correct. We need to use the 'object' itself (and a label) to make a reference. We might need more than just `makeRef` for this purpose.  We need to find and fix all the places where we make references directly from labels.
2. There is no explicit question here...  Yes, many Chunks should be `Referable` and also `HasLabel`. Which means that we need to have a `Label` **inside** those chunks.  And them `makeRef` on those chunks would work as is.

**Comment by samm82** [comment]
When I switched over to using Labels instead of hardcoding in the examples, sometimes import cycles arose (ie. an assumption references a gen def and vice versa), so I made a label in a Labels.hs file and had assumptions and gen defs both import it: assumptions could then reference the gen def by importing Labels, and gen defs would import Labels and Assumptions to use the label and reference the assumption.

I'm sure this is a bit of a hack and can be reworked - just explaining my reasoning for doing it.

**Comment by halonazhao** [comment]
Wait. Which part is the 'desired' design? I understand that labels should be created first and plug them into each chunk. But the thing is that we don't use label directly making references. I just change all the references using labels back to hard-coded version, and the class `Referable` can be removed now. I am not sure whether we want to rework here. 38f70ef656a86fae3fbbe224118930b9798324f7 this version has logs, but built successfully.
But if we change back to use actually chunks doing references, then the import cycle isn't be solved since it didn't get help from labels. I am kind of confused here. @JacquesCarette

**Comment by JacquesCarette** [comment]
The desired design is to first create labels "standalone", in a Labels.hs file (to avoid cycles), and then attach those labels to the correct object. As you said.

The problem is that we shouldn't call `makeRef` on a label. `makeRef` is built to grab the label from an object that contains one.  We should create a `makeRefFromLabel` which takes a `Label` as input, and makes a reference from that.

`IsLabel` and `HasLabel` are different, and should remain so.

**Comment by halonazhao** [comment]
I noticed that the types for `LikelyChanges`, `UnLikelyChanges` and `requirements` were changed from `LabledContent` to `ConceptInstance`, which led `changes` and `requirements` to be un-referable and without labels. May this part need further design? @JacquesCarette

**Comment by Mornix** [comment]
`ConceptInstance` should be adopting `Label` very soon.

**Comment by halonazhao** [comment]
Thanks!

**Comment by JacquesCarette** [comment]
All of this has been resolved.
