### ISSUE TITLE
HTML Table of Contents

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#1018]
I noticed that the HTML versions of the SRS don't include a table of contents. It'd probably be a useful feature for anyone that wants to review the documents.

I don't think it would be a very difficult feature to add, particularly since we can traverse the DocDesc and know exactly which sections are included.

**Comment by JacquesCarette** [comment]
@szymczdm you are right that this would be useful, but how likely is it that you'll implement it?

**Comment by szymczdm** [comment]
As of now, probably not very likely.

**Comment by Nathaniel-Hu** [comment]
@JacquesCarette and @smiths,
I have modified/updated the stable files to include a basic hyperlinked Table of Contents section (see link below for the GlassBR_SRS.html file, for example). Are there any specific changes/improvements to the current formatting of the Table of Contents section that you would like me to make?

Sample HTML file with basic hyperlinked ToC section: [GlassBR_SRS](https://github.com/JacquesCarette/Drasil/blob/Issue%231018_HTMLToC/code/stable/glassbr/Website/GlassBR_SRS.html)

**Comment by smiths** [comment]
Nice!  @JacquesCarette will have to comment on how you did it, but as far as the result goes, the ToC looks great to me.  This is a really nice improvement for the html version of the SRS.  I frequently consult our html examples, so I'll directly benefit from the time saving hyperlinks.  :-)

**Comment by Nathaniel-Hu** [comment]
The work done so far that contributes to this issue can be found in branch Issue#1018_HTMLToC.

**Comment by Ant13731** [comment]
Putting [this comment](https://github.com/JacquesCarette/Drasil/commit/60de32a33db0eaec1e568c70a5f4242058578a40#r40770199) here as a note. I'm not sure how Multiplates work in Drasil, but I'll probably take a go at it once this issue is merged/completed.

@smiths, for [this comment](https://github.com/JacquesCarette/Drasil/commit/60de32a33db0eaec1e568c70a5f4242058578a40#r40758691), when we choose to generate the table of contents, should it use its own LaTeX table of contents, or should it be generated from drasil as in Nathaniel's [commit](https://github.com/JacquesCarette/Drasil/commit/036a6a24a9460eebadef673b84b5e38146c2dca6).

I currently have a working version (except for the LaTeX table of contents stuff), so I'll push it and link it below. Let me know what you think (it's not implemented for all examples yet either).

**Comment by smiths** [comment]
@Ant13731, it makes sense to me to use the LaTeX commands for generating a table of contents, instead of generating our own LaTeX code for this.  Using LaTeX is the "LaTeX" way of doing this.  Moreover, it is likely to look better.  :smile:

I've looked at a few of your generated html SRS tables of contents.  They look great!
