### ISSUE TITLE
Problem with generation of description field for Data Definitions.

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#104]
Going through the examples, I noticed that the data definition descriptions were not being updated properly.

The main issue is that Extract.hs' "vars" helper function can only return chunks that are instances of NamedIdea & SymbolForm. At least for this pass, the DD descriptions need the (verbose) description of their terms, which means we need to get the 'defn' from Concepts.

Hopefully what I said above makes sense, but to simplify: we definitely have "term", but not necessarily "defn" for the terms in the descriptions of the Data Definitions. We need to ensure we have "defn".

Now we have a few options that I can see, but I'm open to other suggestions: 

1. Use "term" instead of "defn" and ensure all of the terms are properly updated (most are currently wrong, having "id" for "term" or some such thing, but that can be fixed fairly easily, if a bit tediously).

2. Change the type class constraints so that we know for sure we have "Concepts". This involves changes to Expr itself (the expressions can point to chunks), but I'm not sure if we want to force this on the users as of yet. If they can have terms without definitions, I think they should be allowed to use those terms (provided they have symbols) in equations/expressions.

3. Completely overhaul how Data Definitions work. However, I think being able to look up the dependencies of a chunk from the defining equation is something we definitely want to keep. That would basically force us to go with option 2 instead.

Option 1 is quick and dirty, it'll get things working very quickly. Option 2 makes us burden the user a bit more by forcing them to only use Concepts in Expr. Option 3 seems like the wrong way to go, since it would (most likely) mean taking a step or two backwards without any real promise of being able to get back what was lost.

@JacquesCarette could you take a look at how things are currently being done (w.r.t. Extract.hs, Expr, and Data Definitions) and weigh in on this?

**Comment by JacquesCarette** [comment]
Yes, definitely.  Not right now, but I'll do it tomorrow morning.

My current thinking is along the lines of a mixture of options 2 and 3 (not 'complete' overhaul of anything though).  But I need to look more deeply into the details to make sure I can make workable suggestions.

**Comment by szymczdm** [comment]
Alrighty, sounds good!

**Comment by JacquesCarette** [comment]
Didn't quite make the timelines that I thought I would...

Ok, this problem is quite interesting.  And rather 'deep'.

Part of the problem is that `C` in `Expr` only promises a `NamedIdea` and a `SymbolForm`.  So if we need a `Concept`, we're out of luck.

Two solutions come to mind:

1. change `Expr` to have more cases (than just `C`) for encoding dictionaries
2. change how we access "attached information"

Option 1 is more type-safe.  But does not feel scalable.  Well, there are fancy tricks we could pull, but I think that isn't the best route to explore.  With option 2, what we ought to do is to take out 'database' approach more seriously -- and our `id`s will come in handy here.  And quite possibly help simplify `Expr` too.

The idea would be to build "databases" of known information -- such as that associated to `Concept`.  In Haskell parlance, a `Map.Map id Concept`.  When building a data definition, we would extract all the `NamedIdea` ids (using the current `var`) and look them in that database.  For those where we success, we print out the definition (otherwise "(concept not defined)" ?).

As I expected, this is a middle ground between your options 2 and 3.

**Comment by szymczdm** [comment]
#67 is closely tied to this as well, since that solution will also likely involve the "database" approach.

**Comment by njericha** [comment]
> JacquesCarette commented on Jan 8

> Part of the problem is that C in Expr only promises a NamedIdea and a SymbolForm. So if we need a Concept, we're out of luck.

Maybe #365 will be the issue to close this

**Comment by JacquesCarette** [comment]
@njericha Yes.

**Comment by szymczdm** [comment]
Related to #256

**Comment by szymczdm** [comment]
With the database approach implemented and the change to DDs in general (now using Document Language) this should be resolved. There's no easy way to check it yet, however, since we still need to switch to using Document Language for all of the examples' DD generation.

There's also the chance that we've changed our documents enough (since the summer) that this issue is no longer relevant, so I'm going to close this issue. The meat of this issue has been addressed and if it turns out something isn't being rendered properly we can open this back up or create a new issue.
