### ISSUE TITLE
Populate ConceptDomains to Chunks

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#1042]
As many concepts need to be classified into different Concept Domains and we are at a stage where the domain information is needed, we should populate domains to proper chunks. 
Should I start with the ideas from the comment from @JacquesCarette in #698?

**Comment by JacquesCarette** [comment]
Yes please. But actually, just do the ones you need to deal with labeling/referencing.

In other words, when referencing a chunk (such as an assumption, requirement, etc), its concept domain should not be the empty list, because we will use the abbreviation of the CIs in the concept domain to generate the labels. @Mornix should be aware of this design as well.

**Comment by halonazhao** [comment]
Most of the work related to this issue was done. This issue can be closed.
