### ISSUE TITLE
Change in notation in SSP

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#1083]
In change cbbeb75ba, I removed { } from being special. SSP used these inside the notation for one particular symbol.  That is rather odd notation...  It needs reconsidered.

**Comment by smiths** [comment]
Yes, the  { } do lead to an odd notation.  The idea was that there are a set of coordinates.  We could probably re-work it to be the more traditional sequence of coordinates.  I'll keep this in mind when I'm doing a detailed review of the latest revision by @bmaclach.

**Comment by bmaclach** [comment]
There are many places where we used this notation for a set of coordinates in the manual version of SSP (for the set of slope coordinates, the set of water table coordinates, the set of slip surface coordinates, and the set of critical slip surface). I would agree that representing them as a sequence would be better, especially since it is feasible and even likely that there would be repeats somewhere in the sequence, so sets are really not even an appropriate choice. Should I update all of the coordinate `Unital`s to use vector symbols, at least for the short term?

**Comment by smiths** [comment]
@bmaclach, switching to vector symbols seems like the right move.  Yes, go ahead and do that.  :smile:

**Comment by bmaclach** [comment]
With the merge of #1222, all unitals that were really sequences of values for each slice have been switched to use vector notation. @smiths I think this issue can be closed?

**Comment by smiths** [comment]
Yes @bmaclach, I agree that this issue can be closed.
