### ISSUE TITLE
Why do we have 3 symbol maps?

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#1087]
(this is different than #268 which is closed)

Here are the definitions of the 3 symbols maps used in GlassBR (first argument of `cdb` and `_quants`):
https://github.com/JacquesCarette/Drasil/blob/389723cb501bddb0c97a915c571b6cac01810b07/code/drasil-example/Drasil/GlassBR/Body.hs#L79-L89
https://github.com/JacquesCarette/Drasil/blob/389723cb501bddb0c97a915c571b6cac01810b07/code/drasil-example/Drasil/GlassBR/Body.hs#L124-L128
https://github.com/JacquesCarette/Drasil/blob/389723cb501bddb0c97a915c571b6cac01810b07/code/drasil-example/Drasil/GlassBR/Body.hs#L204-L228

This uses `this_symbols` and `symbolsForTable` (and `[]`!!!) which turn out to be the exact exports of
https://github.com/JacquesCarette/Drasil/blob/389723cb501bddb0c97a915c571b6cac01810b07/code/drasil-example/Drasil/GlassBR/Body.hs#L69

So we go there and see
https://github.com/JacquesCarette/Drasil/blob/389723cb501bddb0c97a915c571b6cac01810b07/code/drasil-example/Drasil/GlassBR/Symbols.hs#L11-L20

These are close, but not quite the same.  This is weird. [Also, clearly `useddb`'s symbol table is not actually "used" anywhere...].  In this case (but the symptoms vary a bit by example), the Instance Models are somehow in one and not the other.

**Comment by halonazhao** [comment]
1. I would like to explain the `usedDB` a bit. The current `usedDB` actually means the DB of everything which appears in one case. Versus another chunkDB, the first one, means all the pre-stored chunks or the knowledge but not necessary shown in the case. 

2. The glassBR did not implement the collect symbols because, as shown in `symbol.hs` file, all the symbols orginazed in type `QuantityDict`(without definition) instead of `DefinedQuantityDict`(with definition). So it doesn't support the collecting constructor to collect `DefiniedQuantityDict`. But the constructor is in place. Once the symbols are reorganized for GlassBR, that part would work.

Just some explaination related to this issue. Hope this would help.

**Comment by JacquesCarette** [comment]
1. So the "everything" DB corresponds to the 'hand collected' knowledge that the author of the case study things might be relevant? [Might be interesting to get a report of those things which do not end up in `usedDB`, as that might point to an oversight on the authors' part]

2. So is this a "bug" in GlassBR which makes it different than the others? If so, we should file an issue to track that.

**Comment by balacij** [comment]
To follow up with this ticket, switching the one usage of "_usedinfodb" to "_sysinfodb", it appears that it adds a new extra terms in the [Abbreviations and Acronyms](https://jacquescarette.github.io/Drasil/examples/nopcm/SRS/srs/NoPCM_SRS.html#Sec:TAbbAcc) table:
![Screenshot from 2022-05-13 00-17-24](https://user-images.githubusercontent.com/1627302/168210431-31e01032-a8f6-4b72-9ecd-effb6b65750a.png)

I suppose this is mostly a problem of it not being able to determine which chunks are ending up used. Do we already have something that detects this in other usecases?

**Comment by balacij** [comment]
I think we can safely close this ticket in favour of #1661, so as long as we get back soon to the discussion in https://github.com/JacquesCarette/Drasil/issues/1661#issuecomment-1021450950 .
