### ISSUE TITLE
Constants in generated code are not stored in input data structure

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1133]
I noticed that in our manually-written source code for GlassBR, we store constants in the input data structure, whereas in Drasil we do not store constants in the input data structure and instead just paste in their value wherever they are used. For example, `td` and `m` are constants with values of 3 and 7, respectively. In the manual version of GlassBR, they are used like so:
`params.ldf = pow((params.td / 60.0), (params.m / 16.0))`

In the generated code from Drasil, the same line is:
`inParams.LDF = (3 / 60) ** (7 / 16)`

Was this an intentional decision, or something that needs to be fixed? We do have code for generating a "Constants" module, but it is commented out.

**Comment by JacquesCarette** [comment]
This should be a **design choice** that the person requesting code generation makes. So we should be able to output either.

**Comment by smiths** [comment]
I agree.  When Steven generated the code, his goal was to make it work.  We weren't really worried at the time about the bigger picture.  Although td and m are currently constants, it is a likely change (if I remember the SRS correctly) that they could be variable.  It is also a design choice to handle all of the "inputs" through the params structure.  Because it is easier to verify that the requirements were correctly implemented, I prefer the manual version, if we need to make a single choice at the moment.

**Comment by bmaclach** [comment]
Created an issue for capturing how to handle constants as a design choice (#1560). Closing this issue since my question was answered.
