### ISSUE TITLE
Using custom text as an internal reference link

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1142]
Some internal references throughout our example SRSs duplicate information. For example, here's a line from the SRS:
![image](https://user-images.githubusercontent.com/18634568/53579183-1c98bf00-3b47-11e9-9898-2670febd5485.png)
The phrases "goal statements", "theoretical models", and "instance models" are repeated. Ideally, we would want this to say "The goal statements are refined to..." where the phrase "goal statements" itself is an internal reference to the corresponding section. This means we need a way to have custom text get rendered as a link.

The text that gets rendered as a link is passed as a `ShortName` to a `Reference` in Drasil. Thus, if we want to use custom text for the reference text, we need to convert from `String` to `ShortName` or even from `Sentence` to `String` to `ShortName` (though the need for a `Sentence` to `String` conversion is a sign that the `Sentence` may have been 'premature'). We need to think about the design and how best to achieve this functionality.

**Comment by Ant13731** [comment]
I think this is also relevant to #2489, so I'm going to assign myself as well.

**Comment by Ant13731** [comment]
I've been thinking about this for a bit, and with the new Ref constructor and shortname formation, I think this should be doable. However, I think the way that shortnames are handled in drasil may contribute to this problem. 
Some ideas I have are:
- Since we are looking up references by `UID` now, there is no real reason for the `Reference` itself to hold a `shortname` (or even `RefInfo` for that matter) because we want to be able to change the display information on a per-use basis rather than at the central database. In other words, I think the `Ref` constructor in `Sentence` should hold the display name (as a `ShortName` or a `Sentence` and additional display info (as `RefInfo`).
- We could keep `Reference` the same, and modify `RefInfo` so that it could take a display name (by adding something like a `RefDisplay` constructor). The default format would be the `ShortName` within the `Reference`, but if `RefInfo` contains something other than `None`, we could override the `ShortName`. 

The second idea could probably be implemented in smaller parts, but the first could be more concise. @JacquesCarette, what do you think?

**Comment by JacquesCarette** [comment]
Two thoughts: 1. this seems excellent, and 2. there's too much implicit information not spelled out for me to go from 'seems' to 'is'.

I'd like to first really understand what the problem is - both what the user-visible desired functionality should be, what the technical hurdles are, and what the proposed solution is. I've got decent guesses on all of them from the information in this issue, but I'd like to my sure my guesses are the same as your thoughts!  So if you could spell that out? The original issue was pretty good, so using it as a model to show what the end result would be, and how to get there, would be a really good way to explain/illustrate it all.

**Comment by Ant13731** [comment]
Okay, sounds good.

So I think the problem listed in this issue is that we should be able to use in-text references (I'll call it a display name), similar to those on the Drasil website for getting the [haddock documentation](https://jacquescarette.github.io/Drasil/) and analysis file (this sentence itself is an example of that using github's version of in-text referencing). This way, it's easier to read the document (no unneeded labels to get in the way). So for the original issue, the example would be: The [goal statements](https://jacquescarette.github.io/Drasil/) are refined ... (where goal statements links to the goal statements section).

With the old `Ref` constructor (that took in a `Reference` to make a `Sentence`), this would've been really tricky, as a new and different reference would be needed each time a different display name needed to be used. This should be way more doable now since all the References are deferred to the chunk database and only used when needed.

The trick is, there should be a way to add a surface level display name to a `Reference`. This would be a similar fix to the way RefInfo handles page numbers. It should become part of the Ref constructor and almost separated from the actual Reference in a sense. The purpose of this would be to allow the same Reference to be used with different display names at different times within a document.

The two ideas I proposed to go about this are (in more detail):
1. The Reference type would not hold the shortname or a RefInfo. Since those two types are supposed to be surface-level, they don't really encode any useful information needed for the actual reference itself. This way, we can determine the display name and any additional information at the time of referring to the reference. So in Drasil language, the example above would look something like:
```Haskell
S "The" +:+ makeRef2S goalStmt (S "goal statements") None +:+ S "are refined ..."
```
and display as: 
The [goal statements](https://jacquescarette.github.io/Drasil) are refined...

The `Ref` constructor would contain these two pieces of information and feed them to the drasil printer when the `Sentence` turns into a `Spec`.

2. Reference continues to hold a shortname and RefInfo, but only as a default. If no extra information is given at the time of referencing, the drasil database will hold the default shortname and RefInfo. The same example shown here:
```Haskell
S "The (" :+: makeRef2S goalStmt :+: S ") are refined ..."
S "The" +:+ makeRef2SDisplay goalStmt (S "goal statements") None +:+ S "are refined ..."
```
would display as: 
The goal statements [(Section: Goal Statements)](https://jacquescarette.github.io/Drasil) are refined...
The [goal statements](https://jacquescarette.github.io/Drasil) are refined...

So the function used would determine whether the given display name overrides the internal shortname for that Reference.

3. A third option that I think might be even better is to combine the two: References still have a default shortname, but no default RefInfo. I'm not exactly sure how this one would work on the printer side of things, but I'd imagine it wouldn't be that much different from the other two in terms of work.

I initially thought the first version was the best, but now I can see that the second one has its merit, since sometimes we do want a separate reference label for a section, not an in-text reference. The third one, not so much, since it may add a layer of unwanted complexity.

**Comment by JacquesCarette** [comment]
Very good - all 3 parts (problem statement, analysis, suggested designs).

Let's go with solution 2. This gives us the most flexibility. Also, we can have some smart constructors that elide the repeated parts (like that `None` in the raw `makeRef2SDisplay`). 

`makeRef2S` is not a great name either. It's kind of short for "make a reference into a sentence". There might be a less operational and more mnemonic name for what this does - do propose alternatives if some come to mind!

**Comment by Ant13731** [comment]
I'm just getting started implementing this, and I noticed that `makeRef2` is exactly the same as `makeCite`, and `makeRef2S` is the same as `makeCiteS`. I think they may have been different functions before `Ref` started using `UIDs`, but now the only difference is the type constraint:
```Haskell
makeRef2 :: (Referable l, HasShortName l) => l -> Reference
makeRef2 l = Reference (l ^. uid) (renderRef l) (shortname l) None
makeCite :: Citation -> Reference
makeCite l = Reference (l ^. uid) (renderRef l) (shortname l) None
```
Should I remove `makeCite`, or should these functions stay separate?

**Comment by JacquesCarette** [comment]
One reason it might make sense to keep `makeCite` is that, in the code, it makes it clearer that one is dealing with a citation.

Note that the `2` suffix is an artifact of history, and can be removed.

So, thinking about it some more, I think that calling `makeCite` and `makeRef2` both `ref` (assuming it's free) might be a good idea!  `refS` for the `S` version (though we should later see if that's actually needed).

**Comment by Ant13731** [comment]
I think ref is free except for when its used in an argument of another function. But those can be changed to something else (maybe reference, refnce, or just r?).

For a reference with a display name, and displayname with info, would refSD and refSDI be good respectively?

**Comment by JacquesCarette** [comment]
`r` or `rf` could do for the local name.

Hmm, maybe `namedRef` and `namedComplexRef` ?

**Comment by Ant13731** [comment]
Another thing I just realized, `ref` would be exactly the same as `rw` (the function used to convert everything into a reference before going into the chunk database). But now that `ref` is a little more general, I think I could get rid of `rw`?

**Comment by Ant13731** [comment]
Another question, do we want to allow Citation references to have a different display name from its reference address? I'm running into some troubles with the tex and html printers regarding this. 

The tex command for `\cite` only takes in a non-linked sentence and a reference address. The reference address is then automatically used as the display name (it doesn't even use the reference's internal short name). 

If we just override any given display name with the reference address (only for Citations), I think it would be much easier getting everything to work. I'm not even sure if we want to allow references to be given a different display name?

**Comment by JacquesCarette** [comment]
Re: `rw` - seems like a good idea.

I'm not quite understanding the problem with `\cite`. Can you expand your description, with an example? This is an important design to get right, so I don't want to rush to a fix. There was quite a lot of work done on referencing, because there are multiple concepts around (i.e. what each name is used for), and we don't want to much with that too much.

**Comment by Ant13731** [comment]
Ah okay, I'm looking at the tex pdf again for some examples and I think I was wrong in the above comments. I didn't realize the tex files cite things differently than the html ones since latex generates its own footnote style references for citations.

I think the problem I was originally having was that the `Spec` version of `Ref` only has three fields: the LinkType, the reference address, and a display name. This works for the most part, but when making a citation, the third field is not actually used as a display name (like the other two types of references). Instead, that is where the extra information (like page numbers and equation numbers) go. This means that for `Internal` and `External` references, the display name itself is hyperlinked, while a `Cite2` reference does not link that extra text (it displays it as normal). For reference, here is the definition of Ref:
```Haskell
data Spec = Ref LinkType String Spec
```
This works well for latex files since they usually use a footnotes style of citation (with numbers) and a bibliography at the end of the document. However, HTML files don't really do this. They instead use the reference address as the display name and then add the extra reference information afterwords (as if it were a normal hyperlink to the references section of the webpage).

For HTML files, the first Cite2 pattern uses reflink, but with the reference address as the display name. The second pattern match still uses the reference address as the display name but also takes in the Spec as extra information (which will not be hyperlinked):
```Haskell
pSpec (Ref Internal r a)      = reflink     r $ pSpec a
pSpec (Ref Cite2    r EmptyS) = reflink     r $ text r -- no difference for citations?
pSpec (Ref Cite2    r a)      = reflinkInfo r (text r) (pSpec a) -- no difference for citations?
pSpec (Ref External r a)      = reflinkURI  r $ pSpec a
```
On the other hand, TeX files can't take a display name for Cite2. It automatically uses numbers for referencing (as if they were footnotes), so the extra information is just passed as normal text from there that is then given to the cite command:
```Haskell
spec (Ref Internal r sn) = snref r (spec sn)
spec (Ref Cite2    r i)  = cite r (info i)
  where
    info EmptyS = Nothing
    info x      = Just (spec x)
spec (Ref External r sn) = externalref r (spec sn)
```
My first idea to alleviate this (at least for HTML files) was to have another Spec field for the Ref constructor. The first Spec would be the display name, the second for referencing information. This way, the two would remain separate so that we could put a link on one of them but not the other. But now that I see how citations work in TeX, I'm not sure if this is the right idea.

**Comment by JacquesCarette** [comment]
Note that there are also different latex styles, some of which will not use numbers but Author:Year instead.

Furthermore, there are additional pieces of information "around":
1. for the latex source, we want to also control what the symbolic label will be, since we want to be able to read those too
2. for the html source, we want to control the internal names of the anchors related to links too

So that's why referencing is so complicated!

**Comment by Ant13731** [comment]
I think number 1 shouldn't be difficult except for references that use the `\cite` command since latex would use its own system (be it numbers or Author:Year style). The `\hyperref` command seems to accept both a reference address and a shortname already. Currently, I'm trying to get the very first example to show up in a tex file as:
```LaTeX
\hyperref{Section:GoalStmt}[goal statements]
```

For number 2, do the anchors show up on the webpage? I'm not too familiar with html, but I thought just changing the text in the anchor would work. I think the internal anchor name is the reference address, so wouldn't changing that mean changing where the link will point to as well? With the idea I have now, the internal anchor label would still be the reference address, but the text would be different. So the first example's reference would show up in the HTML file as:
```HTML
<a href="#Section:GoalStmt">goal statements</a>
```

Is this on the right track?

**Comment by JacquesCarette** [comment]
No, the anchors are not user-visible (unless you hover over the link, then they'll be in the pop-up).

Yes, this seems like it is on the right track.

**Comment by Ant13731** [comment]
Is this issue okay to close now?

**Comment by JacquesCarette** [comment]
Yes!
