### ISSUE TITLE
Fix output parameters in Instance Model(game physics)

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1163]
Output parameters in Instance Model is not correct(Drasil version) Needs to be reviewed and fixed. Had a discussion with @smiths  at the all-hands meeting. I will work on fixing these.

**Comment by JacquesCarette** [comment]
Did this ever get fixed @oluowoj ?

**Comment by smiths** [comment]
The game physics requirements need to be revised.  It would have been better if @oluowoj took a step in that direction with this revision, but I think the details are now lost to time.  Asking @oluowoj to do it now won't likely be very helpful for her work, or for the game physics example.  Instead, I have added the revision of the game physics example (and completing the code generation for ssp and swhs) to the list of potential projects:

https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/-/tree/git-svn/Planning/PotGradStdProj

Since whatever change was planned here is part of the revision of game physics, I will close this issue in favour of the bigger "to do" item in the planning document.
