### ISSUE TITLE
Non-functional requirements format

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1223]
In Drasil, non-functional requirements are listed out in a single sentence, like so:

![image](https://user-images.githubusercontent.com/18634568/56678487-cea8bf00-6690-11e9-8d16-c1a2c93f01e2.png)

In the manual version of SSP, I changed this to a more formal list with more description:

![image](https://user-images.githubusercontent.com/18634568/56678435-b173f080-6690-11e9-8142-5c8c70589308.png)

Is the current Drasil behaviour enough, or is the more descriptive list preferred? The way Drasil renders non-functional requirements is common between all of the examples, so if we change it the change will need to be propagated to the rest of the examples, not just SSP.

**Comment by smiths** [comment]
@bmaclach, I definitely like the idea of breaking down the nonfunctional requirements into separate requirements.  It was never the long-term intention to just use one sentence to summarize the NFRs.  We did that because the NFRs were not initially a priority, and we had enough to do with the FRs.  

I like the idea of adding separate NFRs, but I don't really like your specific examples, since they aren't abstract.  You say how to achieve usability, not what it means to be usable.  The challenge is that stating NFRs in the right way is far from easy.  That is why we keep "punting" it to the future.  

In the long run, I would like to see the NFRs expanded into considerably more information.  We might want to explore the Volere templates notion of "fit criterion."  For instance, for usability, the requirement could be an experiment, or survey that measures usability.  Alternatively, it could be a count of the number of interactions (mouse clicks, keys pressed, etc) to get a given task done.  I'm sure with some HCI research some other metrics could be devised.

There starts to be overlap with the verification and validation plan, which is another document that Drasil knows nothing about.

My thinking is that it would be nice to do something now with NFRs, but it still isn't time to really delve into how best to state them and measure them.  That would be a bigger task than we currently have time to tackle.  How much work would it be to add NFRs along the lines of what you described?  That is, to have separate NFRs, with each one having its own text?  That would give us a starting point for the future when we decide to really think deeply about the content of the NFRs.

**Comment by bmaclach** [comment]
@smiths I don't know _exactly_ what to do to set up a more formal list of NFRs, but I have a general idea, and there are plenty of other examples of lists (like the functional requirement list) that I can use as a reference. So I would be surprised if setting up the infrastructure for this took more than a few hours. Seems reasonable to add this to my to-do list.

**Comment by Mornix** [comment]
Implementation wise, this should be similar to #1215. I believe all the infrastructure is there. All that should be needed (or it may already exist!) is a `nonFuncReqDom` (or similar) for `ConceptInstance`.

**Comment by bmaclach** [comment]
Thanks @Mornix. Reassigning this to myself to implement.

**Comment by smiths** [comment]
Sounds like a good plan to implement NFRs the same as the FRs.  How best to state the NFRs can be a task that is investigated outside of Drasil.

**Comment by bmaclach** [comment]
Set-up for the new format for NFR's was merged with #1225. Created new issue #1229 for updating each example, so this issue can be closed.

**Comment by samm82** [comment]
@bmaclach Did you define an intro sentence for the nonfunc reqs somewhere in `docLang` (like the one for the func reqs)?

**Comment by bmaclach** [comment]
The intro paragraph (it's actually multiple sentences, my bad for saying "sentence" before) is built from 2 `Sentence`s which are passed to the `NonFReqsSub'` constructor. Specifically, these functions put them together:

https://github.com/JacquesCarette/Drasil/blob/1bf147eb59597e47ed7a119b489aeddea1b2973f/code/drasil-docLang/Drasil/Sections/Requirements.hs#L65-L69

https://github.com/JacquesCarette/Drasil/blob/1bf147eb59597e47ed7a119b489aeddea1b2973f/code/drasil-docLang/Drasil/Sections/Requirements.hs#L76-L79

**Comment by samm82** [comment]
Great! Works like a charm (once I figured out how it was working 😂)
