### ISSUE TITLE
One traceability matrix or many?

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1233]
In the manual versions of the case studies, there are 3-4 traceability matrices, each focusing on certain parts of the SRS (for example, one traceability matrix dedicated to assumptions, one dedicated to requirements, etc.)

For SSP, I used the function Yuzhi created to create one giant traceability matrix with all of the dependencies between everything included. Is there a need to break this down further into the smaller traceability matrices we see in the manual version? Looking at the other examples, it seems like they hardcode dependencies in Drasil to get these smaller matrices, which seems like something we wouldn't want to repeat for SSP, right?

**Comment by JacquesCarette** [comment]
As soon as a project gets beyond small, the traceability matrices will be huge. We definitely want the huge traceability matrix available, but it makes little sense to try to print it in a document, IMHO. The small ones might make sense - up until they too get too large. Definitely an interesting design question.

**Comment by smiths** [comment]
Great question @bmaclach.  For now, I think all of the examples should use the huge traceability table created automatically using the work from @halonazhao.  The great thing about using this approach is that it should be fully automated.  The bad thing is that for nontrivial examples it will be impossible to read.  For the first pass, I pick automation over readability.  Our goal is something that is easy to maintain.

The next stage will be to start thinking about readability.  @bmaclach, can you create an issue related to designing functions for extracting subsets of the full traceability matrix?  I think this would be something that we can discuss in one of our upcoming all hands meetings.  I don't have a feel for how much work is involved here, but when we discuss as a group, we can likely come up with a reasonable plan.

I'm going to close this issue, because I think @JacquesCarette and I have answered the original question.
