### ISSUE TITLE
Stable files have lots of tabs

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1246]
Going through some of the stable files, I've noticed that a lot of the tables have more and more tabs for every line in the table.

Are these tabs necessary?
If they are necessary, should they be changed to be only 2 spaces instead of 4?
When adding new Data Definitions for example (as per #1070), should a similar format be followed?

**Comment by Mornix** [comment]
This is a bug in the TeX printer that @deviprasad135 is working on addressing.

**Comment by deviprasad135** [comment]
I have already fixed this bug in the TeX printer.

**Comment by smiths** [comment]
@deviprasad135, is this fix in a pull request?  It would help @danscime if you included a pointer to the pull request.

**Comment by deviprasad135** [comment]
I have fixed this bug on indentTex branch in commit 0863b30. This bug is caused due to missing parentheses.

![OI](https://user-images.githubusercontent.com/30101689/57036786-4fccfc80-6c23-11e9-831d-20426745f40c.PNG)

The generated code for one of the data definition from SWHS after fixing the over indent bug and applying 4 spaces as indentation is as shown below.

![DD](https://user-images.githubusercontent.com/30101689/57037934-8c4e2780-6c26-11e9-9d59-36cfb6ea82a8.PNG)

**Comment by JacquesCarette** [comment]
So can at least this one-liner fix be made into a PR asap?  Maybe @danscime can take care of it?
