### ISSUE TITLE
Add derivation for surface hydrostatic force DD in SSP

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1277]
It is not obvious how the equation for surface hydrostatic force is derived. A derivation should be added to this DD. The following is an overview of the derivation, provided by @smiths:

"The derivation should start with the fact that we want to know the weight of the water on top of the slope of the soil surface.  We find this force as the volume of water multiplied by its unit weight (gamma_w).  (We should consider adding a DD for unit weight.)  We then make the geometric arguments for the volume.  We know the dimension into the plane is 1.  Therefore, we need the area of the trapezoid formed by the water on top of the soil slice."

**Comment by bmaclach** [comment]
@smiths With regards to adding a DD for unit weight, unit weight is a direct input to SSP. So I don't think it makes sense to write a DD for that since we don't actually calculate it.

Also, the "Base hydrostatic force" DD equation is almost exactly the same as the one for surface hydrostatic force. The "Weight" DD follows a similar pattern as well. Should we write derivations for all of these DDs?

**Comment by smiths** [comment]
Yes, you are right about the unit weight.  The data definition would be for the concept of weight.  The input is the volume and the specific weight, the output is a force (pointing in the negative y direction).  

Do we have Newton's second law anywhere?  It should be in game physics (I believe).  The theory is F = m*a.  Since we know that a = g, we have the weight (force) equal to the mass times g.  We know that the mass is the density times the volume.  So we have volume * density * g.  The term density*g is our specific weight.  If we want to go really crazy, g comes from Newton's Law of Universal Gravitation, with the mass and radius of the earth as inputs.  :smile:

Let us start with a derivation for just the DD we are discussing (hydrostatic force).  Once we like that, you are correct that we will likely modify the other similar DDs as well.

**Comment by bmaclach** [comment]
This derivation has been added with #1286 so I'll close this issue. @smiths Do we want to now make similar changes for the DDs that are similar to surface hydrostatic force (base hydrostatic force, slice weight)? If so, I'll create new issues for those.

**Comment by smiths** [comment]
@bmaclach, yes, let's see what it looks like if you propagate this approach to the other forces.  If it starts to get ugly, don't go too far down this path.  We might need to have another design review meeting.
