### ISSUE TITLE
Ignore Line Breaks in HTML Diffs

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1288]
Is there a way to ignore line breaks in the HTML Diffs?

These two diffs both render the same, but show up as diffs. Can the line breaks be ignored?

<img width="103" alt="Screen Shot 2019-05-08 at 3 16 21 PM" src="https://user-images.githubusercontent.com/28261339/57401716-46eca580-71a4-11e9-80b7-60a735079172.png">
<img width="175" alt="Screen Shot 2019-05-08 at 3 16 27 PM" src="https://user-images.githubusercontent.com/28261339/57401717-46eca580-71a4-11e9-8408-337a10dcd699.png">

This regards @deviprasad135's ```ind``` branch.

**Comment by smiths** [comment]
@danscime, I don't know the answer to your question.  It seems to me that @Mornix may know.

**Comment by JacquesCarette** [comment]
No, there is no way to ignore them -- and that's good!!!  Once we get the latter display, we want it to *stay* that way, so those line breaks really matter.

Now, I understand that this makes the diffs for the `ind` branch extremely noisy. Big pain - once.

The only way I know of to reduce the pain is to switch each tag (like `th`) from using one method of printing (with too many line breaks) to 'inline', one at a time [the commit, do PR, merge]. That way the diffs are still large, but visually easy to understand if they correspond to a desired change or not. So it becomes tedious rather than hard and error-prone. Definitely the better way to do it.

**Comment by danscime** [comment]
Another possible problem that might arise would be the tabs and trailing whitespace on a line.
Not sure if this is ignored. Based on the Makefile, I feel like it would be ignored but just want to ask anyway.

<img width="378" alt="Screen Shot 2019-05-08 at 4 20 42 PM" src="https://user-images.githubusercontent.com/28261339/57405769-486e9b80-71ad-11e9-8f83-ca883fbabbec.png">

**Comment by JacquesCarette** [comment]
whitespace is currently ignored. Eventually, we might want to be pickier, but it caused too many truly spurious issues (a lot of them to do with Windows vs Mac vs Linux) that were not worth our time.

**Comment by Mornix** [comment]
Although, I don't believe we should have any instances where there is trailing whitespace currently.

**Comment by danscime** [comment]
Okay great.

For the big changes, just to clarify:
The changes should first tackle instances of <th> and extra lines, then </th> for example, and so on with <h1>, </h1> etc...
Correct?

Another issue: If we do a bunch of PRs, they will not pass the Travis Checks until fully complete.

**Comment by JacquesCarette** [comment]
@Mornix : agree. Maybe we should test that?

@danscime : not quite, since those come in matched pairs. `th` (in Drasil) will change both `<th>` and `</th>` in the html.  But otherwise yes, one tag-pair at a time.  And you can make them pass Travis by changing 'stable' every time? Or am I not understanding the issue you raise?

**Comment by danscime** [comment]
I may be mixed up. I thought you meant only edit stable.

You mean like make the edit that prints ```<th>``` and ```</th>``` in html. THEN edit stable based upon this change.

Is this what you mean?

**Comment by JacquesCarette** [comment]
Yes, that's what I mean.

**Comment by danscime** [comment]
This issue can be closed. Updating can be communicated through #1299.
