### ISSUE TITLE
Document Derivation of Moment Equilibrium Equation for SSP

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1326]
The moment equilibrium equation in SSP has inconsistencies between manual and Drasil and even within manual. See #1324 for in-depth discussion on these inconsistencies and other ambiguities. We should document the derivation of this equation to ensure we have the correct equation and to avoid future confusion. The derivation and the free body diagram in the SSP SRS should agree with each other.

**Comment by bmaclach** [comment]
@smiths I pushed a first draft of the derivation to the case studies repo. Can you please review it?
https://github.com/smiths/caseStudies/blob/master/CaseStudies/ssp/docs/SRS/SRS.pdf

I brought in the Torque DD from GamePhysics. I also updated the IM2 derivation to be consistent with the moment equilibrium equation from the GD.

**Comment by smiths** [comment]
Thank you @bmaclach.  This is a good start.  I did notice a few things we need to correct/clarify.  Rather than type it up, hopefully we can have a quick discussion during tomorrow's (May 16) meeting.  If we don't have time then, we'll make a quick appointment for another time.

**Comment by smiths** [comment]
@bmaclach thank you for your efforts on this.  I think after you make the changes we discussed yesterday, we will have a good derivation.  @danscime, this is relevant for you because refining the derivation found mistakes in what we did previously, and in the original papers.  The papers mis-defined a variable.  In some cases it was the height of the water table, but in other cases it was considered to be the height where the hydrostatic force was applied.  In the Zhu paper there is a missing assumption about the calculation of the moment created by the soil mass under earthquake loading.  @bmaclach will be adding an assumption about this to our documentation.

**Comment by bmaclach** [comment]
@smiths I've addressed the feedback on the case studies repo. Can you please let me know if you spot any other issues with the derivation before I port it over to Drasil?

**Comment by smiths** [comment]
Looks great @bmaclach.  The only thing that occurs to me is that we don't consider the case where the water table is below the base of the slice (the height of the water table as shown in Figure 4 would be negative in this case.)  Is there an assumption that the water table is always above the slip surface?  If it is below, then the formula will be wrong because the hydrostatic force shouldn't be contributing anything.  Oh, I know what happens.  H_i would be zero (by DD4), so the term related to hydrostatic force won't enter into the equation.  We don't need any special cases in GD10.

Looks good to me.

One nice thing is with our separation of concerns, it doesn't matter that we are still working on the definition of Ut.  That definition is the responsibility of DD3.  (We should change DD3 back, once we verify that Brandon was correct in the first place.)

**Comment by bmaclach** [comment]
This is done with the merge of #1414.
