### ISSUE TITLE
Verify Values of Uncertainties in Input Data Constraints Tables

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1341]
As per discussion on #1334, there are a lot of values in the Tables of Input Data Constraints (in all examples) with a 10% uncertainty, which in most cases seems like a placeholder value (for sure in `time_step` and `time_final` in SWHS). @smiths I'm not sure how I would go about verifying the uncertainty of these values, but in caseStudies:
- GamePhysics has no uncertainty for its values
- GlassBR has 0.1% for Pbtol and 10% for everything else
- SWHS, NoPCM, and SSP have 10% for everything

_This issue is only for correcting the uncertainty values; #1342 is for implementing values with no uncertainties._

**Comment by smiths** [comment]
@samm82, you don't need to invest much effort into verification of the uncertainties.  As you said, they really are placeholders.  The true uncertainties will depend on the measurement techniques, which we really don't know anything about.  I believe that GamePhysics has no uncertainty because the inputs are not experimentally determined.  They are decided by the programmer building the game.  The notion of error isn't really the same here.  GlassBR probably has a low tolerance for Pbtol because, again, the user decided this value.

If we can have values with no uncertainty (#1342), then we could use this for Pbtol and for the GamePhysics inputs.  Leaving the others at 10% for now seems fine.
