### ISSUE TITLE
Add Values with no Uncertainty in Input Data Constraints Tables

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1342]
As mentioned in #1307, we need a way to add values to the Table of Input Data Constraints that don't have an uncertainty value.

- GamePhysics -> All
- SWHS/NoPCM -> `time_final`/`time_step`

**Comment by muhammadaliog3** [comment]
Just as an update of the issue the GamePhysics example currently sets all uncertainties to 10%, so the relevance of the issue is somewhat in question. There are two options we have with regards to examples with irrelevant uncertainty: set the uncertainties to zero for every quantity without uncertainty and keep the uncertainty column, or delete uncertainty column entirely. Deleting the uncertainty column entirely also effects the paragraph that describes the data constraint table, hence the latter option will require more extensive change. 

Anyhow if we are to go with the second option, I was able to track down where the data constraints table is being generated in drasil-docLang/Drasil/Sections/SpecificSystemDescription.hs:
```haskell
inDataConstTbl :: (HasUncertainty c, Quantity c, Constrained c, HasReasVal c, MayHaveUnit c) => 
  [c] -> LabelledContent
inDataConstTbl qlst = mkDataConstraintTable [(S "Var", map ch $ sortBySymbol qlst),
            (titleize' physicalConstraint, map fmtPhys $ sortBySymbol qlst),
            (titleize' softwareConstraint, map fmtSfwr $ sortBySymbol qlst),
            (S "Typical Value", map (\q -> fmtU (E $ getRVal q) q) $ sortBySymbol qlst),
            (short typUnc, map typUncr $ sortBySymbol qlst)]  "InDataConstraints" $
            S "Input Data Constraints"
```

The uncertainty column can be removed simply by removing the line 
```haskell 
(short typUnc, map typUncr $ sortBySymbol qlst)
```
Now the design decision has to be made. When do we remove the uncertainty column? Do we allow the Drasil user to themselves choose whether or not to display the uncertainty column, or do we automatically remove the uncertainty column when the uncertainties of all inputs are 0%?

**Comment by smiths** [comment]
@muhammadaliog3, I would like to always keep the uncertainty column, even if all of the entries are 0%.  Realistically, there shouldn't be any physical problems that have 0% uncertainty.  There is no measurement method for physical quantities that will give 0% uncertainty.  There might be cases where someone wants to ignore the uncertainty, but that is a different matter.  Making the person explicitly state that they are ignoring uncertainty (by putting in 0%) is a better approach, because then that decision can be scrutinized.  If the column is removed, most people won't think to question its removal.

**Comment by muhammadaliog3** [comment]
Currently you cannot add a row into the Input Data Constraints table without having an uncertainty. Here is the definition for the function that creates the input data table 
```haskell
inDataConstTbl :: (HasUncertainty c, Quantity c, Constrained c, HasReasVal c, MayHaveUnit c) => 
  [c] -> LabelledContent
```
Hence the user must manually enter an uncertainty in the table already. Even if there is no uncertainty still they must enter a value.

Therefore this issue seems to be solved.

**Comment by smiths** [comment]
@samm82 had the proposal that it should be possible to have quantities that are known with 100% certainty.  We don't have a type for that in Drasil, so the original issue is not solved.  Although most inputs and outputs should have some uncertainty, even if we choose to ignore it, there are some quantities that we can known exactly.  For instance, if the input is an integer type, we can often count without error.  For instance, if the input to a rigid body dynamics problem includes the number of rigid bodies, I can know this number with 100% certainty.

As things currently are in Drasil, the best way we have to indicate certainty is to have an uncertain quantity with 0% uncertainty.  Although logically equivalent, this isn't sending the same message, or capturing the same information.

**Comment by JacquesCarette** [comment]
We could either allow the uncertainty to be exactly 0 (the easiest thing to do), or create a `MayHaveUncertainty` class and change `inDataConstTbl` to use that.

I think allowing uncertainty to be 0, via a new smart constructor but not otherwise, is the simplest way. Then we could have a special case for printing that removes the 0s, which we would know were not user errors.

**Comment by smiths** [comment]
I like your proposed solution @JacquesCarette.  Simpler is better, and really there shouldn't be too many quantities that really are known with 100% certainty.

**Comment by muhammadaliog3** [comment]
@smiths 
I think that there are 3 design decisions that need to be made. 
1. Is this a feature that is just for display purposes, or is it a feature that will force the uncertainty on a quantity to zero (and thereby influencing calculations)? 

I think that we should do the latter. In this case, perhaps the proposed MayHaveUncertainty class should be a contructor "ignoreUncertainty" that creates input variables with 0% uncertainty.

2. Is this a feature that should automatically happen when the uncertainty is set to zero or should this feature require the user to explicitly state they want no uncertainty?

3. If the uncertainty is ignored, should the table still display the uncertainty as 0% or should it not display the column?
Relevant Code

Essentially UncertainQ and UncertainChunk are both instances of HasUncertainty, and both have a field unc''.
 
```haskell
class HasUncertainty c where
  unc  :: Lens' c Uncertainty
....
data UncertQ = UQ { _coco :: ConstrConcept , _unc'' :: Uncertainty }
makeLenses ''UncertQ
instance HasUncertainty UncertQ where unc = unc''
....
data UncertainChunk  = UCh { _conc :: ConstrainedChunk , _unc' :: Uncertainty }
instance HasUncertainty    UncertainChunk where unc = unc'
```

**Potential Solution** 

My initial thought was to have a separate constructor for creating inputs with no uncertainty, but the limitation of that solution is that IF we wanted to ignore the uncertainty column when uncertainties are ignored (from question 3) then this solution is not feasible. Because there would be no way for the inputDataTable constraint to check if things the uncertainty was set to 0% or if it the input was deliberately set to "ignoreUncertainty". 

Another solution would be to add the field "ignoreUncertainty" to UncertQ and UncertainChunk. However that solution would make every data inputs take more memory for a feature such few of them use. 

My current solution is to have ```_unc'' :: Uncertainty``` become ```_unc'' :: Maybe Uncertainty```. This would be compatible with whether or not we want to ignore the uncertainty column from question 3. However this solution would complicate all the examples who now need to have there uncertainties changed. 

Are any of the above 3 solutions acceptable?

**Comment by smiths** [comment]
@muhammadaliog3 in answer to your question, uncertainty is definitely not just a display concept.  We do not currently propagate uncertainty in any of our calculations, but that is something that we want as an option in the future.  Rather than have the uncertainty set to 0%, I think it makes more sense for the programmer to explicitly state that they want no uncertainty.

@JacquesCarette may have a difference opinion, but in answer to your question 3, I would rather explicitly display the uncertainty as 0%, instead of not showing the column at all.  The decision that there is no uncertainty seems to me to be important enough to make explicit in the documentation.

**Comment by JacquesCarette** [comment]
Great questions.

I think the definition of `Uncertainty` should change. The idea is almost the same as the potential solution: rather than change `_unc'' :: Uncertainy` to `Maybe Uncertainty`, I would change the definition of `Uncertainty` to contain that `Maybe` directly.

The should never be able to set the uncertainty to 0. Trying to do that should be a hard error. However, we can (and should) provide a constructor for both `UncertQ` and `UncertainChunk`, with a name like `exactXXX` that uses `Nothing` for the `Uncertainty`, indicating exactness.

**Comment by muhammadaliog3** [comment]
I have made two branchs with 2 possible solutions. 
The second approach is build off of the first approach, and essentially make uncertainty and inherent Maybe value. 
See Issue_1342 branch and Issue_1342_other_approach branch.

**Comment by JacquesCarette** [comment]
"An uncertain quantity cannot be exact (have 0% uncertainty).  Reconsider whether your value is exact or uncertain."

I do like the idea of giving advice as to what to do next, but I don't want to hardwire constructor names in error messages at this point.

**Comment by muhammadaliog3** [comment]
@JacquesCarette 
Did you prefer the second approach or the first, i.e. do you want exact and uncertain values to differ because of constructors or do you want me to change uncertainty to a maybe value.

**Comment by JacquesCarette** [comment]
I think I prefer the #2170 approach.
