### ISSUE TITLE
Notation Intro Reuse in MIS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1347]
Right now, the intro to the Notation section is:

"The structure of the MIS for modules comes from Hoffman and Strooper (1995), with the addition that template modules have been adapted from Ghezzi et al. (2003). The mathematical notation comes from Chapter 3 of Hoffman and Strooper (1995). For instance, the symbol := is used for a multiple assignment statement and conditional rules follow the form (c1 ⇒ r1|c2 ⇒ r2|...|cn ⇒ rn)."

At least for the time being, can we assume that this intro will be reused among other examples? I'm asking because right now, this is the assumption, and the references are hardcoded. If we want to reuse it, I'll move these references from `drasil-example` into this package (`drasil-docLang`) so they can be referenced. If we don't want to, I'll move this intro paragraph into the GlassBR example and pass it in explicitly.

**Comment by smiths** [comment]
@samm82, thank you for your question.  You are correct that we want to reuse this text among all of our examples.  Over time the text might change, but it will change in all of the examples.  You should definitely follow the reuse approach that you outlined.

I'm closing the issue because I think I've answered your question.  If not, please feel free to re-open.
