### ISSUE TITLE
Exported Constants - ":=" vs. "="

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1358]
For the exported constants section, should "=" be used for listing the values (ie. MAX_ORDER = 2). I think this makes sense because the values have already been assigned, so the assignment operator shouldn't be used. I looked at A3 from 2AA4 and the "=" was used, so I'm just clarifying that this is the correct choice.

**Comment by smiths** [comment]
Yes, the `=` makes sense for the exported constants section.  Go ahead and use this going forward.

**Comment by JacquesCarette** [comment]
It depends on what we're trying to say. `:=` is the right thing to use when we're making a definition, so that from this point forward, `MAX_ORDER` is `2`. `=` is the right thing to use when we are asserting something which is already true (or something we wish to be true, if used in a guard).

It is a fundamental mistake in notation, in both CS and Math, to use `=` as some kind of oriented thing. `=` is symmetric. Basic test: if `2 = MAX_ORDER` makes sense, then `=` is fine. If it doesn't, then you're using the wrong symbol.

**Comment by smiths** [comment]
Based on the comments of @JacquesCarette, I'm rethinking what I said.  We are defining the constants, so `:=` is actually the right choice.  Not all 2s in the code would make sense if they were replaced by `MAX_ORDER`.  I've never thought of it that way, but once you do, I think it is obvious that my 2AA4 example is wrong on this point.  :smile:
