### ISSUE TITLE
Display Type Information?

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1364]
Right now, it looks like `Space` functions as type information. If this is correct, to display the types for the MIS, we would need a way to convert to a `Sentence`, and I think going through `Expr` might be the best way.

Am I on the right track here?

EDIT: If we decide to use `Space` for type information, we'd have to add a constructor to build new types for each example (eg. "ContoursT"), something along the lines of how `Atomic` works for `Symbol`.

**Comment by JacquesCarette** [comment]
Yes, `Space` is sort-of like type. It's meant to be "type but in the semantic domain", as opposed to "type in the programming domain".

I thought there were utilities to render `Space`.

The issue is, I think the MIS is 'code specification', while `Space` is really meant to be about the problem space. But I'm not sure - this needs a deeper discussion as to where in the requirements..implementation MIS really lie.

**Comment by smiths** [comment]
Yes, we need a deeper discussion about this, as mentioned elsewhere.
