### ISSUE TITLE
Visualizations

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#1371]
@Mornix I want to add automatic generation of visualizations to the `Makefile` for all our packages. But I realize that my `Makefile` knowledge is a tad less than needed to get the job done!  What I want to do is that for each package P (as listed in `PACKAGES`), I want to execute
```bash
find ${P} -name '*.hs' | xargs graphmod -q -p --no-cluster | dot -Tpdf > graphs/${P}.pdf
```
where `graphmod` is an executable (available from hackage).  So that visualization will add a couple of dependencies in `stack.yaml` (as I found that I needed to mention both `graphmod` and `dotgen` explicitly to get a proper install).

If you could teach me how to do this (rather than just go it yourself), I would appreciate it.

**Comment by JacquesCarette** [comment]
And now that I dig just a little deeper, that `find` should exclude `.stack-work` from its search, as that just leads to (a bit of) noise that's not needed.

**Comment by Mornix** [comment]
Okay, the `Makefile` is (hopefully) designed to be fairly modular and self-contained by "goal". 

1. First thing I would do is pick a make variable prefix as the `Makefile` uses consistent variable names to try to automate certain parts. Similarly, you should decide a suffix for individual package targets. Basically some unique suffix not used which can be passed to `make` to generate a graph for a single package. Although you generally won't be manually calling these targets having them exposed in this way adds to modularity (i.e. launching with multiple threads can have multiple package graphs generate simultaneously) and debugging or quick regeneration in specific situations. 

2. The first thing to do once you've decided these two things is to add variable to the "configuration" section of the `Makefile` at the top. Since you want to add something that acts on packages rather than examples, the rule suffix you have decided on should be added into the block currently occupying lines 3-4 of the Makefile. 

https://github.com/JacquesCarette/Drasil/blob/0f112c337e690d23745230191d36071d2d6aed35/code/Makefile#L3-L4

3. To actually "create" the list of rules from this suffix, the following block (line 6-7) should have a similarly named variable added which uses the new suffix.

https://github.com/JacquesCarette/Drasil/blob/master/code/Makefile#L6-L7

4. Finally, `PACKAGE_GEN_TARGET` (line 9) should gain a new "prefix." That is whatever you prefixed `_PACKAGES` with in the previous step should be added to `PACKAGE_GEN_TARGET`. `PACKAGE_GEN_TARGET` is used to automated configuration of `.PHONY` rules; any rule which isn't explicitly a file. Note: while you do generate a file at the end of this, the targets themselves aren't filenames (in an effort to be more user-friendly) so they should be made `.PHONY`.

https://github.com/JacquesCarette/Drasil/blob/master/code/Makefile#L9

5. In the block starting at line 48, a new variable (likely of name `GRAPH_FOLDER_NAME` for convention) is needed a similar one is needed for `GRAPH_FOLDER` following the pattern already specified by `LOG_FOLDER` and `BUILD_FOLDER`.

https://github.com/JacquesCarette/Drasil/blob/0f112c337e690d23745230191d36071d2d6aed35/code/Makefile#L48-L57

6. Finally, on line 41 `GENNED_FOLDER` needs to be updated to track the new folder name to ensure `clean` removes the new generated folder.

https://github.com/JacquesCarette/Drasil/blob/0f112c337e690d23745230191d36071d2d6aed35/code/Makefile#L41

----

Now onto the actual targets.

Targets which interact with the source Haskell code and not the generated artifacts are usually easier to setup as there are no target variables.

The general form for build targets can be seen with the target that builds the packages:
```make
$(filter %$(BUILD_P_SUFFIX), $(BUILD_PACKAGES)): %$(BUILD_P_SUFFIX):
```

So what does the previous line do?
```make
$(filter %$(BUILD_P_SUFFIX), $(BUILD_PACKAGES)): 
```
is the interesting part, which matches `%$(BUILD_P_SUFFIX)`, or, ANY target matching our suffix `_build` which exists in `BUILD_PACKAGES`. For example, `foo_build` fails because we do not have `foo` in `PACKAGES` which seeds `BUILD_PACKAGES`.

The part after the first colon
```make
%$(BUILD_P_SUFFIX):
```
is the actual target name. If you look to the target below this one (`packages`) this is the same "thing" as the target name `packages`. The `%` in this rule is a wildcard which matches the make variable `$*` in the body of the rule. So in our previous example, _if_ `foo_build` was valid, `$*` for that rule would be `foo`.

And for completeness, to the right of the second colon would be any dependencies. You may be interested in doing something similar to the `check_stack` rule to ensure `graphmod` and `dotgen` are installed. 

For the body of the target, everything should be configured correctly and you seem to have the command almost completely there, so the body of the rule is left as an exercise to the reader. 😉

----

Almost done, we just have a rule and a field to update.

Under your new rule template, you likely want a meta-rule which will automatically run all the templated rules. Something similar to `prog` or `docs`. This rule usually contains the "sole" dependency of the second argument to the `filter` in the templated rule. 

Finally, because the previous meta-rule you just created isn't tracked anywhere and is a `.PHONY` rule, it should be added to the `.PHONY` section at the very end of the file.

----

That should be everything needed to create exactly what you want for visualization. Let me know if you have any questions or if anything is unclear.

**Comment by JacquesCarette** [comment]
This was great, thanks.
