### ISSUE TITLE
PDFs cause Non-Empty Logs

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1408]
Running `make tex`, and then `make` causes non-empty logs, since the PDF file is in the build/ folder, but not the stable/ folder, which is outputted to the log. Running `make clean` and then `make` (or just manually removing the PDF files before `make`). Resolves this, but is annoying 😊. I think just ignoring the PDFs when log checking should fix it.

@Mornix I might huck this out later, but if you're bored/want a small issue, go for it!

**Comment by Mornix** [comment]
So there is an underlying design decision behind this (at least at the moment) for why generated PDFs cause log errors which I’ll type up (I don’t think I’ve typed this up yet, so it’ll be good for the sake of documentation) in a bit. However, with your current flow you can get a “lighter” `make clean` to remove just the `build` folder (and not require a full recompilation): `make clean_build`.

**Comment by samm82** [comment]
Works for me - I'll close this, but feel free to still add the explanation!

**Comment by Mornix** [comment]
The `diff` process (and more generally the entire Makefile) is designed to be consistent*, simple, and easy to maintain. 

*consistent in the sense that files which `git` tracks are the same which `diff` looks at, with the exception of the `.txt` “hack” mentioned below. 

## How `diff` currently works
`diff`, as it stands, compares two example directories, say `build/GlassBR/` and `stable/glassbr/`. Because we’re comparing two entire directory trees, we ignore some of the files: `-X .gitignore` which are (most) files that aren't tracked by `git` (there are exceptions, more on that in a bit). The other exclusion is `-x ‘*.txt’` which can be seen as a sort of “hack” as it’s only for GlassBR because GlassBR copies a few text files to the generated code folders as "a part" of the generation process. 

https://github.com/JacquesCarette/Drasil/blob/c49798ae5605acd87364ac97f4203897677231d6/code/Makefile#L145-L150

`diff` itself doesn’t support file path exclusions. It only supports _name_ exclusions. What does this mean _practically_? You can’t exclude `a/b.c` with `diff`, you can either exclude files and folders named `a`, a folder or file named `b.c`, or using patterns: `*.c` or `b.*`. This will become more important later.

## Why not add `*.pdf` as an exclusion to `diff`? 
The largest reason I have against this is consistency. By adding (another) non-`.gitignore` exclusion, there is an added inconsistency at which artefacts² (that is artefacts of artefacts generated by Drasil) are tracked in `diff` and those which aren’t. Additionally this adds a complexity in “files `diff` ignores that are tracked by `git`”.

## Why not ignore all artefacts²?
Great question! Remember how I mentioned `diff` only excludes patterns? Going back to GlassBR as the example: one of the artefacts we need to ignore is `GlassBR` itself (as that’s the name of the binary generated on non-Windows systems for C++ and C#). Java codegen generates a folder named "`GlassBR`" as the package the Java code resides in. Sure enough, `diff … -x ‘GlassBR’` ignores the entire `GlassBR` folder containing the generated Java code. 

## Why not add to `.gitignore`?
As a side tangent that will become relevant in a little bit: adding files such as `GlassBR` to the `.gitignore` or targeted `.gitignore` rules (of the form `stable/glassbr/src/cpp/GlassBR`) is not a satisfactory target for automation. There are ways to do it, but it goes in the face of simplicity and maintainability. Especially because any form of generation enables a “race condition” where files may be added to the repo and _then_ not tracked by `diff`. If this slips through a PR there’s a good chance it could go unnoticed for a while. As an example, a PDF had previously slipped through in stable for ~8 months unnoticed because only certain files were being compared within stable at the time.

## Why not ditch `diff` and have a secondary ignore list which is enabled locally and disabled on CI?
This is the closest to a solution I’ve come. It does solve the issues, however it complicates things and adds complexity to the “consistency” category. Having a solution which compares directories, has the ability to ignore paths (like those which may exist in a `.gitignore`,) and disabling the “ignore” list on CI results in added complexity when moving files: is this file a file that is ignored due to being `.gitignore`d? (i.e. a file that could be innocuously copied to `stable`) or is it something that will throw a CI error? In a similar manner, complexity is violated as `diff` tracks a different subset of files which `git` allows. 

Finally, it becomes inconsistent with CI. This sounds a little farfetched, but CI does the standard `make` “and more”. By this I mean, building turns warnings into errors. But the warnings are present during local development, they’re merely enforced there. Similarly, while `hlint` isn’t a “forced” part of local builds, you can run it locally and it will be the same “response” given on CI. Same goes for TeX and code building. In my opinion it gets cumbersome (and goes in the opposite direction of this original issue) to have to run a separate `make` target to ensure your results will match CI, leading to a (subjectively) equal nuisance but in the opposite direction.

## Closing
The design as it stands achieves the goals of consistency (or a reasonable approximation), simplicity, and maintainability by doing something akin to the "dumb" way of `diff`ing the directories.

This was my train of thought. If anything doesn’t make sense, or you have a suggestion which I haven’t considered (or different view on what I’ve mentioned), feel free to add it. 😁

PS: I forgot, another “cleaner” way to tell if your `diff`s are “just” `.pdf`s is to run
`export NOISY=yes` when you launch your terminal, running `make` will cause any `diff`s to be printed in your terminal as part of the `make` process.

**Comment by JacquesCarette** [comment]
It occurs to me that perhaps every example should come with a 'manifest' that explicitly lists files that are expected to be there and verified, expected to be there but are just checked for presence.  Of course any file not in the manifest that appears would be considered an error.

**Comment by smiths** [comment]
Is it possible for us to work with "white lists" instead of "black lists" with our tools?  For instance, if the diff tool understands a white list, then (in my naive estimation) this would seem to help the manifest idea from @JacquesCarette.

**Comment by Mornix** [comment]
A whitelist is a great idea! I took a quick look at the `diff` man page. It does not look like it supports a whitelist. If we were to implement a script or small program which performs whitelisting and shells out to `diff` to perform the per-file `diff`. `.gitignore` also supports whitelisting out-of-the-box. We get almost there. We have a few issues that remain unresolved: namely the "race condition" of adding files to stable and requiring generation (and git inclusion) of nested `.gitignore`s. (Definitely something Drasil _could_ generate if manifests are being generated)
