### ISSUE TITLE
Hardcoded Figure Numbers in GlassBR

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1410]
There are some instances in GlassBR (and potentially other examples) of Figure references being hardcoded:

![figHardcoded](https://user-images.githubusercontent.com/35857611/58354300-ff6e4680-7e3e-11e9-9ebf-8ceff3349d21.png)

**Comment by smiths** [comment]
Thanks for catching this @samm82.  We definitely do want to fix this, since hard-coded numbers will be a maintenance nightmare.  The exact opposite of what we are trying to achieve!

**Comment by samm82** [comment]
Would it be OK to pull the figure definitions out to a separate Figures.hs? I think this is a good idea, because they are referenced in Body, DataDefs, and IMods. (Most of them are also named poorly, so I'll fix that, too.) @smiths @JacquesCarette

**Comment by JacquesCarette** [comment]
Let's try splitting them off that way, until we see a good reason to do otherwise.

**Comment by smiths** [comment]
Sounds good to me.

**Comment by samm82** [comment]
A related issue is that when the figure width is 100%, it just displays the image normally, instead of scaling it by the size of the window. This results in some large images:

![L A R G E](https://user-images.githubusercontent.com/35857611/58586773-d4626900-8229-11e9-9dbb-a138303bc993.png)

It's a quick fix to scale by the width of the window, but it means that some figures now get scaled up take up the whole width of the screen. Should I do this, then use `figWithWidth` (which takes a percent width, as opposed to `fig` which defaults it to 100) for the other figures to ensure they display nicely (ie. approximately the same size as currently)? 

This makes me think that we should always explicitly specify a percent width and rename `figWithWidth` to `fig`, removing the old `fig`, which might be an undesired design decision. @smiths @JacquesCarette

**Comment by smiths** [comment]
@samm82 thank you for raising this.  You are correct that this should be a separate issue.  :smile:  I definitely like it when the figures are scaled.  It makes are generated documentation look much nicer and professional.  I agree with the idea of having to specify the width.  However, we want to avoid documentation generation details for the user, if at all possible.  To be honest, I do my figure scaling in LaTeX using trial and error, but I hope we can remove these details through automation in Drasil.  Is there a way to automate the scaling, at least by default?  @Mornix may have some ideas because he is the one that finally got the figures to at least show up in the pdfs.  :smile:
