### ISSUE TITLE
Add Coordinate System Section to Projectile

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1429]
I'm not sure if this section exists in other examples (I think it doesn't), but should be added to Projectile.

**Comment by smiths** [comment]
@samm82, we should have a look at the very first SRS example, written by Lei Lai as part of her MASc.  Unfortunately we don't have an electronic version.  We can review this when I'm back at Mac next week. 

Lei Lai's problem is similar to yours.  She is looking at the bending of a beam under loading.  The problem is initially stated abstractly, but to have equations that can actually be solved, a coordinate system and sign conventions must be adopted.  Lei Lai's example will be a good starting point for us.

I don't believe there is a section in the template called coordinate system.  We don't want to add one.  The advantage of templates are lost if every instance of its application is different.   Of course there will be exceptions to this, but we need to have a really good reason to modify the template.  The headaches around use cases came up because a former student modified the template, and I didn't question the modification near deep enough.

**Comment by smiths** [comment]
@samm82, you'll see in the SRS sketch that I did (mentioned in #1428), I went with your original idea and made the coordinate system an assumption.  I reviewed the original template (Lai and Smith) and I saw that the coordinate system was listed as a data definition.  We don't have a facility for defining a data definition that is a concept like a coordinate system.  The easiest way to fit the coordinate system is was through the assumptions.  What "bothered" me was that the specific assumption of a coordinate system is a concrete decision, and my original goal was to have assumptions that don't get too concrete.  However, we don't have a facility for levels of assumptions like this.  I thought we could use a separate structure to capture different levels of assumption, but then I realized they are all still assumptions.

Using the projectile problem as a starting point, I would like us to have a conversation with @bmaclach and @JacquesCarette about how we might add a relation between assumptions in Drasil.  My guess is that it won't be that difficult, since we have references within the same level of the "hierarchy" for theoretical models and general definitions.

**Comment by samm82** [comment]
I noticed the coordinate system assumption, and I was about to ask about, but then I re-read your response to this issue and realized it should be closed. 😂

Honestly, as long as the same two assumptions don't reference each other, we can probably already have assumptions reference each other.

**Comment by smiths** [comment]
Yes, I don't think it will be difficult to have references between assumptions.  However, this highlights something that has been missing from our SRS - the rationale.  We don't currently have a facility for capturing knowledge that is used to justify the decisions that are made.  It would be nice to be able to say that we can say the acceleration is constant and then give the rationale with reference to the appropriate assumptions.  We can do this with sentences, but it would be nice if Drasil knew which knowledge was a rationale.
