### ISSUE TITLE
Game Physics NFR

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1433]
@smith , cleaning up the NFR section in gamephy, but I looked at the manual version, I don't think we should reference VnV , specific sections of other documents or even use the Tamias2D name  so should I  update this section and make it as generic as it can be or lleave as is?Let me know your thoughts. I am reviewing all the NFR in Drasil to make sure they make sense at the least.

<img width="627" alt="image" src="https://user-images.githubusercontent.com/43192745/58500786-e1f7f000-8150-11e9-9c62-566ca3eb5c46.png">

And here is what the NFR currently looks like in Drasil:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/43192745/58501055-7d896080-8151-11e9-8dc1-3b09bbc1cd9c.png">

**Comment by samm82** [comment]
The NFRs in Drasil were essentially made as placeholders in #1229 so don't hold them too highly. 😂

**Comment by oluowoj** [comment]
Yes, I see you made some updates. I wouldn't change the introduction part but just the body, I will hold this for now.

**Comment by samm82** [comment]
I'm done my changes for the existing NFRs; feel free to go ahead and fix them however they should be with @smiths's blessing.

**Comment by smiths** [comment]
@oluowoj, thank you for your work on the NFRs.  As we have discussed elsewhere, we don't want to get too distracted by trying to get the NFRs "right," but we do want to have a sensible placeholder.  I agree that you can remove the reference to the VnV document.  We do not yet have VnV documents in Drasil, so the reference wouldn't be something that could actually trace to anything.  In the long run, the specific NFR requirements will likely trace to test cases in the VnV document, but that can wait for the future.

With respect to your question about removing the software name (Tamias2D), I disagree.  The requirements document is for a specific program, and we should give that program a name.  Parts of the document certainly should be abstract and reusable, but we don't want to apply this to everything, or our document won't say very much.  :smile:  I've found over and over again that giving a project a name is a good idea.

**Comment by JacquesCarette** [comment]
I'm not sure what's left to be done in this issue?

**Comment by oluowoj** [comment]
The NFRs in the original manual doc was updated as per the screen shot above, but has not yet been updated in Drasil though we don't want to update Drasil verbatim but I can guide whoever this issue is assigned to in doing the update.

**Comment by smiths** [comment]
The NFRs in all of the case studies should eventually be improved.  The manual version of the game physics example is better than what is currently in the Drasil version.  I'd rather not lose this small improvement by prematurely closing this issue.

I'll assign this issue to @Nathaniel-Hu.  @Nathaniel-Hu, please modify the Drasil version of the game physics example to match the manual version.  @oluowoj can help with your questions.

**Comment by Nathaniel-Hu** [comment]
Hi @oluowoj, I'm just checking that I am modifying the right files/drawing information from the right sources (see below).

Source Information Document (Manual Version, PDF):
https://github.com/smiths/caseStudies/blob/master/CaseStudies/gamephys/docs/SRS/GamePhysicsSRS.pdf

Source Information Code (Manual Version, LaTeX Code):
https://github.com/smiths/caseStudies/blob/master/CaseStudies/gamephys/docs/SRS/GamePhysicsSRS.tex

Requirements Code (Drasil Version, Haskell Code):
https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-example/Drasil/GamePhysics/Requirements.hs

If any of the above files are incorrect, please let me know. I'm having some concerns since the source PDF/LaTeX code files contain comments about the NFRs being "ambiguous". Thanks!

**Comment by oluowoj** [comment]
@Nathaniel-Hu , I plan to review all Drasil issues assigned to me later this afternoon, I will look at this one first, so I can give you some feedback.

**Comment by oluowoj** [comment]
Hi Nathaniel,

Could you please use this doc. to update the Game Physics NFR
https://github.com/smiths/caseStudies/blob/gamephy_finaldoc/CaseStudies/gamephys/docs/SRS/GamePhysicsSRS.pdf. This has the most recent update.

**Comment by oluowoj** [comment]
The NFR still requires work, but you can add what's in the document as is for future improvement. Please ignore what the comments, pretty much the comments are a thread and they have been addressed. 

For usability, update as shown below. 
![image](https://user-images.githubusercontent.com/43192745/82832947-9fafde80-9e8a-11ea-88ce-19f68ebfb20a.png)

**Comment by Nathaniel-Hu** [comment]
Ok then, thanks for the heads up @oluowoj. Just to be sure, I am supposed to edit the following file, correct?

Requirements Code (Drasil Version, Haskell Code):
https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-example/Drasil/GamePhysics/Requirements.hs

**Comment by oluowoj** [comment]
Yes, this is the file to edit. Let me know if you have any other questions.

**Comment by Nathaniel-Hu** [comment]
Thanks, @oluowoj. I have made the changes to the requirements code file and created a new branch for it (Issue#1433, see link below). I haven't added the correct references for the usability section (Section 5.2.3, and the file path/link for the reference VnV Plan file. Does a reference already exist for this file, or should I just hard code the reference and file path directly into the usability section?

https://github.com/JacquesCarette/Drasil/blob/Issue%231433/code/drasil-example/Drasil/GamePhysics/Requirements.hs

**Comment by oluowoj** [comment]
No need to add the reference, I crossed out the text in the screenshot.
https://user-images.githubusercontent.com/43192745/82832947-9fafde80-9e8a-11ea-88ce-19f68ebfb20a.png.

**Comment by Nathaniel-Hu** [comment]
Ok then, thanks @oluowoj. I have made the changes to the requirements code file (link below). Could you just review the changes and ensure that they are correct, please? Thanks!

https://github.com/JacquesCarette/Drasil/blob/Issue%231433/code/drasil-example/Drasil/GamePhysics/Requirements.hs

**Comment by Nathaniel-Hu** [comment]
Hi @oluowoj, I tested the changes I made to the requirements code file, and ran into the following error:

`gamephysics: Invalid character: '%' in string "10% percent of the original development time"`

Do you have any suggestions for how I should address this issue? My current code is at the link below:

https://github.com/JacquesCarette/Drasil/blob/Issue%231433/code/drasil-example/Drasil/GamePhysics/Requirements.hs

**Comment by Nathaniel-Hu** [comment]
The above issue has been addressed and solved.

@oluowoj and @smiths, I have made the NFR edits to the requirements Haskell file for Game Physics and uploaded the stable changes (see link below). Since this change also requires that the stable HTML/LaTeX versions of the Game Physics SRS be updated to absorb these changes, should I make a separate branch and pull request for the proposed changes to the stable versions, and then create a pull request off this branch for my changes to the requirements code?

https://github.com/JacquesCarette/Drasil/blob/Issue%231433/code/drasil-example/Drasil/GamePhysics/Requirements.hs

**Comment by smiths** [comment]
@Nathaniel-Hu, your pull request should include the changes to the Drasil code and the changes to stable.  I see that you have split the changes across two PRs.  This will cause the Travis build to fail.  For good reason @JacquesCarette does not accept pull requests that break our build.

I suggest that you close your changes to stable PR and then add these commits to the other PR.

Since they are available, I will review your changes to stable, but we won't be able to accept that PR.
