### ISSUE TITLE
Template 2.0

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1469]
As mentioned in https://github.com/JacquesCarette/Drasil/commit/4c4cdf7f727136a0ba1797619a0404d9ad635175#commitcomment-33771854, we should consider adding a "template 2.0" in the future. This should be broken down into smaller, well-defined issues. We will learn more while going through the Projectile example.

# Notes
- the problem space and solution space should be separated

**Comment by smiths** [comment]
Thanks @samm82.

**Comment by smiths** [comment]
Although no sections of the template have actually been modified, the description of the template has been improved.  An associated checklist has also been written.  These documents can be found at:

https://gitlab.cas.mcmaster.ca/smiths/cas741/blob/master/BlankProjectTemplate/docs/SRS/SRS.tex

and 

https://gitlab.cas.mcmaster.ca/smiths/cas741/blob/master/BlankProjectTemplate/docs/SRS/SRS-Checklist.tex

**Comment by JacquesCarette** [comment]
As written, it is hard for an outsider to understand what this issue is about. It probably made a lot of sense in June 2019, but less so now (May 2020).  Something needs to be done to it so that it may become a proper 'to do' for someone.

**Comment by smiths** [comment]
@samm82 and I did discuss revising the original SRS template last summer, but we did not break it down into specific issues.  That still has to be done.  Rather than leave this issue open until that takes place, I have moved a discussion of this idea to the "potential projects" document:

https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/-/tree/git-svn/Planning/PotGradStdProj
