### ISSUE TITLE
Redundant Information in Notes

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1476]
In most of the examples, there is a lot of redundant information that occurs in the Description and Notes.

- [x] GamePhysics (#1834)
- [x] GlassBR (#1850)
- [x] HGHC (only has two DDs without Notes sections)
- [ ] NoPCM
- [x] Projectile (done during its creation)
- [ ] SSP
- [ ] SWHS

![redundantNotes](https://user-images.githubusercontent.com/35857611/58897489-6bb23b00-86c6-11e9-8bb7-af4be88075f0.png)

In this example, the redundant information is **q**, _g_, _T_, _t_, and possibly _C_, _ρ_, and ∇. Should these be removed from the notes and stay captured in the description?

**Comment by JacquesCarette** [comment]
My opinion: yes. Especially because this information is "linked together" and thus meant to be read as a single unit, it doesn't make sense to be quite so redundant.

**Comment by smiths** [comment]
I agree with @JacquesCarette.  The notes field shouldn't just repeat the description field.  The description field provides the symbols and their definitions.  The purpose of the Notes field is to capture the information that was lost in the transition of replacing the manual version of the Description with the Drasil version.  Since Drasil could only do the list of variables, we added the Notes field.

For this specific example, you can remove the redundant information, but please keep the new information (the last sentence).

**Comment by Ant13731** [comment]
I briefly looked through all the examples and I couldn't find any that were a direct copy of the description (some were close to defining the same thing twice, but the notes still added necessary context to the variables), so I think this issue could be closed.

**Comment by smiths** [comment]
Sounds good @Ant13731.  I agree that we can close this issue.
