### ISSUE TITLE
Missing values for constants in NoPCM/SWHS

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1503]
Some of the constants used for constraint bounds in NoPCM and SWHS are missing values, both in Drasil and manual.

The ones missing values are:

- Maximum heating coil surface area (m^2)
- Minimum heat of fusion (J/kg)
- Maximum heat of fusion (J/kg)

@smiths Can you provide values for these constants?

**Comment by smiths** [comment]
Great catch @bmaclach.  I can guess at some values, but we really would need an expert to get meaningful values.  It is too bad we don't have a way to record rationale, because if we could include the rationale with the numbers, the wording could highlight our uncertainty.

I suggest the following values:

- Maximum heating coil surface area of 100,000 m^2.  This seems ridiculously large to me.  I looked at some on-line heating coil surface area calculators and the results are in the 100 m^2 range.  They can do some tricks with shapes, and fins, and coils, though, so we can err on the side of caution.
- Minimum heat of fusion of 0.  From Wikipedia: "The enthalpy of fusion is almost always a positive quantity; helium is the only known exception.[1] Helium-3 has a negative enthalpy of fusion at temperatures below 0.3 K. Helium-4 also has a very slightly negative enthalpy of fusion below 0.77 K (−272.380 °C). This means that, at appropriate constant pressures, these substances freeze with the addition of heat.[2] In the case of 4He, this pressure range is between 24.992 and 25.00 atm (2,533 kPa)."  I think we can safely assume our temperatures won't be that close to absolute zero.  :-)
- Maximum heat of fusion.  Let us use 1000 J/kg.  I couldn't find any substances with a maximum heat nearly this large.  The largest I found was water, around 300 J/kg.

It isn't very scientific, but that will give you values.  In a proper requirements exercise, we would involve the experts at this point to vet the numbers.

**Comment by bmaclach** [comment]
Thanks @smiths. For the maximum heat of fusion, I think you were looking at values in J/g. So in J/kg, our maximum value would be 1,000,000 J/kg.

**Comment by smiths** [comment]
Yes @bmaclach,  you are correct.  Please use the value of 1,000,000 J/kg as our maximum.

**Comment by bmaclach** [comment]
Since my question is answered, I'll close this issue. The actual addition of the missing values was done as part of the fix for #1452 in #1505.

**Comment by smiths** [comment]
Great!
