### ISSUE TITLE
Issues with SSP Table of Symbols

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1626]
From #1428, the Table of Symbols for SSP should be revisited.
- [x] Use `xComp`, etc. from #1428 
- [x] Fix capitalization of "Of" after `xComp`, etc.
- [x] Fix incomplete definitions
- [x] Add missing definitions

**Comment by smiths** [comment]
@bmaclach, what do you think of the observations from @samm82 above?  I haven't thought about it deeply, but it does seem to make sense to modify SSP along the lines he is implying.

**Comment by bmaclach** [comment]
@smiths Agreed on both of @samm82's points. Using `xComp` etc. will reduce code duplication which is obviously great. And I didn't realize until now that SSP was the only example that showed the definitions in the Table of Symbols. I definitely like it better without them.

**Comment by samm82** [comment]
How would I decide which definitions to move to Terms and Defs and which are unnecessary? Should @bmaclach go through and decide, or should I just add any term that isn't defined elsewhere in the document to the Terms and Defs? @smiths

**Comment by bmaclach** [comment]
When I did my review of SSP, I added to the terms and definitions when I came across terms @smiths or I felt needed explanation. So that has already been done (though if you come across any terms that are missing that you aren't sure about, I think it would be good to add them).

**Comment by smiths** [comment]
@samm82, I agree with @bmaclach.  We have already done our pass through when we did the major revision of SSP.  I think you can go through and add any terms that you think are missing.  It isn't really "wrong" to have more terminology and definitions.  We'll have a pull request to review to make sure that the changes are good, but I'm sure they'll be fine.  The action that I would be more concerned about is if terminology is being deleted.  We don't want to delete information.  😄

**Comment by samm82** [comment]
How does this sound for a definition of effective stress: "The stress in a soil mass that causes volume changes and mobilizes the shear strength arising from friction" (from [this website](http://environment.uwe.ac.uk/geocal/glossary/gloss_e.htm#EFFECTIVESTRESS))? I can't find anything on effective normal stress - would its definition be related to it the previous definition? Which plane would it be normal to? @smiths

**Comment by smiths** [comment]
@samm82, you didn't quite follow the original source for the definition of effective stress.  The original uses the word effective in the definition, and I think we should too.  Maybe you left it out because It is circular to define a term using the term itself, but you are already using stress in the definition.  😄 The definition is of a compound term, so using each of the parts of the term in the definition doesn't seem circular to me.  I would add the part of the definition from the Wikipedia page (https://en.wikipedia.org/wiki/Effective_stress):

"It represents the average stress carried by the soil skeleton."

The part about the soil skeleton is what I remember from my soil mechanics course all those years ago.  The goal of effective stress is to separate the effects of water (pore water pressure) from the load carried by the soil.

As far as effective normal stress, a part of the definition you cited defines it.  The part about volume changes is due to normal stresses.  You could define effective normal stress as: "The normal stress in a soil mass that is effective in causing volume changes.  It represents the average stress carried by the soil skeleton"
