### ISSUE TITLE
Fix IM Column Width

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1638]
The width of the first column in the IMs should be increased so that "Output Constraints" fits on one line in the LaTeX:

![out cons](https://user-images.githubusercontent.com/35857611/60295338-7b9df300-98f1-11e9-8be3-4c9c6d54d4f1.png)

**Comment by smiths** [comment]
@samm82, can you include a screen shot so that others can see what we are talking about.  My guess is that all of the examples will benefit from a minor increase to the width of the first column.

**Comment by samm82** [comment]
@smiths Do you specifically want the column widened? We could also see how to force the LaTeX to push the whole word to the next line.

**Comment by smiths** [comment]
Good point @samm82.  I made the mistake of specifying a potential solution, instead of specifying the problem.  The problem is that the text "Output Constraints" is spaced awkwardly and has a seemingly unnecessary word-break.  Whatever approach works to solve the problem is fine with me.  :smile:  We want it to be a fix that won't hurt the other examples, and won't introduce new problems.

**Comment by samm82** [comment]
Looking into it more, I think that making the column wider is the correct approach to take 👍
