### ISSUE TITLE
Capitalization Consitency In Folders Containing Examples

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1686]
In build, stable, and drasil-example, we have different capitalization styles for the folders.
Very minor but I feel like they should be consistent.

<img width="616" alt="build" src="https://user-images.githubusercontent.com/28261339/60924872-40e07700-a270-11e9-99f1-11490d587776.png">
<img width="622" alt="stable" src="https://user-images.githubusercontent.com/28261339/60924873-40e07700-a270-11e9-84a1-adf34c43b449.png">
<img width="624" alt="example" src="https://user-images.githubusercontent.com/28261339/60924871-4047e080-a270-11e9-86f1-7da1a9980469.png">

I believe @Mornix prefers folder names to be lowercase.
@smiths @JacquesCarette

**Comment by smiths** [comment]
Thanks @danscime.  I like issues like this.  It shows I'm not the only one that is bugged by inconsistency.  😄  The most important thing for me is consistency, but if I had to pick, I prefer lowercase folder names (easier to type).  😄

**Comment by danscime** [comment]
If @JacquesCarette agrees, I will go ahead and make these changes.

**Comment by JacquesCarette** [comment]
Consistency is good. And {Chipmunk, gamephys} are also inconsistent, while you're at it!  Oh, and {HGHC, Tiny} too.

**Comment by danscime** [comment]
@JacquesCarette Those inconsistencies will be tracked in #1684.

**Comment by JacquesCarette** [comment]
I think this is all done, but I'll need to double-check.

**Comment by Awurama-N** [comment]
I renamed the files in my editor and tried to commit the changes, but there "are no changes to be committed"
is there a better way to do this so the changes are recognized?

@smiths @JacquesCarette

**Comment by smiths** [comment]
@Awurama-N, what files did you rename?  The original issue was about renaming Folders, so we should make sure that the changes you are making are desired changes.

To rename a folder you can use `git mv`.  Details can be found at:

https://www.kunal-chowdhury.com/2016/11/git-cheatsheet-git-mv.html

**Comment by JacquesCarette** [comment]
Also on platforms whose file system is not case-sensitive, this may be impossible to do.

**Comment by JacquesCarette** [comment]
@Awurama-N was there really something to fix here? I was pretty sure this was already fixed, I just wanted someone to verify this is indeed so.

**Comment by Awurama-N** [comment]
Yes changes were not made yet. The stable folder names are all lower case whilst the build folder names have some capitalization. The same as the screenshot at the start of this issue

**Comment by JacquesCarette** [comment]
It would indeed make things easier if they were all lower-case.  You might not be able to do it yourself, depending on which OS you are on.

**Comment by balacij** [comment]
Since it looks like most are in favour of the lowercase letters, I think this is a bit simplified actually.

To resolve this, I think you can:
1. Edit the `Makefile`'s `<EXAMPLE>_DIR` variables. Each one of them right now is used to "correct" the lowercase names inputted for commands for each of the examples.
2. Rename all `pdController`s to `pdcontroller`. In the `Makefile`, there are 2-3 areas that have a reference to `pdController` and those should be changed to `pdcontroller` (Note that you should not be renaming variables here, only the values of the variables!). In `drasil-example/package.yaml`, there is an executable created called `pdController` (again, should be renamed to `pdcontroller`).
3. Rename `stable/pdController` to `stable/pdcontroller`. In other words, renaming stable's `pdController` folder to `pdcontroller` to remove the 1 uppercase letter.

I think this is all that would need to be done, but it would be good to run through the CI steps manually on your machine as well to validate that this would work. @Awurama-N what do you think?

**Comment by Ant13731** [comment]
Also, when this issue is completed, the hardcoded `"pdController"` can be replaced with `$ map toLower pdController`:
https://github.com/JacquesCarette/Drasil/blob/3573f089df4290f0162b11ed366537512a527b99/code/drasil-website/Drasil/Website/Example.hs#L63

**Comment by Awurama-N** [comment]
@balacij I agree. But when i tried editing the capitalization in the Makefiles and then saving it it still says there's nothing to commit?

**Comment by Ant13731** [comment]
I think Mac OS might ignore case. Maybe we could rename it to something completely different, save, and then rename it to all lowercase?
I can try on Windows and my Linux subsystem to see if that would work when I work on the website stuff.

**Comment by smiths** [comment]
If I remember correctly @Awurama-N had this same problem with renaming some folders.  @Awurama-N, how did you solve this problem?

**Comment by balacij** [comment]
@Awurama-N and I just figured it out over Teams. It was just a miscommunication about which Makefile to edit. The `code/Makefile` was the Makefile in question, not the ones in the `build/` folder, which is why there was nothing to commit.

**Comment by smiths** [comment]
Great!
