### ISSUE TITLE
Add "Variables" to GOOL

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1689]
Currently GOOL has a single type `Value` used for both values and variables. This means that any value can be passed in places where really what is wanted is a variable. For example, a `Parameter` can be made from an expression (which is a `Value`), which doesn't make sense -- a `Parameter` is just a variable. We should therefore separate `Value` into two types: `Variable` and `Value`.

A `Variable` would be equivalent to some `VarData` type that holds a (string) name and a type.
A `Value` would be equivalent to the current `ValData` type, except the `valName` field can be removed.

Then, `Variable`s should be used instead of `Value`s where appropriate:
- `Parameter`s should be made from `Variable`s, not `Value`s
- Assignments should take a `Variable` (being assigned to) and a `Value` (being assigned), instead of 2 `Value`s
- Every instance of a `Value` being passed in GOOL should be evaluated to determine whether it should instead be a `Variable`. 

(This issue based on discussion in #1680)

**Comment by JacquesCarette** [comment]
Note that a `Variable` should still be a `Value` -- i.e. there should still be a case of `Value` that contains the data for a `Variable`.  But otherwise yes to all of the above.

Note that you'll likely want the concept of an `lvalue` [lvalue at wikipedia](https://en.wikipedia.org/wiki/Value_(computer_science)#lrvalue) too. It does make sense to separate things where a `Variable` is a subset of lvalue but not the same.
