### ISSUE TITLE
Make Definition Format Consistent

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1754]
The definition of the gravitational constant (updated in #1522, shown below) doesn't fit with how it's used in the sentence. I've previously noticed some inconsistencies with the definitions while working on other issues, like inconsistent periods (partially fixed in #1160). These are the inconsistencies I've noticed so far, with my proposed fixes in parentheses:

- Capitalization (should be made lowercase)
- Leading articles (should be removed?)
- Ending periods (should be removed, as per #1160)

What are your thoughts @smiths?

![image](https://user-images.githubusercontent.com/35857611/61805986-df3e1200-ae04-11e9-9976-e27e74d7da75.png)

**Comment by smiths** [comment]
Yes, @samm82, the definition does not fit into the sentence.   I would prefer "G is an empirical physical constant ..."  You are right about the capitalization and removing the "the," but I do not understand the point about the period.  The sentence should end with a period.

**Comment by samm82** [comment]
My fixes were in regards to the definitions in general, for example in:
```haskell
gravitationalConst :: ConceptChunk
gravitationalConst = dcc "gravitationalConst" (cn "gravitational constant" )
  "An empirical physical constant, used to show the force between two objects caused by gravity"
```

Some of these definitions have periods hardcoded in them, and they shouldn't. As mentioned in #1160, the period should be added when actually using the definition, not while defining it. So all periods at the ends of sentence would still appear, just not hardcoded in the definitions themselves.

**Comment by smiths** [comment]
@samm82, yes, I agree that the period should not hardcoded in the definition, but added at the end of the sentence.  Will updating the ConceptChunk definition cause problems elsewhere in the documentation?  That is, does fixing the text in one spot, break it somewhere else?

**Comment by samm82** [comment]
Some of the `Sentence`s in the examples will have to be fixed to deal with the changed definitions, yes.

**Comment by smiths** [comment]
@samm82, I'm glad that you are aware of the consequences of your change.  It sounds like you have it under control.  One thing we do not want to do is to try to handle every English language situation.  We tried something like this in the early days of Drasil and it can become a major distraction.  It is great to automate, but the nuances of the English language make this a time sink that we don't want to invest in (at least not at the moment).  It sounds like you are aiming for a definition that will need a minimal amount of customization when it is used in the documentation.  Sounds good to me.

**Comment by samm82** [comment]
There is a comment saying to make the definitions of strain and stress clearer. The current definitions are:
Strain: a measure of deformation of a body or plane under stress
Stress: forces that are exerted between planes internal to a larger body subject to external loading

Some potentially better definitions from https://www.engineeringtoolbox.com/stress-strain-d_950.html (slightly altered) are:
Strain: the deformation of a solid due to stress
Stress: the ratio of an applied force to a cross-sectional area

What do you think of the new definitions, and should I add the reference to the link? @smiths

**Comment by samm82** [comment]
For definitions in the examples, there are a lot that are created locally for unitals. Should they all be pulled out into the Concepts file for uniformity and to increase the chances for reuse?

**Comment by smiths** [comment]
If definitions are repeated in different examples, they shouldn't be recreated locally.  I don't think we want to rush into pulling everything into the Concepts file.  To start with, you might want to create an issue for each of the potential concepts to move.  We would want to know the consequences of the move.  There may be unintended consequences, especially if the concept name is reused, but with subtly different definitions.

@samm82, you are combining separate issues/questions in the same issue again.  I think we've talked about this before.  😄 It is easy for your questions to get lost when they are posted this way.  It is also more difficult to reply to them, since I have to repeat some of your question, so that you (and others) know which of above points are being referenced.

From above: https://github.com/JacquesCarette/Drasil/issues/1754#issuecomment-515599954

The new definitions of stress and strain are a bit better.  However, strain is not deformation, deformation is deformation.  Strain is a dimensionless version of deformation.  For instance, for a uniaxial deformation, the deformation might be u.  In this case the strain is u/L, where L is the length of the specimen.

I prefer this definition "Strain is a measure of deformation representing the displacement between particles in the body relative to a reference length."  I found this on Wikipedia.

The proper way to define strain is actually much more detailed than what we have done.  I've written up the definition of strain in the following document:

https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/tree/git-svn/FamilyOfGamePhysicsEngines

We aren't ready to get into this kind of detail though.

The definition of stress you have given isn't too bad, but again, the concept is really much more involved, as given in the document linked above.  The short definitions that are given are really definitions of normal stress and normal strain, and many assumptions are implicit in those definitions.  Again, this isn't really the time to get into the full story on stress and strain from a continuum mechanics point of view.
