### ISSUE TITLE
Generate sample input file along with source code

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1755]
Drasil should generate a sample input file to go with the source code it generates for each example.

From https://github.com/JacquesCarette/Drasil/issues/1716#issuecomment-514693617:
Generating the comment lines based on the inputs in Drasil is very doable, and we could generate the input values based on the typical values entered in Drasil. Plus, with #1728 I've added the ability to generate non-source code files as part of a GOOL Package, so generating a sample input file should be easier now.

This could be something we could also turn off or on with a `Choice`, if we wanted.

**Comment by smiths** [comment]
I like this idea @bmaclach.  It doesn't sound like much work, and it is another example of reusing the same information in a different place.  @Mornix might want to follow along, since this seems like an example of something that he was looking for in his project write-up.  😄

**Comment by bmaclach** [comment]
I've started working on this but hit a roadblock when it comes to getting the typical value of each input to write to the sample input file. In short, at the level of `Code`, nothing has a typical value. 

This is because the input format is described by a `DataDesc`, where the inputs themselves are represented by `CodeChunk`s. `CodeChunk`s are built from `QuantityDict`s, which do not have typical values. Typical values are introduced in `ConstrainedChunk`s, which are built from `QuantityDict`s:
https://github.com/JacquesCarette/Drasil/blob/7298f4d67dc2dfaae0743981d85c649411758168/code/drasil-lang/Language/Drasil/Chunk/Constrained.hs#L24-L29
`reasV` is the typical value. It's also a `Maybe`, which raises questions about how to handle the `Nothing` case if it arises when generating the sample input file. 

Here are some ideas I've brainstormed for how to deal with these problems:
- Update `CodeChunk` to be built from `ConstrainedChunk` instead of `QuantityDict`.
  - Probably not great because not everything we want in `Code` will be a `ConstrainedChunk`. Also, this does not help with the case where the typical value is `Nothing`.
- Introduce typical values to the `QuantityDict` chunk instead of the `ConstrainedChunk`. 
  - Again, doesn't help with the `Nothing` case of typical value. There may also be a good reason why typical values were tied to the `ConstrainedChunk` in the first place.
- Introduce a new type on top of `CodeChunk`, say `CodeChunkWithTypicalValue`, for which we can probably come up with a better name. This type would always have a typical value (i.e. the field for typical value would not be a `Maybe`). We'd then update `DataDesc` to represent inputs as `CodeChunkWithTypicalValue`s instead of `CodeChunk`s.
- Don't use typical values in the sample input file we generate. We could instead generate placeholder text. The sample input file would then be more of a template for a user of Drasil to fill in, rather than being a working input file without modification. Something like:
```
# length (mm)
<value of length>
# width (mm)
<value of width> 
# weight of charge (kg)
<value of weight of charge>
...
```

I would lean towards the 3rd option above. The 4th could work too, but since the generated input file wouldn't be usable without modification, we would still have to keep a hard-coded copy of a working input file in the repo to use in our Travis builds. Thoughts @JacquesCarette @smiths?

**Comment by JacquesCarette** [comment]
Yes, definitely 3rd option. We need a 'hierarchy' of code chunks that is somewhat similar (but likely smaller, and different) to that of the SRS chunks.

In this case, I would think that we'd want a `PointedCode` chunk which contains a value (and not a `Maybe`!) as well as a `CodeChunk`. Having a `ConstrainedCode` (and then `ConstrainedPointedCode` too) might also make sense.

**Comment by bmaclach** [comment]
@JacquesCarette I added a `PointedCode` chunk but shortly ran into more problems...

Since `DataDesc` is now built from `PointedCode`s instead of `CodeChunk`s, all inputs now must have a typical value (since we always make a `DataDesc` out of our inputs). This is all fine and good (or at least, I think it is), but the problem is that, as mentioned above, typical values are introduced with the `ConstrainedChunk`, which means if we want to add a typical value to a quantity with no constraints, we have to create a `ConstrainedChunk` and pass in an empty list of constraints, which I know we don't want to do (#1524). I don't understand why both constraints and typical values are tied in to the same level of chunk. Can we create a new chunk in between `QuantityDict` and `ConstrainedChunk` that adds the typical value?

Also, since `ConstrainedChunk` has a `Maybe Expr` for the typical value but `PointedCode` just has an `Expr`, I had to use `fromMaybe` for the constructor that makes a `PointedCode` out of `ConstrainedChunk`s (or any other chunk that is an instance of `HasReasVal`). I know you've said that `fromMaybe` is usually bad. I looked into where we use the typical value and it was only used in one place, and `fromMaybe` was also used for that. This makes me think that it doesn't need to be a `Maybe` at all, in any chunk. Can we update the `HasReasVal` class and all chunks that are instances of that class to represent the reasonable value as an `Expr` instead of `Maybe Expr`?

**Comment by JacquesCarette** [comment]
That constraints and typical values are tied together is a historical artifact of the examples we had. It can and should be split into separate ideas.  Please do split things. 

Should all our inputs really have a 'typical value'? That seems like going overboard to me.

It will then make sense to fix all of the chunks to either have a typical value to **not** use a `Maybe`. And for `HasReasVal` to return it. But you'll also need a new class `MayHaveReasVal` that does return a `Maybe` too. Because it will make sense for certain things to not have a typical value.

Uses of `fromMaybe` is a strong code smell that reflects a bad design. In this case, the bad design is the conflation of 2 ideas into a single class, and which later pops up in this way.

**Comment by bmaclach** [comment]
If we don't enforce typical values for every input, the consequence will be that when generating our sample input file, if we hit an input with `Nothing` for the typical value, our sample input file wouldn't be immediately usable. Maybe we are okay with that?

I've also just remembered that I don't think we actually run our generated code as part of our Travis build. We just compile it. So if we don't have a perfectly working sample input file, that's not a concern for our Travis builds. It is a concern for me when I go to run the examples after I make changes, but I can deal with that if need be.

If we do want to add running the code to the Travis build in the future, we will just need to make sure that we add a typical value to every input for our own examples. Either that or continue to keep a valid input file in the repo to use instead of the generated input file.

**Comment by JacquesCarette** [comment]
So I'm not convinced that generating our sample input file is a good idea. It reminds me of the "fallacy of the average" - https://www.thestar.com/news/insight/2016/01/16/when-us-air-force-discovered-the-flaw-of-averages.html .  

I think that 'sample input file' is a different idea than having each value that corresponds to an input somehow having a typical value.  So that 'sample input file' should likely be made up of data that was human-curated; the actual file might still be generated (so it can be commented, etc).

**Comment by bmaclach** [comment]
@JacquesCarette I see what you mean. So we may still want to generate an example input file, but the values of the inputs should not come from the typical values. Instead we would get a set of valid data from some other source (a source specifically intended for this purpose). 

Should the changes to reasonable values described above still be implemented? (changing `HasReasVal` and appropriate chunks to not have `Maybe`, and adding `MayHaveReasVal` with a `Maybe Expr`)

**Comment by JacquesCarette** [comment]
Yes, those changes to reasonable values are all positives and ought to be implemented. Maybe not as urgently anymore, but still worth doing.

**Comment by smiths** [comment]
Great discussion!  I also really like the fallacy of average article. I like the proposed ideas from above.  Another step that we should take in the future is to better characterize the input values.  A single combination of values could be meaningless (as the average fallacy shows), but input "profiles" are part of what is needed to select calculation algorithms.  I can write down a second order differential equation with constant coefficients and show how the numerical algorithm needed changes dramatically as the ratio between the coefficients change.  (I'm familiar with this example from my Masters thesis since I needed to use upwinding schemes to solve my ODE because polymers are poor thermal conductors.  Most of the heat transfer was due to advection, not diffusion.)  We could come up with many more examples.  I wonder if we need a heading in the template for "Properties of Valid Input," like we have a "Properties of Correct Solutions"?  Of course there can be problems where our goal is to solve the problem for very general input, but in many cases physics gives, and common sense, give us reasonable "bounds" that we should take advantage of.

**Comment by bmaclach** [comment]
I separated the reasonable value improvements to #1808.

In terms of generating the sample input file, where would we like the data source to be? My first thought was that we could add a field to `SystemInformation`, say `sampleData :: [Expr]`, which contains the values of the inputs in a sample data set, in the same order as in the list of inputs. Then we would probably want some check that the size of that list is the same as the size of the inputs list.

@JacquesCarette @smiths

**Comment by smiths** [comment]
Your design sounds reasonable to me @bmaclach, but @JacquesCarette is the design expert.

**Comment by JacquesCarette** [comment]
This feels "too untyped" to me. Weirdly, I think that using (say) `.csv` files for data inputs might be better. These could then be read in using the internal description of the format (i.e. the same one used for generating reader code) for validation.

**Comment by bmaclach** [comment]
@JacquesCarette To clarify, if we read `.csv` files for the sample data, would that be a fixed decision? So Drasil would be saying "give me your input data in `.csv` and I will generate an input data file in the format you chose"? In other words, if a user wants to generate a sample input file, we require them to provide a sample input file in `.csv` format?

If I'm understanding that right, then why wouldn't the user just choose `.csv` as their input format in the first place? I guess one reason they might want to do this would be because they could add comments to the input file for free.

But maybe I'm misunderstanding your suggestion.

**Comment by JacquesCarette** [comment]
I'm not wedded to `.csv`. And what I really mean is to have a single 'standard' format (it could be any kind of text files that allows some amount of documentation that we can easily parse) for supplying sample input. This choice would be for the developer to make for generation-time purposes; the run-time input format of the generated code can still be arbitrary (but describable). 

Indeed, even the generated sample input files can be in (multiple!) chosen formats, as chosen by the devs as 'supported' run-time formats.

Basic ideas:
- separate the choice of generation-time input description and run-time input formats supported
- fix a single (simple) generation-time input format
- use the same "input description" language both for generation-time reading of input and generation of reading code
- make generation-time 'sample' data a non-code artifact that is still human-readable.

**Comment by bmaclach** [comment]
@JacquesCarette Based on the above, here is my understanding of the series of steps that would be followed in a use-case, presented to perhaps expose mistakes in my understanding:
- User chooses format for sample data that they will supply to Drasil (henceforth referred to as F1)
- User chooses format(s) for inputs to be read by generated code (henceforth referred to as F2)
- User manually creates a sample data file in F1 and passes it to Drasil
- Drasil reads sample data (in F1) with the help of `DataDesc` language
- Drasil generates sample input file(s) in F2 (again with the help of `DataDesc`) using the data it read in the previous step
- Drasil generates code to read input files in F2 (again with the help of `DataDesc`)

Specifically, here are some questions I have:
1. The first 2 of your points under "Basic ideas" seem contradictory to me. If the generation-time input description is a choice, how can we fix a single generation-time input format?
2. Why would a user want their generated code to accept inputs in a different format than the format of the sample data they are providing to Drasil?
3. I was thinking a possible answer to 2. would be that F2 could allow for documentation that the user basically gets for free. But from your last comment, it sounds like you want F1 to already be documented and human-readable? This seems weird, especially considering that the sorts of things that would be documented for the inputs are already captured in Drasil, but we'd be asking the user to supply them again in the sample data they give to Drasil? (and indeed, the inspiration for this issue was to generate the documentation strings in the input file instead of keeping them hardcoded)

I'm fairly certain there's a big piece of this plan that has gone over my head and is causing my confusion, just need some help nailing down what that is.

**Comment by JacquesCarette** [comment]
I didn't expand enough, which is probably what caused the confusion.
What I meant is that we can fix a lot of things in format F1 (csv, nothing encoded in binary, clear markers, etc) once and for all. This is the 'meta' format, and we can restrict it as much as we want to make our own lives easier. There are still choices, because what actual data is needed is not fixed for all applications.
For format F2, the actual data files might be in evil forms -- from XML to weird binary encodings. Because that might be required by the application domain. So the generated code must be able to deal with the data that it gets in "normal operating environments".
For Q3, I wasn't thinking of documenting the format, but documenting the choice of data points [i.e. why is this a decent 'sample input'].

**Comment by bmaclach** [comment]
Thanks @JacquesCarette. I think it's clear enough now for me to start working on this!
