### ISSUE TITLE
[GamePhysics] Duplicated Chasles Theorem

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1815]
The DD below should be updated with the correct label/refname and the source from Wikipedia, and the TM should be removed.

![tm](https://user-images.githubusercontent.com/35857611/62805939-6e168400-babf-11e9-9666-c0c9751d0ad2.png)

![dd](https://user-images.githubusercontent.com/35857611/62805900-55a66980-babf-11e9-804b-003f35259e60.png)

_While updated the Notes section in the examples. I noticed that Chasles' theorem appears twice, once as a TM and once as a DD. The only differences I see are that 
a) the labels are different
b) the DD has more assumptions

Is the DD a refinement of the TM because of the assumptions, or should only one be kept? If so, which one?_

**Comment by oluowoj** [comment]
@samm82, yes, I actually moved it from a TM to a DD as per @smiths and have not removed the one in TM, I just wanted to be more convinced its a DD. @smiths I know you wanted to make this a DD, is it still the case? @samm82  what do you think? 

@samm82, as per label, I want something more descriptive than Chasles' , unless @smiths thinks otherwise. The definition relates to the velocity of an arbitrary point on a rotating and translating body. I have not found a lot of good info. on Chasles theorem online, so not sure about this label. If you find anything please post here. But let's see what @smiths thinks

Thanks for spotting this

**Comment by smiths** [comment]
@oluowoj, can you tell me your opinion on whether this is a TM or a DD, and why?  I don't want to be the only one that has an opinion on this.  :-)  I think over the course of the summer we have come to a fairly reasonable distinction between TMs and DDs, but if I cannot communicate the distinction to others, than it isn't as good as I hope.  :-) 

We've discussed it before, but let me recap again the distinction that we are using as a working model.  TMs are refined to create new models, that are called GMs or IMs.  DDs are not refined; they are just used.  GDs and IMs are derived, or refined, from other models.  DDs are not derived; they are just given.  If a DD includes a derivation, then that means it is refining other models, which would make it a GD or an IM.

I've been using the above mental model for most of the summer and it seems to be working.  Of course, I'm open to refinement or change.  If there is an inconsistency, that would be good to know and then we can fix it.  I think this is what is meant by grounded theory.  :-)

I'm not trying to test you @oluowoj.  I just want you to apply the above mental model to Chasles' theorem and see what decision you make.  Whatever you say is useful information.  Much more useful than me just saying what to do.

As far as information on Chasles' theorem, my first google hit was:

https://en.wikipedia.org/wiki/Chasles%27_theorem_(kinematics)

In the long term we should find a proper publication to cite, but in the short term, the Wikipedia entry would be helpful.

**Comment by oluowoj** [comment]
@smiths sorry, I keep asking questions related to the model, I just try to make sense of it with every update that I make. This does not look like a DD to me, but got a bit confused when you asked to move it to DD. More like a TM because it gets refined to a GD. Correct me if I am wrong. What is your opinion and why? 

I understand you are not trying to test me, more like putting me on the spot which is fun :)

I already saw the wiki page for Chasles' theorem which is insufficient. I wanted to verify the equation and was looking for a reference related to the equation in the manual version. I hope we can find a publication to cite.

**Comment by smiths** [comment]
Thank you for your quick reply @oluowoj.  Don't apologize for asking questions!  That is how both of us learn!  I already learned something from your response.  :-)  We have a different definition of refined.  My mental model may still prove to be flawed, but I am making a distinction between "refined" and "used."  A model is refined to another model if it is changed by the refinement.  When we change a general 3D equation to a 2D equation, we are making a refinement, by applying the assumption that the third dimension does not matter.  If we use a definition, like the definition of density, we aren't refining, or changing that definition, we are just using it.

I had to go back to the manual version of the game physics case study to investigate this, since the Drasil version does not have Chasles' theorem used anywhere.  At least, a search through the Drasil generated files for Chasles, or for the referenced by field, does not show anything.  In the manual version, Chasles' theorem is used in the derivation of the impulse.  Chasles's theorem is not changed or modified by this derivation; it is used, as is, by the derivation.  This is why I suggested that Chasles' theorem is a DD, not a theory.

If we had a model where we changed from a 3D version of Chasles' theorem to a 2D version, then we would need to consider the theorem as a TM.  We don't do that though.  We take Chasles' theorem as given.  We do not derive it; we do not refine it; we use it.

If Chasles' theorem was built from more fundamental building blocks of translation and rotational motion, then those chunks would be the DDs that Chasles' was built upon and Chasles' would be "higher" up.

The above examples highlight that the categorization of Chasles's as a DD is local to our documentation for Game Physics.  If we did things differently, or in a different problem context, it might not be a DD.  This is the same as how the definition of acceleration is a TM in Projectile, when it would be a DD in other problems.

It might help you to think about the picture outside my office door (the one on the poster that we discussed).  The distinction between the definitions are made for the purpose of avoiding cyclic import cycles and to highlight the traceability between the models.  Knowing that one model uses, or refines, another model is useful information.  For instance, if we find an error in one of the parts, we should trace it to the others to see if the error propagated.

If you would like another source of Chasles theorem, the links on the Wikipedia page are a good start.  For instance, the course notes at the following link show a proof of the theorem:

https://www.seas.upenn.edu/~meam520/notes02/EulerChasles4.pdf

Any book on spatial kinematics is very likely also going to have this theorem, although it might look different.  Citing the Wikipedia page really is fine for now though.

**Comment by samm82** [comment]
Should I tackle this or do you want to @oluowoj?

**Comment by oluowoj** [comment]
@smiths, thanks for clarifying this. My thought about refinement was ditterent, thanks for providing more info.

@samm82, please go ahead with this. We update and keep the DD and remove the TM.

**Comment by samm82** [comment]
@smiths @oluowoj Just to be sure, which Refname (ChaslesThm vs. chalses) and Label (Chasles' theorem vs. Velocity At Point B) should I use for the DD?

Also, am I correct in assuming the Wikipedia article should be added as a source to the DD (at least for now)?

**Comment by oluowoj** [comment]
@samm82 , Refname: ChaslesThm
                     Label: Chasles' Theorem
and yes, the wiki link is as source. Thanks

**Comment by samm82** [comment]
Oh no. I think based on our discussion today that Chasles' theorem should have been the TM that was refined into a GD for "velocity at point B" (not a DD). We might have to revert this change. @smiths @JacquesCarette

**Comment by smiths** [comment]
If we are just going to have Chasles' Theorem for the specific vectors used (velocity at point B), without deriving it, or refining it, then it should be a DD, as originally planned.  The original idea was that this specific instance of Chasles' Theorem (velocity at point B) was a "given."  Now that you have introduced the notion that the specific version of Chasles' Theorem (velocity at point B) in the documentation is a refinement (renaming) of the more general theory, you are correct that we cannot have a DD.

With the new discussion, you are correct that Chasles's Theorem should be a TM and "velocity at point B" should be the refinement of that TM into a GD.

**Comment by oluowoj** [comment]
Sam, please add me as a reviewer on this one? So I can keep a track of this change.
