### ISSUE TITLE
Acceleration due to gravity - GD

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1823]
<img width="268" alt="image" src="https://user-images.githubusercontent.com/43192745/62914106-ba322480-bd5c-11e9-9a5b-b9ed0f9600f7.png">

@smiths, I think we should be defining equation for 'g' here and not 'F'? And then if we already defined 'g' as a vector then we do not need to specify g as having x and y coordinates right?

**Comment by smiths** [comment]
Yes, based on the label "acceleration due to gravity", it makes more sense to define g.  The definition of g should be the equations at the end of the Derivation section.  However, the equations given are wrong.  (I'm looking at the case study version, because this is not yet in Drasil.)  Equation 4 is correct, in terms of the vectors, but the simplification to individual vector components is incorrect.  The x and y components come from the unit vector in the direction of r (r hat), not from the scalar quantity.  The scalar (G*M/|r|^2) is the same for both the x and y components.

Rather than present the g_x and g_y components, you can just rearrange Equation 4 to be an explicit formula for the vector g.  This is what will be shown for the Equation in GD3.

**Comment by oluowoj** [comment]
Thanks for the clarification, this has been addressed in PR #1828
