### ISSUE TITLE
Code variability: double versus float

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1863]
A "low hanging fruit" code variability is to switch the computational representation of the mathematical concept of real between double and float, for languages that make the distinction.  Double will have twice as many bits dedicated to representing floating point numbers.  We (@bmaclach, @JacquesCarette and myself) discussed this issue on August 29, 2019.

**Comment by bmaclach** [comment]
In thinking about implementing this via our plan for #1866, a couple questions came up:

1. Python does not support floats. A `float` in Python is actually a `double`, and what other languages call a `float` is not available in Python. So would we throw an error if someone chooses to uses floats and generate Python? Or can we just generate the same Python regardless of the choice between floats and doubles?

2. If we do want to throw an error in Python, then this would be our first case where Drasil's generator would have to do a check on which language is being generated: if `Float` and `Python` are both chosen, then don't use floats and instead skip to the user's second choice (assuming we implement this choice as an ordered list of the user's preferences, as we have done for similar choices). We try to avoid doing checks on which language we are generating, though. Would a check like this be okay in cases like this one, where we are checking if the user's other choices are compatible with the language(s) they chose? Or would a better implementation be to have GOOL read this choice directly in the renderers to determine which code to generate, so our generator doesn't need to check the choice and instead just passes it along to GOOL? 

Thoughts @JacquesCarette @smiths?

**Comment by JacquesCarette** [comment]
1. Excellent question. At the very least, we should give some sort of diagnostic warning. But I think this is a bigger design decision that needs discussion.
2. I think language choice should be a choice - and we will have 'dependent choices'. What we do with choice conflict is an interesting question.

I think we want to have language choice be, as much as possible, orthogonal to all other choices. This is not going to always be feasible, but we'll have to make explicit decisions, with a decent rationale, for the exceptions.

**Comment by bmaclach** [comment]
@JacquesCarette 

1. I agree we should at least give a warning. More generally, I think that in any case where a user passes in an ordered list of preferred choices, if we don't use their first choice, we should log somehow which choice we ended up using (and why, if that's feasible). 
   -  The above is good for the case where the user actually passes an ordered list with multiple choices. But what about the case where they pass in only one choice in their list? If they pass `[Float]` for this choice and want to generate Python, we would have to throw an error because they didn't specify `Double` as their second choice. My personal feeling on this is that throwing an error in that case seems excessive/annoying. `Double`s are the natural "other" option here, so I feel like we should just use `Double`s (and log that we did this) instead of throwing an error. In general, I wonder if we should define a fixed "fallback list" for these types of choices (i.e. any choice that is implemented as an ordered list). For example, our "fallback list" for the double vs. float choice could be `[Float, Double]`. Let's say a user passes `[Float]` for this choice and wants to generate Python. Instead of throwing an error, we could fall back to the fallback list and use `Double`. In general, the actual ordered list we use in the generator would be `nub $ list passed by user ++ fallback list defined by us` (`nub` preserves the order of the first list). 

2. If we implement fallback lists like I've described above, then the dependency between language choice and double/float choice would never result in an error. That means the user would never have to change their other choices based on which language they choose. We would still need to decide whether to handle this choice conflict in Drasil (by checking the chosen language against the double/float choice and calling different GOOL functions based on the result) or in GOOL (by having GOOL's `double` function read the double/float choice, which decides on the `Doc` it generates), but regardless of which way we choose, the user-facing behaviour would be the same.

**Comment by JacquesCarette** [comment]
I think the idea of a fallback list is good, but I don't like the idea of not listening to a users' request. Dumb requests should result in errors, not us trying to patch things up anyways.

I think the best way to handle that would be to have a "consistency checker" of choices that runs first [and could be run independently].

**Comment by bmaclach** [comment]
I've started looking at this again, and found another problem that makes this not so straightforward. From #1866, our current plan for implementing this was to have users define a map from `Space` to `[CodeType]` and use this to match each chunk's `Space` to the first appropriate chosen `CodeType`. This is similar to what we did with concept matching with pi.

One of the arguments to our function for generating code is a `CodeSpec`. The `CodeSpec` is like `SystemInformation` but in the context of code -- so the chunks in a `CodeSpec` are already in the code context, and their type is stored as a `CodeType`. In other words, the mapping from `Space` to `CodeType` has already happened before we start generating code. This is fine, it just means our check against a new `SpaceMatchMap` would have to happen during the construction of the `CodeSpec`. The problem with that, though, is that the `CodeSpec` is not target-language-dependent.

What this boils down to is if you choose to represent reals as floats (first choice) or doubles (second choice), and you choose to target a combination of languages that includes Python, then in all chosen target languages you will get doubles, because floats are incompatible with Python. This does not seem like the behaviour we want -- I think the users should still get doubles in the languages where that is possible, right?

If so, then what we need to do is delay the `Space -> CodeType` translation so that it can be done during the code generation, and therefore happen differently based on the language currently being generated. This will mean changing `CodeChunk`s and probably also `Func`s to store their type as either `Space` or as a function of type `SpaceMatchMap -> CodeType`. The function is a messier type, but I think the better choice because it will grant the needed flexibility to handle cases where we need to force a certain type regardless of the user's choice (for example, if an external library method requires a type to be double but the user has chosen `Float`, we could force the type for that specific `CodeChunk` to be double by setting the `SpaceMatchMap -> CodeType` function to `const double`).

@JacquesCarette, please let me know your thoughts!

**Comment by JacquesCarette** [comment]
We definitely want to delay making this choice until later, i.e. when we have more information to make it.

I don't see how the function type adds more flexibility than `Space`? The logic in the back-end could be to combine user preferences (which would need to be available) with other constraints. So while a user might prefer `Float`, their preferences might be incompatible with the context, so they get `Double` (assuming that's in their choices).  If they only choose `Float`, they should get an error, as that is incompatible with other demands.

**Comment by bmaclach** [comment]
@JacquesCarette  `Space` and context would be sufficient for most of our modules, which have dedicated generation functions so all of the context will be known. But I'm thinking of the modules represented by the `Mod` AST (where function bodies are represented by `FuncStmt`), which will be the case for when an external library is called. The functions for generating a GOOL module from a `Mod` are not module-specific, so the context we need would need to be somehow stored in every `CodeChunk` that appears in the `Mod`. And the easiest way I've thought of to do that is to use the function type instead of just `Space`. We could provide smart constructors for the two main cases (primary case is to lookup the `Space` in the map, secondary case is to use `const` to force a certain type). That way our current examples wouldn't even need to change.

**Comment by JacquesCarette** [comment]
Storing the context in each `CodeChunk` doesn't seem like a good design.  Why are the modules generated "context free"? That seems odd.

But yeah, the smart constructors route (and the function type) might be the shortest way there. Still, I think it's odd that the modules generation function don't allow context.

**Comment by bmaclach** [comment]
It doesn't seem odd to me, so maybe what I am thinking of as context and what you are thinking of as context are not aligned.

Continuing to use external libraries as an example, the case here is that an external library function requires, say, `double`s and not `float`s. To Drasil, an external library is just data. We could theoretically define infinitely many external libraries, many of which do not care whether the user uses `double` or `float`. But we need a function that can generate code from any external library data, and all that function "knows" is that it is generating code to call an external library. That is not enough context to determine when it needs to force a value to have type `double` instead of `float`. So that information must be stored in the data passed to the function, and the way I thought of doing that was on a per-`CodeChunk` basis. 

I suppose an alternative would be to set this per-`ExternalLibrary` -- so add to the `ExternalLibrary` AST a way to say "When using this external library, the `Real` `Space` maps to `Double`". But if we do that, we have to hope there would never be a case where a single external library requires `float` at some times and `double` at other times (I can't think of why this would ever be the case, though, so maybe this is the better way to go).

@JacquesCarette Hopefully that clears up my thinking?

**Comment by JacquesCarette** [comment]
I was thinking of passing that data on a "per instantiation" basis, i.e. as something in the top-level. I think the external libraries should declare whether they require `double`, `float` or don't care.
