### ISSUE TITLE
Making concept matches in the code generator more explicit

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1866]
We discussed at the meeting on Aug. 29th, 2019, in relation to the concept matching aspect of #1862, how we already do some concept matching, only it is done implicitly. We should make these more explicit (i.e. pull them out from the depths of the code and do them closer to the surface). The example given by @JacquesCarette was a match of the `Space` `Real` to the code type `Double`.

Looking in the code generator, we have `spaceToCodeType`, which is used when converting `Quantity`s from Drasil to `CodeChunk`s in the generator: https://github.com/JacquesCarette/Drasil/blob/7cf2d779878822c737c120dbbb3779956f2ac29e/code/drasil-code/Language/Drasil/Code/Code.hs#L27-L39
Here we map `Real` to `Float` (we don't distinguish between floats and doubles in `CodeType`). But this seems like an explicit match to me already, so I may be missing the point of what you wanted changed, @JacquesCarette. Is it that we need to add a `Double` constructor to `CodeType`?

Note that elsewhere in the generator we map the `Dbl` constructor of `Expr` to GOOL's `litFloat` (which should really be called `litDouble`), which seems related to this issue as well:
https://github.com/JacquesCarette/Drasil/blob/7cf2d779878822c737c120dbbb3779956f2ac29e/code/drasil-code/Language/Drasil/Code/Imperative/Import.hs#L138-

I can see that this would need to change for adding a choice between floats and doubles as the representation of reals, but you mentioned these changes were independent of adding the choice.

**Comment by JacquesCarette** [comment]
First, the issue of `Space` matching: right now, we have sufficiently few of them that it doesn't make a lot of sense to have variations, except for the `float`/`double` thing.  But there are two places where we'd want more flexibility already:
1. `Vect`: we want to have a choice of representation of vectors.  Right now, this goes to `List` only.
2. `Discrete*`: lots of languages have enumerated types, which we'd want to use instead.

Once we have larger container types (like arrays / matrices) and get into representing functions, this is going to become an even bigger issue.

The bigger thing here is that of matching
**specification level concept**  <-> **code level representation**
in a flexible way, i.e. in a way that can be done via a Drasil-level recipe, rather than as Haskell-level code.

**Comment by bmaclach** [comment]
So now that we've done #1862, where we implemented a map from UID to code concept, does that shed light on what we should do here? We can't use the same map because, unlike with pi, the choices here are not related to any specific quantity, but rather related to a whole `Space`, so we can't index the map by UID. Should we implement a second map, this one from `Space` to code concept? But have it work in a similar way to the one we implemented for pi? @JacquesCarette

**Comment by JacquesCarette** [comment]
Yes, I think that's right, i.e. indexed by `Space` but working similarly to what was done with pi.

**Comment by JacquesCarette** [comment]
@bmaclach this has evolved quite a bit since then - can you comment on the current state?

**Comment by bmaclach** [comment]
With the implementation of the concept match map in #1862 and the space matching in #1863, I think it's safe to close this issue. I left it open for the stuff about `Vect` and `Discrete` in a comment above, but I think it makes more sense to create two new issues to tackle those two ideas. The infrastructure is now in place to do those.

I will close this and create the new issues.
