### ISSUE TITLE
HGHC Case Study SRS - Missing problem description

### ISSUE THREAD

**Issue by best-zhang-zhi** [JacquesCarette/Drasil#1888]
@smiths 

In the Specific System Description, it says"This section first presents the problem description", but the problem description is not presented as the first subsection, the subsections start with the Solution Characteristics Specification, which should followed the problem description as introduced in the Specific System Description.

**Comment by smiths** [comment]
@best-zhang-zhi good job noticing this issue.  This is an example where the outline of a section does not match the contents of the section.  Therefore, this is a part of a larger open issue (#946).  Rather than fix each instance, our plan is to fix the generator so that this kind of inconsistency is not possible.
