### ISSUE TITLE
Question: Game Physics SRS - Goal Statements

### ISSUE THREAD

**Issue by sorainsm** [JacquesCarette/Drasil#1894]
@smiths why is _collision forces_ in brackets here?

**Comment by smiths** [comment]
@sorainsm, as I mentioned in issue #1896, it is nice if you can include a screen shot of the "offending" text.  It saves the reviewer time and makes the issue easier to read in the future.

I've looked up the text and the brackets are in the wrong spot.  The original intention was to make the example of collision force, since they are handled differently than others forces, parenthetical.  Also, from a sentence readability point of view, using commas instead of brackets is difficult to parse.

@oluowoj, can you please change the introductory sentence for the Goal Statements in the Game Physics SRS to:

Given the kinematic properties, and forces (including any collision forces) applied on a set of rigid bodies, the goal statements are:

**Comment by oluowoj** [comment]
fixed in PR #1928
