### ISSUE TITLE
Suggestion: Game Physics SRS - Terminology Addition

### ISSUE THREAD

**Issue by sorainsm** [JacquesCarette/Drasil#1895]
@smiths  I suggest adding _damping_ to the terminology section since it is referenced in the assumptions and as a likely change in the future. It would future proof this section to add it now.

**Comment by smiths** [comment]
Yes, @sorainsm, I agree.  I think this should be an easy fix.  @oluowoj, can you please look into adding the definition for damping to the terminology section of the Game Physics SRS.  (@oluowoj, this issue was created as part of an exercise reviewing the existing case studies as carried out by the 741 students.)

**Comment by oluowoj** [comment]
Completed in PR #1902. Closing issue
