### ISSUE TITLE
Unpopular format in units

### ISSUE THREAD

**Issue by caobo1994** [JacquesCarette/Drasil#1908]
https://jacquescarette.github.io/Drasil/examples/GlassBR/srs/GlassBR_SRS.pdf
Page 4, the unit for k and m are written in \frac{m^{12}}{N^7}, but popular ways are m^{12}/N^{7}, or m^{12}N^{-7}. Also, the two-line fractions have smaller fonts, and not so easy to read compared to other two.

**Comment by smiths** [comment]
Thank you  @caobo1994.  Rather than a link to the entire pdf, it is nice if you can provide just a screen shot of the symbols (in context) that you don't like. 

Yes, the units could be displayed in a different way.  This is a stylistic choice.  In the future, Drasil will have configurable parameters that would allow the users to make the choices that are appropriate for their preferences.  For now though, we'll stick with the defaults.

When you review your colleagues work later in the course, try to dig a little deeper on your observations.  Something related more to content, rather than appearance, would be more impactful.
