### ISSUE TITLE
Wrong definition of Right-handed coordinate system.

### ISSUE THREAD

**Issue by caobo1994** [JacquesCarette/Drasil#1910]
In the Terminology and Definitions, Specific System Description,  _SRS for Game Physics_, _Right-handed coordinate system_ is defined as 'A coordinate system where the positive z-axis comes out of the screen.' However, this definition is not the same one as the popular definition. 

The popular definition is that $\hat{\mathbf{e}}_z=\hat{\mathbf{e}}_x\times\hat{\mathbf{e}}_y$, where  $\hat{\mathbf{e}}_x$ is an unit vector with direction in the positive $x$ axis, and likewise. 

A coordinate system with the positive $x$ axis pointing to right, $y$ axis downwards, and $z$ axis out of the screen is a right-handed coordinate system in the definition in this SRS, but not one int the popular sense.

**Comment by smiths** [comment]
Great feedback @caobo1994.  I do like your mathematical definition of a right-handed coordinate system.  It is more formal than the current definition.  I'm going to keep the current definition for the moment, since the example is intended to be simple, but we will keep this change in mind for the future.
