### ISSUE TITLE
Research related - Olu

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1920]
@JacquesCarette & @smiths, I am creating this issue to keep a track of discussions, questions, information or feedback related to my research

**Comment by oluowoj** [comment]
@smiths is the research proposal that you are working on in se4sc? Just checking if I can read

**Comment by smiths** [comment]
@oluowoj, the research proposal is at

https://github.com/smiths/AIMSS

**Comment by oluowoj** [comment]
Thanks Dr. Smith

**Comment by JacquesCarette** [comment]
I think this issue might be better in the se4sc repo. It's really not about Drasil itself (indirectly, of course), so I think that will be a better place for it.

Also, you should create one issue per item. We should strive to close issues quickly, if at all possible. So we ought to use different mechanisms for longer-lived things.

**Comment by smiths** [comment]
I agree with @JacquesCarette.  Issues related to leveraging Drasil would be better in the se4sc repo, since they don't actually involve changing Drasil.  Also, we don't want issues that are intended as an open discussion, or chat.  We want well focused issues where what needs to be done to close them is obvious, and hopefully not too time consuming.  😄
