### ISSUE TITLE
GOOL: Splitting introduction and elimination rules

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#1943]
Some classes, such as `BodySym` https://github.com/JacquesCarette/Drasil/blob/2a0e4afbeb8b2bd90d0c3df41ba53799fbb2b244/code/drasil-gool/GOOL/Drasil/Symantics.hs#L87-L95 have introduction rules (the first 4 methods) and an elimination rule (the last).

We should split this into 2 classes, one for each.  The 'associated type' would need to be pulled out at the same time, to be made into a (closed?) type family.

**Comment by bmaclach** [comment]
@JacquesCarette I don't think we can use a closed type family because we would have to import the concrete `repr` types (`JavaCode`, etc.) in Symantics.hs which would cause an import cycle. I suppose we could move the definitions of all of the `repr` types to their own file to avoid that, but is there a reason to do that instead of just having it as an open type family?

**Comment by JacquesCarette** [comment]
Right - let's go with open.  closed just gives more error messages when things go wrong.
