### ISSUE TITLE
Bundled + Combined choice combination broken in Java, C#

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1952]
If you choose `Bundled` for the Input Structure `Choice` and `Combined` for the `InputModule` choice, Java and C# don't work because they end up with 2 classes with the same name in the same file.

Before fixing this, I need to understand what the desired structure is for the `InputParameters` module when `Combined` is chosen. This is the choice that combines all of the input-related functions/classes in one module. In Java and C#, since all functions need to be in a class, the only way to do this is to make the functions methods of the `InputParameters` class. But in Python and C++, which of the following options is what we want to do:

#### Option 1

- `InputParameters` module
  - `InputParameters` class
    - Variables for input
  - `get_input` function
  - `input_constraints` function
  - `derived_values` function

#### Option 2

- `InputParameters` module
  - `InputParameters` class
    - Variables for input
    - `get_input` method
    - `input_constraints` method
    - `derived_values` method

Looking at the case studies repo, GlassBR is the only example that uses the combined structure and it uses Option 2. Option 2 would also be easier for me to implement right now, if that matters. @JacquesCarette @smiths

**Comment by JacquesCarette** [comment]
Let me "reason it out loud", to document my thinking.

`Bundled` means that all variables end up in a single 'record' -- which in many OO languages, means a class. But the fields of that class can be `public`, so that it's easy to treat it as a record.

`Combined` means that the secrets of the input details (how to read, how to insure constraints are satisfied, how to derive some values) are not put into 3 modules, but all inside a single module. And then there is a non-trivial question of whether these 3 are part of the resulting module's API or not. In the non-combined case, what is the visibility of these sub-modules?  If they are seen only by the `InputParameters` module (which would make sense to me), then it would also make sense to me that the `Combined` version would not expose things.  Then the `InputParameters` class would have a single constructor exposed, which can call the 3 methods (`get_input`, `input_constraints` and `derived_values`) to set everything up.

Which does seem to argue for option 2.

**Comment by bmaclach** [comment]
@JacquesCarette In the non-combined case, all 4 of the input-related modules are seen by and called by the `Control` module. The `InputParameters` module in that case is only a record, and doesn't actively do anything (i.e. it does not have a custom constructor). Despite that, I like your idea for the combined case where there is a constructor for `InputParameters` that calls these methods. It seems to line up well with @smiths's justification for why we would want to combine these into the same module in the first place -- they are tasks that would always want to be done together, not independently.

**Comment by JacquesCarette** [comment]
The nice thing about all of this is that we're now in a position to be able to 'internalize' design, but also to give it an external interface.
