### ISSUE TITLE
Implement arrays in GOOL

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1988]
The ODE solvers in Java and C# use arrays.

By "arrays", I am referring to each language's built in list type, usually represented by `[]`. This is already what the Python renderer uses for lists, though the other renderers import different types for lists. I think arrays should be implemented in GOOL since they are in all languages and used often in high-level patterns, but I wonder how best to do it. 

An interesting wrinkle is that we plan on letting users choose which type they want to use for lists (#1519), and arrays would surely be an option to choose. But there are cases, like when using these ODE solvers, that the list MUST be an array, even if the user has chosen something else for their list-representing type. Another interesting note is that GOOL's current `listType` function takes a `Permanence` parameter (either `static` or `dynamic`), though this parameter is always ignored. I wonder if the original purpose of this parameter was to differentiate between arrays and other lists? But I don't think static vs. dynamic is equivalent to array vs. list object. Maybe I'm wrong.

**Comment by smiths** [comment]
Thanks for this issue @bmaclach.  I didn't realize that we didn't have arrays in GOOL.  I would have thought this would have come up sooner.

This issue between conflicting variabilities has come up before.  I think we agreed that if we didn't follow the user's choices, we would issue a warning to them.

**Comment by JacquesCarette** [comment]
I'm pretty sure `Permanence` came from Objective-C.  Since that backend is not likely to be resurrected, we might end up removing that. Though if we ever do Swift or Rust, who knows what kinds of things might be needed there.

Generally, we might need 3 concepts:
1. generic container with a certain API (the current `listType`)
2. linked lists
3. arrays

Good GOOL code would try to use 1 as much as possible, but sometimes be forced to use 2/3 for external reasons.  The other possibility is to try to use 1 lots, but have GOOL be able to force the backend implementation if certain constraints force it to do so.

**Comment by bmaclach** [comment]
Okay, so I'll start by adding support for arrays in GOOL since that's what we need already. I can create a separate issue for adding linked lists. And I guess I'll keep the `listType` permanence parameter for now, in case it becomes useful later?

**Comment by bmaclach** [comment]
Also, of the two possibilities you list I'm thinking we should go with the first one. Thinking of the ODE solvers, I'm not sure what the constraints would be that GOOL would be able to recognize to determine which values it should force as arrays instead of regular lists.

**Comment by JacquesCarette** [comment]
If permanence was really just for Objective-C, we should look to see if Swift/Rust need it; if not, dump it.  And if option 1 works, great, let's go for that.
