### ISSUE TITLE
Adding more Projectiles to stable

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#2010]
We've decided it would be a good idea to add more versions of Projectile to stable to get more coverage on the various `Choice` combinations. 

What I've done so far on the `manyProjectiles` branch is selected a subset of our `Choices` that have the biggest impact on the generated code, and therefore are most likely to cause issues. I set up the `main` function for Projectile to build `Choices` structures using every possible combination of the choices in the subset, and generate the code with each. This led to 96 projectile programs. 

I then updated our script for building the generated code to go through each of the 96 projectiles and build them all. This required hardcoding a check for if the current example was projectile, though I could make this a little nicer by having a Makefile variable store the names of any example for which there are multiple versions. 

I tested this step of the build locally. Prior to this change, when we were only building 1 projectile, 1 glassBR, and 1 NoPCM, this step only takes about 15 seconds. After the change, it unsurprisingly takes about 5 minutes. Adding 5 minutes to each build is probably not wanted, and especially unrealistic when we think about adding more choices, and how each time we add a choice the time for this step of the build will (at least) double. (I also don't know if Travis builds run slower/faster than locally for this step).

The other option is to hand-build some Choices structures for a handful of combinations, and only generate those, but I don't like this option either. For one, how would we decide which combinations were important enough to test? And as we add more choices, we'd need to hand-build more `Choices` structures and might eventually run into the same problem where we are adding too much time to the build.

I really like the idea of having a test suite of Projectile programs covering the entire spectrum of variations we offer. So here are some alternative ideas that could make this work:

- Have the standard build still only build 1 projectile, but have a once-daily build that will build them all. This has the drawback that if something breaks a certain choice combination, we won't know until the daily build after it gets merged.
- Store all versions of Projectile in stable, but still only build 1 projectile in our standard travis build. Then at least when we are working locally, we can see the diffs with all versions and the Travis build will fail if there is a diff with any version and stable (though from a developer's perspective, this diff would be very long and tedious to go through). We could also provide a rule in the Makefile that will build all versions of Projectile. We wouldn't use this rule in any Travis builds, but it would allow a developer to test them locally.

What are your thoughts @JacquesCarette and @smiths?

**Comment by Mornix** [comment]
👀Popping in here. 

First thing to note is Travis has an upper limit on their free tier of builds at 60 minutes I believe. Another note: there is already some Makefile/CI infrastructure in place to run parts of the build on only pull requests (@drasil-bot and continuous deploy file changes). There is infrastructure to only run the continuous deploy once daily through a cron (including detection if the build is a daily scheduled or manually started one). While the CI infrastructure may possibly be in place to reduce the number of full Projectile builds run. 

You are right that the scope can easily explode as more `Choices` are added. Especially in terms of repository size, diff logs, and (some) build times. One idea not mentioned above that jumps to mind, is using Drasil’s existing CI to start a Rube Goldberg machine. 

This Rube Goldberg machine would entail:
1. A commit is made to Drasil
2. Drasil CI (only on a cron or PR) would look for changes to drasil-code, drasil-gool, or drasil-examples/Projectile
3. If a change is found, have @drasil-bot commit to a specific Drasil-Projectile repository (Either to a new branch if PR or master if a cron) with the git hash of the current build; if it’s a PR build @drasil-bot would tag the PR as “Build Pending”

What’s in Drasil-Projectile? All the generated Projectile `main` combinations and the last stable. Included is the hash of the main Drasil repository the stable is in reference to.

4. The automated repository commit kicks off a CI build for just projectile but ALL THE PROJECTILE! The build would: regenerate `Choices` if anything has changed, build all the Projectile and their source, and finally compare stable. (As @bmaclach mentioned, if there’s a stable diff, it’s bound to be very noisy)
5. When the build completes, @drasil-bot would comment with the Projectile build on the PR. 

I don’t fully have a solution on how to “accept” the Projectile stable diffs automatically, or prune branches on the Drasil-Projectiles repository since I’m typing this up as I go. And while this has a level of added complexity and is likely overkill for the time being, it does have a few benefits:
* it keeps the main Drasil repository clean for outside viewers and contributors
* Centralises a place where people can be pointed “Hey, want to see every possible combination of generated code for a single example? Check out Drasil-Projectiles!”
* Keeps the main Drasil build experience “light”
* Resilient — if at some point too many `Choices` exist that we exceed the Travis build time limit, it doesn’t take the entire Drasil CI down with it, it only affects the Drasil-code “extended” tests. 
* Prevents GitHub diffs (even when minified) from “overpoweringly” the code which produced those diffs. 

Anyways, that was a thought off the top of my head that (I think) achieves the goals while minimizing the overall “impact.” Of course, my knowledge of Drasil may be very outdated at this point.

**Comment by JacquesCarette** [comment]
I would prefer our standard Travis build to do 5-6 Projectile versions, with as different `Choices` as possible, to get some level of default coverage.

Having a parallel build infrastructure (thanks @Mornix for the details) to do more thorough coverage testing sounds like an excellent idea.

**Comment by smiths** [comment]
Yes, I agree that the standard build doesn't need (and shouldn't) build all of the possible permutations.  Not more than 5-6 version sounds right to me.  A parallel build infrastructure to do more thorough coverage sounds good to me.
