### ISSUE TITLE
Redo our datatype/class/instance inventory

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2095]
Please update and reorganize the datatype/class/instance inventory.  The steps are as follows:
1) find all 'data' types defined in all drasil- packages [also 'newtype']
2) find all 'class' definitions in all drasil- packages
3) find all 'instance' in all drasil-packages
4) organize the information thus obtained in tables that can be visualized [since information in 3 links that of 1 and 2, but as a block matrix]
5) try to re-arrange the rows/columns of 4) so that the information looks 'organized'

You can find the current draft, last updated 9 months ago, at:

https://github.com/JacquesCarette/Drasil/blob/master/People/Dan/DataTypes.xlsx

For now, create a folder with your name in the People folder, and add your version of DataTypes.xlsx.  Since two people will be working in parallel, we'll need two separate copies.  Once we converge on the "definitive" version, we'll move it to a more logical home than in the People folder.  @JacquesCarette, maybe we should have a Design folder for Drasil where information like this could be kept?

When you have completed the task, you can check your name off on the list below:

- [x] Nathaniel (@Nathaniel-Hu)
- [x] Muhammad (@muhammadaliog3)

**Comment by Nathaniel-Hu** [comment]
Hey Dr. Smith, 

Can I separate the entries by drasil- package (e.g. build, code, lang, etc.) onto several sheets, or should I have them all on the same sheet in the excel document?

**Comment by Nathaniel-Hu** [comment]
Hi Dr. Smith,

Should I separate the 'data' types from the 'newtype' types in the drasil- packages, or should I just leave them together in the same section/column?

**Comment by smiths** [comment]
> Hey Dr. Smith,
> 
> Can I separate the entries by drasil- package (e.g. build, code, lang, etc.) onto several sheets, or should I have them all on the same sheet in the excel document?

To start with, I think we should have all of the packages on the same sheet.  We are looking for potential patterns and they might be easier to see if everything is together.  If my advice turns out to be wrong, we can always split things up later.

>Should I separate the 'data' types from the 'newtype' types in the drasil- packages, or should I just leave them together in the same section/column?

@Nathaniel-Hu, I like the idea of splitting data and newtype.  We could always collapse the column into another column, but it is better to have higher resolution data to start with.

**Comment by Nathaniel-Hu** [comment]
Alright then. Thank you!

**Comment by JacquesCarette** [comment]
A Design folder is a good idea.

The vast majority of instances will be intra-package -- but it will be interesting to see the exceptions.

**Comment by muhammadaliog3** [comment]
Originally I committed and tried to push to the master, but it looks like I am not allowed, so instead, I just made a branch "muhammad_data_table" where I made a folder named "Muhammad" in the "People" directory with my excel table.

**Comment by muhammadaliog3** [comment]
[#901](https://github.com/JacquesCarette/Drasil/issues/901)
[#872](https://github.com/JacquesCarette/Drasil/issues/872)
[#1048](https://github.com/JacquesCarette/Drasil/issues/1048)
[#806](https://github.com/JacquesCarette/Drasil/issues/806)

Contraints in general, this would solve a group of issues 
[#1799](https://github.com/JacquesCarette/Drasil/issues/1799)
[#1798](https://github.com/JacquesCarette/Drasil/issues/1798)
[#1795](https://github.com/JacquesCarette/Drasil/issues/1795)
[#1797](https://github.com/JacquesCarette/Drasil/issues/1797)

[#1476](https://github.com/JacquesCarette/Drasil/issues/1476)
[#1570](https://github.com/JacquesCarette/Drasil/issues/1570)
[#1809](https://github.com/JacquesCarette/Drasil/issues/1809)
[#1153](https://github.com/JacquesCarette/Drasil/issues/1153)
[#1732 ](https://github.com/JacquesCarette/Drasil/issues/1732)

**Comment by smiths** [comment]
Yes, @muhammadaliog3, that is correct that you don't have permission to push to master.  (If you ever work on the se4sc repo, you do have permission there.)  You should use a pull request with your branch.  You can have a look at the Contributor's Guide for instructions.  (If any instructions are missing, please let us know, so that we can answer your question, and so that you can fix the instructions.)  :smile:

**Comment by Nathaniel-Hu** [comment]
In the "People" directory, I created a new folder "Nathaniel" in the branch "Nathaniel-DataTable" with my excel spreadsheet file. I have created a pull request with my branch to merge it with the master branch.

Note: My folder "Nathaniel" also contains a sample .txt file that can be deleted if need be.

**Comment by JacquesCarette** [comment]
Can you rename that file to DataTable - there is no need to have your name in there twice, it's already contextually there because of the directory name.

**Comment by JacquesCarette** [comment]
Ok, I've now looked at both.  @Nathaniel-Hu I really like your version. It lets me visualize things better. I had not quite realized how huge Drasil had gotten.  To help visualize things even better:
1. please re-order the packages so that the ones with no instances (examples, utils, data) are at the bottom.
2. re-order the columns so that all the classes defined in the gool package are 'last'
3. also re-order the columns so that all the classes from Haskell itself are first

There will probably be a second pass that needs done, but I've already spotted patterns on this. They will likely be easier to see still once the above 3 have been done.

@muhammadaliog3 can you check that your version agrees? i.e. that both spreadsheets actually contain the same data?

**Comment by Nathaniel-Hu** [comment]
@JacquesCarette, I have reformatted the data table as per your requests (see link below). Could you review it, and let me know if anything needs to be corrected/changed?

Data Table (Reformatted):
https://github.com/JacquesCarette/Drasil/blob/Nathaniel-DataTableReformatted/People/Nathaniel/DataTable.xlsx

**Comment by JacquesCarette** [comment]
Big improvement.  [I have a big screen, but I still need to zoom to 10% size to see it all at once]

So now that I see more structure emerging, what I would like you to do is to change the order a bit more:
- put line 259 at 196 instead (i.e. move 259 up to a new hole in 196 and push the rest down).
- then take all of the gool package and move it to be right after the theory package
- move the build package down to below printers
- move the lang package to come first

That will reveal even more structure.  Note that the above is not a 'correction', I am asking for further changes because what you did revealed some latent structure that I couldn't easily see before.

**Comment by JacquesCarette** [comment]
I think what I'd like to do is to close this particular issue, as the main work is done, and open new issues, as what we're talking about here are refinements. Ok?

**Comment by Nathaniel-Hu** [comment]
@JacquesCarette, here is the Data Table with your requested changes. Please let me know if there is anything else you would like changed/adjusted.

Data Table Link:
https://github.com/JacquesCarette/Drasil/blob/Nathaniel-DataTableReformatted/People/Nathaniel/DataTable.xlsx

**Comment by JacquesCarette** [comment]
Note that you don't have to put "Nathaniel-" as a prefix to the names of your branches. Shorter names are fine, since the branches will get deleted when their contents are merged in.

Did you make the original spreadsheet by hand, or with some scripts?

I do want to explore what the data is telling us some more, but I think that will be best done on sub-spreadsheets and the like.  And I'd like to keep this up-to-date, so that's why I'd like to be able to reconstruct them with scripts.

You should do a PR with the current work. I'll then open new issues for the next pieces.

**Comment by Nathaniel-Hu** [comment]
@JacquesCarette I have created a PR with my current work. 

Also, I made the original spreadsheet by hand. Should I start looking into to program scripts to create the next spreadsheets?

**Comment by JacquesCarette** [comment]
Merged.

Yes, I think doing it as a script is a good idea. Probably generate the data as .csv, but keep in mind that we'll want to tweak things so as to be able to order the rows / columns semi-manually. So the script should be based on a configuration file that allows this order to be set.

**Comment by Nathaniel-Hu** [comment]
@JacquesCarette, is it intended for the scripts generating the data table to be run when the user(s) build the Drasil framework? Or will the data table generating scripts be run separately?

I am asking this so that I will know what the working directory will start out as (it will likely be obtained using `getCurrentDirectory`). I'm just unsure as to whether the working directory will be ./code/ or ./scripts/. Thanks!

**Comment by Nathaniel-Hu** [comment]
Also, as a future enhancement, should I consider looking into using `ByteString`s instead of `String`s for reading and writing files (given that `ByteString`s are faster and more space efficient to use compared to `String`s)?

**Comment by JacquesCarette** [comment]
Yes, these scripts should be run when the Drasil framework is built. We may as well automate that too.  You can assume that this will in general be run automatically from the Makefile, so the working directory can be set there. If someone will run it by hand, then they might need to do a bit of work to set it up properly.

Yes, definitely, we should move away from `String`. Probably to `ByteString`, but a re-investigation of that issue should probably be done to find the best "state of the practice" before we commit to a change. I think there are alternatives here, and that things have evolved over time as to what the best choice is.

**Comment by Nathaniel-Hu** [comment]
@JacquesCarette, in CppRenderer.hs, there are several instances of the 'variable' `p CppSrcCode CppHdrCode` in instances such as:
```haskell
instance (Pair p) => OOProg (p CppSrcCode CppHdrCode)

instance (Pair p) => ProgramSym (p CppSrcCode CppHdrCode) where
  type Program (p CppSrcCode CppHdrCode) = ProgData
  prog n mods = do
    m <-  mapM (zoom lensGStoFS) mods
    let fm = map pfst m
        sm = map (hdrToSrc . psnd) m
    p1 <- prog n $ map return sm ++ map return fm
    modify revFiles
    return $ pair p1 (toCode emptyProg)
```
 Should this 'variable' be placed in the output file as `p CppSrcCode CppHdrCode`, or are there different (formatting) requirements for these kinds of variables?

**Comment by JacquesCarette** [comment]
`p` is supposed to be an abstract generation-time pair. `p` should never appear in any output.

**Comment by Nathaniel-Hu** [comment]
So I do not include `p CppSrcCode CppHdrCode` in the output file all then? (Currently, it is not included in the output file). 

Also, @JacquesCarette, my latest version of these scripts is able to extract and re-order the class instances by ClassType (Haskell, Drasil and GOOL). However, what is the amount of semi-manual control that you would like the configuration file to be able to have on the Data Table Generation?

I am asking this because while the scripts can organize and order the class instances by class type, the exact order of the classes within each class type grouping largely doesn't match the class instances ordering in the manually made Data Table file (while some small clusters maintain the same ordering). Should I try to get the class instances ordering to more closely match that of the manually generated Data Table file, or no?

**Comment by JacquesCarette** [comment]
Apologies: I completely misunderstood your question!  [I thought you were working inside GOOL, but you're not, you're working on a tool to analyze Drasil code.]

Nevertheless, I think the answer still stands: you can skip `p` from being analyzed.  `CppSrcCode` and `CppHdrCode` do need to be included.

Regarding ordering: I don't think we want to go crazy here. I think some very simple heuristics ought to give us rather good output, and that should be enough.  Let's see what the scripts currently give, and we can work together to try to improve that with as little hacking as possible.

**Comment by Nathaniel-Hu** [comment]
@JacquesCarette okay then, thanks for the clarification. My latest version of the scripts is able to extract the same information/replicate the manually generated Data Table. (I am currently working on my latest version, and will commit it soon) I have attached the script-generated DataTable.csv (as a .xlsx) file below. Please let me know if there are any changes that you would like to be made.

My latest version of these scripts still uses my own (likely buggy) SourceCodeReader.hs file to extract the data, newtype, classes and class instances from Haskell scripts. Should I continue to look into how I can utilize the GHC API to parse the Haskell scripts and extract this same information? 

Or can I create a pull request to push my latest scripts to the master branch, and then create some issues regarding future improvements to these scripts? (i.e. switching to using GHC API to read Haskell files, switching from `String` to `ByteString` or [something else more (memory) efficient](https://github.com/JacquesCarette/Drasil/issues/2095#issuecomment-647790570), [real parsing for config file](https://github.com/JacquesCarette/Drasil/commit/8b38d6dc24bf8f4ae9261e2060a1f6eebd190212#r40456923)) Other than these three main issues, the scripts are just about done.

DataTable.csv File: [DataTable.xlsx](https://github.com/JacquesCarette/Drasil/files/4892387/DataTable.xlsx)

**Comment by JacquesCarette** [comment]
Go ahead and create a PR and some issues.

What I do with the spreadsheet: on my very large screen, I make excell full-screen and zoom to 25% (or 20%) to view the resulting data as a "density matrix".  [So using YYYY instead of just Y would actually help].  What I then want is to re-order blocks of classes and blocks of packages so that the resulting matrix is as 'blocky' as possible. I would prefer some kind of upper-block-diagonal structure (or lower, I don't care about that part as much).  That order on classes and on packages needs to be human-provided. But it should be quite crude (i.e. each order should be about <= 10 things).  For example, the classes order should basically be about haskell-provided and the drasil- packages. We wouldn't want to partition using lower-level information.  This should allow us to spot classes that are used in odd ways, because they will be outliers in the block structure. [That part is definitely a human activity]
