### ISSUE TITLE
Error in SWHS Output Constraint

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2135]
While working on issue #1030 I noticed an error in the output constraint of SWHS (https://jacquescarette.github.io/Drasil/examples/SWHS/srs/SWHS_SRS.html#IM:eBalanceOnWtr) for one of the IMs.  
![Screen Shot 2020-05-24 at 11 33 46 ](https://user-images.githubusercontent.com/1855141/82758138-cd295900-9db2-11ea-8ad2-d7f8d28ae176.png)
The point is that the output is the function T_W while the constraint is on time t, which isn't part of the output.

That 'constraint' is really part of the type of T_W (its domain).

This 'bug' appears to be present in other Instance Models too.

**Comment by JacquesCarette** [comment]
I have removed this constraint (and 4 more like it). They are **not** output constraints. They are type constraints on (here) `T_W`, as it is a _function_ (of time) rather than a constant. Our modelling of functions, especially of time, is extremely sloppy.

This occurs 3 times in SWHS and once in NoPCM.

**Comment by smiths** [comment]
@JacquesCarette, I agree with the removal.  The constraint on t wasn't anywhere in the manual version of the case studies.  It doesn't make sense to include it as an output constraint here, because t is not an output.  I agree that our handling of types is sloppy.

I think we can close this issue.  It is assigned to me, but I don't see anything else that needs to be done.

Rather than consider `T_W` a real number, it would be great if we could consider it a function from real to real.  I think we already have issues that deal with improving our use of types in Drasil.
