### ISSUE TITLE
Running GlassBR

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2138]
@bmaclach, as part of verifying another issue (#2133), I wanted to run GlassBR from stable.  It didn't work because of a problem with TSD.txt.  I'm hoping you know what steps are required.  Initially the file was missing in stable.  I copied another version of the file there, but there are so many copies of TSD.txt, I'm not sure I copied the right one.  Rather than look too deeply into it, I though I would ask first.  You usually seem to know these kind of things.  :smile:

This is another case where the README file (#2123) would be handy.  It might also be nice to have the TSD.txt artifact automatically included in the same folder and the generated source file.

**Comment by bmaclach** [comment]
Right. We used to automatically copy all text files from the `datafiles` directory over to the build folder during a build. I think when I implemented generation of a sample input file, I removed this feature because we no longer needed to copy the sample input file from `datafiles`, since we were generating it instead. 

I didn't realize at the time that for GlassBR, there were other .txt (TSD.txt and SDF.txt) files that still needed to be copied over from `datafiles`. So now GlassBR doesn't run unless you copy them over manually.

There are a few possible solutions to this:
1. The quick fix would be to update the paths to TSD.txt and SDF.txt in GlassBR's DataDefs.hs to be `../../../../datafiles/GlassBR/TSD.txt` (and similar for SDF.txt). The downside to this is that these paths are printed in the SRS, so we'd now have long ugly file paths in the data definitions in the SRS.
2. As you suggest, put in the README that the user needs to copy over those files from `datafiles`.
2. Bring back the feature that copies over .txt files from `datafiles` during a build. The reason this is now harder than it was before is because we no longer want to copy over ALL .txt files from `datafiles` (we now store a "sampleInput.txt" file in `datafiles` for each example that has code generation turned on, and this shouldn't be copied during a build). We need some logic to determine which .txt files should actually be copied. My approach to this would probably be to have a sub-directory with a specific name in `datafiles/GlassBR/` to hold the files that need to be copied during a build (it wouldn't even need to be restricted to .txt files, though that's all we would use it for currently). Then the Makefile/scripts could look for this sub-directory and copy over its files if it exists.

**Comment by smiths** [comment]
Thank you @bmaclach for the quick response.  I can easily run the GlassBR code now, after copying over the correct files.

Thank you for laying out 3 possible solutions.  I think at this time my preference is the second choice.  We don't want to go too crazy with customizing our generated examples so that they only work within the Drasil ecosystem.  The eventual goal would be that Drasil generates the files for the problem at hand, but then the files can be moved elsewhere.  They should be able to exist independent of Drasil.  Until we generate an installer that takes care of all of the installation details, I think it is best if we just tell potential users what they need to run the code.

Your third option sounds pretty good too; we should keep that in mind for the future.

Since my question has been answered, I'll close this issue.
