### ISSUE TITLE
Figures in SRS Documents

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#214]
Hello Dan.  Can we automate the generation of documents so that they include the figures?  From our discussion the other day, it sounded like this wouldn't be too hard to do if the user was expected to provide the full path to the file in their input.  The generated version could put the files wherever it wants to, with the correct path.

**Comment by njericha** [comment]
I have been able to get my figures to display by placing the .png or .jpeg file in the same folder as the HTMP or TeX file. Then I just need to change the string (one of the parameters in `Figure`) in my Body.hs to match the file name. I imagine this should work with subfolders too but this may not work for outside folders.

**Comment by JacquesCarette** [comment]
We need our document generation process to be aware of these extra files, and make sure that generating documents involves making sure these extra files are 'available' to be referenced.  This needs to be automated rather than a hand process.

**Comment by smiths** [comment]
@szymczdm, any update on this issue?  I was building the GlassBR example SRS document from the tex file and it failed because it couldn't find the image files for the figures.  The web-page version also does not include the files automatically.  Can we either include the path to files in the tex file (and html file), or create copies of the files locally?  (I prefer the first option, since redundantly copying files seems like a waste.)

**Comment by szymczdm** [comment]
I've gotta convert a few "images" (pdfs) to actual image files (png) and create a place for them. I'd like each example to have its own resource folder, and we can link to those.

The need for conversion is because while embedding a pdf in a tex document works, it doesn't work in HTML. Also, I don't like having images as pdfs.

**Comment by smiths** [comment]
@szymczdm, I understand the problem for pdfs with html, but I don't understand why you don't like having images as pdfs.  In many cases the pdf is much crisper than the png, especially for a printout.  I have always attributed this to the png file being a raster format and the pdf being a vector format.

**Comment by szymczdm** [comment]
You are completely correct regarding the crispness of raster formats, and I do prefer using vector images when possible (though I don't have an editor for them atm). It's a personal preference with the pdf thing, especially since pdfs can be multiple page documents, it can just get messy.

**Comment by smiths** [comment]
I think we should follow the suggestion of @JacquesCarette: We should automatically generate raster documents from the pdf files so that they can be viewed from the html pages.

**Comment by JacquesCarette** [comment]
I've added the 'design' label as this does require some, well, design. There is a slightly larger issue of having a proper "build" process for documents, not just for code. There are different ways to lay out the files for html, and these choices should be exposed.

**Comment by niazim3** [comment]
For now, should the images from the case studies repo be moved to the [code/datafiles](https://github.com/JacquesCarette/Drasil/tree/master/code/datafiles) folder for the remaining examples and have the addition of a resource path like it was done in commit c6b5c02? Doing so will address the warnings coming up when attempting to make the PDF files using LaTeX (documented in #701).

It will also allow for easy changes when long-term design choices have been made and implemented for this issue, since completely removing the `resourcepath`s would allow for errors to pop up in places where modifications are needed.

**Comment by JacquesCarette** [comment]
Yes, I think so.

**Comment by JacquesCarette** [comment]
What is left to do for this issue?  Looks like quite a lot of it is, in fact, done.

**Comment by szymczdm** [comment]
So as far as I can tell, getting images to render in our generated content (provided we have a file path to the image files themselves) is done. 

What is left to do is:
 - Find the image files and automatically copy them to the appropriate (generated output) directory; error out if not found?
 - Automatically convert pdf image files to a raster format for HTML; format TBD by user?

**Comment by JacquesCarette** [comment]
We have figures in our SRS does right now. I think all the pieces now seem to work.

**Comment by smiths** [comment]
Agreed!
