### ISSUE TITLE
Makefile should require and run `hlint` locally

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2152]
That would help people not check in things that will break the build.

**Comment by Mornix** [comment]
I touched on this in #2151, but not including HLint in the build was intentional to avoid friction from intermediate/working changes failing a build, or if the return code is to be ignored in the Makefile, that may mean the terminal messages output by HLint may be ignored or missed before code is pushed. I suggested that some depending on individual developer preference either `hlint . && make` or `hlint .; make` can be run to achieve the desired result of an additional Makefile target.

**Comment by JacquesCarette** [comment]
Or have an `hlint` target in the Makefile. I'm ok with not having it on by default. The usefulness of having it in the Makefile is that we can automate dealing with installing + dependencies.

**Comment by JacquesCarette** [comment]
Do you still want this assigned to yourself?

**Comment by balacij** [comment]
We now have `hlint` + `hot_hlint` targets. HLint seems to take ~1min to run, so it may be best to leave it as a target and not have it run with each build, or else it would cause a bit of delay in debugging one's own work. I think that we should run `make hlint` or `make hot_hlint` (preferred) before creating PRs from branches we've been working on.

**Comment by JacquesCarette** [comment]
We should lint when we also run tests but not when we just build. Having a separate target definitely makes sense.

**Comment by balacij** [comment]
That sounds good. If I understand you correctly, then I think we can close this ticket. The expected workflow would be to manually run `make` followed by a `make hot_hlint` to see if code is "PR Ready". We could also add a new target "pr_ready" which just has a dependency on both "all" and "hot_hlint". What do you think?

**Comment by JacquesCarette** [comment]
`make pr_ready` is an excellent suggestion.

**Comment by balacij** [comment]
I just need to remember to add this to the wiki in a place or two, and then we should be able to close this.

**Comment by balacij** [comment]
I added the `make pr_ready` in a few places across the wiki already, but I also added a few more to the `Workflow` page for good measure. I'm going to close this ticket, but, of course, we can re-open it if desired.
