### ISSUE TITLE
Compiled versions of nopcm are labelled SWHS for cpp, csharp and Java

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2153]
It seems inconsistent that the generated code for nopcm uses the name SWHS.  @bmaclach, is this something that can be fixed quickly?

**Comment by bmaclach** [comment]
Should be a quick fix, except that the same chunk used to determine the executable name for the generated code is also used to refer to the program in the SRS. I think using the name SWHS was intentional, because NoPCM is part of the SWHS software family, and re-uses the program name chunk from SWHS.

If we were to make a new, NoPCM-specific chunk, then the name "NoPCM" would also have to be used throughout the SRS and that might be confusing to a reader because the SRS doesn't mention PCM otherwise (since it's not a consideration in the NoPCM example). Would that be okay @smiths?

**Comment by smiths** [comment]
I change my mind.  :smile:  The name nopcm makes no sense in the SRS.  The nopcm program is also a Solar Water Heating System.  As you said, it is a program family.  There are no name clashes.  The fact that it is in the nopcm folder is a consequence of our case studies.  If we actually distributed this software, the nopcm name wouldn't actually appear anywhere.

I'll close this issue.
