### ISSUE TITLE
Contributors Guide - User evaluation test

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#2171]
Hello @muhammadaliog3 , @Nathaniel-Hu 

I'm aware that @Nathaniel-Hu is already working on the Contributor's guide and I read some of the information in the thread. We had a discussion with @smiths and @JacquesCarette and wanted to provide more info about on other information is required in your test,  if not already included.

Task:
1) Write down in point form what you wish you knew before you started working on Drasil
2) @Nathaniel-Hu , write a test that would sort of help new Drasil users evaluate whether they have knowledge of the stuff you and @muhammadaliog3 listed in point 1. You both can use this issue to provide feedback on point 1.
Let me know if you have any queries.

**Comment by muhammadaliog3** [comment]
Things I wish I knew
- When I first started Drasil I thought that to use git all I needed to know was branching and adding/commiting/pushin/pulling. However you actually need to know a bit more, things like what is the difference between a remote branch and local branch, what is origin, how to reverse commits, what is head, which branch are you pulling from when you "git pull". You need to be confident in using the command line.
- The original book that me and Nathaniel read was [learn you a haskell](http://learnyouahaskell.com/), you really do need to learn a fair bit conceptually. Sections like the IO section are perhaps not important, but having a strong understanding of the concepts (especially monads and lensing, and a little bit of states and zoom) is important or you will get confused when reading Drasil code. Practice is not as important as you can always use those resources as reference. This is because in the issues that I have done, it is not the implementation that takes time but rather figuring out the code structure and then what to code, so nowadays I just use those resources as reference.
- Don't be afraid to ask questions
- You rarely have to implement at a low level, chances are many of the things you want to implement have already been implemented (i.e. check existing modules and packages there might be similar functions).

**Comment by smiths** [comment]
@oluowoj,  please check that the information shared by @muhammadaliog3 is captured in the current contributor's guide.  If it isn't, please add the information.  This is also somewhat relevant for your Drasil user's guide.

Once you have completed this task, please close this issue.

**Comment by JacquesCarette** [comment]
Re-assigning once more: @Awurama-N can you check the status of all of this?  Also, if there is additional information that you wish you knew when you started, do add it!  I'm going to ping @Ant13731 too.

**Comment by Ant13731** [comment]
The above tips helped a lot, but I just want to add one more thing that might be helpful (although #2404 should hopefully relieve this):
If you are having trouble reading the code in the examples, looking at `Utils.Drasil` (documentation and code) is a good first step.

**Comment by Awurama-N** [comment]
@smiths I'm going to add whatever muhammeddaliog3 shared to the Contributor's guide if it already isn't there and then close this issue, but for something like the difference between a local & remote branch would you agree that it might be better suited to add it to the Git2Know since it seems a bit more simple?

Also @Ant13731 is there anything that you haven't already shared that you would like to have added to the wiki pages about what you wish you knew before working on Drasil?

**Comment by smiths** [comment]
@Awurama-N, yes this sounds like a good plan.  Add any remaining material from @muhammadaliog3.  Yes, the difference between local and remote branches makes sense to be in the Git2Know Wiki.

**Comment by Ant13731** [comment]
Hmm, I don't think so. All the stuff I wish I knew before have been separated into separate pages (like with the New Workspace setup, git2know, and some of the documentation I'm currently working on). As we learn more about better ways to introduce people to Drasil, it might be nice to keep the contributor's guide on the smaller side by using other pages for more in-depth explanations and keeping the main guide as more of a summary of the most important bits. 

For example, the [common issues](https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide#issueerror-fixes) section has almost a summary of stuff that is/will be included in the Debugging and git2know pages. Same with the LaTeX section and the New Workspace Setup documentation.

**Comment by smiths** [comment]
@Ant13731 is correct.  Now that we have supporting pages, we should keep the contributor's guide simple.  Rather than repeat any content, we should point to another wiki page for details.

@Awurama-N, please do a pass through the contributor's guide to replace any repeated information with a pointer to the details.

**Comment by Awurama-N** [comment]
Okay, Yes This makes sense,
I'll work on that.
