### ISSUE TITLE
Traceability when assumptions reference assumptions

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2185]
As mentioned for Projectile (#1628), when assumptions reference other assumptions, this does not appear in the traceability matrices.  For instance, in Projectile A: neglectDrag, A: freeFlight, and A: neglectCurv are all referenced, but don't show up as such in the traceability table.

@Mornix mentioned this is related to #1023, but closing that issue did not fix the problem.  My guess is that the work of @Mornix makes it possible to show the traceability between assumptions, but no table is currently created to show this traceability.  Fixing this problem might be as simple as adding such a table.

**Comment by Mornix** [comment]
All the work to resolve this should already be completed. If you look at the Projectile SRS, you can see assumptions referencing other assumptions in the "RefBy" block present at the end of each assumption. When I updated the traceability matrices I replaced them in all examples to match the standard set that were present in the caseStudies repo at the time. 

The good news about this issue is it's a three to six line fix only requiring minimal code changes to `drasil-example`. 

In what matrices would you like assumptions to be included in the rows? Or would you like a new matrix? Should this change be enacted in just Projectiles or all examples? (The answer to this last question may change `drasil-example` to `Drasil-docLang`)

I'm going to assign this to myself but I probably won't be doing it for a few days. If anyone else wants to take a shot at it, feel free to take it.

**Comment by smiths** [comment]
Thanks @Mornix!  I was very confident that you had fixed the original problem when you "whacked all those moles"!  :smile:  Nice to hear confirmation that assumptions can reference other assumptions.

As far as where to include the assumptions, I like the idea of a new matrix where the rows and columns are assumptions.  The reason I suggest this is that I think this matrix will be empty for all of the examples, except for projectile.  I'm fine with showing the empty (assumption X assumption) matrix, but it would be nice to down the road have the option to not display this matrix if it is uninteresting.  Adding the assumption rows to the first matrix displayed in the examples would make a very large matrix, with almost always a sequence of empty rows at the bottom.

As I said above, I think the only examples we have of assumptions referencing assumptions is in Projectile.  However, I don't think this has anything to do with Projectile being special.  I think it is just a consequence of us putting some extra thought into the assumptions for this example.  If there is an assumption it should be used for something, and some of the assumptions only had the purpose of justifying other assumptions.  :smile:

My preference is, at least initially, to put the new matrix in all of the examples.  It probably won't be that interesting, but the easiest way to visualize this is to see the matrix.  I'm thinking that currently all of the examples are handled the same way for generating the traceability matrices, so this is the easiest approach.  If it is actually more work to add the matrix to all of the examples, we should just add it to projectile.

If you can't get to this task, let me know and we'll assign one of the summer research students.  Thanks again!
