### ISSUE TITLE
Generating Traceability Matrices

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/Drasil#222]
I am sort of stuck right now with generating traceability matrices, currently I am using Strings for Eq to build the traceability matrix so that I don't have to have a list similar to:
`T1 = [EmptyS, EmptyS, EmptyS, EmptyS, S "X"]`
but instead have:
`T1 = ["IM4"]`
to generate

```
        | IM0 | IM1 | IM2 | IM3 | IM4 |
---------------------------------------
 T1     |     |     |     |     |  X  |
---------------------------------------
```

If I automate the generation of the abbreviations ("im1", "im2", etc...) from the `DType` and `Sentence` it will produce a `Sentence`, but I don't think there is `Eq Sentence`? Any suggestions on how I should resolve this?

**Comment by JacquesCarette** [comment]
We don't want an `Eq Sentence`.

Short term, one option is to have the abbreviation function return a `String` rather than a `Sentence`, assuming all abbreviations can be `String`.

But really, the best option is to build the traceability matrix from a proper 'traceability graph`.  The graph can be indexed by chunk IDs (which are always `String`s).  We will need to move to this structure soon anyways - I think @szymczdm is already working on some kind of 'database' functionality for other features.

**Comment by njericha** [comment]
Doesn't `makeTMatrix` defined in `Data.Drasil.Utils` close this issue?

**Comment by smiths** [comment]
Has to wait for reference redesign.

**Comment by samm82** [comment]
Bumping now that `addLabels` is merged. @szymczdm

**Comment by JacquesCarette** [comment]
I think we're now fully ready to tackle this -- @halonazhao ?

**Comment by halonazhao** [comment]
Yes, I'll get started on this.

**Comment by JacquesCarette** [comment]
Thanks. But when you do, please first create a new issue with a design proposal.

**Comment by halonazhao** [comment]
This issue is basically the same thing as #1020. We can concentrate on the new one and I will close this for now. If anyone thinks it is still worthy to be open, please reopen it.
