### ISSUE TITLE
Posting the auto-generated Analysis to Website

### ISSUE THREAD

**Issue by Nathaniel-Hu** [JacquesCarette/Drasil#2221]
Now that pull request #2208 has been merged, the next step would be to post the auto-generated analysis (the DataTable.csv file) to the [Drasil Nightly Generated Case Studies and Documentation](https://jacquescarette.github.io/Drasil/) website.

The `deploy` target in the Makefile (in /code/) has already been updated to trigger the `analysis` target (which runs the scripts that auto-generate the analysis). Changes will likely need to be made to the `deploy_lite` target (as discussed in this [comment](https://github.com/JacquesCarette/Drasil/pull/2208#discussion_r458941627)) as well as the script deploy_stage.sh (in /scripts/) at the very least.

**Comment by JacquesCarette** [comment]
Changes to the appropriate scripts now done (but not necessarily debugged). The website itself still need to have the results hooked in.

**Comment by Ant13731** [comment]
@JacquesCarette I'm not really sure how to go about doing this. Is there another example I can follow or something I can read up on?

**Comment by balacij** [comment]
@Ant13731 I don't believe the analysis artifact(s) are currently being [uploaded](https://github.com/JacquesCarette/Drasil/tree/gh-pages/) either so that'll probably also be an issue, the related scripts are the [deploy_stage.sh](https://github.com/JacquesCarette/Drasil/blob/master/code/scripts/deploy_stage.sh) and the main [Makefile](https://github.com/JacquesCarette/Drasil/blob/master/code/Makefile#L95-L96). You should check the [website Hakyll build setup](https://github.com/JacquesCarette/Drasil/blob/master/code/website/Main.hs#L171-L180) for how the links are generated/passed along as environment variables for generation in the index.html file (for how you should add in the link too).

**Comment by Ant13731** [comment]
Okay, I'll check it out. Thanks @balacij!

**Comment by JacquesCarette** [comment]
And do continue to ask for help. I don't know how much you know about this kind of shell scripting and web infrastructure - it's a pretty deep rabbit hole if you haven't delved into it before.

**Comment by Ant13731** [comment]
Will do. I think I can get by with my current bash knowledge but the web stuff is new to me.  I'm going to try and imitate how the other files are generated on the website (like the documentation and examples) and see if that works.

**Comment by Ant13731** [comment]
@JacquesCarette Is this issue and #2231 okay to close now?

**Comment by JacquesCarette** [comment]
Almost. If you go to https://jacquescarette.github.io/Drasil/analysis/DataTable.html and scroll all the way to the right, in Firefox at least, the tables have all sorts of weird artifacts. Looks like something's odd in the generation?

**Comment by Ant13731** [comment]
Ah okay, I'll take another look. I think it's probably my `mkhtmlEmptyCell` function.
