### ISSUE TITLE
Review instructions for creating VM, installing soft dev tools and forking Drasil

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2236]
Please have a look at these instructions and let me know if you see any problems, or if you can think of any additions.  Ideally, I would like you to follow the instructions on your own machine to make sure that everything works.

https://gitlab.cas.mcmaster.ca/smiths/cas741/-/tree/master/Tools/VM_Instructions

I originally thought it worked without doing anything, but the CI is not maintained in the new forked repo.  (We discussed this point with @JacquesCarette during our last meeting.)  We'll have to look into how the yaml file can be hooked into the forked version.  This isn't a big deal though, since most students will not be modifying Drasil, but rather using Drasil.

**Comment by smiths** [comment]
I found the instructions for enabling Travis CI.  It seems fairly straightforward, and it now seems to be working.  (Please ignore my pull requests on the original Drasil repo.  It points to that repo by default, and I kept missing it.)

https://docs.travis-ci.com/user/tutorial/

**Comment by balacij** [comment]
Because I saw this ticket floating around, I would probably discourage cloning over HTTP(S). Using an SSH key and signing commits is good practice because you'll be able to work with other git hosts/servers faster. It's also safer than using HTTP(S) because you can have a local password protecting your private SSH key and you never need to store your GitHub credentials locally.

![Screenshot from 2023-01-30 23-00-03](https://user-images.githubusercontent.com/1627302/215659755-0993345d-794f-4119-b691-1be61f8c8728.png)

Also, since the Travis CI isn't used anymore, we might want to redirect the Travis CI bit to [our new section](https://github.com/JacquesCarette/Drasil/wiki/Workflow#continuous-integration-ci---github-actions--builds--tests).

**Comment by smiths** [comment]
Great advice @balacij.  I also needed a push to use ssh instead of https.  :smile:  I've updated the instructions to follow your advice in 8b3793d.  I think that is good for reviewing the instructions.  We can close this issue now.
