### ISSUE TITLE
Add torque symbol in GamePhysics SRS pdf.

### ISSUE THREAD

**Issue by gabrielasd** [JacquesCarette/Drasil#2240]
@smiths
Table 2 in GamePhysics SRS pdf is mising the torque symbol (tau).

**Comment by smiths** [comment]
@gabrielasd, you are correct that the symbol is missing from the pdf version, although it is present in the html version.  Since the tex code is generated based on all the symbols, this is an odd error.  My guess is the problem is related to something with compiling the tex file.

I'll leave this issue open, since it really should be investigated at some point.

**Comment by Awurama-N** [comment]
@smiths It seems like the torque symbol has already been added to table 2 of the tex file now?

**Comment by smiths** [comment]
The torque symbol appears in the tex file, but not in the pdf file.  If you look at the compiled pdf file (or compile your own), the torque symbol does not appear:

https://jacquescarette.github.io/Drasil/examples/GamePhysics/srs/GamePhysics_SRS.pdf

My guess is that it is because the unicode symbol for tau was used, instead of \tau.

**Comment by Awurama-N** [comment]
@smiths I replaced the tau symbol with "\tau" in both the build and stable tex files... would that be the right thing to do?
it seems to register the changes to the stable file but not to the build file. Everytime i make the changes and run "make", the logs show that build hasn't been changed. Please how could i resolve this issue?

**Comment by smiths** [comment]
@Awurama-N your solution is too simple because the build files are rebuilt every time you run make.  We don't change the build files, but rather the generator the builds the build files.  There is a pretty-printer for the tex files in Drasil that generates tex.  Somewhere in that file, it is writing the unicode symbol tau, rather than \tau.  You could search the Drasil code for the unicode symbol tau, but after that I don't have good advice on how to proceed.  That is more of a question for @JacquesCarette.  It is possible that you'll have to postpone this issue until you learn a little more about Drasil.

**Comment by JacquesCarette** [comment]
What's really odd here is that it seems that only tau is affected. Why that one unicode symbol and not others? Very strange.  Being able to use unicode in latex is why we switched to lualatex!

But this [tex stackexchange](https://tex.stackexchange.com/questions/354443/some-luatex-unicode-characters-not-working) question+answer gives some hint as to what is going on. @Awurama-N can you see what's in the logs?

**Comment by Awurama-N** [comment]
the logs after i made the changes? Yes, i see the logs 
```
diff --strip-trailing-cr -r -X ../.gitignore -x '*.txt' stable/gamephysics/SRS/GamePhysics_SRS.tex build/GamePhysics/SRS/GamePhysics_SRS.tex
194c194
< $\mathbf{\tau}$ & Torque & $\text{N}\text{m}$
---
> $\mathbf{τ}$ & Torque & $\text{N}\text{m}$

```
so the stable file was changed but the branch code hasn't been.
I understand that's because i can't change the code from editing the stable files manually

**Comment by JacquesCarette** [comment]
Not the Drasil logs, the log you get from running lualatex. I think things similar to what that stackexchange post points to will be there. That will tell us what to do next.

**Comment by Awurama-N** [comment]
Where can i access the lualatex logs? i read the site you sent and followed a few other links, i understand what to look for but not quite where to find it. 
I ran `lualatex` in the terminal as well but see no logs?

**Comment by JacquesCarette** [comment]
It should leave a .log file in the same directory that you run it in.

**Comment by Awurama-N** [comment]
would this be it?
<img width="1099" alt="Screenshot 2021-05-20 at 9 28 47 AM" src="https://user-images.githubusercontent.com/72299644/118987260-1a042900-b94e-11eb-872b-9690af78dac3.png">

**Comment by JacquesCarette** [comment]
Yes - except that you need to run `lualatex` on an actual file to get a useful log. There should be a `Makefile` in the same directory that automates that. Simplest to use that.

**Comment by Ant13731** [comment]
I did a bit of light digging in this and here's what I think the problem is. For the examples which use torque (and the bolded tau symbol) specifically, we get this error:
```
Missing character: There is no τ (U+03C4) in font [lmroman12-bold]:+tlig;!
```
However, I noticed that SWHS uses tau as a "dummy variable" rather than for torque and that it showed up there. So I think the `\mathbf` command is causing some problems (see this [stack exchange](https://tex.stackexchange.com/questions/595/how-can-i-get-bold-math-symbols#:~:text=By%20default%2C%20%5Cmathbf%20renders%20bold,bold%2Dstyle%3Dupright%5D%20.) for more details.

I have some possible ideas for how to go about fixing this:
1. Make torque from a `vec` to a `prime` in terms of its decoration. The function that controls the printing of symbols is `sFormat`:
    ```Haskell
    sFormat :: L.Decoration -> L.Symbol -> D
    sFormat LD.Hat    s = commandD "hat" (symbol s)
    sFormat LD.Vector s = commandD "mathbf" (symbol s)
    sFormat LD.Prime  s = symbol s <> pure (text "'")
    ```
    In the symbol for torque, getting rid of `vec` would also get rid of our problem with the symbol not being available in `lm roman bold`, as it shows up on the pdf when not used with `mathbf`. I don't know the impacts/significance of bold letters in physics, but I figured I would put this idea out there.
2. Get the printer to use a different command when it comes to tau symbols. The `\symbf` command works with tau and displays it as bold, so we could detect when a tau pops up and use `symbf` just for that symbol.
3. Switch all bolded symbols from using `mathbf` to another bold symbol command (maybe `symbf`). I'll have to look a little bit more into this one to see if it will work for all symbols, but it at least worked for tau.

I think 3 might be the cleanest, but I wanted to hear your thoughts @smiths and @JacquesCarette

**Comment by smiths** [comment]
Great that you are tackling this issue @Ant13731.  I don't know which of your options is best, but I can answer the question about the meaning of bold.  We are using the convention that bold is used to represent vectors, tensors and matrices.  When we say \tau, we are talking about a single torque.  When we say \mathbf{\tau} we are talking about a [torque vector](https://en.wikipedia.org/wiki/Torque).

**Comment by Ant13731** [comment]
Ah, okay. So then option 1 shouldn't be considered. Thanks!

**Comment by smiths** [comment]
Right, we shouldn't remove `vec` on torque.  If it was just this one example, we could probably let it go, but the bold face convention is very common and likely to come up again in the future in other examples.

**Comment by Ant13731** [comment]
Update on using `symbf` instead of `mathbf`: 
- On DblPendulum, all of the bolded symbols stayed the same, except I think the hat decoration alignment actually looks better. However, I think the hat itself doesn't seem to be bolded. 

On the old version (misaligned but bolded hat):
![image](https://user-images.githubusercontent.com/69334555/126696225-fda516c1-b016-4783-bb86-a28971cf5f7c.png)
While on the new version (aligned but hat not bolded):
![image](https://user-images.githubusercontent.com/69334555/126696259-93f76250-2bf4-4e2a-b4f2-bc201ff154aa.png)

I still have to go through the rest of the examples to make sure nothing funky is going on, but it looks hopeful!

**Comment by smiths** [comment]
I agree that the new version looks better.  The hat shouldn't really be bolded, so that is actually better if it isn't bolded.
