### ISSUE TITLE
CAS 741 Issue Assignment

### ISSUE THREAD

**Issue by JohnErnsthausen** [JacquesCarette/Drasil#2248]
# CAS 741 Issue Assignment

I'm a student in CAS 741. Hello, I'm John.

The aim of this assignment is to gain __experience__ submitting an issue.

## Submitting an Issue

I'l be doing this shortly.

## Assign the issue to Prof Smith @smiths 

I don't see where to do this yet.

**Comment by smiths** [comment]
@JohnErnsthausen, thank you for your question.  I forgot that only Collaborators can assign issues to other Collaborators.  As a guest, you won't actually have the option to assign an issue.  Just go ahead and create it, and then at me (@smiths) in the issue.

I've labelled this issue as a question.  Since it has been answered, I'll close the issue.
