### ISSUE TITLE
'RefBy' missing in data definitions in GamePhysics

### ISSUE THREAD

**Issue by shinsid** [JacquesCarette/Drasil#2250]
@smiths 

'RefBy' value is missing in several data definitions - DD:chaslesThm and later

**Comment by smiths** [comment]
@shinsid, you are correct.  The reason the refby field is empty is that no other objects in the document uses Chasles Theorem.  The reason for this is that the derivations are not complete in the Game Physics example.  Once the derivations are written, Chasles Theorem will be used.  Therefore, this problem will be fixed by future edits.
