### ISSUE TITLE
Projectile SRS - a few questions (issue creating exercise) - Tiago

### ISSUE THREAD

**Issue by machadotiagom** [JacquesCarette/Drasil#2255]
Hello Prof. @smiths 

I am creating an issue after doing a second reading on the Projectile SRS document, and actually, I have a few questions regarding its structure that I would like to share with you:

1. Shouldn't Figure 1 caption be better explained? Also, I noticed that it is not cited or referenced at any part of the text before (or even after) its first appearance.

2. Why the subsections 3.2.2, 3.2.3, 3.2.5 from section 3.2 are needed to be described in main structure of the SRS document? Couldn't we create an Appendix section and put 3.2.2 and 3.2.3 there, for instance, as a complementary source of information? I am enquiring this because sounds to me that SRS is the document where we will express "what is the problem that we intend to solve", and as such, I didn't figure out why theoretical models and general descriptions that contain physics laws and its detailed derivatives is relevant in this document.

3. Does the 3.2.5 (Instance Models) subsection can be understood as the mathematical modelling process, for which we will give computational meaning in our algorithm development? If so, my first impression is that this section relates more to the design phase, I mean, that part of the process that we will think of on "how to solve the problem itself".

If we have time, I would like to discuss items 2 and 3 in class to understand better the rationale behind it.

That is it for this first assignment from my side.
Thank you
Tiago.

**Comment by smiths** [comment]
@machadotiagom, I will respond to your comments/questions below.
> 
> I am creating an issue after doing a second reading on the Projectile SRS document, and actually, I have a few questions regarding its structure that I would like to share with you:
> 
> 1. Shouldn't Figure 1 caption be better explained? Also, I noticed that it is not cited or referenced at any part of the text before (or even after) its first appearance.

@machadotiagom, since the symbols are defined elsewhere in the document, this information is not repeated in the caption.  However, I can see why you would suggest more detail in the caption.  When Drasil is more powerful (in the future), we will allow the user to build a recipe that would provide more detailed figure captions.

The figure is referenced before it is used, but the name is Fig:Launch, instead of Figure 1.  This is a consequence of the generator used for Drasil.  This is a known issue that we are working on.

> 2. Why the subsections 3.2.2, 3.2.3, 3.2.5 from section 3.2 are needed to be described in main structure of the SRS document? Couldn't we create an Appendix section and put 3.2.2 and 3.2.3 there, for instance, as a complementary source of information? I am enquiring this because sounds to me that SRS is the document where we will express "what is the problem that we intend to solve", and as such, I didn't figure out why theoretical models and general descriptions that contain physics laws and its detailed derivatives is relevant in this document.

Moving information to an Appendix would be a different document; it wouldn't be following the template that we are following.  Certainly arguments can be made to reorganize the information.  Once Drasil is more powerful, options like this will be available.  However, the value of standardization is important for our class.  It is helpful if we all follow the same template.  Moreover, the SRS template is based on existing templates and document design principles.  The idea is that the document should support reuse, and it should explain every decision (as well as possible).  We want a document that will convince a reviewer that the correct model has been selected for the problem at hand.  If we just give the model, without justification, we are leaving out important information.

> 3. Does the 3.2.5 (Instance Models) subsection can be understood as the mathematical modelling process, for which we will give computational meaning in our algorithm development? If so, my first impression is that this section relates more to the design phase, I mean, that part of the process that we will think of on "how to solve the problem itself".
> 
It depends on the problem at hand what goes in the instance model.  In some cases there isn't even a need for an instance model, because the theoretical model is adequate.  If the instance model is not abstract (that is, if the instance model includes implementation details), it probably should not be included in the SRS.  This kind of information is part of the design documentation.

> If we have time, I would like to discuss items 2 and 3 in class to understand better the rationale behind it.
> 
Hopefully the classroom discussion, especially around the presentations clarified any remaining confusion.

> That is it for this first assignment from my side.
> Thank you
> Tiago.
