### ISSUE TITLE
DD:coeffRestitution ambiguity at GamePhysics_SRS.pdf  (CAS 741 assignment)

### ISSUE THREAD

**Issue by shmouses** [JacquesCarette/Drasil#2256]
In the denominator of the equation:  Vi.n
To avoid Vi.n = 0 (when vectors are perpendicular) a clear definition for n is valuable. 
The collision-line/axis and plane are not well defined. 

@smiths

**Comment by shmouses** [comment]
@smiths 
Dear Dr. Smiths, I was wondering to follow up on this initial issue that I posted at beginning of the semester as you have not yet closed it.
Regards,
Shayan

**Comment by smiths** [comment]
@shmouses, dealing with the open issues is still on my "to do" list.  Since it doesn't impact anything else, it is relatively low on the list.  :smile:

**Comment by smiths** [comment]
@shmouses, my suspicion is that it isn't possible for two bodies to collide if the velocity vector and the surface normal are perpendicular.  They can collide at an angle, but once the angle is 90 degrees, I don't see how the bodies can collide.  This is an interesting boundary case though and it should be documented.  It might be something to consider for the section related to properties of a correct solution.

Since nobody is currently actively working on the game physics example, I will close this issue, but add a link to it in the guide for potential projects (one of the potential projects is revising the game physics example.)
