### ISSUE TITLE
Inconsistent descriptions in Projectile_SRS.pdf

### ISSUE THREAD

**Issue by XingzhiMac** [JacquesCarette/Drasil#2260]
@smiths 
The term '_v_' in 'GD:rectVel' is described as "speed", but the following derivation part claims it as "velocity". Despite the velocity in the context is equivalent to a scalar, using unified terms would make the text clearer.

![微信图片编辑_20200917234143](https://user-images.githubusercontent.com/70971553/93552839-9669e680-f93f-11ea-807c-1176678881ef.jpg)

**Comment by smiths** [comment]
@XingzhiMac, you are correct that the text is a bit lax with the difference between velocity and speed.  This is a common in physics writing, but Drasil should do a better job with consistency.  I'm not sure if the solution is to replace velocity by speed, since the velocity does have a direction; it is just a known 1D direction.  The documentation should be reviewed to correctly distinguish the velocity vector, 1D velocity in a known direction, and speed.

**Comment by smiths** [comment]
I've had a deeper look at this and I don't think we need to change anything.  The terminology of saying speed for 1D velocity is pretty standard.  Moreover, we have a data definition (DD:vecMag) that explicitly makes the connection between speed and the magnitude of the velocity vector.

If we add another example of kinematic motion we might find that something is missing, but for now, the example seems to be consistent in the use of terminology.
