### ISSUE TITLE
Unit prefix

### ISSUE THREAD

**Issue by LeilaMousapour** [JacquesCarette/Drasil#2266]
Hi Dr. @smiths 

I went through the "Software Requirements Specification for Solar Water Heating Systems". I have a question about unit prefixes. Is the software able to recognize unit prefixes (such as K (kilo) M(mega) d(deci) c(centi) etc.) and adjust the input values respectively or the inputs should be exactly in the units which are specified in the retirements document?

Thank you

**Comment by smiths** [comment]
@LeilaMousapour, no the software doesn't take the unit prefixes as part of the input.  My approach in documentation, and in code, is to use SI units for everything.  If all the inputs are in SI, then all of the outputs are in SI.  :-)  That is, I like everything to be in m, kg, s, etc, without prefixes (except for kg).  If there is a reason to do otherwise though, the requirements can be written with different units.  The software would then be written assuming these units.

**Comment by smiths** [comment]
Since the question has been answered, this issue can be closed.
