### ISSUE TITLE
CAS741 - Question Related to Reference Material Section

### ISSUE THREAD

**Issue by moalaa** [JacquesCarette/Drasil#2269]
Hello Dr. @smiths 

I have a question in SRS organization: **What is the benefit from Reference Material Section, and is there a relation with the References Section at the end?** As all SRSs that I checked have this statement **This section records information for easy reference.** under Reference Material Section.

**NB:** I couldn't find the labels to make this issue as a question.

**Comment by smiths** [comment]
@moalaa the benefit of the reference section is that it provides the definitions of all the symbols and terms in the document.  As a reader is going through the body of the document, they are likely to come across symbols that they do not know.  The details of the meaning of a symbol are not given every time it appears in the document.  Therefore, if a reader needs this information, they know that they can always return to the reference section to learn.  The SRS is not meant to be read sequentially.  The reference section is referred to as necessary.

The references section at the end is where the bibliographic information for the citations is given.  It is standard practice in most documents to have the bibliographic references at the end.

I've labelled this issue as a question.  My guess is that you do not see the label options because you aren't a collaborator on the Drasil project.
