### ISSUE TITLE
Questions related to NoPCM python/C++ examples

### ISSUE THREAD

**Issue by salahhessien** [JacquesCarette/Drasil#2271]
@smiths 

This time I went through the NoPCM example and reviewed both SRS document and run c++ and python on my machine. I have the following questions:

When I opened the README.md files located at "Drasil/code/stable/nopcm/src/python", it was mentioned that this readme file is an artifact generated by Drasil. I wonder how the Drasil tool can automate the generation of such useful information that includes the versioning and external libraries' dependency? 

Another question, Does Drasil can help in generating the source code itself? I mean C++/python code? or this is something that has to be done manually?. If yes, then at what extend can it do so?

Salah.

**Comment by smiths** [comment]
@salahhessien, yes Drasil generates the README file.  Drasil also generates the Python, C++ etc source files.  Drasil generates code by first generating GOOL (Generic Object Oriented Library) code.  The GOOL code is then translated into any language that we have a renderer implemented for.  If you are curious, details on GOOL are given at https://arxiv.org/abs/1911.11824.

GOOL doesn't need to generate code for everything.  If there is an external library available, we generate code that interfaces with that library.  This means that we need to keep track of the external libraries, which is why this information is available for the README file.  :smile:
