### ISSUE TITLE
Drasil User's Guide - doccon'

### ISSUE THREAD

**Issue by muralidn** [JacquesCarette/Drasil#2279]
@oluowoj

In step 6 of the section 'Adding more sections in SRS Body - Introduction', it is instructed to add `doccon` to `symbMap` as follows,

![image](https://user-images.githubusercontent.com/71282513/99003077-81868980-2563-11eb-8266-6df31cc9a3df.png)

The program compiled successfully but crashed at run-time with the following error,

```
pidController: Term: srs not found in TermMap
CallStack (from HasCallStack):
  error, called at ./Database/Drasil/ChunkDB.hs:81:24 in drasil-database-0.1.1-3lhpd7X9GO3HitQV8LWDSK:Database.Drasil.ChunkDB
```

It looks like another constructor, `doccon'`, should be added to the chunk database as well.

**Comment by oluowoj** [comment]
@muralidn, could you try and add  doccon', not sure what functions you have used up until this point but maybe try this and lets see if it works

**Comment by muralidn** [comment]
@oluowoj yes `doccon'` cleared the error. I reviewed my imports again, and couldn't find any other imports (from Drasil libraries) other than what has been suggested in the guide. I am fairly certain `doccon'` is an additional dependency for `IntroSec`.

**Comment by smiths** [comment]
Thank you @oluowoj.  @oluowoj, can you make sure that the documentation is updated with any changes that the conversations with @muralidn highlight.

**Comment by JacquesCarette** [comment]
Switching assignees from @oluowoj to @Awurama-N

**Comment by Awurama-N** [comment]
I have located where `doccon'` should be placed, Code\drasil-database\database\drasil\ChunkDB.hs.
But what should i equate it to? for example the two ways the constructors are put in this file are:

```
refbyLookup :: UID -> RefbyMap -> [UID]
refbyLookup c = fromMaybe [] . Map.lookup c

```
or

```
labelledconLookup :: UID -> LabelledContentMap -> LabelledContent
labelledconLookup = uMapLookup "LabelledContent" "LabelledContentMap"
```
I understand it would probably be:

```
doccon' :: __ -> symbMap -> __
```
but i'm unsure of what the second line should be and what would fill in the spaces.

**Comment by JacquesCarette** [comment]
Hmm, I would be interested in hearing what you think the problem is, that you think this is the solution.  Yes, that is indeed the code that give the error, because it is where the "look things up in the right database" code is. The problem is that the information should have been there all along, which is what this issue is about.

`doccon'` is a list of documentation concepts, defined here: https://github.com/JacquesCarette/Drasil/blob/b585428f1626a9a6aebd93bb7309869c7ed720d7/code/drasil-data/Data/Drasil/Concepts/Documentation.hs#L38-L41  The original error occurred because the document referenced some concepts from documentation that are in the `doccon'` list (but not in `doccon`, defined in the same file).  So when building new examples, it is required to make sure both of these are visible, i.e. that the concepts with the names in those lists, are visible in the appropriate "Chunk database".

What the conversation above says is that Drasil implicitly assumes, when it builds a document, that all the concepts in `doccon` and also in `doccon'` are visible. But that's not what our instructions say - and that's what needs fixed.

**Comment by Awurama-N** [comment]
Oh I see, that makes sense.
I initially thought doccon' had not been defined in ChunkDB and that was causing the issues.
So in this case I am making changes to the instruction and not the actual code. Since the inconsistancy is between what the instruction says and what actually happens?
@JacquesCarette

**Comment by JacquesCarette** [comment]
Correct. It is indeed the instructions that need changed.

This 'detour' has been useful though: I think now you understand what's going on much better, so that your fix of the instructions will be enlightened by that understanding. You are also in a better position to read the surrounding instructions to see if they too are coherent with what's going on.

[Note that, over time, we want to automate these parts. These lists of documentation and adding them to the right places in the examples should not be a step that a human needs to do. In fact, for `doccon` and `doccon'`, that might be possible now.  Could you open a new issue with that idea, so it can be discussed on its own?]

**Comment by Ant13731** [comment]
I think this issue can be closed now as the [instructions](https://github.com/JacquesCarette/Drasil/wiki/Creating-Your-Project-in-Drasil#adding-introduction-section) have now been updated to include both `doccon` and `doccon'`?
