### ISSUE TITLE
Code generation 

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#2281]
@JacquesCarette looking at glassBR Main.hs, I see that it uses an allMods function. Tracing this I found allMods in  ModuleDefs.hs file.

![image](https://user-images.githubusercontent.com/43192745/101192951-d5980180-3629-11eb-9c52-f8d69ba4c1a9.png)

Only glassBR example has the ModuleDefs.hs, I was just wondering if this is used at all for code generation or it is related to the design document only.

Info from the readMe file shows this:

![image](https://user-images.githubusercontent.com/43192745/101192749-89e55800-3629-11eb-9cf2-29a7e493af23.png)

**Comment by smiths** [comment]
@JacquesCarette will be able to provide more detailed information, but in looking at the code for allMods I can see that it takes care of the interpolation.  This is an interesting example because allMods is where information is introduced that is necessary for solving the problem, but this information is not in the requirements.  The requirements are correctly abstract - they just say that the necessary numbers can be interpolated from tables of data.  The allMods is where the concrete decisions are made on how to do the interpolation.  The requirements alone are not enough to generate code, so allMods was added.  However, I don't think allMods is the source of all of the code that is generated.  The software provides output from multiple equations that appear in the SRS, but the information is (correctly) not repeated in allMods.  I think there is some information in `si` that is the source of these equations.  My guess would be the inputs and outputs fields, but I haven't investigated.

**Comment by bmaclach** [comment]
@oluowoj `allMods` is used in code generation. The modules defined in `allMods` are needed for the code to work, but Drasil is not yet "smart" enough to define these modules automatically, thus the user needs to define them instead.

**Comment by oluowoj** [comment]
> @JacquesCarette will be able to provide more detailed information, but in looking at the code for allMods I can see that it takes care of the interpolation. This is an interesting example because allMods is where information is introduced that is necessary for solving the problem, but this information is not in the requirements. The requirements are correctly abstract - they just say that the necessary numbers can be interpolated from tables of data. The allMods is where the concrete decisions are made on how to do the interpolation. The requirements alone are not enough to generate code, so allMods was added. However, I don't think allMods is the source of all of the code that is generated. The software provides output from multiple equations that appear in the SRS, but the information is (correctly) not repeated in allMods. I think there is some information in `si` that is the source of these equations. My guess would be the inputs and outputs fields, but I haven't investigated.

Thanks Dr. Smith

**Comment by oluowoj** [comment]
> @oluowoj `allMods` is used in code generation. The modules defined in `allMods` are needed for the generated code to work, but Drasil is not yet "smart" enough to define these modules automatically, thus the user needs to define them instead.

Thanks Brooks. I will take a closer look.  But do the functions in allMods trace to other modules for GlassBR?

**Comment by oluowoj** [comment]
@smiths , I know this is an outdated graph but I wanted to ask  about the IM  - mayref

If we have 2 IMs (IM1, IM2),  just an example. Can we have IM2 take the output of IM1 as its input? Is my interpretation correct?


![image](https://user-images.githubusercontent.com/43192745/101210505-94145000-3643-11eb-81c2-b4e51253e910.png)

**Comment by oluowoj** [comment]
@andreamclemeno, please post a screenshot of the error you are getting while trying to generate your code

**Comment by andreamclemeno** [comment]
This is the error I am getting: 
![image](https://user-images.githubusercontent.com/70977402/101228032-f5e6b100-3667-11eb-8011-ab647d3a2bbf.jpeg)

vLoad is my Data Definition!

**Comment by oluowoj** [comment]
Thanks @andreamclemeno 
I would just put the resolution of this error in here. The definition info. was missing from SystemInformation in Body.hs. 

![image](https://user-images.githubusercontent.com/43192745/101269806-927c8200-3740-11eb-82d7-8acfc56288ed.png)

**Comment by smiths** [comment]
From above (https://github.com/JacquesCarette/Drasil/issues/2281#issuecomment-738998556)

From the point of view of the SRS, there is no problem at all for the output of one IM to be the input of another.  I don't know if this is a problem from the point of view of code generation.

**Comment by bmaclach** [comment]
> > @oluowoj `allMods` is used in code generation. The modules defined in `allMods` are needed for the generated code to work, but Drasil is not yet "smart" enough to define these modules automatically, thus the user needs to define them instead.
> 
> Thanks Brooks. I will take a closer look. But do the functions in allMods trace to other modules for GlassBR?

Some of the DDs in GlassBR make reference to "interpY" and "interpZ", which are functions defined by the modules defined in `allMods`.

**Comment by oluowoj** [comment]
> > > @oluowoj `allMods` is used in code generation. The modules defined in `allMods` are needed for the generated code to work, but Drasil is not yet "smart" enough to define these modules automatically, thus the user needs to define them instead.
> > 
> > 
> > Thanks Brooks. I will take a closer look. But do the functions in allMods trace to other modules for GlassBR?
> 
> Some of the DDs in GlassBR make reference to "interpY" and "interpZ", which are functions defined by the modules defined in `allMods`.

Thanks Brooks, yes, I saw those in the data definition.

**Comment by JacquesCarette** [comment]
I don't have anything to add to what @smiths and @bmaclach said, the information they gave seems quite complete.

I don't know why the error in @andreamclemeno is being discussed in this issue?  In any case, the problem seems to be that Drasil cannot find a 'path' to compute `elimConst` and `predictedVL` from the data it is given. It does know `vLoad` exists (but does not use it) and it knows `vLoadt` and `time`. It feels like some equations must be missing. That is the the high level content of the suggestion that @oluowoj makes: that some of the defined knowledge is not being added to `definitions`.

**Comment by oluowoj** [comment]
@smiths, so looking at GlassBR, the code generation function is defined in genCode. genCode calls the code generator. codeGenerator uses the options in choices, systemInformation (from body.hs) and codeSpec to create the requested code output file. I added some notes  in glassBR Main.hs since its one of our baseline examples for code generation


![image](https://user-images.githubusercontent.com/43192745/102150232-166bf380-3e3e-11eb-8b44-7d9084d0492d.png)


 codeSpec is based on systemInformation, Choices, and Mods -- defined by the user.
codeSpec also has all the various functions to convert chunks and quantity definitions to implementation e.g functions to get the list of constraints, list of derived input, and function to determine what parameters need to be calculated are defined in codeSpec. These elements are part of what is required to generate code. 
![image](https://user-images.githubusercontent.com/43192745/102152703-921c6f00-3e43-11eb-951a-6a78d96fc891.png)

I think codeSpec collects all the related info for a program. There is way more stuff connected to this but i'd say this is high level and I will dig in.

**Comment by smiths** [comment]
Thank you for the information @oluowoj.  Very helpful.

**Comment by balacij** [comment]
Closing in favour of #3355
