### ISSUE TITLE
Try to use pre-compiled binaries in github-actions.

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2326]
Now that github-actions seem to work properly, it's time to optimize.

The current build takes 4 minutes, but a preliminary 47 minutes needed for the prelims!  That's quite excessive. We should look into binary distributions that have many libraries also pre-compiled.

**Comment by balacij** [comment]
Oh, that's interesting. When I tested previously, it was only ~25min without the cache and ~10min with the cache. I think this latest run took this long because I added `website` to the base `stack.yaml`, which resulted in a lot more dependencies being built in the `Install dependencies` step. Maybe we can start with reverting that one change and then use a prebuilt binary of Hakyll for website deployment later?

**Comment by JacquesCarette** [comment]
Ah, right, it might indeed be a one-time cost because of that.

**Comment by balacij** [comment]
This does also bring up another issue as well. The caching doesn't seem to be working properly with PRs. I currently set it to use last commit hash (which seems to be standard practice) for caching, but it doesn't seem to be using it quite properly (since the `Install dependencies` step should all be cached).

**Comment by balacij** [comment]
Removing the `website` from the base stack.yaml seemed to bring the time of the action run from the 1hr back to the ~25min https://github.com/JacquesCarette/Drasil/runs/2477716758

**Comment by balacij** [comment]
Reminder to self: graphmod & dotgen can likely be bundled into a script like the current hlint script we use. Just need a provider of binaries!

**Comment by balacij** [comment]
Are we okay to close this in favour of #2789 @JacquesCarette ?

**Comment by JacquesCarette** [comment]
Yes.
