### ISSUE TITLE
Link in Contributor's Guide Not Working

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2344]
In the Contributor's Guide under the fourth point of the Issues/Error Fixes, the "Quick Start (in Quick Start Guide)" link does not work (gives page not found error).

**Comment by smiths** [comment]
@Ant13731, nice to see you have created your first issue!

For future issues, please include a link (when applicable) to the source of the problem.  In this case, the link would be to:

https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide

Since you didn't assign anyone to the issue, I'm going to assign it to you.  :smile:

To fix the problem, you need to edit to the Wiki page.  The Edit option is at the top of the page.  You then find the offending link and replace it with:

https://github.com/JacquesCarette/Drasil#quick-start

(I haven't checked, the problem might be related to markdown not liking the hash symbol, rather than an incorrect link?)

When you have corrected the wiki, you can close this issue, along with a comment explaining what you did.

**Comment by Ant13731** [comment]
Okay thanks @smiths ! Will do.

**Comment by Ant13731** [comment]
It worked! Thanks!

**Comment by smiths** [comment]
Now you've create and closed your first issue!  :smile:
