### ISSUE TITLE
Add "Updating Stable" to contributor's guide

### ISSUE THREAD

**Issue by Awurama-N** [JacquesCarette/Drasil#2415]
Add information about "Updating Stable" to contributor's guide

**Comment by balacij** [comment]
Just wanted to note that there's an area on the [Creating Your Project in Drasil Wiki page](https://github.com/JacquesCarette/Drasil/wiki/Creating-Your-Project-in-Drasil#updating-stable-folder-in-codestable) that discusses this as well, perhaps you can also edit that too?

**Comment by smiths** [comment]
Thank you @balacij, great idea.

**Comment by Awurama-N** [comment]
### Updating "stable"
Stable files should not be tampered with, and so normally pull requests should not break stable logs unless the Issue it resolves requires you to. (stable logs should not change unless specifically intended to do so). This discusses how to go about fixing broken stable logs.

* How to find problems in the logs: ***

       1. Run `make` in your terminal.

       2. Look for; `diff --strip-trailing-cr -r -X ../.gitignore -x '*.txt' stable/<FileName> build/<FileName>/ > "logs/FileName"`

       3. Click on the log files and non-empty files will show you were there are any discrepancies between the stable & build files.

* When edits are made in the generated documented the "stable" folder must also be updated to match the build files, this can be done in a number of ways: ***

       - Copy and paste a specific build file (the one the logs showed there was a problem in) into the stable folder to replace the file. 
        (Recommended).

       - Copy and paste the entire build folder to create a new stable folder.

**Comment by Awurama-N** [comment]
i was going to put the above into the contributor's guide, but i realised, there's a bit written about updating stable in it already (just not very detailed?).
Should i still go ahead and add this as well.

**Comment by JacquesCarette** [comment]
- different people use different IDEs / methods of editing, so instructions like `click on the log files` are not great, because that's not how I would do it. Use more generic descriptions like "view the log files".
- same for "Copy and paste". I tend to use a manual `cp` at the command line.  So `Place a copy of the build file...` would be better.
- don't even mention "entire build folder" as an option. Let people figure that one out for themselves. Reason: I really want step 2 (to look at the diffs very carefully) to be done each time.  I always look at them in the diffs, and will reject changes that are 99% good and 1% bad.

Do put something like this in the Contributor's Guide. Just make sure that the results is better than before. So instead of a pure addition, you should edit it to improve it.

**Comment by Awurama-N** [comment]
Oh Okay.
Will do.
