### ISSUE TITLE
Adding Higher Level Operators to DBLPendulum

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2476]
From the last comment of #2399. Now that `Utils.Drasil.Sentence` imports as qualified, I think trying to implement as many level 3 (or level 2) combinators into `dblPendulum` would be a good first step to completing #2399.

In addition, I think it would be good to have a separate `the_ofThe` combinator for each level, but I'm not sure how a good naming scheme would work. So far, the most common among combinators are:
Level 1 `Sentence -> Sentence` level combinators: prepends an `s` to most combinators
Level 2 `NP or NounPhrase` level combinators: appends `NP` to most combinators
Level 3 `NamedIdea` or higher level conceptual combinators: are the cleanest ones (only appended by `'` and `_`, although they convert `NamedIdeas` into `NP`s)

Edit: For clarification, this issue is meant to incorporate more conceptual-level combinators for ideas and phrases, rather than using `Sentence`-level combinators. This is to allow Drasil to gain more information about the semantics of what we mean and be more self-sufficient, rather than just telling it the exact sentences we want it to generate.
From #2399:
> The point is that this piece of English actually is very semantic [referring to combinators such as `the_ofThe`]. It embodies the pattern "the unique attribute X associated to the unique object Y" where here X = angle and Y = pendulum. Recognition of the semantics of what the English is actually saying will let us generalize things.

**Comment by JacquesCarette** [comment]
I think that all 3 levels should be called `the_ofThe`, and that users of these should be forced to disambiguate which one they mean at the point of use.

We should undo the naming conventions listed above (prepend `s`, append `NP`); these conventions pre-date our better understanding of what we want.

Note that this issue is not as precise as it should be. While it is perfectly understandable to us now, it may not be so to someone next year, if somehow this issue were not closed over this summer. [There are many such issues already, we want to minimize them, not let them multiply!]

**Comment by Ant13731** [comment]
@JacquesCarette in order to have `the_ofThe` named the same at all 3 levels, should I separate the level 2 (`NounPhrase`) combinators from `Utils.Drasil` so they can be qualified and imported separately just as `Utils.Drasil.Sentence` is separated? 

As for the prepending `s`, some of the combinators would clash with Haskell's syntax (namely `of` and `and`). Should an underscore just be appended to the end of those ones? That's how the conceptual combinators are currently named too.

**Comment by Ant13731** [comment]
So far, I've only started on the Haddock documentation. I know @JacquesCarette suggested a handmade HTML document that organizes and links the Haddock documentation in a previous issue, but I still have to figure out how to go about doing it (I'm not too familiar with HTML). Is there a program that can help with this or should I try and match the design of HTML files that are created by drasil?

**Comment by smiths** [comment]
@Ant13731, I wonder if you can use the Drasil Wiki.  You can use markdown, which is simpler than html.  You should be able to use urls to point to specific pieces of code.

You can also work out the documentation in whatever way is convenient, and then later port it to a more maintainable form.  My question is more motivated by collecting the documentation to come up with a good design.  The question of how best to maintain the document can be something that is potentially sorted out after the design emerges.

**Comment by Ant13731** [comment]
Okay I see! I'll try the Wiki then. Thanks!

**Comment by JacquesCarette** [comment]
Whether it should be done in `Utils.Drasil.NounPhrase` or in `Language.Drasil.NounPhrase` directly (or a sub-module), I'm not sure. But otherwise, yes, it should be separated.

Let's use the convention of appending an underscore when things would clash with Haskell, and not use a trailing underscore for any other reason. Hmm, that convention should probably be documented somewhere (any potentially, multiple somewheres!)

**Comment by Ant13731** [comment]
I think this issue has been completed from the last PR, so I will close it.
