### ISSUE TITLE
Projectile's rectVelGD

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2493]
Presently, we have a data definition and a general definition that both define the same thing, `speed` through their relations (e.g., in the left-hand side of their equations, they both define `speed` at the moment). The general definition, `rectVelGD`, currently relies on OthModel/RelationConcepts. While trying to convert `rectVelGD` into something other than an OthModel (for #2371), I wanted to make it an EquationalModel using a QDefinition, but then it causes a UID conflict between itself and the related data definition, resulting in references that once referred to `rectVelGD` changing into references to the related data definition of speed.

We need to either merge the 2 models into 1, or change the UIDs so they don't conflict. Do we have any preferred way for this? If we want the latter case, I imagine we would want to just change the quantity that  `rectVelGD` defines into something new. If so, how should we define the new `rectVel` quantity that it defines?

Related data definition:
![image](https://user-images.githubusercontent.com/1627302/119034645-90b81b00-b97c-11eb-89be-48de27a34ec0.png)

Related general definition:
![image](https://user-images.githubusercontent.com/1627302/119034730-a9c0cc00-b97c-11eb-887d-078a59743483.png)

**Comment by JacquesCarette** [comment]
The equations are different (although related), so one isn't a superset of the other. The do, in some sense, both define 'speed'.

Nevertheless, my instincts tell me that this is "bad modeling". Somehow the wrong structure(s) are being used in the modeling process. There shouldn't be a data definition and a general definition of the same thing. It feels like the data definition, in this case, is redundant information. Can you trace where it's used?

**Comment by smiths** [comment]
We definitely want both pieces of knowledge.  They are different.  Whether to call them data definitions or general definitions or something else is up for debate.  We will have multiple definitions of the same thing in our documents, so we need to find a plan on how to handle this.  In this case they are two different pieces of information about the same thing.

The data definition provides the relationship between speed and the velocity vector.  Speed is the magnitude of the velocity vector.  This relationship is true whether the speed vector is in 1D, 2D or 3D.  This piece of information could come up in any number of projects.   No assumptions are needed for this relationship to be true.

The general definition provides the function of speed over time in 1D under constant acceleration.  We need assumptions for this function.  We need the velocity vector in 1D, or a component of the velocity vector in 2D or 3D and we need constant acceleration, like the acceleration due to gravity.

If we need to distinguish the two use of the term speed, one is the magnitude of the velocity vector and the other could be the magnitude of a velocity vector (in the 1D case) or the magnitude of of one of the components of a velocity vector.

In 2D with the velocity vector v at an angle of theta with the x-axis we have:

v_x = |v| cos(theta)

(This is your answer to the question above @JacquesCarette.  The data definition is used in building the component-wise representation of the velocity vector.  As an aside, it is so nice that the generated documentation has a RefBy field.  Traceability is definitely much easier in our documents because of this field!)

|v| is the speed of the velocity vector and v_x is the speed in the x direction.  We are using the symbol |v| in the data definition and calling this speed.  We have a few different speeds here.  We have the speed (magnitude) of the full vector and the speed of the components.

Is the problem that we are using the same symbol v for speed and for the speed of a component?  The problem with using different symbols is that we'll make the equations less generic.  The equation for rectilinear motion isn't really the equation for the component of a velocity vector; it is the equation for 1D motion under constant acceleration.  We then apply that equation to the components of the velocity vector.  The equation for the magnitude of the velocity vector being called speed works in 1D, 2D or 3D.

I'm glad this issue has come up because we need to sort out our framework for data definitions etc.  I don't know what is best for formally representing this kind of knowledge.  If @balacij or @JacquesCarette can give me constraints on how we need to express these ideas, I think I can come up with something that works.

**Comment by balacij** [comment]
Thank you very much @smiths @JacquesCarette!

Reading through @smiths analysis really helped me understand the ideas we want to contain!

> Is the problem that we are using the same symbol v for speed and for the speed of a component? The problem with using different symbols is that we'll make the equations less generic.

The problem is that they have the same unique identifier (I don't really know if we should be thinking of this as it's symbol as well), but this (and other related discussion) also makes me wonder if we should relate them by merging the 2 models into 1 TheoryModel using an `EquationalRealm` (which I worked on a bit today in #2440, similar to #2436).

I think that if we did this, we would need to have additional "assumptions" set into the `Realm Expression Variants` so that we can also allow for varying assumptions [like how you described in your analysis] too in addition to having a basic assumption set for the whole theory model. Afterwards, we could "observe" the model for an instance of a projectile using any number of the formulas, using the related set(s) of assumptions.

However, if we merged them into 1 model, we would be categorizing them together (which I don't know if we want to do), and likely constricting them to some unknown degree. 

I couldn't find any usage of the "v_i + a_c * t" variant in the code. If it's meant to be an alternative definition to speed, related to `v = |V|`, then this might also be reason to merge them?

**Comment by smiths** [comment]
This is a great conversation @balacij.  It is going to come up multiple times throughout the current examples, and future examples.  I don't think we want to merge the 2 models.  @JacquesCarette and I were talking the other day and his terminology that each UID should be a separate idea resonated with me.  The three ideas are:

- We can build an equation for the 1D velocity under constant acceleration.
- The magnitude of the velocity vector is called speed
- We can represent a vector in its component form, with the components in this case being found using trigonometry

The third idea is much more general than just a velocity vector.  Any vector in a 2D Cartesian coordinate system, where we know the angle with the x-axis, can be decomposed in the same way.  This knowledge belongs to the category of mathematics, more than it does to physics.

If we want to clearly separate the math and the physics in our documentation, we could change the symbol that we use in the decomposition of a vector into its components.  What would be really neat is if we could capture the knowledge of decomposing a generic vector, but then be able to instantiate it in our documentation using the specific vector of interest.

**Comment by JacquesCarette** [comment]
As @smiths has covered the high-level well, let me address the lower-level parts that should enable further progress "now": those two things (which are really 3 ideas) are separate. So they should have different UIDs. The best solution is probably to change the UID of **both** of them - that will then force you to explicitly choose which to refer to 'downstream'.

**Comment by balacij** [comment]
Thank you very much! I'll draft a working solution shortly!
