### ISSUE TITLE
`make stabilize`: new target to merge `build` changes into `stable`

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2501]
I think it would be helpful to add a new target to our main Makefile that assists with copying/merging stable-breaking changes.

It should:
1. Re-run the build no matter what
2. Copy over files (ignoring binaries, making sure not to delete the stable/README.md file)

**Comment by JacquesCarette** [comment]
Part of me says "No! It should be not-easy to change stable, so that you really do have to make an effort when you do so", and part of me says "Yes, that would really help."

But when I work myself, I kind of end up using exactly the process you outline above...

If we weren't using PRs, I'd go with the 'No' side. But we are, so that's the QA step. It does mean that whoever does reviews does have to be very picky with respect to changes to `stable`.

Upshot: go ahead - I just wanted to explain that this isn't a "slam dunk" feature that it at first appears to be.
