### ISSUE TITLE
Investigating outdated Doclang Constructors (ddefn)

### ISSUE THREAD

**Issue by Awurama-N** [JacquesCarette/Drasil#2504]
This is to investigate the removal of Doclang constructore `ddefn`

details in Issue #1602

**Comment by Awurama-N** [comment]
Here is all the information i have gathered thus far on the constructor ddefn while trying to answer the 4 questions in Issue #1602:

- `ddefn` is defined in the `Drasil.DocumentLanguage.Definitions` file: The comment above it says it's suppose to "Create a data definition using a list of fields, a database of symbols, and a QDefinition (called automatically by 'SCSSub' program
```
ddefn :: Fields -> SystemInformation -> DataDefinition -> LabelledContent
ddefn fs m d = mkRawLC (Defini Data (foldr (mkDDField d m) [] fs)) (makeRef2 d)
```
- I followed the link to were `Defini` is defined (Language.Drasil.Document.Core) and found `data Defini` has been commented out.
```
-- For 'Defini' below.  From DocumentLanguage.Definitions
--   tmodel, TM, mkTMField [ Para, EqnBlock, Enumeration]
--   ddefn, DD, mkDDField [Para, EqnBlock, Enumeration]
--   gdefn, General, mkGDField [Para, EqnBlock, Enumeration]
--   instanceModel, Instance, mkIMField [Para, EqnBlock, Enumeration]
```

- there is a constructor similar to this except it is for "general definitions" `gdefn`, I found that this constructor is also not used in any of the examples (though not in the Doclang file). But there are no constructors which do exactly the same as `ddefn`

- The only other place `ddefn` is mentioned is in drasil-printers/language/Drasil/HTML/Print.hs & the "*_SRS.css" files of all the examples.

(I will make another comment when i have finished investigating this constructor with a final answer to the questions. Could you please provide some more clarity on anything listed above? @JacquesCarette @smiths )

**Comment by Awurama-N** [comment]
I also found that deleting `ddefn` from the Definitions.hs file has an impact on:
`firstPair`
`buildDDescription`
`mkDDField`

DataDefinition is used in their definitions:
eg. 
```
firstPair' :: InclUnits -> DataDefinition -> ListTuple
```

**Comment by tingyuw** [comment]
I don't know much about the detail, but I think I can simply address some of the them.

- ``Defini`` is a data still defined in ``Language.Drasil.Document.Core`` as followed
``` 
data RawContent = Table [Sentence] [[Sentence]] Title Bool
               | Paragraph Sentence -- ^ Paragraphs are just sentences.
               | EqnBlock Expr
               | DerivBlock Sentence [RawContent]
               | Enumeration ListType -- ^ Lists
               | Defini DType [(Identifier, [Contents])]
               | Figure Lbl Filepath MaxWidthPercent -- ^ Should use relative file path.
               | Bib BibRef
               | Graph [(Sentence, Sentence)] (Maybe Width) (Maybe Height) Lbl 
```

- ``ddefn`` is also called by the ``mkSolChSpec`` in ``Drasil.DocumentLanguage``  
![image](https://user-images.githubusercontent.com/47548045/119483354-e09f3500-bd22-11eb-9da2-cde4faf4ae3c.png)

- The ``ddefn`` in the ``Print.hs`` and CSS files are not the ``ddefn`` defined in the ``Definition.hs``.  The ``ddefn`` in ``Print.hs`` is a string tag for the HTML class. 
![image](https://user-images.githubusercontent.com/47548045/119484912-7f786100-bd24-11eb-903c-c265101fbef1.png)

- And the reason why ``ddefn`` would affect ``firstPair``, ``buildDDescription``, and ``mkDDField`` is because that the ``DataDefinition`` parameter that feeds these three functions comes from ``ddefn`` . ``ddefn`` calls ``mkDDField``, ``mkDDField`` calls ``buildDDescription``, and ``buildDDescription`` calls ``firstPair``. They pass on the same ``DataDefinition`` parameter.

**Comment by Awurama-N** [comment]
Thank You! @tingyuw

**Comment by JacquesCarette** [comment]
This is good, because it is all about `ddefn`.  It is important to note that we're talking about the Haskell-level `ddefn` function. 

So it looks like it is still used, so it cannot be removed.  What it means, with respect to issue #1602 is that not only examples have to be looked at, but all of Drasil itself, to see if any of these things are not actually used.
