### ISSUE TITLE
Swift; missing doxygen generation

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2524]
Right now, if you click on any of the "Generated Code Documentation" links on the main website page, it will 404.

caused by:
![image](https://user-images.githubusercontent.com/1627302/119843148-429f9c00-bed5-11eb-90b6-502a4f701702.png)

![image](https://user-images.githubusercontent.com/1627302/119843355-7c70a280-bed5-11eb-98b6-26dc4eea94bc.png)

**Comment by balacij** [comment]
Well, just changing the ticket after a bit of discovery. It looks like we're not generating doxygen docs for Swift, and it also appears that doxygen doesn't support Swift at the moment.

**Comment by JacquesCarette** [comment]
Right - so we should remove the Swift links entirely. We can revisit later, if the need arises.

**Comment by balacij** [comment]
@Ant13731 Would you mind taking a look at this since you're familiar with the template language for Hakyll?

**Comment by Ant13731** [comment]
Sure! Should I just remove the links from the webpage (and anywhere the links are generated)?

**Comment by balacij** [comment]
Yep. If possible as well, if you could eliminate those swift-related `stat` errors (in the original post) that just signal that the target directory in question doesn't exist, that would be great too, but I don't think that's too important really.

**Comment by Ant13731** [comment]
I'm having trouble finding a way to not insert the missing doxygen stuff. I tried doing some things on the haskell file but it's not really working. I tried changing the `mkExampleCtx` function and the `mkExamples` function but even if I replace the file path with an empty string it still shows up on the website. Is there documentation available for the index.html file syntax (for example, could there be an if statement that checks if a file really exist or if the variable name is "Swift")?

**Comment by balacij** [comment]
Hmm, that's weird. Looking at the [Hakyll docs](https://jaspervdj.be/hakyll/reference/Hakyll-Web-Template.html), it looks like the `if` is only for checking existence of keys and whether or not boolean keys are true.

A possible solution is to edit `mkExamples` to check for the list of languages for which the docs exist -- check if the docs folder exists for each language, change the zip4 to a zip5, add the list of languages for which the docs exist to the `Example` type. Afterwards, we can add a boolField to the `vers` list (e.g., "docsExist") where it's based on whether or not the language is an element of the language docs found for that `Example`. If we want to start off simpler, since we know that Swift will never exist and the other languages will always exist (otherwise the build would've failed I assume?), we can completely skip over the edit to `mkExample` and just add a new boolField based on whether or not the language is `Swift` or not.

**Comment by Ant13731** [comment]
I'm trying to implement the first idea but I'm having a lot of trouble getting the intermediate functions to work. This [commit](https://github.com/JacquesCarette/Drasil/commit/b4bdb5a2cf4eae2c56798e9854ea5b4d78453005) has comments in the code saying how I was trying to implement it. Main.hs compiles but doesn't work at all. 

One big problem I had is trying to match up the boolean values for each document source to its proper place (notably, line 220 of Main.hs). I originally thought it could split up like the codesource stuff, but I I get a list of values for the boolField instead of just one (which I try to solve with `selectSrc` but doesn't really work).

Also, how does line 219 get the right source as input? Does that come from line 222?

**Comment by JacquesCarette** [comment]
I'm going to let @balacij dive in. I took a look, and couldn't right away help, as there are too many details that I'm missing. And I'm ok with leaving it that way...

**Comment by balacij** [comment]
Took a look at your code. It looks _very close to working_, I think the issue is what you mentioned + the checked location.

I added a `mock_deploy.sh` script (my old `rn.sh` script) because I think it's a good addition for debugging. Maybe we can move it into the `website` package though.

> Also, how does line 219 get the right source as input? Does that come from line 222?

Do you mean 227-229? The src is found before this entire function and are given as inputs via the Example E data. The code just does a bit of extra packing. The first item in the tuple is the actual Example and the second item is the  CodeSource. 

> One big problem I had is trying to match up the boolean values for each document source to its proper place (notably, line 220 of Main.hs). I originally thought it could split up like the codesource stuff, but I I get a list of values for the boolField instead of just one (which I try to solve with selectSrc but doesn't really work).

I think going off of implicit ordering wont work too well. I think it will be easier to just create a list of Strings for the languages.
e.g.,
```
data Example = E Name [CodeSource] SRSVariants Description [DocsExist]
data DocsExist = CPP Bool | CSharp Bool | Python Bool | Java Bool | Swift Bool
```
->
```
data Example = E Name [CodeSource] SRSVariants Description [String]
```
where instead of having `[Cpp False, C# False, Java True, Python True, Swift False]`, we could instead just have `["Java", "Python"]`. This also allows the website generator to not have to care about what languages are supported.

Also, I think that the best way to gather the names is to go into the `deploy/examples/<GlassBR>/doxygen` folders (of course, varying the GlassBR using the found `name`s), gathering all of the names of the non-empty folders (e.g., it will always be `cpp`, `csharp`, `java`, `python`, `swift`). This would change your
```
  let docSources = map (map (\(CS _ dPath _ name) -> (dPath, name))) sources
  docsExistSources <- mapM (mapM doesFileExist) (map (map fst) docSources)
  let docsExist = fillMissingCheck (map (uncurry filePathCheck) $ zip docsExistSources (map (map snd) docSources))
```

into something that resembles more like the `descriptions` gatherer;
```
  -- a list of Just descriptions or Nothing based on existence and contents of desc file.
  descriptions <- mapM (\x -> doesFileExist ("descriptions/" ++ x ++ ".txt") >>=
    \y -> if y then Just . rstrip <$> readFile ("descriptions/" ++ x ++ ".txt") else return Nothing) names
```
(except that it would be the list of names for which the `<name>` folder is non-empty in the doxygen folder of each example).

I also think that you need to use `doesDirectoryExist` or [`listDirectory`](https://hackage.haskell.org/package/directory-1.3.6.2/docs/System-Directory.html#v:listDirectory) instead of `doesFileExist` since you're checking directories, not just files. It looks like the function is picky about this.

Finally, you could tie it all up with a boolField very similar to your existing one (which I left as pseudocode in b47985c1e6f3ede5b62b8f53a2f8c749535c02ef):
```
boolField "doxExist" ((\x -> langName (snd x) `elem` dox (fst x)) . itemBody)
```

**Comment by Ant13731** [comment]
I tried to implement some more changes but now I am running into a problem with the projectile example. Since the contents of the projectile folder are separated by example, the documentation is also separated by example. I'm stuck on trying to find a way around it (although what I have so far works for GlassBR example). Thanks for your help!

**Comment by Ant13731** [comment]
Originally, I had tried to achieve this by wiping out the doxygen path if it didn't exist. However, because of the structure of the IO functions, this didn't do anything except bring the user back to the Drasil website homepage.

After that, I tried to get the examples to show which doxygen documents existed by having an if statement in the `index.html` template file that would take in which documents existed and display the results accordingly. In order to get to that point, I made a `DocsExist` type where
 ```Haskell
data DocsExist = CPP Bool | CSharp Bool | Python Bool | Java Bool | Swift Bool
```
Then this would be added to the `Example` type so that it would take in 
```Haskell
data Example = E Name [CodeSource] SRSVariants Description [DocsExist]
```
for each example. However, this didn't really work out as the IO function I was trying to use (`boolField`) only accepted booleans. Making a function to convert from `DocsExist -> Bool` was more difficult than I thought, as the booleans now had to be organized in a list. But without the accompanying constructor for the boolean, I didn't know which order the list of booleans was in, or what languages they corresponded to. I couldn't manage to get this idea to work. The intermediate functions (`selectSrc`, `getBool`, `fillMissingCheck`) I was trying to make/use seemed to be making more new problems than it was solving. I think this method didn't work out mostly because I'm not too familiar with IO (and even Monads) in haskell yet (although I spent some time learning more about it this morning when implementing the next idea so I might fare better a second time around).

The next way I tried doing this was to use strings of the folder names. If the doxygen folder didn't exist for a specific language/example, there would just be an empty entry/list there. Although this doesn't use rigorous data types, it did make getting the `boolField` function to work much easier (we could just use `elem` to see if the desired language was in the list of doxygen directories). I also used the `>>=` operator a lot in checking if the documents existed, but the projectile example caused some problems since its folder structure includes variants within the doxygen directory.

I also noticed that if no code generation exists, the website still displays an empty bullet point sometimes. Also, the projectile example seemed to cause problems for all the above ideas. I'm not really sure what the best way to go about doing this is.

**Comment by JacquesCarette** [comment]
Please try again, but back up to the very begining: what problem are you trying to solve exactly? [I roughly know, but it's helpful to spell it out.]  And then go from the problem to the design. There's a whole bunch of steps before "wiping out the doxygen path" will even make sense as part of the solution description.

The reason I'm asking is that I think something went wrong in your design a couple of steps before this, and that's what I'd like to fix.

**Comment by Ant13731** [comment]
The original problem I'm trying to solve is that the Swift doxygen links that don't actually have a doxygen file should be removed from the website. I am trying to remove both the name and link of the "[Swift]" part from the "Generated Code Documentation" section of each example

Starting from the very beginning, I thought all I had to do was modify the Hakyll template (the file in `code/website/index.html`). I was planning on doing this by creating an if statement inside the existing for loop that would catch the `Swift` variables and just skip over them. However, [Hakyll's template syntax](https://jaspervdj.be/hakyll/reference/Hakyll-Web-Template.html) doesn't support complicated if statement expressions as the variables must be True/False themselves (there are no comparison operators like `==` or `!=`). I believe this is because all the variables are supposed to be generated by the Haskell file associated to the template file. Here is something similar to what I wanted to do.
```HTML
$-for(src)$
    if(doxPath != "Swift")-$
        <a href="$doxPath$">[$lang$]</a>
    $-endif$
$-endfor$
```
Following this idea through, I figured that if I could make the `doxPath` for Swift empty, then the if statement would return false and it would not display the non-existent link.
That is where the first idea above comes from (wiping out the file path for Swift). That didn't work as doxPath did not remain empty. It still contained the root file path "`Drasil/code/deploy`" because of how the existing structure of the IO functions.

After that, I realized this is what Hakyll can accept:
```HTML
$-for(src)$
    if(doxExist)-$
        <a href="$doxPath$">[$lang$]</a>
    $-endif$
$-endfor$
```
So then came the Boolean idea. If I could pass some booleans that were calculated using `Main.hs` into the template file, then it would skip over the ones that were False, just as I had originally wanted. But that introduced some ordering problems as the booleans now had to be sorted correctly in order for the right language to match up with the right boolean in the list.

That's where using strings came in. If the language name existed in the list of filled directories, then I could easily get a boolean out of it by using `elem` with the language name.

**Comment by JacquesCarette** [comment]
Thank you.

So part of the problem is caused by the technology we use (Hakyll in this case).  It is too inflexible to do the job, and leads to pain and hacking. Re-using technology is good, but not at this level of pain.

Drasil already contains an HTML generator. Why not use it to generate the web site instead? Then the programming language to use would be full Haskell, with no weird restrictions.  We could then simply generate the website ourselves, and avoid these issues altogether!

**Comment by Ant13731** [comment]
Okay, I think that would be cool! Where would be a good starting point for doing something like this? I'm not really familiar with how Drasil generates from the printers to the actual html file. Would it be similar to generating an example where we could use the drasil language to write what we want to print (without all of the SRS sections)? I'm guessing the `build_website` function in the deploy_stage.sh script and the makefile will have to change a little as well?

**Comment by JacquesCarette** [comment]
Let's talk about it at the meeting.

**Comment by balacij** [comment]
Yep, the build_website and deploy_stage.sh scripts would likely change slightly, but probably not too much since we'd still want to generate Drasil code/doc/etc artifacts before building the final website artifacts, and then generate website artifacts with copies of the Drasil build artifacts.

A good start is probably to create a new package for the website (`stack new drasil-website`) and to create a very basic hardcoded website. You will probably find the `drasil-printers` package to be very helpful as that's what contains all the TeX/HTML/Markdown magic. In particular, the [LayoutObj.hs](https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-printers/Language/Drasil/Printing/LayoutObj.hs) will probably be a good start to looking around, we could build out our existing website with a `Document` and `LayoutObj`s (with hardcoded data if any), and try printing it out via the [`genHTML/build`](https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-printers/Language/Drasil/Printers.hs) (though we may need to expose more functions from things to get more functionality for non-scientific softwares to make things too).

**Comment by Ant13731** [comment]
Okay, sounds good. Thanks for all your help!

**Comment by Ant13731** [comment]
Should I use Drasil `Sentences` to hardcode the information for now, or leave it as strings?

**Comment by balacij** [comment]
Either way is fine, whichever is easiest. The project will surely progress in a situation where you have to decide later. I imagine we'd end up with Sentences in the end for most things, but starting with just Strings should be fine for a proof of concept.

**Comment by balacij** [comment]
I just realized this now, but, this new website could (should?) be an example of Drasil (under `drasil-example`).

**Comment by Ant13731** [comment]
Yea, I was thinking something like that too. But I'm not sure if it should be included with the actual examples since making a website seems a little too far off from a SRS. I finished hardcoding all the info and am starting to check out the generators themselves. I think I could possibly make it like an example (with different hardcoded sections) and its own `SystemInformation` (maybe to be used for implementing URL `References` or something similar.

**Comment by JacquesCarette** [comment]
Although that's appealing, I think that's pushing things too far. As it won't be an example of Drasil per se, just of a small part of it.

I would go with `drasil-website` for now. And if we can eventually make it an example, great!

**Comment by Ant13731** [comment]
The website content files are almost ready, but I'm not quite sure how to run it. I haven't had a solid chance to look at how the makefiles are run yet so I'll try tomorrow. Is there a way to use stack to individually make the website file an executable along with the dependencies?

**Comment by balacij** [comment]
If you have specific questions, I can try to answer them. The general idea is that we bundle all the artifacts into a "deploy" folder (Haddock docs, doxygen, tex/pdfs, SRS docs, etc) which is then passed along to the website executable as variables (hence the DEPLOY_FOLDER and related environment variables in the `Main.hs` website file). The website then uses those assets to do whatever processing it needs to do of the website. The website executable builds a `_site` folder in the `website/` folder which is then copied over by the `deploy_stage.sh` script back into the "deploy" folder.

I'm not quite sure what you mean "an executable along with the dependencies" -- do you want Stack to zip/jar the executable with the HTML assets and other artifacts together? If so, I don't think Stack does that, but the above mentioned environment variables is likely how can go about it.

**Comment by Ant13731** [comment]
Ohh okay I see now, I think I was going about trying to implement/compile the website the wrong way. For now, is it okay if I hardcoded all of the folder paths?

**Comment by balacij** [comment]
Of course, that's a simple enough thing that can be added back later.

**Comment by Ant13731** [comment]
I'm still getting a similar error to above, it now shows without the first few lines:
```
Error: While constructing the build plan, the following exceptions were encountered:

Unknown package: website

Some different approaches to resolving this:


Plan construction failed.
```
where changing the build rule in the makefile from `stack build --ghc-options="-Wall" website` to `stack build --ghc-options="-Wall" otherName` also changes the error message to `otherName`. As of now, website is defined as an executable in the yaml and cabal files, but I'm not entirely sure if that's even the problem.
A few more questions:
What does the `stack exec --website rebuild` command do (specifically the rebuild part. Is that something from stack)?
Should I move all of the needed files from `website` to `drasil-website` (like images and descriptions folders)? On that note, does Drasil generate the css file needed as well?
I also don't really know where the actual website html file will go when the program manages to compile.

Thanks for all your help!

**Comment by balacij** [comment]
Hmm, that's weird. You could probably try to remove the "website" designation entirely and it should work.

I've never seen the `rebuild` used with stack. Did you check their RTD?

Yep, moving over the assets sounds like a good idea.

I believe the CSS was hand-written (or copied, I don't know for sure), and it looks like it's just copied and compressed by the existing website infrastructure.

That's fine. Once you build the artifacts, we just need to create a predictable/reproducible infrastructure for the overall deploy phase.

Does the website really rely on all of those Drasil packages? If it does, we'll need to make sure that we can share the stack cache for the GitHub Actions. We might just need to make the working directory for the build and such in the `code/` directory. But that can be done later.

**Comment by balacij** [comment]
Ah, yes, the `package.yaml` file is an `hpack` file. Stack uses hpack to create the cabal files. We should never be altering the cabal files manually anymore.

**Comment by Ant13731** [comment]
I don't think it relies on all of them, but definitely on the drasil-lang and printers/generator stuff. 
I couldn't find anything about stack and rebuild.

When I compile (used `make deploy_lite`)without the website package specified in the makefile, I think it went through everything and compiled it (not just Drasil packages, but also lens, vector, and unicode packages). When recompiling after making a change to the website, it seems to only recompile the related changes. I had also removed the unneeded drasil packages from the dependency list (like `drasil-gool`) but the program still compiled it the first time.

I'm now getting a lexical error but I should be able to figure it out. Thanks!

**Comment by balacij** [comment]
> When I compile (used make deploy_lite)without the website package specified in the makefile, I think it went through everything and compiled it (not just Drasil packages, but also lens, vector, and unicode packages). When recompiling after making a change to the website, it seems to only recompile the related changes. I had also removed the unneeded drasil packages from the dependency list (like drasil-gool) but the program still compiled it the first time.

Ah, yes. On the GitHub Actions, that won't be a problem then -- since it sounds like the `.stack-work` is shared between building the drasil-* and the drasil-website. Nice!

**Comment by balacij** [comment]
This ticket certainly spiraled into something much larger (and better) than I expected!

**Comment by balacij** [comment]
@Ant13731 are we okay to delete the [remoteSwiftDoxygen](https://github.com/JacquesCarette/Drasil/tree/removeSwiftDoxygen) branch?

**Comment by Ant13731** [comment]
Yes, I think so. We don't use Hakyll anymore, so any changes there are not needed.

**Comment by balacij** [comment]
Thanks!
