### ISSUE TITLE
New ModelKind: `EquilibriumModel`?

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2581]
Related to #2371 

Considering SSP's [equilibrium TM](https://jacquescarette.github.io/Drasil/examples/SSP/srs/SSP_SRS.html#TM:equilibrium) and [momentEql GD](https://jacquescarette.github.io/Drasil/examples/SSP/srs/SSP_SRS.html#GD:momentEql), I don't these are models that we can model as `EquationalRealm`s because an `EquationalRealm` says that some quantity can be defined using one of any number (> 1) expressions. I think we need a new kind of model that says:
* for some pool of expressions, they are equivalent under certain conditions (conditions may be trivial/empty)
* we can calculate settings where the above equivalence holds using a set of QDefinitions that define the variables

Related models:
![image](https://user-images.githubusercontent.com/1627302/121242311-63b7a380-c86a-11eb-8f44-3a19446ed970.png)
![image](https://user-images.githubusercontent.com/1627302/121243041-433c1900-c86b-11eb-9fd7-b1dc88212002.png)

**Comment by smiths** [comment]
@balacij, the way equilibrium conditions are written isn't so much to show that the sums of forces and moments are equal; it is just a short-hand notation to show that they are all equal to zero.  That is, the important fact isn't that they are equal; the important fact is that they are all equal to zero.

It might help to write the equilibrium condition as three separate equations, each of which is a sum of forces (or moments) that are equal to zero.

The reply for @JacquesCarette just showed up as I was typing this.  :smile:

Yes, this is a conservation law.  It is a special case of the conservation of momentum, where the momentum is zero.  It might be confusing to call it this though, since the concept of momentum isn't needed anywhere else in the problem.  We can derive equilibrium from Newton's second law, but that might be making things too abstract.

**Comment by balacij** [comment]
Perfect!

Would [TM consThermE](https://jacquescarette.github.io/Drasil/examples/SWHS/srs/SWHS_SRS.html#TM:consThermE) of SWHS also be considered an `EquilibriumModel`?

![image](https://user-images.githubusercontent.com/1627302/121249471-9e253e80-c872-11eb-9498-f26010dde0c4.png)


Also, the linked source for this one calls a similar equation a "steady state equation". Perhaps `SteadyStateModel` is a more precise name than `EquilibriumModel`?

**Comment by balacij** [comment]
Ah, thank you @smiths! I'll need to go through this ticket slowly and come back with a fresh set of questions :smile:

**Comment by balacij** [comment]
That sounds good. I can work on building them today with multiple equations instead of one. Thank you.
