### ISSUE TITLE
Double Pendulum: Scope of Requirements

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2616]
@cd155, please remove the double period at the end of the sentence in the Scope of Requirements section for the Double pendulum example.

**Comment by cd155** [comment]
A quick update on this ticket.

In order to remove the extra period on scope, I can change the `foldlSent` to `foldlSent_`. Most of examples use `foldlSent_` in their scope variable, so it seems a safe move change it to `foldlSent_`.

Base on the documentation about `foldlSent` and `foldlSent_`, the only difference between two is that `foldlSent` will add a period at the end of sentence. On the other hand, `foldlSent` doesn't. 

One question that I have, I actually not sure why there will be a period when using `foldlSent_`. If I understand it right, there shouldn't be a period at the end when using `foldlSent_` and there should be one period when using `foldlSent`.

**Comment by smiths** [comment]
Given that @JacquesCarette is away, do you think you could look into this question @balacij?

**Comment by balacij** [comment]
Of course!

@cd155 Like you mentioned, it does look like changing the `foldlSent` to the `foldlSent_` is the solution here.

[`foldlSent`](https://jacquescarette.github.io/Drasil/docs/full/drasil-utils-0.1.1.0/Utils-Drasil-Fold.html#v:foldlSent) is the variant that appends the "." at the end, and [`foldlSent_`](https://jacquescarette.github.io/Drasil/docs/full/drasil-utils-0.1.1.0/Utils-Drasil-Fold.html#v:foldlSent_) does not. So, it looks like your understanding is correct (sans a typo where you said `On the other hand, "foldlSent" doesn't.` -- the `foldlSent` should be a `foldlSent_`).

**Comment by smiths** [comment]
Thank you @balacij.

**Comment by cd155** [comment]
@balacij In the scope variable, I just wonder why `foldlSent` would end to have two periods. Should the `foldlSent ` end to have one period, and `foldlSent_` end to have no period?

**Comment by balacij** [comment]
It's not quite the `foldlSent` (that you're looking at) that's making it result in 2 periods at the end -- that one is only 1 period. There's some later processing done in `drasil-docLang` that causes the second period to appear. It looks like it's supposed to be a cookie-cutter sentence, so I assume it strictly wants just a sentence stub that it can in-place in the "Scope of Requirements" section.

Related `drasil-docLang` processing: https://github.com/JacquesCarette/Drasil/blob/4b9ad0a3016fecb3c7a2aa82ab142f9e805b5cc8/code/drasil-docLang/Drasil/Sections/Introduction.hs#L105-L109

Here it creates a section out of the scope requirements sentence. Note that it uses `foldlSP`:

`foldlSP`:
https://github.com/JacquesCarette/Drasil/blob/4b9ad0a3016fecb3c7a2aa82ab142f9e805b5cc8/code/drasil-utils/Utils/Drasil/Fold.hs#L45-L51

which relies on `foldlSent` (which appends the period!).

If we wanted to change the `foldlSP` to a `foldlSP_` (which would use `foldlSent_` -- not appending a period), then we would probably need to alter all the other examples to add a period.

If you want to follow the chain of `IScope` usage that I used, the same `grep` usage will help a lot.

**Comment by cd155** [comment]
@balacij thanks, I see what's going on here. The grep search command is super useful, thanks for introducing it. :D
