### ISSUE TITLE
Double Pendulum: Fix Physical System Description

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2617]
The figure of the physical system for the double pendulum example only show one pendulum.  Please update the figure to show both pendulums.

**Comment by cd155** [comment]
I made a new figure for the double pendulum.
<img width="445" alt="Screen Shot 2021-07-13 at 3 09 08 PM" src="https://user-images.githubusercontent.com/16947266/125512076-fa391f32-28e7-47d1-b919-507b05c0242d.png">
I think it may need to be refined because this figure will reflect the double pendulum theory. The theory part is missing, so these labels are likely changed when double pendulum theory be introduced.

**Comment by cd155** [comment]
The previous figure has slightly different elements than the example. The center mass of two objects is on the center of the rod rather than at end of the rod. Here is a slightly different version which the center mass at end of the rod.
<img width="445" alt="Screen Shot 2021-07-14 at 3 24 21 PM" src="https://user-images.githubusercontent.com/16947266/125681394-453122c7-b2a5-4f07-9f3a-61038b304812.png">

**Comment by smiths** [comment]
Yes, the second figure looks very nice @cd155.  Please go ahead and add it to the generated document.  We might want to make some changes, as you say when we update the theory, but this is a good start.

What software did you use to draw the figure?

**Comment by cd155** [comment]
I drew the figure on [draw.io](draw.io) 

I think this website was recommended in your class, intro to software design. I used it draw UML before.

**Comment by smiths** [comment]
I thought it looked like draw.io.  :smile:

**Comment by JacquesCarette** [comment]
Should this be closed? Are we sure the diagram is actually used?

**Comment by smiths** [comment]
I closed it because the figure was drawn, but you are right, we should wait until it is incorporated into the example.
