### ISSUE TITLE
Double Pendulum: Characteristics of the intended reader

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2632]
In the introduction for the double pendulum, add a section about the characteristics of the intended reader.

**Comment by cd155** [comment]
A quick update on this ticket.

Adding characteristics seems similar to adding purpose in SRS. Technically, there is litter difficult to add this section. However, the Characteristics of Intended Reader section has more customized information than the purpose. For example, in the physics games example, it says "reviewers should have an understanding of rigid body dynamics and high school calculus". Those kinds of information are missing in the current SRS. I wonder should I just try to search through the internet to add the information of Characteristics of Intended Reader.

**Comment by cd155** [comment]
For the characteristics of the intended reader, I referenced the manual version of double pendulum example, [https://github.com/Zhang-Zhi-ZZ/CAS741Project](https://github.com/Zhang-Zhi-ZZ/CAS741Project)

The following new information will be added in  characteristics of the intended reader:

"The intended readers are expected to have an understanding of advanced Physics and Calculus, with knowledge of ordinary differential equations."

I checked the phrases we have, it seems we don't have any nouns related to advanced. We do have highschool physics and highschool calculus,
https://github.com/JacquesCarette/Drasil/blob/bae3160fbbdba87da35a0650d0cdca2857f11dba/code/drasil-data/Data/Drasil/Concepts/Education.hs#L26
https://github.com/JacquesCarette/Drasil/blob/bae3160fbbdba87da35a0650d0cdca2857f11dba/code/drasil-data/Data/Drasil/Concepts/Education.hs#L36-L37
@balacij Do you think it is a good idea to add "advanced" in Education.hs

**Comment by balacij** [comment]
At the very least, I would say that it's a good start. We can also use "advanced" to also describe actions (for example, "You've advanced a level"), but I'm not sure how we want to organize words like this. Perhaps @Ant13731 could also pop in here since he's working on Sentences often :smile:

**Comment by tingyuw** [comment]
I agree that we can include this kind of word in the concepts. But the word "advanced" doesn't seem to fit in the Education category. We can see if there is a better way to organize this word or maybe just add ``advancedCalculus`` in Education? I think it might work since we have ``scndYrCalculus`` :)

**Comment by Ant13731** [comment]
Yea, I think only having the advanced attached to a noun (like `advancedCalculus`) is good. I don't think we would want to make "advanced" its own chunk because then we wouldn't know if its being used as a verb (eg. "you've advanced a level") or as an adjective (eg. "advanced calculus"), which would have different uses and should probably be represented differently in Drasil. So keeping it attached to a noun will keep it in line with our current setup of using `NounPhrases`.

Alternatively, we could add `advanced` as a combinator in `Utils.Drasil.Concepts`. It's not quite the same as the rest of the combinators (which are more focused on joining two ideas rather than modifying one idea), but at least users would be forced to use it before a noun.

Also we might want to avoid the word "advanced" because it could be a little ambiguous. Giving a precise year or education level could be better for new readers to understand quickly. But either way, I think adding `advancedCalculus` will work just as well.

**Comment by cd155** [comment]
Thanks all, @tingyuw The `scndYrCalculus` use `compundNC`
https://github.com/JacquesCarette/Drasil/blob/bae3160fbbdba87da35a0650d0cdca2857f11dba/code/drasil-data/Data/Drasil/Concepts/Education.hs#L38
Since we don't have an adjective for "advanced", can `advancedCalculus` still be written like `compoundNC something1 something2`? 

As @Ant13731 mentioned "advanced" adjective may be ambiguous, @smiths do you think I can interchange it with "undergraduate"?

Change:
 "The intended readers are expected to have an understanding of **advanced** Physics and Calculus, with knowledge of ordinary differential equations."

To:
 "The intended readers are expected to have an understanding of **undergraduate** Physics and Calculus, with knowledge of ordinary differential equations."

**Comment by Ant13731** [comment]
>Since we don't have an adjective for "advanced", can `advancedCalculus` still be written like `compoundNC something1 something2`?

You might have to use the [`nc`](https://jacquescarette.github.io/Drasil/docs/full/drasil-lang-0.1.60.0/Language-Drasil-Chunk-NamedIdea.html#t:NamedChunk) constructor to do it, but it should be similar. The only difference is that you would have to give it a UID and find the function that can create the term (probably [`cn`](https://jacquescarette.github.io/Drasil/docs/full/drasil-lang-0.1.60.0/Language-Drasil.html#v:cn))

**Comment by smiths** [comment]
@cd155, I like "undergraduate" better than "advanced".  As was mentioned by @Ant13731, advanced is ambiguous.  However, I think we can do better than "undergraduate", since undergraduate could be Level 1 introductory calculus, or Level 4 "advanced" calculus.  :-)

I think we should provide the level of the calculus and physics that we mean.  Physics and mathematics are very standardized across institutions.  If someone says level 1 calculus, that is a fairly meaningful statement.  For the double pendulum example, let us say Level 2 physics and Level 1 calculus.  We really should refine these ideas, since it isn't all physics and calculus that are necessary.  I will comment on this with the pull request.  (https://github.com/JacquesCarette/Drasil/pull/2697#pullrequestreview-709924161)
