### ISSUE TITLE
Formatting of generated READMEs

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2682]
The formatting of the generated READMEs can be cleaned up a little bit. The current formatting of the document does not play well with GitHub's (nor VSCode's) Markdown renderer.

For example, this is GlassBR's:
![image](https://user-images.githubusercontent.com/1627302/125657284-bdc03811-edc2-4f1c-99fb-d22c34401dfd.png)

Tasks:
* Since it looks like the document is formatted to have sections, we should use markdown headers instead of bold facing spaced code.
* The file list looks like it should be on the next line but renders on the same line as the bold-faced `configuration` text.
* The versioning requirements can likely be cleaned up a little bit: use list formatting + remove the word "Version" from each line.
* There's a TODO note in `drasil-printers/Language.Drasil.Markdown.CreateMd` for adding the license information + Drasil logo to the document.

**Comment by balacij** [comment]
@Awurama-N / @Ant13731 Anyone interested in this?

**Comment by Ant13731** [comment]
For the license, can I just copy the text in the `LICENSE` file in the home directory?

**Comment by balacij** [comment]
Hmm, I think linking to it would be best. What do you think?

**Comment by Ant13731** [comment]
Maybe we could just have the first sentence: "Copyright (c) 2014, JacquesCarette All rights reserved." and then link to it?

**Comment by balacij** [comment]
I'm not too sure about copyright, sorry. Dr. Carette or Dr. Smith will need to weigh in here.

For the Drasil icon, yep, I think that's the only way to do it. Good catch!

**Comment by smiths** [comment]
I don't think we should keep "Copyright (c) 2014, Jacques Carette All rights reserved." in the generated LICENSE file.  The date will be wrong, and the author is wrong.  I think for the case study examples the author should be the authors of the SRS, as given in the Drasil source data.  I think it would make sense for the Copyright date to be the date of generation, although maybe we should add "date" information as data in the Drasil source files.

At some point we should get fancier and allow the Drasil source files to include input so that the user can select their License model.  Here is a web-page for helping people select their license:

https://choosealicense.com/

Here is a list of licenses:

https://tldrlegal.com/

By default for now we could use the @JacquesCarette LICENSE with the date and author updated.  We can create an issue for the future to add more flexibility in license selection.

I just had a thought - if we use the current date in the LICENSE file `stable` and `build` will not match.  We would be better off with date information as an input.

**Comment by Ant13731** [comment]
Okay, I just updated the author section as in [here](https://github.com/JacquesCarette/Drasil/tree/changeReadMeGenFormat/code/stable/pdController/src/python).

Should we create an issue to allow date information to be passed through? I don't think any of the examples have the date recorded.

**Comment by smiths** [comment]
Thank you @Ant13731.

Yes, @Ant13731, please create an issue to add date information.  We don't currently have this information in Drasil, but we should.
