### ISSUE TITLE
Single pendulum and double pendulum example

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2692]
@smiths I did remember that @JacquesCarette said we can copy the current double pendulum to a new example. Then, rename one of them to a single pendulum and fix the other one to a double pendulum. Later on, we can cross-reference two examples. In this way, we can learn the family of a pendulum.

I am currently editing the double pendulum example. Before I start to edit the theory of the current pendulum example, should I make a copy to keep the current pendulum example?

**Comment by smiths** [comment]
@cd155, you remember correctly.  Our goal is to have a mini-family of pendulum examples.  Ideally we'll also want an n-pendulum, which is almost the same, except that it supports any number of pendulums.

Since the current example is closest to being a single pendulum, you should make a copy of it and modify the copy to become the double pendulum example.
