### ISSUE TITLE
Latest deployment/build failed

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2695]
https://github.com/JacquesCarette/Drasil/runs/3104389895?check_suite_focus=true

I don't really know how this happened. I wonder if we had 2 PRs that got merged in which did conflicting changes but didn't cause git merge issues against each other. Maybe we need to add a `git pull origin master` step to the top of the build tests to fix this (for the future)?

**Comment by balacij** [comment]
Maybe we should add the "make website" step to the test deployment step too actually?

What do you think @Ant13731 ?

**Comment by Ant13731** [comment]
Yea, maybe we could add it to the `make` command as well? Just so it always compiles?

**Comment by Ant13731** [comment]
I've been trying to solve this (the fix on `fixingWebsite2` should have been all it needed), but my linux subsystem isn't generating an updated version of the website (its using the old name "Drasil_Website.html" instead of the new name "index.html" and not including any changes I make to the files in `drasil-website`.

**Comment by balacij** [comment]
That's a good idea. It depends on how we view the targets and the website as being an example or not. I'd tend towards not doing this right now but discussing it in #2642.

**Comment by Ant13731** [comment]
Yea. The website really does a lot of stuff an example would do. Maybe having a stable folder could be good - any unexpected changes in the website could mean something is way off. I think I should also fix it up to be more recipe-like (especially Example.hs), just because it's a little too messy right now.

**Comment by Ant13731** [comment]
Okay, the changes worked on my forked repo so I opened a PR for it.

**Comment by balacij** [comment]
I think that one of the constraints on the drasil-website is that hpack (our package.yaml files) doesn't support multiple libraries in a single cabal file. Right now, we have all of the executables listed in a single cabal file and Cabal supports multiple libraries (apparently) and executables designated in a single file, but hpack doesn't. If we could split every single example into library+executable (where the executable file is essentially a `Main.hs` file + dependency on the library of the example), we could also have the `drasil-website` depend on all of the other examples through their libraries and pick up the information from them nicely too. I guess we could just include the files in the source files listed for the website too but I think that would result in those files getting compiled twice each time.

**Comment by Ant13731** [comment]
Okay, I think I get it. Could we then pass the `SystemInformation` from each example to the website? Would each example need their own `.yaml` file?

**Comment by balacij** [comment]
> Could we then pass the SystemInformation from each example to the website?

Yep :smile: 

> Would each example need their own .yaml file?

It depends. I guess if we changed `drasil-example` into just a folder carrying individual stack projects for each example (e.g., `projectile`, `glassbr`, `pdcontroller`, etc), then we would, of course, need a `package.yaml` + `stack.yaml` for each example individually (we could still have a stack.yaml inside of `drasil-example` I think). But I think the 'best' solution would be if hpack natively supported converting multi-library softwares into multi-library cabal files as well.

I guess we have another alternative; 1 single `drasil-example` library that each example pulls from. Then the executables for each would be a `Main.hs` + a dependency on `drasil-example` (a library containing all code necessary for all examples).

So, we now have a few potential solutions to the issue of `drasil-website` not having a dependency on the examples (and pulling information from them directly):

1. Split each example into lib+exe in their own stack package (this would require moving each example's code into another folder for just them)
2. Make all of the "source" files of `drasil-example` belong to a focal `drasil-example` library and then have `projectile`/etc examples all depend on the single `drasil-example` library.
3. Get `hpack` to natively support multi-libraries in a single `package.yaml` file (I don't think this will be as easy the above 2)

I hope I'm explaining this well.

Do you have any thoughts and/or preferences on this @JacquesCarette?

**Comment by JacquesCarette** [comment]
Looks like there is a new break in the build - probably a merge error?  @Ant13731 @balacij https://github.com/JacquesCarette/Drasil/runs/3107188741?check_suite_focus=true

**Comment by Ant13731** [comment]
Ah yep, I'll add that to the fixingWebsite merge.

**Comment by JacquesCarette** [comment]
About this particular issue: eventually, we'd like to have so many examples that having a single example package would be ridiculous. So we'll eventually want to split it up. If that moment is now, because of other reasons, that's fine.

`drasil-website` really ought to depend on the examples, "logically". So I'd rather not hack that. Changing `hpack` to natively support multi-libraries in a single `package.yaml` might be the best solution, but it also seems like a rather slow (and potentially difficult one). So, I'd rather not count on that.

**Comment by balacij** [comment]
I agree. Changing `hpack` seems like it will be slow and difficult.

On the bright side of splitting up the examples into multiple package.yaml files and folders, we _may_ get slightly faster single example runs. A `make swhs_diff` probably wouldn't build and copy the binaries of the other examples like it currently does.

Relating to #2642, I think this can be one of the tasks under it's umbrella.
