### ISSUE TITLE
Differences in generated cabal files - remove autogenerated cabal files?

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2750]
I recently ran `make` to build the Drasil examples locally and now the cabal files have been modified.  Now that the cabal files are generated, should we remove them from version control?

I had a look at my generated file versus the one in the repo.  The difference is in the comments at the start.  The hpack version number is different and the hash.  Here are the comments in my local version of `drasil-build.cabal`:

```
-- This file has been generated from package.yaml by hpack version 0.34.4.
--
-- see: https://github.com/sol/hpack
--
-- hash: 2e0c5df1143056f1218ea9befb510511e30bfb9f342e9b7b6481244e84233c6f
```
The version in the repo has hpack version of `0.33.0` and a different hash.

I will just reset my local cabal files, so this isn't a big deal.  However, if the cabal files are frequently updated locally, we might want to remove them from version control.

**Comment by balacij** [comment]
I agree, and I think it's worth trying.

The Stack team has some mention of this issue on their [Sphinx instance](https://docs.haskellstack.org/en/stable/stack_yaml_vs_cabal_package_file/#should-i-check-in-generated-cabal-files) (ultimately linking to [this blog post](https://www.fpcomplete.com/blog/storing-generated-cabal-files/)), where they say that there are 3 main reasons to keep the cabal files, with 2 being potentially bugs and the last one being that the software would be inaccessible to non-hpack/Stack users. Considering we require users to have Stack installed to use Drasil too, we wouldn't have any users that don't have hpack on their machine (since it comes with Stack).

I'll create a PR for, and we can test it out quickly too.

**Comment by smiths** [comment]
Sounds good @balacij.  Thank you for investigating this.
