### ISSUE TITLE
Derivative Display Issue: Clarification of the problem

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2827]
This morning, we discussed what is my next step/ticket on the Drasil project. To be honest, I am not exactly sure what is the problem. Dr.Smith mentioned some display issues on current Drasil, then Dr.Carette mentioned derivative-related topics.

I wonder if anyone could recap the issue. I feel I missed some key parts of the information. Sorry for the inconvenience.

**Comment by balacij** [comment]
I think the display-related component was related to the second derivative. For example, the [PD Controller IM](https://jacquescarette.github.io/Drasil/examples/pdcontroller/SRS/srs/PDController_SRS.html#IM:pdEquationIM)'s equation has second derivative that should be written as "d^2y/dt^2" but is currently written as:

![Screenshot from 2021-08-31 12-19-28](https://user-images.githubusercontent.com/1627302/131539800-528e97d6-c34a-4e46-91d3-c66bfc2653d5.png)

Should be more like:
![Screenshot from 2021-08-31 12-22-50](https://user-images.githubusercontent.com/1627302/131539907-80755d90-e7f7-4314-b083-528fe1dc6a0c.png)

**Comment by balacij** [comment]
Dr. Carette suggested altering the derivative term in ModelExpr to fix this, and I am working on removing the derivative term from Expr. It might be a bit simpler to do this using the code from #2791 as a base branch instead of `master`, just note that the code there is still a work-in-progress, so you would probably need to pull from it frequently (it's stable at the moment however, and I'll try to keep it stable). From that branch, you would need to look into the `Language.Drasil.ModelExpr` and `Language.Drasil.ModelExpr.Lang` files in `drasil-lang`. I imagine the focal part of the change would be to add an integer, denoting the `n` in "n-th derivative", to the constructor for Deriv, and then modifying the smart constructors for Deriv to search for and increment Derivatives when Derivative terms are stacked on each other. It would probably also involve creating a new set of smart constructors for it, where you directly designate the degree of the derivative.

**Comment by cd155** [comment]
Thanks @balacij for clarification. As you mentioned I better use brach in #2791, what else should I need to keep note when multiple developers work on the same branch.

**Comment by balacij** [comment]
Ah, sorry, I should clarify. Instead of working on that branch at the same time, we can branch off of it and then regularly pull changes from it in the new branch.

e.g.,
To branch off of it:
```
git fetch
git checkout origin moveDerivToModelExpr
git checkout -b <NewBranchNameForAlteredDeriv>
```
and then, periodically until `moveDerivToModelExpr` gets merged into `master`,
```
git pull origin moveDerivToModelExpr
```
when the new branch is checked out. When it gets merged into master, then just run the normal `git pull origin master` regularly.

The reason why we'd want to keep the work on separate branches is just so that the PR is kept as small as possible (even though it's already very large).

**Comment by cd155** [comment]
@balacij Thanks for answering my question and  I will create a proper ticket soon. The tactic you mentioned, it sounds like a branch of a branch. Once I am done with my change, should I create a separate pull request?

**Comment by balacij** [comment]
> sounds like a branch of a branch
Yep, exactly that!

> Once I am done with my change, should I create a separate pull request?

Yes, and if you choose to branch off of `moveDerivToModelExpr`, make sure to note that it builds on that PR.

**Comment by smiths** [comment]
@balacij, thank you for clarifying the workflow for when someone is working off of an existing branch.  I feel like the instructions above should be added to our wiki for contributors.  If you agree, could you please add those instructions to the wiki?

@balacij you did a great job summarizing the task for @cd155.  One additional detail @cd155 involves the process of bringing the changes into Drasil.  You should initially keep the smart constructor for the first order derivative as it is; that is, you should make a new constructor with a new name for taking the natural number for the order of the derivative.  Once that code is working and the higher order derivatives have been fixed in the examples, you could move to replacing the original first order smart constructor with your new smart constructor.  The idea is to not make too big a change at once, since you don't want to break the code in too many places all at the same time.

**Comment by balacij** [comment]
Thank you, @smiths! I added a little blurb to the [Workflow](https://github.com/JacquesCarette/Drasil/wiki/Workflow#creating-a-new-branch) page.

**Comment by cd155** [comment]
@smiths thanks for the notice, I will keep it in mind when I work on this issue.

**Comment by smiths** [comment]
The edits to the workflow page look good @balacij.  Thank you.
