### ISSUE TITLE
Eliminate Duplicate Strings "# The default value is: NO." and "# The default value is: YES."

### ISSUE THREAD

**Issue by peter-michalski** [JacquesCarette/Drasil#2842]
Details:

"# The default value is: NO."
Number of instances of string: 99
Number of files containing the string: 1
./Drasil/code/drasil-code/Language/Drasil/Code/Imperative/Doxygen/Import.hs:"# The default value is: NO."

"# The default value is: YES."
Number of instances of string: 52
Number of files containing the string: 1
./Drasil/code/drasil-code/Language/Drasil/Code/Imperative/Doxygen/Import.hs:"# The default value is: YES."

**Comment by peter-michalski** [comment]
Proposing similar solution as in #2844. All such strings will be located in the same /code file.

**Comment by JacquesCarette** [comment]
Again, too simple, but here for a different reason: you did not analyze the reason why this string is duplicated so many times. We need to find the reason for the duplication, so that the solution matches it.

All duplication elimination needs to come with a deeper analysis + explainable solution. The point is not to merely eliminate duplication, but to understand the deeper reason for the symptom.

**Comment by peter-michalski** [comment]
Looks like each of the projects has doxConfig.txt files generated for each language (java, Python..). These files include "The default value is: " string for various parameters. 

comment in the file:
-- | A 'Doc' that holds optimized choices for configuring doxygen files.

Seems to me that it would be best to leave these strings as they are. They indicate optimized choices. They are simply being printed in a documentation file. The code is readable and understandable as is.

Is removing this duplication for the sake of removing duplication a good idea? My current thought is no, but please comment if you disagree.

**Comment by smiths** [comment]
@JacquesCarette is the best person to comment on this, but when I look at [Import.hs](https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-code/lib/Language/Drasil/Code/Imperative/Doxygen/Import.hs) I can't help but think that it would be better if the doxygen config file wasn't hard-coded into the Haskell code.  A doxygen config file is relatively easy to generate using doxygen itself.  When Brooks did this he would have just used doxygen to create the config file and then converted it line by line to Haskell code.  There are a few spots (maybe only one?) where it is customized (the project name), but for the most part it is just standard boilerplate doxygen config info. 

If we need to change the doxygen config file, say for a new version of doxygen, then we need to re-run doxygen config and then copy over the lines into Haskell code.  It wouldn't be difficult to do, especially with a good editor (or script), but wouldn't it be better if our code could just work with the doxygen config file directly?  Alternatively, what if we called doxygen and created the config file specific for each project?  I'm fairly certain that doxygen config can be given the program name as an input.  This would also let us change other doxygen configuration choices between projects, if we wanted to.

If we cannot run doxygen to create our own doxygen config file, or move all of the information that is hard-coded into the haskell code, then I agree that doing "clever" things with the existing code to remove duplication doesn't really make sense.  It is good that it looks exactly like a regular doxygen config file, since that is how I could see what was going on to brainstorm my previous suggestions.  Anything else will unnecessarily obfuscate what is happening here.

**Comment by JacquesCarette** [comment]
Let me play the "Devil's Advocate" role here.

First, @smiths is correct, this is just a transcription of the output of `doxygen` with a few 'holes' poked into it to become parameters. But let's analyze the alternatives:
1. call doxygen itself to get a new config file, and then some clever parsing tricks to find the spots that we want to programmatically change. 'clever parsing' tends to be fragile, and may fail in odd ways in the future, i.e. the failure might be subtle, and thus not caught for a long time.
2. doxygen is quite configurable, why don't we call doxygen in a "good" way so it generates the output we want? There was probably a reason for this - I would search through the Drasil repo (I see 4 hits on the wiki, 57 issues and 45 commits for the word 'doxygen') for a hint. This design was not random, although it might not be best either.
3. having 'template' code (here, doxygen config) goes against the basic Drasil philosophy. Over time, various bits started out templated (our CSS, parts of the HTML, parts of the generated Makefiles) and 'evolved' into full-fledged generators. As we better understood what information went into the files, we could "compress" this down to a very small generator that was much more semantic in its approach -- and much more configurable too.

For option 3, merely removing duplicate strings is not good ROI. Although doing it via some combinators, so that one could fold over a sequence of YES/NO wouldn't be such a bad idea. Even better would be to understand the actual content of the config file, separate out the content from the format, and then write a proper generator.  So that, for example, if doxygen were to move its config files to YAML (for example), we could readily adapt to that if we had such a generator. Any of the other methods would require a huge amount of rework.

**Comment by smiths** [comment]
Great analysis @JacquesCarette.

Yes that is a great idea to look into our previous conversations on doxygen.  I don't remember the details, but I do recall that there was an element of "get it done quickly" to our decision making.  That isn't a retroactive criticism.  I think we were optimizing our time and focusing on the most important areas of Drasil.  Focusing on the most important things might still rule out the "proper generator" approach.  I agree that a proper generator is the best choice in the long run; we'll have to evaluate whether now is the right time to go down this road.  The investigation by @peter-michalski will help us determine how much work will be involved in a proper generator.

**Comment by smiths** [comment]
@peter-michalski, great job summarizing the previous discussions on this topic.

Yes, a "proper generator" would still work if the user's doxygen is broken.  At least it would work to generate the proper config file.  The `make doc` rule wouldn't work, because there is a problem with doxygen in this scenario, but that isn't the responsibility of Drasil.  The reason that the "proper generator" doesn't depend on the status of doxygen is that it doesn't call doxygen.  The proper generator captures the doxygen knowledge inside Drasil.

A proper generator would plug in the right `PROJECT_NAME` etc as it generated the file.  Fragility is not a concern in this case.  If doxygen changes the format of their config file, we would change the generator to the new format.

As far as where to get started, @JacquesCarette will likely have some advice.  If I remember our last meeting correctly, he suggested that you start factoring out the repetition to see what it looks like.  I think it is when you try it that we'll get a clearer idea of whether we should aim for a proper generator, or something less ambitious.

I'm not sure what code is most relevant to look at as an example.  Maybe the code that generates the Makefile or the README file?  Both of these examples also incorporate the `PROJECT_NAME`.

**Comment by JacquesCarette** [comment]
I don't think we want to write a "proper generator" right now. To get the information we need, one of the best first steps is actually to convert a template into a 'cheap' generator, that just abstracts out the commonalities. The next step is to **name** the commonalities extract, and always choose *semantic*, i.e. *meaningful* names. If we can't find such a name, then perhaps what we've abstracted out is an artificial commonality, and we need to dig deeper.

Drasil is chock full of generators... but the simplest ones are the ones for the generated Makefile, README, and the one for generating the Drasil web site. It's a good exercise to find them.

**Comment by peter-michalski** [comment]
I believe the README file generator is found in https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-code/lib/Language/Drasil/Code/Imperative/WriteReadMe.hs

I am looking into the contents of this file, and where the functions are called.

**Comment by JacquesCarette** [comment]
`TagDefaultNO` is too specific, we want slightly higher level concepts.

On the other hand, ideas like "create sub-directories", "allow unicode names" and so on, are definitely things where we'd want to be more data-driven in our code.  If nothing else, maybe start with a large record (in Haskell) with the fields being names for Doxygen settings?

**Comment by peter-michalski** [comment]
Completed with #2874
