### ISSUE TITLE
addRe negation display issue

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2876]
The `addRe` can display a plus sign, and follow up a negation.

To take `a` `addRe` `neg` `b` as an example, this will display a + -b rather than a - b. 

e.g. the pdcontroller has a negative constant, -rₜKₚ. 
<img src="https://user-images.githubusercontent.com/16947266/139301779-d7000304-f65f-4ba3-8d26-3a5ee7ea058c.png" width="500">

Constant: -rₜKₚ
```haskell
c = neg (sy qdSetPointTD) `mulRe` sy qdPropGain
```

the constant term can be added after the coefficients, the standard form will be `ax0 + bx1 + cx2 + .... + contant = 0`. For the display purpose, `a + -b` should be displayed to `a - b`.

<img src="https://user-images.githubusercontent.com/16947266/139305120-77a414dc-2e09-4736-96ef-8db92e727276.png" width="500">

**Comment by cd155** [comment]
@JacquesCarette I think I narrowed down what happened.

There are three files related to `addRe` printing
1. 
https://github.com/JacquesCarette/Drasil/blob/5cac409d2821ee77614f918b0aea027d04fb4403/code/drasil-printers/lib/Language/Drasil/Printing/Import/CodeExpr.hs#L115
https://github.com/JacquesCarette/Drasil/blob/5cac409d2821ee77614f918b0aea027d04fb4403/code/drasil-printers/lib/Language/Drasil/Printing/Import/CodeExpr.hs#L170-L171

2. 
https://github.com/JacquesCarette/Drasil/blob/5cac409d2821ee77614f918b0aea027d04fb4403/code/drasil-printers/lib/Language/Drasil/Printing/Import/Expr.hs#L117
https://github.com/JacquesCarette/Drasil/blob/5cac409d2821ee77614f918b0aea027d04fb4403/code/drasil-printers/lib/Language/Drasil/Printing/Import/Expr.hs#L167-L168

3. 
https://github.com/JacquesCarette/Drasil/blob/5cac409d2821ee77614f918b0aea027d04fb4403/code/drasil-printers/lib/Language/Drasil/Printing/Import/ModelExpr.hs#L117
https://github.com/JacquesCarette/Drasil/blob/5cac409d2821ee77614f918b0aea027d04fb4403/code/drasil-printers/lib/Language/Drasil/Printing/Import/ModelExpr.hs#L182-L183

They all use their local `assocExpr` function to create a printable AST layout

The `assocExpr` function use `intersperse` to insert the operator between each element in the list. If we want to fix (a `addRe` `neg` b), I think we can create a new function almost like intersperse, but the `newIntersperse` should have a condition before inserting the operator.

**Comment by balacij** [comment]
Depending on how we view this problem, it might also be worth considering making this affect the "Expr" building via the smart constructors `addRe` and `addI`, pattern matching for the "right" added terms being a "UnaryOp Negation _". This would affect the Expr construction, instead of at printing. Specifically, it means addition of negated terms would always become a subtraction. I don't know if this is a good thing, it might be problematic if we later choose to write proofs using `Expr`s.

Additionally, I've previously had a printing-related issue with negated terms being contained as terms in multiplications (parentheses would appear/wouldn't appear when not needed/needed). I don't know for certain, but it might also be relevant (in particular, we might need to push negation outside multiplied terms as much as possible, removing double negations where possible too).

**Comment by JacquesCarette** [comment]
Before this really good comment gets lost: Yes, it would be better still if we had a more semantic representation of negation. `UnaryOp Negation _` would be a good way to do that. Then we could ensure that internally we represent all constants as positive, so that we can 'know' which ones are negative.

Also @cd155 what I was saying in the meeting: it is better to print things properly to start with rather than to generate something not-quite-right and then fix it up with a filter pass. Of course, to generate things properly to start with, your generation process might need some extra information.  Or might need to do 2 (shallow!) passes, one to generate the extra information, and one to format.

**Comment by cd155** [comment]
@JacquesCarette Thanks for reiterating it. I totally agree with the concept that it is better to generate the right things at the beginning. Otherwise, the bad thing will propagate the program. A new ticket will be created to address this issue.
