### ISSUE TITLE
SWHS: TM:latentHtE equation confusion

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2879]
In [SWHS's `TM:latentHtE`](https://jacquescarette.github.io/Drasil/examples/swhs/SRS/srs/SWHS_SRS.html#TM:latentHtE), we define "Q(t) = definite integral of (d/dTau Q(Tau)) w.r.t Tau, from 0 to t", but we use the same "Q" symbol, so if I'm not mistaken, the right-hand side of this equation should ~ evaluate to "Q(t) - Q(0)". In which case, the definition for "Q(t)" is "Q(t) = Q(t) - Q(0)". Quickly glancing at the source reference (a wikipedia article on latent heat), I wasn't able to find this specific form of the equation. Additionally, looking into `IM:heatEInPCM`, I'm a bit confused how "Q_p(t)" is defined as a derivation from `TM:latentHtE`. I might be missing some information here, but I'm not quite sure what specializations took place here to take the theoretic latent heat equation and derive "Q_p".

Any help would be much appreciated! Thank you!

(EDIT: I hope it's okay that I'm assigning you to this ticket, @smiths)

**Comment by smiths** [comment]
Great question @balacij.  Your question brings up issues with how the theory is presented.  (I'm optimistic that a more rigorous process using theories throughout won't have issues like this.)  Another unfortunate issue is that the translation from the manual example to the Drasil example appears to not have been complete.  (Unfortunately when past students couldn't come up with how to do something in Drasil, they sometimes decided to just not do it.  I thought I caught all of these, but in looking into your question I found a big one that it appears we missed!)

To start with, there is a mistake in the Drasil version of the definition of Latent Heat.  In the [original document](https://github.com/smiths/swhs/blob/master/docs/SRS/PCM_SRS.pdf) T3 (on page 13) has Q(0) = 0.  We don't have Q(0) = 0 in the Drasil version.  The definition of `TM:latentHtE` doesn't really say anything, but it is in there for solving the ODE, since we need a rate form dQp/dt.  (We might want to change this in the future when we revised with theories.) With Q(0) = 0, the theoretical model says Q(t) = Q(t).  This isn't wrong, but it probably could be said in a better way.  The purpose of the theoretical model was to capture the idea that the latent heat isn't added all at once.  When a material is melting the heat is continually added, without raising the temperature, until the material is all melted.

The bigger error in the translation from the manual version to the Drasil version is for the definition of Q_p.

In the [original manual version](https://github.com/smiths/swhs/blob/master/docs/SRS/PCM_SRS.pdf) IM4 (on page 24) defines dQ_p/dt.  This definition is entirely missing from the [Drasil version](https://jacquescarette.github.io/Drasil/examples/swhs/SRS/srs/SWHS_SRS.html#IM:heatEInPCM).  No wonder you were confused!  We calculate Q_p (the energy added) by knowing the rate at which energy is added, and the initial energy (0 in this case).

We shouldn't rush into doing so, but my guess is that we will be able to remove TM:latentHtE.  What we really need is the simple calculus that we can find the total of something by integrating the rate of change of that something.  We could introduce that in the exposition for IM4.  What really matters is the latent [heat of fusion](https://jacquescarette.github.io/Drasil/examples/swhs/SRS/srs/SWHS_SRS.html#DD:htFusion).  Thinking about it now, the definition of latent heat of fusion, which is currently a data definition, should probably be a theory.  (In the Wikipedia entry you pointed to, this is called `L` in our document it is `H_f`.)

Again, we shouldn't rush into it, but a separate chunk to define dQp/dt might make Drasil happier.  I think that will be revealed when we revise using theories consistently.

The other piece we need is the [melt fraction](https://jacquescarette.github.io/Drasil/examples/swhs/SRS/srs/SWHS_SRS.html#DD:meltFrac).  Once we have Q_p we can solve for phi.

I set up the problem to make it easy to solve with a generic ODE solver.  In hindsight, this might not be the most logical way to set up the problem, or maybe the generic ode form of the final theories should be made more explicit.  The ODE form can be seen in the [Matlab code](https://github.com/smiths/swhs/blob/master/src/Program/Matlab/temperature2.m). In this version T_1 it T_w, T_2 is T_p and T_3 is Q_p.  I'm getting outside of the scope of your original question though, so I'll postpone this aspect of the discussion for the future.  😃 

Yes, it is okay if you assign tickets related to the physics to me.  I'll hopefully be able to answer the questions.

**Comment by balacij** [comment]
Thank you for amazing explanation! I think I understand the majority of what's going on now.

>  With Q(0) = 0, the theoretical model says Q(t) = Q(t). This isn't wrong, but it probably could be said in a better way. The purpose of the theoretical model was to capture the idea that the latent heat isn't added all at once. When a material is melting the heat is continually added, without raising the temperature, until the material is all melted.

>  We shouldn't rush into doing so, but my guess is that we will be able to remove TM:latentHtE.

I like the idea of capturing how it's continually added.  Were you thinking of replacing it's definition with a Riemann sum then?

>  In the original manual version IM4 (on page 24) defines dQ_p/dt. This definition is entirely missing from the Drasil version. No wonder you were confused! We calculate Q_p (the energy added) by knowing the rate at which energy is added, and the initial energy (0 in this case).

>  Again, we shouldn't rush into it, but a separate chunk to define dQp/dt might make Drasil happier. I think that will be revealed when we revise using theories consistently.

It sounds like this might spawn a few tickets. @cd155 might also be interested in this discussion.

**Comment by smiths** [comment]
@balacij, interesting thought on Riemann sums, but I wasn't thinking of introducing that idea.  Integration captures the same idea.  I was just thinking that in the derivation of the equation for Q_p we introduce how we can calculated Q_p given the rate of change of Q_p.  We might not have to explicitly introduce integration.  We might just phrase it as solving the ODE.  (Solving the ODE involves integration, but the algorithms are different from algorithms for numerical integration.)  Solving the ODE approach is nice because that's how we actually find Q_p.

**Comment by balacij** [comment]
Ah, ok, that makes sense to me. Solving the ODE sounds good to me. Should we close this ticket in favour of creating a new one with the required changes, or do you want to leave this one open to track it?

Thank you again :smile:

**Comment by smiths** [comment]
Yes, we should close this issue, assuming I answered your question.  :-)

**Comment by balacij** [comment]
Yes, thank you very much @smiths! :smile:
