### ISSUE TITLE
Question about the scale of Connect NewDEModel to code generator

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2902]
I have some ideas about what should be changed, but I would like to double-check if I am on the right track.

### Current situation
In each example that solved an ODE, we create a `ODEInfo` datatype and send it to the ODE solver. Some information in the `ODEInfo` are duplicated with `NewDEModel`.

### Purposed change
remove duplicated information in ODEInfo, and use information from `NewDEModel` instead.

### Result
The `NewDEModel` connects to the code generator via `ODEInfo`.

### My thought and questions
I feel my purpose is a little naive. It didn't strategically change the way we connect the ODE solver. It's more like an optimization. Here are questions I have

1. Do I want to completely get rid of the `ODEInfo` class?
    - I feel it is unlikely we want completely get rid of the `ODEInfo` class, because some information on it does not belong to `NewDEModel`. For example, the start time, final time, and initial value. The ODE still holds without that information. They are be given to solve an ODE, and we can plot results on a chart. 

2. Besides removing the duplicated information in ODEInfo, I am not sure what else I can do. I think the ultimate goal is solving a second-order ODE, so I think I should also make the single pendulum and double pendulum to generate code to solve its ODEs. However, this plan seems not to fall the scale of connecting `NewDEModel` to code generator. They are belonging to the other two separate tickets.

**Comment by JacquesCarette** [comment]
The purpose of `NewDEModel` is to represent (the information contained in) a model that is expressed as a differential equation.

The purpose of `ODEInfo` is to represent (the information sufficient for) emitting code to solve a differential equation.

The overlap in purpose means that necessarily there will be overlap in information. However, because the purpose is different, it also means that the representation can be different, and the redundancy is not necessarily bad.

So there needs to be an analysis of what information is needed by the backend. Also, because the data-structures available to the front-end and to the back-end are *different*, we don't want to plainly re-use `NewDEModel` as is. At least, I don't think so.

Thus there does need to be some translation step.

Having said that, `ODEInfo` could indeed be redesigned to contain a lot more information, arranged differently. It probably should. But first we need to understand what information is actually needed, and in what form.

**Comment by cd155** [comment]
No problem, thanks for the clarification.
