### ISSUE TITLE
More Documentations: 

### ISSUE THREAD

**Issue by daijingz** [JacquesCarette/Drasil#2926]
Hi everyone, I am a new student for this project. While I was reading coding files and documents, I found understanding each part of the information is quite incomplete. To completely understand a coding file, I need to read many pages and sometimes there exist concepts that have never been mentioned. Can we have more developments on those files?

**Comment by JacquesCarette** [comment]
The documentation in Drasil is actually quite a bit better than your average open source project... but you're right that it could be quite a bit better still. Especially as it is conceptually complicated.

It's inevitable that to understand (some of) the code, you'll first need to read a number of the Wiki pages that try to explain things.

Note that this issue is too broad: there's nothing we can really do about it, because it's too big. If there are very specific pieces of code you want to understand, open a new issue that points to the specific one, and we might be able to do something about that.
