### ISSUE TITLE
Choices Legend for Input & Logging options are swapped on the website

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2941]
@smiths just caught this in the meeting

![image](https://user-images.githubusercontent.com/1627302/153654621-27a84279-2077-450d-a657-f75f4d130d01.png)

**Comment by smiths** [comment]
I noticed that too!  Thanks @balacij.

**Comment by cd155** [comment]
This is different than the code generator.

In code gerenrator: 
1. inputStructure: Structure - a decision on input variables structure
    - Unbundled: 
    - Bundled:
2.  logging: [Logging] - the kinds of log messages the generated program should print
    - LogFunc: log messages for function calls
    - LogVar: log messages for variable assignments

**Comment by smiths** [comment]
I looked at the code to see where the error is.

`loggingLegend` has the title for `inStructTitle`

https://github.com/JacquesCarette/Drasil/blob/54348791735033d5948b872b0339b901d3219d94/code/drasil-website/lib/Drasil/Website/CaseStudy.hs#L156-L161

and

`inputStrLegend` has the title for `loggingTitle`:

https://github.com/JacquesCarette/Drasil/blob/54348791735033d5948b872b0339b901d3219d94/code/drasil-website/lib/Drasil/Website/CaseStudy.hs#L163-L169

The funny thing is that if we manually wrote the webpage, instead of generating it, we probably wouldn't have made this mistake.  I still prefer the generative approach.  :smile:

I'll do a pull request.
