### ISSUE TITLE
What does software should consist of?

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2948]
When I was working on the code generation part, I was keeping think about how to categorize the existing attributes in `Choices`. However, I think it might be worthwhile to re-evaluate what attributes should include in the `Choices`. In other words, what does software consist of? This kind of puzzled me a while. From my intuition, the software is a very customized system. It has executable code and documentation. It is usually guided by an SRS, but will the SRS be so detailed on how to write the code. Here are a few examples.

1. Will an SRS specify to write the documentation?
2. Will an SRS specify we need a ReadME file?

One reason people want to write the documentation is that it benefits maintenance. I feel the norm is constantly evolving, maybe we will replace documentation with something else in future. (unlikely happen)

I think there is some common ground on this, so I just wonder to know what does software should consist of?

**Comment by JacquesCarette** [comment]
In another thread, we've taken to calling "softifacts" the total collection of all the things that make up "software", where 'code' is just one piece. Your title question can then be turned into "what are all the softifacts that we know of?".  I think there is a list on the wiki, done by @smiths .

The body of your comments leads somewhere else though: you have noticed that `Choices` is partly about a variety of softifacts, and so is a bit of a problem. It should be organized differently. Lastly, you've noticed something else that is true: our current process is much too driven by the SRS. But the SRS is just one softifact.

What we really need is a softifact description language. That should be what the generator is fed, and should be where we describe which artifacts to generate. Each artifact can then have a language of its own to describe what's in it, and how to generate it.

There's actually an open issue that's close to this. At the time it was first opened, I didn't have good ideas about how to move forward - but now I think things are finally getting clearer (see above).

**Comment by smiths** [comment]
@cd155 I did make a list of [some softifacts](https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/-/wikis/Advice-and-Checklists-for-Repos-(including-a-list-of-recommended-artifacts)).  The list isn't exhaustive.  It is the softifacts that are commonly recommended in research software development guidelines.  @oluowoj has a longer list of softifacts that she collected from existing repositories.

@cd155 @JacquesCarette implicitly answered your question, but to be explicit - the SRS does NOT specify how to write the code.  The SRS does not specify what documentation to write, or whether to do a README file.  As said by @JacquesCarette  the SRS is just one softifact.  A document that would cover what documentation to write would be a process document.  We do not currently capture any of this information explicitly in Drasil.  We do not generate a document describing the process.  This might be added in the future.  We certainly want to build Drasil so that we can add softifacts in the future.

**Comment by smiths** [comment]
I think this question is answered, so I will close this issue, but if there are parts of the question that were not answered, please feel free to reopen.
