### ISSUE TITLE
Friction missing from gamephys

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/Drasil#298]
friction is mentioned a single time in the SRS and MIS for gamephys but it is never defined anywhere and it is used in the example for the code. There is no definition equations or explanation for how it is used in gamephys.

It probably should be added? Should I pull an equation from how the code uses it? or is there a reference for it somewhere?

**Comment by smiths** [comment]
Hi Henry.  The documentation is not as explicit as it should be, but in the first version of our 2D physics engine we originally intended to assume there was no friction.  This was to keep things simple.  The friction in the Chipmunk code is because the developer of Chipmunk did not make the same assumption and Luthfi did not delete that part of the code.  We have been using the Chris Hecker papers as our guide, and he neglects friction at the point of collision.

We do not currently have a model for friction, although you are free to propose one and we can decide whether or not to incorporate it.

Something else that is missing that is related is solving for the motion constraints.  We actually have quite a bit of material worked out on this that you might not be aware of.  I just had a look at the Case Study folder in our repo and the SRS for Constraints is not included.  I'll add it shortly.  Please have a look at this document.  We can then discuss with @szymczdm whether or not to write this material in Drasil.  It is a longish document, so this would take some time.

**Comment by JacquesCarette** [comment]
@smiths could you review this? When something is a really long-term feature request, I've been closing the issue but putting a link to it on the wiki.

**Comment by smiths** [comment]
Good idea to close this issue for now.  I've added a link in the wiki (https://github.com/JacquesCarette/Drasil/wiki), as you suggested.
