### ISSUE TITLE
Allowing shared datafile across examples

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2980]
In the datafiles folder, there are data files for each example. Specifically, in nopcm, it has cpp, csharp and java folders containing external libraries. The problem comes when we have other examples that may want to use exactly the same libraries. 

Currently, the following makefile code check errors with generated artifacts.
https://github.com/JacquesCarette/Drasil/blob/adfc15f13c7cf81101c1dbab97a6aa61f10a4ec6/code/Makefile#L371-L376

It will check based on the example name, so sharing files across seems not possible for now.

The alternative way is copying exactly the same files into different examples, but this obviously makes duplication.

**Comment by smiths** [comment]
Good observation @cd155.  We definitely want to think of a way to share the common files without having to copy them multiple times in the repo.  Some hacks we could consider are symbolic links (but this isn't elegant, and often doesn't seem to work under version control), and changing the makefile instructions to point to the existing version of the library (in another projects datafile folder).  Maybe for resources that are potentially shared we should "elevate" them to their own folders in the datafiles folder, rather than have them buried inside projects?

**Comment by JacquesCarette** [comment]
The other issue is, we don't want to copy megabytes (like the boost library!).  Small data files is ok.

This is related to the 'deployment' issue we discussed 1 or 2 weeks ago.

**Comment by cd155** [comment]
@smiths I added a odelib folder in datafiles, and create a couple of symbolic links to point files to this shared folder. Although creating symbolic links is very elegant, it does share the files across the examples. Should I close this issue? @smiths
