### ISSUE TITLE
Dormand Prince method MinStep Error in the Java ODE Library

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2981]
In the Java ODE library, it will use Dormand Prince method to solve the ODE.

In the [DormandPrince54Integrator](https://commons.apache.org/proper/commons-math/javadocs/api-3.6.1/org/apache/commons/math3/ode/nonstiff/DormandPrince54Integrator.html) interface, it will require a min step and a max step. For other libraries, it asks the size of the step, but this asks for a range of a step size.

In our nopcm example, we set both min step and max step to one value (`time step` 10.0). However, in the PDController, we set the `time step` = 1.0e-2. This triggers a library error, 
```
org.apache.commons.math3.exception.NumberIsTooSmallException: 
minimal step size (1.00e-02) reached, integration needs 5.54e-03
```
I change the step size to 1.00e-03, and the library is happy with the new number.

I think there could be two ways to get around,
1. just change the step size to compromise the library, but this will need to change SRS in PDconroller.
2. we might need to know what the max step and mix step mean in this Dormand Prince method, then change accordingly. @smiths

**Comment by smiths** [comment]
@cd155, although we have the time step information in the SRS, in the future we will likely move this information to a design document at some point.  The SRS should identify the ODE, but how to solve it should really be a separate decision.  We will want to be able to change the ODE solver algorithm, not just the time step size.

**Comment by cd155** [comment]
Currently, we can define what algorithm to solve the ODE. 
https://github.com/JacquesCarette/Drasil/blob/adfc15f13c7cf81101c1dbab97a6aa61f10a4ec6/code/drasil-code/lib/Language/Drasil/Data/ODEInfo.hs#L37-L48
https://github.com/JacquesCarette/Drasil/blob/adfc15f13c7cf81101c1dbab97a6aa61f10a4ec6/code/drasil-code/lib/Language/Drasil/Data/ODEInfo.hs#L55

I think the bottleneck for selecting various algorithms is the C# olso ode library, it only supports two algorithms Runge-Kutta and Backwards Differentiation Formula.

We may also want to classify all available algorithms. Some algorithm has slightly different variability from their original one. For example, the Dormand Prince method we are using in Java is a member of a Runge-Kutta family of algorithms. Also, the step size is used differently in some algorithms.

Back to this specific problem, any suggestion on how to get around this library's error?

**Comment by smiths** [comment]
@cd155 as we discussed in today's meeting (#2977), let's just correct the step size for this specific example to get it working.  In the future (possibly outside the scope of your MEng), we will need to think more clearly where we should enter the design/implementation details, like solver name and solver parameters.  Those decisions do not really belong in the SRS because they are not abstract.  The SRS should be about "what" we want, not "how" to do it.

Based on what you said above the different step size should fix the problem, so I will close this issue.  If I missed something else that was asked, but not addressed, please feel free to reopen the issue.
