### ISSUE TITLE
Double Pendulum generated code did not show up on the website

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#3008]
After #3004, the double pendulum has generated code, but it didn't show up on the website.

**Comment by JacquesCarette** [comment]
Note that drasil-bot updated the web site **after** you posted this. I'm sure that not everything shows up, but I think it's worth checking again.

**Comment by cd155** [comment]
No problem. A few things I checked
1. code did show up on the website
![Screenshot from 2022-06-02 14-59-26](https://user-images.githubusercontent.com/16947266/171717097-cce8b406-e961-4f63-b262-52321d80306b.png)

2. it also shows up in the case study table
![Screenshot from 2022-06-02 14-59-39](https://user-images.githubusercontent.com/16947266/171717176-c4949ad3-100f-4a07-976d-7aaed50b3b87.png)

**Comment by cd155** [comment]
@JacquesCarette The weird thing is the documentation links for the double pendulum are broken.

**Comment by smiths** [comment]
@cd155 for clarification, it is the generated code documentation links that are broken.  The other documentation links (SRS) look fine.

I don't know the fix for the fix for the documentation links, but I suggest looking at the other examples with documented code to see where they differ.

Nice to see another example generated with code.  Feels like real progress.  :smile:

**Comment by balacij** [comment]
I _think_ that for the DblPendulum to have Doxygen generated, you will need to move it from the `EXAMPLES` list in the `Makefile` to the `SRC_EXAMPLES` list:
https://github.com/JacquesCarette/Drasil/blob/5ea03dd072b372fe2f09b14e0291d966d2b238a2/code/Makefile#L29-L31

Is this a problem that there's metadata in the Makefile?
