### ISSUE TITLE
Chapter 2 ODE Data Represent - MEng Report

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#3028]
Chapter 2 ODE Data Represent is ready for review.

pdf file: https://github.com/JacquesCarette/Drasil/blob/dongFixWhenWritting/People/Dong/report/templates/Thesis_Main.pdf

tex file: https://github.com/JacquesCarette/Drasil/blob/dongFixWhenWritting/People/Dong/report/templates/chapter1.tex

last commit 7d837c8c406bfe293b2ae418a4e441ad0b432caf

**Comment by JacquesCarette** [comment]
Comments:
- Data Represent -> Data Representation
- introduction paragraph: what you're missing is something stronger on the motivation. You do mention "it restricts any transformation of ODEs", but that's easy to miss.
- before you present DifferentialModel, you should do a bit more of an analysis of what is in a "System of Linear ODEs". Basically the reader should not be surprised, after your analysis/explanation regarding any of the fields of that data-structure.
- there is a gap in between your example in (2.2.1) and the data-structure explanation. I think it would be easier if you show a simpler (concrete) example of low-order, maybe translate that to a 'direct' version of the (internal) Drasil structure to show how UGLY that would be, thus motivating the need for some helpers to make it nicer.
- similarly, in 2.3, I would first motivate the reason for the 2 constructors before explaining them
- in 2.4, I would show examples.

Overall:
- the content is excellent
- the English needs quite a lot of work in places (such as the introductory part). Maybe work with a fellow student on that?

**Comment by smiths** [comment]
@cd155, I agree with the comments from @JacquesCarette.  I'll also add a few of my own:

- I think you should use your short title as the long title.  That is, "SOLVING HIGH-ORDER LINEAR ORDINARY DIFFERENTIAL EQUATIONS FOR SCS IN DRASIL" can be shortened to "SOLVING HIGH-ORDER LINEAR ODES IN DRASIL"
- The last sentence of the first paragraph should say that you are describing the new way of storing ODEs in Drasil.  As written it isn't clear if you are describing how it used to be done, or how you are going to do it.  Actually, you should also say that you are contrasting the new approach to the old approach.  You really want to emphasize the advantages of the new way of capturing this information.
- Although you are focusing on linear ODEs, you should make it clear when you present the scope (likely in Chapter 1) that Drasil can solve nonlinear ODEs (like the double pendulum nonlinear ode).  You can explain in your future work what steps might be taken to support nonlinear ODEs with data structures in Drasil.
- The bold face notation in Equation 2.1.1 should be maintained when the associated symbols come up in your text
- Since hyperlinks are so easy now, I suggest you include a hyperlink to the [PDController case study](https://jacquescarette.github.io/Drasil/examples/pdcontroller/SRS/srs/PDController_SRS.html) when you mention it
- You can also use hyperlinks when referencing other sections in your document.  The `hyperref` packages does that pretty much automatically
- After Equation 2.1.2 you should say the variables and constants y_t etc represent.  
- Rather than * to show "by" (as in an m*n matrix) use [$\times$](http://www.malinc.se/math/latex/basiccodeen.php#:~:text=In%20LaTeX%20you%20use%20the,to%20make%20the%20symbol%20%C3%97.) in LaTeX ($m \times n$)
- I'm not sure the information in Appendix A.1 should be in the Appendix.  It seems like it wouldn't hurt the flow of Chapter 2 to include it in your chapter
- Rather than say the independent variable is usually time (on page 8), you can say it is often time. I don't think you have written about boundary conditions and initial conditions yet, but I believe you cover both initial value problems and boundary value problems.  For boundary value problems, space is often the independent variable.  (You don't need to say that, I'm just explaining why "often" is better in your text than "usually.")
- Is there any constraint enforced that the entries in `_coefficients` can only be functions of the independent variable (often t)?  This is required for [linear ODEs](https://en.wikipedia.org/wiki/Linear_differential_equation).  What would happen if the expression in `_coefficients` depended on `_depVar`?  I think the answer depends on how you eventually link to the external library for solving the ODE.  I'm thinking about the double pendulum example.  I believe you solve that ODE, even though it is nonlinear.  Do you represent it in matrix form?  I tried to find your double pendulum example.  Where is it?
- Why is the type of `_unknowns` an `Integer`?  The unknowns are actually functions that take arguments and generate a real number.  Is it the case that you never actually use the type information?  Maybe you mean the order of the derivative?  That is what the sample code on page 12 suggests.
- You say that `unknowns` needs to be descending.  Would `unknowns = [3]` be valid?  (I don't see why not, I just want to verify.)
- Are the new data structures used in the current Drasil examples?
-

**Comment by cd155** [comment]
@JacquesCarette 
1. > introduction paragraph: what you're missing is something stronger on the motivation. You do mention "it restricts any transformation of ODEs", but that's easy to miss.

Can I use polymorphic to describe the ODE? There is the new edit for the motivation.

"_Although writing ODEs in text maintains the relationship of ODEs, it restricts any transformation of ODEs. For example, if the text-based ODE is a high-order linear ODE, we can not transform it into its equivalent system of first-order ODE. Therefore, the Drasil team is exploring a new approach to store ODEs in a new data structure, and the new structure would allow ODEs to be **polymorphic**. Once we capture ODEs information in this data structure, we can generate its equivalent forms._"

2. > before you present DifferentialModel, you should do a bit more of an analysis of what is in a "System of Linear ODEs". Basically the reader should not be surprised, after your analysis/explanation regarding any of the fields of that data-structure.

Adding analysis of "System of Linear ODEs" remind me that the DifferentialModel didn't fully support a system of linear ODE. We can input a system of ODE in DifferentialModel, but unfortunately there is no study case able to test or show it. All eligible case studies have a single ODE. Also, the later transformation that changes a single ODE to an ODE solver format doesn't support a system ODE. The transformation only works for a single ODE for now, but some helper functions could be reused if we want to expand it.

3. 
> - there is a gap in between your example in (2.2.1) ...
> - similarly, in 2.3, I would first motivate the reason for the 2 constructors before explaining them
> - in 2.4, I would show examples

I also made edits based on the feedback above. What is a good way to get those edits to be reviewed? I think I should better highlight those changes in a PDF. Is that be Ok post an edited pdf in the issue tracker? [edit_c_ch1.pdf](https://github.com/JacquesCarette/Drasil/files/9135269/edit_c_ch1.pdf) (see highlighted)

**Comment by cd155** [comment]
@smiths 
1. > I think you should use your short title as the long title. That is, "SOLVING HIGH-ORDER LINEAR ORDINARY DIFFERENTIAL EQUATIONS FOR SCS IN DRASIL" can be shortened to "SOLVING HIGH-ORDER LINEAR ODES IN DRASIL"

If the long title is "SOLVING HIGH-ORDER LINEAR ODES IN DRASIL", will the short title be the same as the long title?

2. > Although you are focusing on linear ODEs, you should make it clear when you present the scope (likely in Chapter 1) that Drasil can solve nonlinear ODEs (like the double pendulum nonlinear ode). You can explain in your future work what steps might be taken to support nonlinear ODEs with data structures in Drasil.

When it comes to nonlinear ODEs, we didn't use this new data structure at all. For example, we write an explicit ODE equation in the double pendulum. What I did is expanding Drasil capability to generate the right interface when we write an explicit equation for high-order ODE. I am not sure whether I should add the nonlinear ODE part in this chapter because the nonlinear ODE doesn't use this data structure. I plan to put the double pendulum example in the chapter after ODE data representation and External libraries analysis. In the Connecting ODE data representation with External Libraries chapter, I want to describe that the high-order linear ODE can be solved with the transformation, but other ODE, like non-linear ODE need to use our old technique, manually write the equations twice to get the numerical solution. Is that the right flow?

3. > Is there any constraint enforced that the entries in _coefficients can only be functions of the independent variable (often t)? This is required for linear ODEs. What would happen if the expression in _coefficients depended on _depVar? I think the answer depends on how you eventually link to the external library for solving the ODE. I'm thinking about the double pendulum example. I believe you solve that ODE, even though it is nonlinear. Do you represent it in matrix form? I tried to find your double pendulum example. Where is it?
4. > Why is the type of _unknowns an Integer? The unknowns are actually functions that take arguments and generate a real number. Is it the case that you never actually use the type information? Maybe you mean the order of the derivative? That is what the sample code on page 12 suggests.

I think I didn't explain well what is the _unknowns. The _unknowns is not a [y_t'', y_t', y_t], the _unknowns is orders of y_t, so it is ['', ',  ]. I use [2, 1, 0] to represent the order of derivatives. The y_t will be stored in _depVar, and its order of derivative will be stored in _unknowns. That's why _unknowns is a list of integers.  Technically, the combination of _depVar and _unknowns is the unknown vector [y_t'', y_t', y_t]. 
Currently, there are a few constraints to input _coefficients, the dimension of _coefficients (m * n) needs to match with _unknowns (n * 1). Other than that, there are no other constraints. We will assume users did the job to make the ODE in the shape of Ax = b. Anything in A does not depend on x. We also assume the entries in _coefficientscan only be functions of the independent variable.

5. > You say that unknowns needs to be descending. Would unknowns = [3] be valid? (I don't see why not, I just want to verify.)

[3] would be valid, as long as the order is descending. [1, 3] would be invalid, and there is a guard to check it. If someone put [2, 2, 1] in there, it will also complain, because the vector can be simplified to [2, 1] 

6. > Are the new data structures used in the current Drasil examples?

PD_Controller and No_PCM currently using the new data structure. The double pendulum doesn't use the new data structure, we explicitly write the ODE twice in the double pendulum

**Comment by smiths** [comment]
> @smiths
> 
> 1. > I think you should use your short title as the long title. That is, "SOLVING HIGH-ORDER LINEAR ORDINARY DIFFERENTIAL EQUATIONS FOR SCS IN DRASIL" can be shortened to "SOLVING HIGH-ORDER LINEAR ODES IN DRASIL"
> 
> If the long title is "SOLVING HIGH-ORDER LINEAR ODES IN DRASIL", will the short title be the same as the long title?
> 
Yes, the short and the long title can be the same.
> 2. > Although you are focusing on linear ODEs, you should make it clear when you present the scope (likely in Chapter 1) that Drasil can solve nonlinear ODEs (like the double pendulum nonlinear ode). You can explain in your future work what steps might be taken to support nonlinear ODEs with data structures in Drasil.
> 
> When it comes to nonlinear ODEs, we didn't use this new data structure at all. For example, we write an explicit ODE equation in the double pendulum. What I did is expanding Drasil capability to generate the right interface when we write an explicit equation for high-order ODE. I am not sure whether I should add the nonlinear ODE part in this chapter because the nonlinear ODE doesn't use this data structure. I plan to put the double pendulum example in the chapter after ODE data representation and External libraries analysis. In the Connecting ODE data representation with External Libraries chapter, I want to describe that the high-order linear ODE can be solved with the transformation, but other ODE, like non-linear ODE need to use our old technique, manually write the equations twice to get the numerical solution. Is that the right flow?
> 
Yes, what you describe is fine.  What I'm saying is that you want to be clear on the scope.  You have developed an approach for higher order linear ODEs.  You leave it as future work how to handle nonlinear ODEs.  In your writing you should make it clear how nonlinear ODEs are currently handled.  This will help future students.  From what you said, you are already planning on including this information.
> 3. > Is there any constraint enforced that the entries in _coefficients can only be functions of the independent variable (often t)? This is required for linear ODEs. What would happen if the expression in _coefficients depended on _depVar? I think the answer depends on how you eventually link to the external library for solving the ODE. I'm thinking about the double pendulum example. I believe you solve that ODE, even though it is nonlinear. Do you represent it in matrix form? I tried to find your double pendulum example. Where is it?
> 4. > Why is the type of _unknowns an Integer? The unknowns are actually functions that take arguments and generate a real number. Is it the case that you never actually use the type information? Maybe you mean the order of the derivative? That is what the sample code on page 12 suggests.
> 
> I think I didn't explain well what is the _unknowns. The _unknowns is not a [y_t'', y_t', y_t], the _unknowns is orders of y_t, so it is ['', ', ]. I use [2, 1, 0] to represent the order of derivatives. The y_t will be stored in _depVar, and its order of derivative will be stored in _unknowns. That's why _unknowns is a list of integers. Technically, the combination of _depVar and _unknowns is the unknown vector [y_t'', y_t', y_t]. Currently, there are a few constraints to input _coefficients, the dimension of _coefficients (m * n) needs to match with _unknowns (n * 1). Other than that, there are no other constraints. We will assume users did the job to make the ODE in the shape of Ax = b. Anything in A does not depend on x. We also assume the entries in _coefficientscan only be functions of the independent variable.
> 
Yes, your use of the `_unknowns` list became more clear later in the chapter.  You'll want to add some additional wording on the first occurrence to clarify to the user what it means.  Please make all of the constraints and assumptions you mentioned very clear in your writing.  It is fine to make assumptions, but we want to make sure that the person programming Drasil knowns their responsibilities.
> 5. > You say that unknowns needs to be descending. Would unknowns = [3] be valid? (I don't see why not, I just want to verify.)
> 
> [3] would be valid, as long as the order is descending. [1, 3] would be invalid, and there is a guard to check it. If someone put [2, 2, 1] in there, it will also complain, because the vector can be simplified to [2, 1]
> 
Sounds good.
> 6. > Are the new data structures used in the current Drasil examples?
> 
> PD_Controller and No_PCM currently using the new data structure. The double pendulum doesn't use the new data structure, we explicitly write the ODE twice in the double pendulum

Good.

I believe everything has been addressed, so we can close this issue.  If there is something still pending that I missed, please create a new issue for it.
