### ISSUE TITLE
Generate Table in Drasil

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#3043]
In today's discussion #3040, we mentioned about it would be nice to have Drasil generate tables. It requires new knowledge, including what a table is, and what a table looks like.

Currently, we take raw table data and lays out on Latex and HTML. If Drasil captures the knowledge of what a table is, then we can generate them.

**Comment by smiths** [comment]
Thank you @cd155 for creating this issue.  It is a good reminder about our conversation.

Since we wouldn't be closing this issue any time soon, I'm going to close it, but create a [potential project](https://github.com/JacquesCarette/Drasil/wiki/Potential-Projects) in its place.  Instead of emphasizing tables, which we do currently generate in Drasil, I'll emphasize graphs.
