### ISSUE TITLE
Should we be passing pieces of a `ConceptChunk` to be rebuilt as a `UnitalChunk` with `dqd'`?

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3074]
As part of #2677 and #2704, using `ucStaged` instead of `dqd'` (currently only done with `launAngle :: ConstrConcept` in `Projectile.Unitals` shown below) would require passing in pieces of a prexisting `ConceptChunk` to be reconstructed behind the scenes.

https://github.com/JacquesCarette/Drasil/blob/1ab7a8c2b875e8a7e6ff6bcc45e74c4e4bc38b32/code/drasil-example/projectile/lib/Drasil/Projectile/Unitals.hs#L30

Some further questions:
- Is there a way in Drasil to map from a `Sentence` to a `String`? `ucStaged` takes a `String` for its definition, but the definition of a `ConceptChunk` is stored as a `Sentence`.
- Should another helper be defined similarly to `ucStaged` that takes a `Concept`?

**Comment by smiths** [comment]
@samm82, if it makes sense to discuss these issues during tomorrow's meeting (which I think it does), you can edit the meeting agenda (#3069) to include links to these issues.  @JacquesCarette and I were talking earlier today about finding good examples of QuantityDict etc so that could use them to describe our "ontology" of chunk types.  We can talk about this during our meeting tomorrow too.  :smile:

**Comment by JacquesCarette** [comment]
Again: we never want to map from a `Sentence` to a `String`. So we need to dig deeper as to why `Sentence` and why `String`. Often there are reasons for both - but sometimes not.  The usual reason for `Sentence` is because the thing we want to say will have symbols in it; the usual reason from `String` (outside laziness) is that it's going to be used as a "root" for constructing something else later.

As to the last question, I think I need to see a bunch of examples to see what's really going on.

**Comment by samm82** [comment]
Since this specific use case has been implicitly answered in #3199, I will close this and make a more refined issue for the more general question of "should we be passing `Concept` pieces to higher-level constructors" before (or immediately after!) #3199 is closed.
