### ISSUE TITLE
Should `t_flight` (of Projectile) be used "in code"? 

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3088]
Taking Java as an example, here is how the Projectile example uses `t_flight` (the theory):
https://github.com/JacquesCarette/Drasil/blob/b555167ce688040b766742b03442fbf7af750087/code/stable/projectile/projectile_u_p_nol_u_wi_v_d/src/java/Projectile/Projectile.java#L31-L56

`t_flight` is used as justification in the [derivation of `p_land`](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/srs/Projectile_SRS.html#IM:calOfLandingDist), but it just ends up being inlined rather than "used" in the code.

Is this the expected behaviour? If so, should `t_flight` still appear and be calculated in the code? As of right now, it seems to be calculated but the value is unused.

Of course, there is a greater discussion: we inlined it manually (I believe, and I think there is an open issue about this), but we also have created unused variables. Should we have not generated the code, but left it as an instance model that was just "inlined"?

**Comment by smiths** [comment]
Technically we should calculate t_flight because there is a requirement (specifically requirement Calculate-Values) that says we are supposed to.  Unfortunately there is no requirement to output this value, so it isn't even used for output.  The unused variable is caused by the requirements, so the problem originates there.

It doesn't really make sense to calculate a value that we never use.  We should fix this somewhere.  We can either remove the requirement to calculate t_flight, or add a requirement to output the value.  There isn't really a right answer between these two alternatives.  It depends on how the program will be used, and since we made up this program, without a specific context, we have an arbitrary decision to make.  This is an example of how Drasil supports a program family.  We have a variability on whether to output intermediate values.

I like the idea of adding a requirement (actually modifying Output-Values) to output t_flight.  The usual approach in scientific computing is to output meaningful intermediate values, since this information can be useful in another context and because it helps with debugging.

**Comment by balacij** [comment]
>  We have a variability on whether to output intermediate values.

I did not think about this at all. Is this option something we could/should make explicit? How should we be grouping intermediate values together? It sounds like this would also be related to #1154.

> I like the idea of adding a requirement (actually modifying Output-Values) to output t_flight. The usual approach in scientific computing is to output meaningful intermediate values, since this information can be useful in another context and because it helps with debugging.

Would we also want to modify `p_land` to directly use `t_flight` in it's equation too?

**Comment by smiths** [comment]
Great comments @balacij.  The intermediate symbols in #1154 and the intermediate values in this discussion aren't the same things.  This issue would be like #1154 if Drasil was displaying `p_land = v_x^i * t_flight`, but wanted it to expand t_flight into its definition.  The intermediate symbols in that case are just used for the purpose of display.  The intermediate values in the current case are values that we might want to display.  I don't think what I'm saying here is rigorous enough for us to codify any rules around it.  In issue #1154 the intermediate symbols could have their values calculated and we could ask the Drasil-generated program to output those values.  Those values are so trivial though that this isn't something that someone would typically want.  The value for t_flight could potentially be of interest, even though it is intermediate.

I don't think we (at least not now) can automate what values are output by the Drasil-generated program.  The values that are output should be those that the user specifies in the SRS.  I don't think the requirements in the SRS are particularly strongly connected to the generated code, but to avoid duplication of information, that is something we should strive to do.  In the current case, it is a user's decision whether to output t_flight.  If I was the user, I would elect to output that value.  Some other users might not.

No, I don't think we should modify `p_land` to use `t_flight`.  The SRS already did the substitution symbolically and simplified the resulting expression.  (The simplification, in this case, isn't very dramatic, but in other cases, the simplification can result in simpler (and potentially faster) calculations.) An argument could be made that defining `p_land = v_launch*cos(theta)*t_final` is better for the readability of the code, but my preference is to send the code reader back to the SRS to see the formula's derivation if they require additional information.

**Comment by balacij** [comment]
I see, that makes a lot more sense to me now. Thank you @smiths !

**Comment by balacij** [comment]
I'm not quite sure why I didn't just close this ticket. But now that I re-read what you wrote (@smiths), should we add the flight duration (`t_flight`) to the outputted values? It's as simple as adding `qw flightDur` to the outputs list in Projectile's `Body.hs`.

**Comment by JacquesCarette** [comment]
The requirements should probably be adapted too, to say that both those values are wanted. (More comments on the PR itself)
