### ISSUE TITLE
Chapter 4: ModelKinds Ready for Review

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3097]
Please let me know what you think about about chapter 4. I've posted it to `jasonRewritingCh4`. It involved me splitting up the chapter into 3 to address your feedback.

**Comment by JacquesCarette** [comment]
(I made sure to switch to that branch and recompile first - but apparently it's not plugged in? I don't see a split)

I find the text of the first 2 pages of this chapter to be quite disjointed and insufficiently precise. I don't understand what most of it is trying to convey - nor necessarily why that information is important.

Personally, I'd write something like
> In scientific theories, a lot of the information is encoded in equations, such as `F = m a`. Often the quantity of interest is `a`, which makes the preceding equation a *relation* involving `a`. However the type of relations has quite a broad language (e.g. `x<1 and y>3` also expresses a relation), which makes it difficult to analyse the content of the encoding.

and that would basically be it. 

But as I'm really not sure if I'm even reviewing the right thing, I'll stop here. Please send me a PDF **asap**, we can worry about me being able to build things myself later.

**Comment by balacij** [comment]
Hmm, I'll send you a copy over email right now to make sure it's the same copy.

**Comment by JacquesCarette** [comment]
The Writing Directives on this chapter are exactly right.

In order to better understand Source Code 4.2, I think the easiest way is to write it out in formatted English, i.e. what ends up being shown for this IM in the SRS. Source 4.2 is really an 'encoding' of the contents of that IM. You might even want to show the IM (qua SRS piece) first. Then proceed as you currently do.

Minor: "Drasils" is usually wrong (there is only 1 Drasil) and you mean "Drasil's".

4.1 is now way better. It really captures the problem you faced really well. I like P1, P2, P3.

I find 4.2 quite verbose, i.e. it has a lot of words to convey what is essentially not that much total information. However, it's good enough, it's not worth changing. So the only thing to do is to insert the English version of the IM.

**Comment by balacij** [comment]
>  The Writing Directives on this chapter are exactly right.

Nice! I think I'll continue using them in this way in the future.

>  In order to better understand Source Code 4.2, I think the easiest way is to
>  write it out in formatted English, i.e. what ends up being shown for this IM in
>  the SRS. Source 4.2 is really an 'encoding' of the contents of that IM. You
>  might even want to show the IM (qua SRS piece) first. Then proceed as you
>  currently do.

For some reason, I put the explanation of it at the end of Chapter 3, but I
moved it back now to Chapter 4.

>  Minor: "Drasils" is usually wrong (there is only 1 Drasil) and you mean
>  "Drasil's".

I started writing these correctly, then got confused, changed them all to the
wrong way, and now I realize the change was wrong. I think I also use too many
commas. I will need to make a pass on everything grammar-related in my thesis
this weekend, after writing the Chapter on Typing and the Conclusion fully.

>  4.1 is now way better. It really captures the problem you faced really well. I
>  like P1, P2, P3.

Perfect! Thank you.

>  I find 4.2 quite verbose, i.e. it has a lot of words to convey what is
>  essentially not that much total information. However, it's good enough, it's not
>  worth changing. So the only thing to do is to insert the English version of the
>  IM.

Sounds good! It's now in there, at the top of Chapter 4.


Related commit: https://github.com/JacquesCarette/Drasil/commit/6f6e9e91eee39753227105533337c77896d2a5a4

**Comment by JacquesCarette** [comment]
Don't worry too much about the too many commas - that can be fixed after the committee gets the first draft in their hands.
