### ISSUE TITLE
Type checking error in projectile DataDefn: ``speed (vecMag)

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3113]
Related to #3093 

```
`speed` exposes ill-typed expressions!
  - ERROR: Vector norm only applies to vectors of real numbers. Received `Real`.
```

https://github.com/JacquesCarette/Drasil/blob/0a240c0231b6f737011bc090962ae1925fbc83e2/code/drasil-data/lib/Data/Drasil/Theories/Physics.hs#L110-L121

**Comment by JacquesCarette** [comment]
So the "real" problem is quite a bit deeper: if we track down `speedEqn`, we see
https://github.com/JacquesCarette/Drasil/blob/e595893f1084cb9a7c4be561d20ab6b9de8749ac/code/drasil-data/lib/Data/Drasil/Equations/Defining/Physics.hs#L15-L19

`speedEqn` on its own seems fine, but the lines above give us a clue that something is weird - `newtonSLEqn` is defined using **real** multiplication between mass and acceleration. Which causes us to look up acceleration
https://github.com/JacquesCarette/Drasil/blob/e595893f1084cb9a7c4be561d20ab6b9de8749ac/code/drasil-data/lib/Data/Drasil/Quantities/Physics.hs#L47

Looks innocuous enough, right? Except that `uc` defaults things to being `Real`. So that `acceleration` is not a `Vector` at all.

There is a hack-fix for this: use `abs_` instead of `norm`. This makes things type-correct (though it does change the output, as it should.) But of course, the right fix is to change `acceleration` to be a `Vector`. I suspect that will have much larger ripples!

**Comment by smiths** [comment]
I haven't looked at the example, but maybe for the equation in question acceleration is a scalar?  Some of the equations are 1D, so we can treat acceleration as a scalar.  There are definitely other cases where acceleration should be treated as a vector, but I don't know if we ever generate code based on those equations. 

Also, we should be able to define multiplication for a scalar times a vector.  It wouldn't be `mulRe` though.

**Comment by balacij** [comment]
As @smiths mentioned, we don't have vector (nor matrix) scaling in Drasil (yet). I have an old ticket about this too (#2497). I'm not quite sure how much work will be needed to fully implement it yet, but we can likely get something working if we're okay with it not yet generating code.

**Comment by JacquesCarette** [comment]
Aha, that actually went through, and now it seems that `Projectile` fully type-checks.
