### ISSUE TITLE
Should `Space` contain `Radians`?

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3132]
Related to #3093 

We're using `Space` to capture the universe of types that `Expr`s can take on. One constructor of `Space` is `Radians`. All of the other constructors are similar to types, but `Radians` is a unit. Is it safe to remove it in favour of flushing out the unit system again later?

https://github.com/JacquesCarette/Drasil/blob/c47b16ab53a52686fe40283ec8daa7902a1c5b44/code/drasil-lang/lib/Language/Drasil/Space.hs#L31-L48

**Comment by JacquesCarette** [comment]
Adding @smiths on this. I thin you're right though, `Radians` is a unit, not a space.

**Comment by JacquesCarette** [comment]
Wikipedia says "The radian, denoted by the symbol rad, is the unit of [angle](https://en.wikipedia.org/wiki/Angle) in the [International System of Units](https://en.wikipedia.org/wiki/International_System_of_Units) (SI) and is the standard unit of angular measure used in many areas of [mathematics](https://en.wikipedia.org/wiki/Mathematics)."

**Comment by smiths** [comment]
Yes, I agree that radian is a unit.  I was actually looking at the symbol rad the other day to make sure that it is an SI symbol.  Our table of units says that rad is SI, but I wasn't actually sure, since rad is a derived unit.  It is really m/m (arc length/radius).  I seemed to remember that SI didn't use any symbol for rad, since one isn't technically necessary.  The table "SI derived units with special names and symbols" on the Wikipedia page for [International System of Units](https://en.wikipedia.org/wiki/International_System_of_Units) confirmed for me that rad is a symbol used in SI.  

We would not consider metres to be a space, so radians should definitely be out of Space.  :-)

I could see us having an angle space or a length space (etc), if we wanted to attach extra meaning to a specific Real.  We wouldn't name this space after the units though.

**Comment by balacij** [comment]
Thank you both very much!
