### ISSUE TITLE
Numerics should have dimensions and units

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3137]
We would not consider metres to be a space, so radians should definitely be out of Space.  :-)

I could see us having an angle space or a length space (etc), if we wanted to attach extra meaning to a specific Real.  We wouldn't name this space after the units though.

_Originally posted by @smiths in https://github.com/JacquesCarette/Drasil/issues/3132#issuecomment-1327684757_

We've discussed this many times in the past, but I didn't find a ticket to track discussion, so this can be a start. I'm not quite sure what the current state of things is, so if anyone can fill us in (here on the ticket), I'm sure all of us would appreciate it.

**Comment by smiths** [comment]
@balacij it is a good idea to have a placeholder issue, but I'm not sure exactly what the issue is.  :smile: That is, what would have to happen for us to close this issue.

I'm not exactly sure what is meant by numerics having dimension.  However, I think we are thinking at least mostly along the same lines.  I just don't know the proper terminology.

What I'm thinking is that we have extra information about some variables.  We eventually want a means to capture that other information.  For instance, if we have a variable for an angle, say named theta, we can assign the type of that variable to Real.  However, we can say more than that because we know theta isn't a Real it is a Real representing an angle.  That comes with at least a little extra information, like sin(theta + n*2pi) = sin(theta) for any n \in Z.  (Maybe this kind of information is better captured through the functions on theta?)

For a length, we know that it isn't just a Real, it is a positive Real, or zero.

We might also want to know not just the constraints on length, but that the variable's type is length.  I'm thinking about the example the @JacquesCarette mentioned of Work and Torque having the same units (N*m).  They are the same units, but the concepts of Work and Torque are very different.

I might be associated the idea of the meaning of a variable with type when the meaning should actually be kept somewhere else.  @balacij and @JacquesCarette are better judges than me of where this information should go.  At some point though it would be nice to capture this richer information. 

We've talked before about the idea of capturing information that would let us talk about the mass of something, but the something would have to be something that has mass.  We could talk about the mass of a volume of water, or a beam, but not the mass of temperature or the mass of Section 7.2.  Maybe this is information that would come through the type of a variable, or maybe I'm inadequately conflating different ideas.  :smile:

**Comment by balacij** [comment]
Thank you @smiths. I definitely didn't write enough in the original ticket. I think my understanding aligns with yours.

When I mention "numerics having dimension", I'm referring to the 7 or so (I vaguely remember you mentioning that there might be more) types of physical quantities. With #3093, we can "type" mathematical expressions (amongst other languages) with respect to any universe of types, so it wouldn't be too far-fetched to also similarly add a type-checking system for the dimension of expressions. I _believe_ each dimension has a standard unit (e.g., length has meters, mass has kilograms, time has seconds, etc), for which the other units are a scaled version of the corresponding standard units.

I'm not quite fully sure what the needs are for this. My physics knowledge is very limited, so I'm glad you already provided examples :smile:

To be honest, if you don't think there's anything that really needs to be done in this general area, we can probably close this ticket immediately. Otherwise, I'm not quite sure what the criteria would be to close this ticket, it would really depend on what we want of Drasil and the Drasil-checked SRS abstraction in particular.

**Comment by smiths** [comment]
The seven SI base units are listed on the [NIST page](https://www.nist.gov/pml/owm/metric-si/si-units).  I'm sure it would be possible to build the foundation on a different 7 units (using force instead of mass for instance), but there very well could be something fundamental about the number 7 here.  I'm not an expert, and I don't think we have to be experts.  We can follow what the SI experts have built.

There are 22 derived units in SI.  I'm sure that this number involves some arbitrary decisions.  We should just follow SI though.

Yes, I think we can close this ticket for now.  I think we are still at the discussion stage.  I don't know if we are ready to express these ideas as an issue or issues just yet.

**Comment by balacij** [comment]
Sounds good then, let's open one whenever we're read :smile:
