### ISSUE TITLE
Abstract + Lay Abstract Ready for Review (Again)

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3168]
(I will send a copy of my thesis over Discord)

**Comment by JacquesCarette** [comment]
The Lay Abstract is good, but by trying to be easy-to-understand, perhaps claims do to more than it really does (especially points 2 and 4).

Abstract:
- remove "usable" from "usable software" -- you don't want to have to justify that
- the abstract also oversells your accomplishments:
  - the theory kind system is great, but it is a start, not a finished thing
  - catch "all existing typing issues" is also an over-claim. It only catches those encoded in the type system.
- no point talking about "case studies generating code and those not", that is just confusing. Just talk about the 10 case studies.

Otherwise, this is ready.

**Comment by JacquesCarette** [comment]
That'll work.
