### ISSUE TITLE
Continue Refactoring of solChSpecF

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/Drasil#321]
The following has changed:
```
solChSpecF :: (NamedIdea a) => a -> (Section, Section) -> Sentence -> 
  (Sentence, **Sentence**, Sentence) -> 
  ([Contents], [Contents], [Contents], [Contents], [Contents], [Contents]) -> 
  [Section] -> Section
```

Bool has been changed to sentence, if your example has uncertainty replace the True with dataConstraintUncertainty, otherwise replace with EmptyS.

A new data type has been made to refactor solChSpecF, the new function is:

`solutionCharactersticCon :: (NamedIdea a) => a -> SOLsec -> [Section] -> Section`

a is the name of the program, [Section] is any additional subsection that we are not generating right now with this function.

it is a nested structure representing the solution characteristic subsection

SOLsec has 6 fields of type SOLsub (1 per subsection) 

to make both data types you call these functions:

```
mkSOLsec :: SOLsub -> SOLsub -> SOLsub -> SOLsub -> SOLsub -> SOLsub -> SOLsec
mkSOLsec as tm gd dd im dc = Sect as tm gd dd im dc

mkSOLsub :: Sentence -> Sentence -> Sentence -> Section -> [Contents] -> SOLsub
mkSOLsub start middle end refSection ys = Subs start middle end refSection ys
```

SOLsub are the subsections of the solution characteristic specification, each SOLsub takes a 3 sentence a Section and a list of contents. Please look at gamephys commit 9d5da47a  for more details on how to implement.

I am also looking for feedback or critique on the design and better names for the types.

**Comment by hmadej** [comment]
this is related to issue #244

**Comment by JacquesCarette** [comment]
6-tuples are usually not a good idea -- too easy to swap them by accident.

Better would be some kind of data-structure that contains the 'knowledge', and another which describes how to 'render' that knowledge into English (`Sentence`, `Contents`, `Section`, etc), and lastly an "assembler" which puts them together.  `solChSpecF` is kind of that assembler.

**Comment by njericha** [comment]
Our current plan is to pass `[SecItem]` as the input to each section, and pass each section as the input to SolSub with "tags" shown below. SolSub would replace solCharSpecF and take care of how to display it as `Sentence`, `Contents`, and `Tables`.
```
solutionChar = SolSub (Assump [ProgName ssp, Ref imods, Cont sspAssump])
                                     (TMods [Cont sspTmods]) 
                                      ...
```
Where
```
Data SecItem = ProgName NamedIdea
                       |  Cont           [Contents]
                       |  Ref             Section
                       ...

SolSub :: Assump -> TMod -> GenDef -> ... -> Section
```
This way, we can just read what the input is and render accordingly without worrying what order the list is in. The section needs to take 6 inputs because there are six subsections but tagging them will ensure they are in the right order, and if you don't have any `GenDefs`, you would put `(GenDefs [])`.

**Comment by JacquesCarette** [comment]
Good.

**Comment by hmadej** [comment]
need a simple way of passing references to sections, also can potentially generate the tables for Instance models, theoretical models, general definitions, and data constraints inside of solutionCharSpec so instead of passing the contents can just pass the knowledge to be rendered.

**Comment by niazim3** [comment]
Related to #368

**Comment by smiths** [comment]
@szymczdm is working on completely removing this combinator.

**Comment by JacquesCarette** [comment]
I think this might be done? @szymczdm

**Comment by szymczdm** [comment]
Essentially. We just need to remove the use of SolChSpecF from the examples. Again, that'll likely be mechanical, so I'll divide it up.

**Comment by niazim3** [comment]
Note: @szymczdm has mentioned that this task should be worked on once the [Devi](https://github.com/JacquesCarette/Drasil/tree/Devi) and [yuzhi](https://github.com/JacquesCarette/Drasil/tree/yuzhi) branches have been merged in.

**Comment by szymczdm** [comment]
@niazim3 indeed! I will be looking at the Devi branch tomorrow (it is 2nd on my priority list).

**Comment by niazim3** [comment]
What's left of this issue is related to #714.

On the `master` branch, `solChSpecF`
- **GlassBR**: can be removed easily
- **NoPCM**, **SWHS**, **SSP**: can be removed once the [`yuzhi`](https://github.com/JacquesCarette/Drasil/tree/yuzhi) branch is merged in
- **GamePhysics**: DNE
- **HGHC**: ??? (no implementation at the moment (see [HGHC.hs](https://github.com/JacquesCarette/Drasil/blob/master/code/Example/Drasil/HGHC/HGHC.hs)))

**Comment by JacquesCarette** [comment]
So @szymczdm are you working with @halonazhao to merge in parts of that branch so we can proceed with this?

**Comment by szymczdm** [comment]
Yup. We're still working on finishing up the stable changes and figuring out what information is still missing.
