### ISSUE TITLE
Projectile: GD:rectPos explicitly depends on time

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3211]
In GD:rectPos the position should explicitly be shown to depend on time.  That is, the equation should show p(t), not just p.

**Comment by harmanpreet-sagar** [comment]
I modified the `rectPos ` by creating `projPos`, which is similar to `projSpeed`. I have added `projPos` in all the various places that `projSpeed `was included in order to mimic the way `projSpeed `was created. However, when I try running `make projectile_diff` on bash, it gives me the following error: 

![image](https://user-images.githubusercontent.com/110783820/236567247-5d01686e-0fc5-4ae0-9809-774801d48eb9.png)

I am not sure how to add `projPos` to the `SymbolMap` or what `SymbolMap` it is referring to. I also could not find how `projSpeed` was added to the `SymbolMap`. The branch in which I made my changes can be accessed [here](https://github.com/JacquesCarette/Drasil/tree/3211-show-GD-rectPos-depends-on-time), for reference.

**Comment by smiths** [comment]
@balacij, when you get a chance, could you please advice @harmanpreet-sagar?

**Comment by balacij** [comment]
Ah, yes! This is similar to our [debugging example](https://github.com/JacquesCarette/Drasil/wiki/Debugging-in-Drasil#example). The SymbolMap is a table used to keep track of all symbols (QuantityDicts) for each example.

**Comment by balacij** [comment]
No problem. I'll take a closer look at this soon, because it might actually be a bit trickier than we thought.
