### ISSUE TITLE
Problem Statement Ready for Review

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3241]
The PDF is in the [`People/Jason/CAS 741/problem statement/build/` folder](https://github.com/balacij/Drasil/blob/beamBending/People/Jason/CAS%20741/problem%20statement/build/problem-statement.pdf) of the `beamBending` branch on my Drasil repo.

**Comment by smiths** [comment]
Great job @balacij!  This is going to be an exciting project!  I would like to request one change though.  I agree with the simplifications to the physics (one type of beam for instance), since we have enough other work to do that we don't want to complicate the problem.  However, I would rather leave the load as a function of the length along the beam, if at all possible.  If the load is uniform, then the problem is really simple to solve in closed-form, which undermines the use of a BVP solver.

Could we refer to the distributed load as w(x) in the SRS in all the documentation, but then set w(x) as a data definition?  That way we could change w(x) by changing the data definition.  We wouldn't need the user to enter w(x), which gets into problems of how to communicate entering a function, but we still allow w(x) to be more interesting and variable.

The BVP solver will take care of solving the problem, so if we can pass this information to the BVP solver, something more complicated doesn't add to your workload.

If you think we need to fix w(x), to make the project feasible, I'm okay with that, but I'd still like something more interesting than constant.  Maybe we could do a cubic function for the load?  (That would still let us also do a uniform load, by setting some of the parameters to zero.)

Even though we have this one point still to discuss, I'm going to Approve your project.  w(x) is just a detail we'll sort out.  The overall project vision is great.  :smile:

**Comment by balacij** [comment]
That's a great idea @smiths. The textbook I borrowed from you and some online resources have closed-form solutions to the same problem, so I was wondering why we wanted the BVP solver, but I just assumed it was for the sake of having a BVP solver. So, this idea makes things a lot more clear for me, thank you!

Having the load be some function sounds like a good plan. I suppose we can discuss the function a bit more later? I'm not sure if there are any limitations of the BVP solvers.

**Comment by smiths** [comment]
There will be some constraints on w(x) at this point.  We won't want any discontinuities in either w(x) or the derivatives of w(x).  Any smooth continuous function should be fine.  The BVP solver might be able to handle discontinuities, but it will be a nuisance at this stage to properly convey the information.
