### ISSUE TITLE
chemCode: “ChemCode” Abbreviation missing

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3266]
I know this is against the grain of https://github.com/balacij/Drasil/issues/4 (which I haven't commented on yet), but I think it's worthwhile to mention what “ChemCode” refers to. I believe it would refer to the software artifact?

**Comment by samm82** [comment]
I don't think this is necessary, since the title of the document is "Software Requirements Specification for ChemCode: A program for solving chemistry problems" and I think everyone reading the document will read the title (or if they don't, that's on them). Should this information still make sense to explicitly include? If so, I think it would make more sense in the Terms and Defs section.

**Comment by balacij** [comment]
It's definitely one of those things that is on the fence of being pedantic (or maybe it is!). Personally, I would include it because of personal preference. I understand that readers should at least read the title of everything they read, but I would add it to the AnA for the sake of completeness. I don't think the Drasil examples allow us to infer a rule of thumb -- [GlassBR](https://jacquescarette.github.io/Drasil/examples/glassbr/SRS/srs/GlassBR_SRS.html) does not have it, but [SWHS](https://jacquescarette.github.io/Drasil/examples/swhs/SRS/srs/SWHS_SRS.html).

Again however, it really doesn't matter much. Feel free to close this ticket :smile:

**Comment by smiths** [comment]
As far as preferences go, I agree with @balacij.  It is just one more entry in the table.  If it is helpful to 1 reader in 100, why not include it?  It also feels more complete.  I suppose this would be one of the stylistic choices that might eventually be part of writing a Drasil program.  Part of the "recipe" for an SRS might be whether to include all acronyms, or just the major ones.

**Comment by samm82** [comment]
@smiths So I think I should include "ChemCode" in the table of abbrs. and acronyms with the description "Chemistry Code". None of the other entries in the table have definitions here, as this is not the purpose of this section; if a definition should be added, I think it should go in the Terms and Defs section with the other ones (probably "A program for solving chemistry problems" from the subtitle).

@balacij In https://github.com/balacij/Drasil/issues/4 I said that BeamBending's "description is not particularly informative," which looking back I think is indicative that it isn't needed in the table. This is supported by the fact that it is "neither an abbreviation nor an acronym."

**Comment by smiths** [comment]
@samm82, I like ChemCode in the table of Abbreviations and Acronyms, since ChemCode is an abbreviation of Chemistry Code.  I agree that you shouldn't put a definition in the table.  Since the entire SRS is defining ChemCode, I don't think you need to have an entry for it in the terms and definitions section.

**Comment by samm82** [comment]
Closed in samm82/Drasil@79622d40e
