### ISSUE TITLE
chemCode: law of conservation of mass equation?

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3282]
Do you think TM2 can be written equationally?  [Wikipedia](https://en.wikipedia.org/wiki/Conservation_of_mass) has an entry about this, but I'm not sure how fruitful this would be (so feel free to immediately close this). If you would change it to be equational, then I think you might be able to somehow derive your other IMs from it. However, this might be asking for too much.

Alternatively, is there anything else that can be done to get you more "model" derivations for your IMs?

**Comment by smiths** [comment]
Thank you for the comment @balacij.  I wrote some notes on the marked-up version of the SRS with some thoughts on how to write an equation for mass balance.  Unfortunately the equations in the Wikipedia article won't work, since they are for conservation of mass when there is a substance (usually a fluid) that isn't undergoing any chemical reactions.  We need an equation that captures the idea that the number of atoms of each element on one side of the equation are the same as the number of atoms of the corresponding element on the other side of the equation.

**Comment by balacij** [comment]
Thank you @smiths, that makes sense. Honestly, I was just throwing a shot in the dark with my idea. I'm definitely glad there's something better!

**Comment by samm82** [comment]
This will be tracked at https://github.com/samm82/Drasil/issues/20
