### ISSUE TITLE
chemCode: IM2: is it a data definition too? Is it validation/input data constraint?

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3285]
IM2 seems like it's just a "validation model", where you validate the inputs provided by the users. Do you think this could be incorporated into the Input Data Constraints instead? Alternatively, do you think it would be more appropriate as a Data Definition (similar line of thinking to #3284)?

Also, if it should remain an IM (which I wouldn't be opposed to), then it might be good to add some sort of derivation for your description (specifically about your comment about conservation of mass and why it is important).

**Comment by balacij** [comment]
I forgot to comment about one more thing: the title is "determination of feasibility", which is more reason to why I ask if it should be a validation/input data constraint or a DataDefinition too.

**Comment by balacij** [comment]
It might also be good to describe the IM mathematically.

**Comment by balacij** [comment]
One last thing: if this is going to be changed, then 4.2.7 should also be changed to be more descriptive, and maybe just written mathematically (a bit faster to read than the English description).

**Comment by samm82** [comment]
My rationale for this was using it as a intermediate step: if the matrix is feasible, then its balanced form is outputted; otherwise, a descriptive message is displayed. Do you think this should be merged into IM3? (If it is relevant, I'm planning on implementing part of IM2 by row reducing the matrix, which is then used for IM3, so there is already some overlap between the two.)

**Comment by samm82** [comment]
My rationale for this was using it as a intermediate step: if the matrix is feasible, then its balanced form is outputted; otherwise, a descriptive message is displayed. Do you think this should be merged into IM3? (If it is relevant, I'm planning on implementing part of IM2 by row reducing the matrix, which is then used for IM3, so there is already some overlap between the two.)

**Comment by balacij** [comment]
Hmm, it's difficult for me to make a decision about this because I think it's really just a matter of personal preference, but with a thought for “what would Drasil be able to work better with right now?”.

Is this a case where the design of the generated code/generator capabilities might be affecting how you encode this information? Maybe....

If you want the error message to be defined by your SRS, then keeping it as an IM sounds about right (similar to Projectile's output IM). Otherwise, if the error message is relatively generic, then having it defined as an input constraint might _look_ better (however, I don't know to what capacity Drasil can generate input assertions). However, if we're considering how you want the Drasil-generated code to look like here too, then the IM might be easier to deal with, but I don't think we have any `Maybe`-like types (or assertions between IMs in a system) for IMs to work with.

**Comment by smiths** [comment]
For the original question of DD versus IM, the current version of the SRS template uses DD for statements of "facts".  The DDs are things that are given.  They aren't proven and they aren't refined from anything else.  The DDs in turn are not refined.  They are just there to support the TMs, GDs and  IMs.

**Comment by samm82** [comment]
As part of a redesign of the SRS based on feedback, IM2 has been removed (see samm82@efab6b7), and as such, this issue is obsolete.
