### ISSUE TITLE
chemCode: "R5" is not reflected in IMs

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3286]
From your description, R5 looks like it should be satisfied by an IM, similar to Projectiles "messageIM".

**Comment by samm82** [comment]
How would I specify this abstractly? Say something like "a balanced form of the chemical equation represented by $\textbf{E}$ using the entries of $\textbf{c}$, the smallest solution to $\textbf{E}\textbf{c} = \textbf{0}$ from TM1"? @smiths

**Comment by smiths** [comment]
You aren't really saying what smallest solution means.  My thinking is that you want to reproduce the steps from this [wikiHow](https://www.wikihow.com/Balance-Chemical-Equations-Using-Linear-Algebra).  Using the step numbering from the wikiHow page, we have:

1. Identify the equation to balance - this is your input - a sequence of compounds.
2. Identify the elements - this is part of your input, since the sequence of compounds contains elements.  You might want a function that takes a sequence of compounds and returns the set (sequence?) of elements in the sequence.
3. Set up the vector equation. You can have a GD for constructing a column vector given a sequence of elements.  You could combine this with step 4 by having the column vectors have negative signs for the compounds on the RHS of the equation.
4. Set the equation to 0 and obtain the augmented matrix.  As I said above, maybe we could just do this as part of step 3.
5. Row-reduce to reduced row-echelon form.  This is a standard operation, so you could just characterize what row-echelon form means.  (Changing E matrix into the identity matrix.)
6. Re-parameterize the free variables and solve for the variables.
7. Substitute an appropriate value for t.  This is where you characterize smallest.  You pick the parameter t such that it is the least common multiple.  You could have a data definition defining least common multiple.

**Comment by samm82** [comment]
So I've captured this knowledge here for now, but I feel like this is a lot of information that should be specified more precisely--how will the code generator use this information as is? From this, I'm thinking there should be a DD for lowest common denominator and a DD/IM for getting the actual coefficient for each compound from the matrix. Should there be a DD for reduced row echelon form as well?

![image](https://user-images.githubusercontent.com/35857611/221759472-856d5dd1-7dc5-4ce3-a53d-174d736aa867.png)

**Comment by smiths** [comment]
I agree @samm82.  My thinking is that you introduce the concept of a [pseudo inverse](https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse).  You don't need to say how to calculate it.  Giving information on how to calculate something takes us away from being abstract, and you are going to link to a library anyway.  To define the pseudo inverse (A<sup>+</sup>) you can give the properties of the pseudo inverse, without having to say how to calculate it.  You can then clearly express your solution as A<sup>+</sup> c.  

If you say the type of the entries of A<sup>+</sup> are rational numbers and the type of A<sup>+</sup> c is rational, then we can define the lowest common denominator to turn the rationals into natural numbers.
