### ISSUE TITLE
Distinguish between Easy and low-hanging-fruit labels

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3311]
We noted in #3310 that the Easy and low-hanging-fruit labels should not be synonyms; one of these refers to issues that have a clearly defined solution path and are really good for firstcomers, and the other refers to more simple issues that still require some further thought and/or discussion. 

There should also some explanation in the contribution guide for newcomers to understand how to understand (and use!) these labels.

**Comment by balacij** [comment]
Thank you, when I'm done my labelling passes, I'll write something more complete in the Wiki, but for now I added descriptions to 'Easy' and 'newcomers'.

'newcomers' tickets should be completely expectable in workload, doable in <30min for the 'experts'. If I (as a newcomer) were to ask an expert for an explanation of the solution, they should be able to point me to exact lines of code to change with a precise description. Optimally, it wouldn't be spoonfed however, so that newcomers can still learn and get ramped up in Drasil.

'Easy' tickets are a potential lie. They are things we _want_ to be 'easy' and we think are 'easy', but can be surprisingly complicated, time-consuming, or can lead to suboptimal solutions and a ticket about designing a better solution.
