### ISSUE TITLE
Chapter 3 Lesson Plan is ready for review

### ISSUE THREAD

**Issue by tingyuw** [JacquesCarette/Drasil#3320]
Please refer to chapter 3 in [Thesis](https://github.com/JacquesCarette/Drasil/blob/tyThesis/People/Ting-Yu/thesis/thesis.pdf). Thank you!
I guess I should assign @JacquesCarette this time?

**Comment by smiths** [comment]
Yes, alternating between your two supervisors is a good idea.

**Comment by JacquesCarette** [comment]
On my pile - which has grown quite a bit over the last few days.

**Comment by JacquesCarette** [comment]
Comments:
- "conducting lesson plans" -> create lesson plans. You conduct a lesson, but create a plan.
- in the introduction to chapter 3, before 3.1, I would have expected a short overview of the academic literature on lesson plans and lesson plan structure. You're not implementing something "random" at all - but you need to tell the reader this. I see you do this inside 3.1, but mixed with implementation details. It would be better to split the analysis from the implementation.
- you should indicate, in your analysis, what parts of a lesson plan are manditory and which are optional
- you should probably use something more structured, like a table, instead of bullets, for the information about the parts
- the commentary about each sub-part currently being the same but designed to allow future divergence is excellent.
- you can probably use a slightly smaller font for the code itself, so that more may fit 
- it's also possible to use thinner margins and also less margins in your code listings, for the same reason
- some of the code, like the last 2 functions in Code 3.7, is not informative at all, so you should omit it. Only present the code that needs to be explained.
- Table 3.2 is good.
- I think the points made about re-use in 3.2.1 should be more prominent. It is a non-trivial advantage of doing things in Drasil.
- you should be more explicit that 3.3 is generated from 3.10. Also, the font is too small!
