### ISSUE TITLE
Goal Statements section assumes there will be multiple

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3342]
This related to some other issues @balacij and I have noticed, but the Goal Statements intro assumes that there will be more than one goal statement (this should say "the goal statement is"). Is there another way we would want to handle individual goal statements while we're here (e.g., eliminating the itemization)?

![image](https://user-images.githubusercontent.com/35857611/230534340-44caedda-b5be-4958-b489-c6e0022f279b.png)

**Comment by smiths** [comment]
I agree that we should say "is" when we only have one goal.  If we don't have any inputs to list, we shouldn't have the "Given ," part at the start.  However, I think the beam bending example does have some inputs we could list.

I still like the idea of introducing the goal as a list.  It doesn't have to be a list, but it should be named and separated from the introductory text.  We want the goal to stand out.

**Comment by ManvendraJani** [comment]
@samm82 I tried implemented something like this
```
goalStmtF :: [Sentence] -> [Contents] -> Section
goalStmtF givenInputs otherContents = SRS.goalStmt (intro:otherContents) []
  where intro = if length otherContents == 1
                  then mkParagraph $ S "Given" +:+ foldlList Comma List givenInputs `sC` phraseNP (the goalStmt) +: S "is"
                  else mkParagraph $ S "Given" +:+ foldlList Comma List givenInputs `sC` pluralNP (the goalStmt) +: S "are"
```
but `otherContents` is always length one. It seems to be a passing a list of Contents but is that just a misuse of the type?

**Comment by samm82** [comment]
I don't think `otherContents` is always length one. `mkEnumSimpleD` creates a `[Contents]`, so the produced `[Contents]` should be length four. What does the output of this code look like for SWHS?

![swhs goals](https://github.com/JacquesCarette/Drasil/assets/35857611/cbd86ccf-d1f6-4c5c-8935-76335a10d8e7)

---

A similar but related issue: when no goals are present, it just generates `[]`, which renders as follows (I removed the goals from Projectile). If this happens, it may indicate a bug with the program, since it doesn't make sense to make a program if it doesn't have a goal. @smiths Does it make sense to generate an example without any explicit goals (e.g., generating the Goals section but having it empty)?

![proj without goals](https://github.com/JacquesCarette/Drasil/assets/35857611/365c3df7-ad06-43ef-8b0e-9f3066a3f9c7)

--- 

A side note about your code: the  cases for 1 goal and multiple goals are quite similar and duplicate code, which should be reused.

**Comment by ManvendraJani** [comment]
Here is what it looks like for Projectile
![image](https://github.com/JacquesCarette/Drasil/assets/58832908/3b10e919-7252-4f0f-a4f1-6b5ef992610f)
Here is what it looks like for SWHS
![image](https://github.com/JacquesCarette/Drasil/assets/58832908/a04d7728-e23b-4452-bb57-c5fc9ae0e573)

> I don't think `otherContents` is always length one. `mkEnumSimpleD` creates a `[Contents]`, so the produced `[Contents]` should be length four. What does the output of this code look like for SWHS?
> 
> ![swhs goals](https://user-images.githubusercontent.com/35857611/238768286-cbd86ccf-d1f6-4c5c-8935-76335a10d8e7.png)
> 
> A similar but related issue: when no goals are present, it just generates `[]`, which renders as follows (I removed the goals from Projectile). If this happens, it may indicate a bug with the program, since it doesn't make sense to make a program if it doesn't have a goal. @smiths Does it make sense to generate an example without any explicit goals (e.g., generating the Goals section but having it empty)?
> 
> ![proj without goals](https://user-images.githubusercontent.com/35857611/238768974-365c3df7-ad06-43ef-8b0e-9f3066a3f9c7.png)
> 
> A side note about your code: the cases for 1 goal and multiple goals are quite similar and duplicate code, which should be reused.

**Comment by smiths** [comment]
> A similar but related issue: when no goals are present, it just generates `[]`, which renders as follows (I removed the goals from Projectile). If this happens, it may indicate a bug with the program, since it doesn't make sense to make a program if it doesn't have a goal. @smiths Does it make sense to generate an example without any explicit goals (e.g., generating the Goals section but having it empty)?

@samm82 I cannot think of any case where an SRS following our template would not have a goal.  I definitely can't see any value in generating the goal statement section with an empty list of goals.  We don't need to worry about the content of the section reading nicely for this case.  

Someday we probably will want to generate an SRS that is Smith et al template compliant.  In this case, where our generator is claiming that the generated SRS is compliant, an empty list of goals should generate an error.

At the moment we are giving the user flexibility on what elements of our template they wish to use.  This means that someone could ask to generate a goal statement section with an empty list of goals.  The easiest thing to do is what I described above - not care.  :smile:  Whatever the generator gives us for an empty list of goals is fine, because we have explicitly decided to not care.  Another option would be to generate the following contents for the Goal Statement section when there is an empty list of goals: "Not applicable".  This text is saying that the goal statement section is not applicable for this hypothetical document, but still providing the Goal Statement section heading, so that the document is compliant with the standard template.

**Comment by JacquesCarette** [comment]
meta-comment: using `length` for testing that something has a short length can be really bad, since it will force the input to be fully traversed. Checking if something has length 1 is best done with pattern-matching, which is lazier.
