### ISSUE TITLE
Should add Well-Understood paper to front page description

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#3360]
Right now the main thing we link to is the old position paper.

**Comment by daijingz** [comment]
@JacquesCarette Dr.Carette, can you provide more information?

**Comment by JacquesCarette** [comment]
Reason it out. If you look around, you'll find that paper, and you'll also find how the old position paper is referenced on the front page.

**Comment by daijingz** [comment]
@smiths I am still confused about which paper it is, because there are lots of publications inside the folder.

**Comment by daijingz** [comment]
@JacquesCarette @smiths Dr.Carette and Dr.Smith, I guess this is what you designed to do: **You want to add a link referring to the original Well Understood Paper**. Additionally, If you mean adding some descriptions, then I feel it is unnecessary because there are existing words saying about it.

Inside your requirements, the "old position paper" is the published essay "Generated Software for Well-Understood Domains".
And the front page is ["The GitHub front page of Drasil"](https://github.com/JacquesCarette/Drasil) -> the README file. (Since I did not see any occurrences or mentioning of it elsewhere)

I just used the original way to add the link through the front page.

**Comment by balacij** [comment]
@daijingz Yes, that's the desired outcome. You do not need to explain the contents of the paper in the front page description, as you note.

The "old position paper" is not the "Generating Software for Well-Understood Domains" paper, it is the [ICSE](https://github.com/JacquesCarette/Drasil/blob/master/People/Dan/ICSE%20Workshop%20-%20SE4Science/ICSE_LiterateFrameworkForSCSoftware_LSS.pdf) paper. The "Generating Software for Well-Understood Domains" paper is the paper this issue refers to, which needs to be linked from the front page description.

You can add a link to it to the README.md (perhaps hyperlinked at the first reference to `well-understood` in the README.md file, or otherwise) and/or the front page of the website (which might involve editing a bit of Haskell code).

**Comment by daijingz** [comment]
> @daijingz Yes, that's the desired outcome. You do not need to explain the contents of the paper in the front page description, as you note.
> 
> The "old position paper" is not the "Generating Software for Well-Understood Domains" paper, it is the [ICSE](https://github.com/JacquesCarette/Drasil/blob/master/People/Dan/ICSE%20Workshop%20-%20SE4Science/ICSE_LiterateFrameworkForSCSoftware_LSS.pdf) paper, and that is already linked in the README.md file. The "Generating Software for Well-Understood Domains" paper is the paper this issue refers to, which needs to be linked from the front page description.
> 
> You can add a link to it to the README.md (perhaps hyperlinked at the first reference to `well-understood` in the README.md file, or otherwise) and/or the front page of the website (which might involve editing a bit of Haskell code).

Sorry for my confusion!

**Comment by daijingz** [comment]
> > @daijingz Yes, that's the desired outcome. You do not need to explain the contents of the paper in the front page description, as you note.
> > The "old position paper" is not the "Generating Software for Well-Understood Domains" paper, it is the [ICSE](https://github.com/JacquesCarette/Drasil/blob/master/People/Dan/ICSE%20Workshop%20-%20SE4Science/ICSE_LiterateFrameworkForSCSoftware_LSS.pdf) paper, and that is already linked in the README.md file. The "Generating Software for Well-Understood Domains" paper is the paper this issue refers to, which needs to be linked from the front page description.
> > You can add a link to it to the README.md (perhaps hyperlinked at the first reference to `well-understood` in the README.md file, or otherwise) and/or the front page of the website (which might involve editing a bit of Haskell code).
> 
> Sorry for my confusion. I just saw the old position paper link before, but I forgot to change my mis-understanding.

**Comment by balacij** [comment]
Closed in #3860
