### ISSUE TITLE
Add Clarification to Workflow Section within the Contributor's Guide

### ISSUE THREAD

**Issue by harmanpreet-sagar** [JacquesCarette/Drasil#3368]
The [Workflow ](https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide#workflow) Section of the [Contributor's Guide](https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide#) could be modified in order to reinforce the need to update [stable](https://github.com/JacquesCarette/Drasil/tree/master/code/stable) for changes that intentionally modify the generated documentation/code. Further discussion on this topic is available [here](https://github.com/JacquesCarette/Drasil/pull/3367#issuecomment-1532124695).

**Comment by smiths** [comment]
Sounds good @harmanpreet-sagar.  Other than an explicit link like you included, another way to have traceability to other issues is to use the hash symbol followed by the number of the issue.  For instance, to link the related issue, you just need to type #3367.  :smile:

**Comment by harmanpreet-sagar** [comment]
Thank you for the tip. 😄 That makes it so much more easier to link the two together.

**Comment by JacquesCarette** [comment]
It seems what you did was add "Note: If changes are made that intentionally modify the generated documentation/code, it is imperative to update the stable folder in order to prevent any CI errors. Further information on how to accomplish this can be found in the Workflow article linked above." , right?

Rather than that second sentence, better hyperlinked documentation would have the link in this paragraph. I would make the words 'update the stable folder' be a link to that information, and delete the 2nd sentence.

**Comment by harmanpreet-sagar** [comment]
Thank you for the feedback. Yes, that was the change that I had originally made. I have now modified the section to incorporate the requested changes.

**Comment by harmanpreet-sagar** [comment]
Am I good to close this issue now as completed, or are there any further changes that I need to make for this issue?

**Comment by smiths** [comment]
We can close this issue now.
