### ISSUE TITLE
Fill `purpose` for Game Physics

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3419]
Spun-off of #3391. Other examples (except for HGHC and Template which are meant to be bare bones) had a short introduction to the Problem Description section in the SRS which could be directly used as the `purpose` in `SystemInformation`. However, this introduction for Game Physics is too long to be used directly. A short summary of this introduction (and the Goal Statements) is needed.

**Comment by smiths** [comment]
@hrzhuang this is a good issue.  I've assigned it to you, since I don't think it will take long and you know the context of what we are trying to accomplish.  You can put the proposed text as a comment first so that I can give you comments before we proceed.

**Comment by smiths** [comment]
@hrzhuang I like your proposed purpose, but I think we should simplify it even further.  Our first goal is to get the functionality right.  I have less confidence that we'll achieve the nonfunctional requirements like simple, lightweight, etc. 
Also, I don't want to claim those things until we have an unambiguous way of specifying those qualities.  At some point, we will want to return to the conversation about the nonfunctional requirements, but for now, I think we should leave them out of the purpose.  Let's just say:

"simulate 2D rigid body physics for use in game development"

I thought about taking out the game development part, but I think we should keep it, since the scope of the project comes from an existing project built for game physics.

I agree with you that the introduction would be changed to something like "A simple, lightweight, fast, and portable 2D rigid body physics library allows ..."  I left the nonfunctional requirements in there to help remind us that this is something we should expand/clarify in the future.  @hrzhuang please either fix the introduction, or create an issue that we can assign to someone else for this.

**Comment by hrzhuang** [comment]
I created a PR that adds this purpose and fixes the introduction. I changed the first sentence of the introduction to

> A system is needed to simulate 2D rigid body for use in game development, in a simple, lightweight, fast, and portable manner, which will allow for the production of higher quality products.

so it reuses the purpose instead of saying the same thing slightly differently. Also Drasil puts the phrase "A system is need to" at the beginning of every introduction (which is something we might want to relax as another issue).
