### ISSUE TITLE
What is the purpose of `CodeInfo`?

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3433]
All other instances of `OOProg` correspond to programming languages, and `CodeInfo` is the odd one out. It seems to have to do with getting information out of GOOL, but what are some specific examples of information that we are looking to get from it?

**Comment by JacquesCarette** [comment]
Can you provide more context please? Probably some permalinks to the codebase, to illustrate what's going on here? [It's been too long since I've looked at GOOL, I need to have someone refresh my memory.]

Also, you should search for `CodeInfo` via the Search functionality in github; particular attention should be paid to mentions in issues (but also to the PR that introduces it).

**Comment by hrzhuang** [comment]
Ah, thank you for the tip of looking into PRs. It seems `CodeInfo` was initially introduced to collect information for determining what needs to be imported in a C++ file. For convenience to those with the same question in the future, the most relevant PRs are #1970 (which introduces `CodeInfo`) and #1971 (which introduces the primary use of `CodeInfo`).
