### ISSUE TITLE
Name generation in GOOL

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3475]
There is currently no way to generate "fresh" variable names in GOOL. Currently when we emit `for` loops for a higher-level pattern (e.g. `listSlice` and `notifyObservers`) the loop variable name is just hard-coded in without regard for whether that name is already used.

This is coming up because the work I am currently doing with vectors emits loops for vector operations, and I am further interested in generating names for variables to hold intermediate values.

My proposal:
* Add a `_usedNames :: Set String` field to `MethodState`.
* Implement a `freshName` function that takes a `[String]` (candidate names, e.g. `["i", "j", "k"]`) and a `String` (last resort name, e.g. `"i"`) and returns a `MS String` (computation in the `State MethodState` monad that yields the fresh variable name). It picks the first candidate that is available, and if no candidate is available then it appends a number to the last resort name to produce a fresh name (e.g. `"i2"`). This is so that we generate names that are as idiomatic as possible (i.e. names that a human programmer would choose).

**Comment by smiths** [comment]
@hrzhuang I like the idea of generating a name that is as idiomatic as possible.  I did some quick reading on [Lisp's gensym](https://stackoverflow.com/questions/59493025/what-does-gensym-do-in-lisp) and they definitely don't emphasize it being readable.  By default gensym has names that start with G followed by a number that makes it unique.  The user can provide their own prefix string, rather than "G".

Is there any way for `freshName` to know the scope of the variable?  It isn't really idiomatic for a programmer to have code where they only use the loop index i once.  They tend to use it every time, unless there are nested loops.  I'm not an expert, but what I'm asking is probably too hard to do because of all the different languages and scope rules.  Programmers also reuse variables like a loop index by just resetting the value to zero at the start of the next loop.  We wouldn't want to have to worry about the sequence of instructions.  I think it is okay to sacrifice some "idiomaticy" in favour of the safety of having unique names.  :smile:

**Comment by hrzhuang** [comment]
As you said, different languages have different scoping rules: C++ has block scope while Python doesn't. Though I am interested in exploring our own notion of "scope" independent of the scoping rules in the target languages. Again as you said, in Python my loop variable `i` remains in scope after the loop that declared it ends, but I simply don't care about its value anymore! So it is idiomatic to use the variable name `i` again: as far as we are concerned, the scope of the variable `i` has ended. Among our current target languages, Python is the only one that doesn't have block scope. But Python also doesn't have a syntax for declaring a variable separate from simply assigning to it, so we can "re-declare" variables as long as we don't care about the old value anymore. I would be interested in hearing if there is any language (that we could reasonably expect to target in the future) that both lacks block scope *and* disallows this kind of "re-declaration."

I mention this as a possible future step, but I think our top priority right now is to get some version of name generation working even if the names are not absolutely optimal, since we are currently emitting erroneous code when there is a naming conflict. In `listSlice` for example, the loop variable name `i_temp` is hard-coded in. So if `i_temp` is already used outside the loop in Python, it would get overwritten. In the other languages, the `i_temp` declared by the loop would shadow the `i_temp` outside the loop, so if the list that we are slicing is the variable `i_temp` (from outside the loop), then we end up indexing the loop variable `i_temp` with itself.

I understand that GOOL takes a "garbage in, garbage out" approach when it comes to errors in the generated code, but I don't think it is fair to ask users of GOOL to memorize all of our internal loop variable names. Especially since the fact that we are even generating a loop for `listSlice` is an implementation detail in the first place!

**Comment by smiths** [comment]
Yes, @hrzhuang I agree.  The notions of scope and "re-declaration" are interesting and should be explored in the future, but for now, the practical approach you have outlined sounds good to me.  We might not get perfect variable names, but we can be confident that there won't be a name clash because of the name generator.

**Comment by JacquesCarette** [comment]
I approve of this proposal. [No need to be verbose about it - everything above is great.]
