### ISSUE TITLE
Remove Game Physics from table of Abbreviations

### ISSUE THREAD

**Issue by ManvendraJani** [JacquesCarette/Drasil#3514]
The `Abbreviations and Acronyms` table has `Game Physics` listed. Currently it is shown as: 
![image](https://github.com/JacquesCarette/Drasil/assets/58832908/c003baab-db99-49a0-834c-17890b93c1a2)
I believe this is unnecessary for 2 reasons; 
- as mentioned in #3491 the term 'game physics library' should not exist, as we don't specify that for other examples.
- `Game Physics` is neither and abbreviation or acronym.

**Comment by samm82** [comment]
I made a comment [here](https://github.com/JacquesCarette/Drasil/issues/3491#issuecomment-1621045798) that I won't repeat, but as far as your first reason, I'm not sure if that is a valid reason. If the full name of the Projectile program is "Projectile", then it doesn't have an abbreviation (unless we want to use "Proj" or something later 😅). However, since "the Game Physics Library" is a bit long, it makes sense for it to have an abbreviation ("GamePhysics").

**Comment by ManvendraJani** [comment]
If we are planning to use "the Game Physics Library" for our final `progName` it make sense to keep the abbreviation, but I will wait till after the meeting to close this issue.

**Comment by smiths** [comment]
Although awkward, Game Physics Library can be the name of the game physics library.  It is fairly common for the term library to be in the name of a library.  For instance, [netlib](https://www.netlib.org/) and [GSL](https://en.wikipedia.org/wiki/GNU_Scientific_Library) (Gnu Scientific Library) have the name library in their names.  People talk about the netlib library and the GSL library.  It is redundant, but it is still common practice.

I think the root cause of the problem is the poor name of the Game Physics Library.  If we called had an abbreviation GPL, I think we could get rid of the problems?  "The primary purpose of this document is to record the requirements of GPL" doesn't sound awkward.  We would also have an abbreviation for the table of abbreviations.  :smile:

**Comment by samm82** [comment]
> People talk about the netlib library and the GSL library. It is redundant, but it is still common practice.

Oh no, [RAS syndrome](https://en.wikipedia.org/wiki/RAS_syndrome) is spreading!

**Comment by smiths** [comment]
Another example similar to RAS comes from @JacquesCarette 's [favourite movie where they talk about the redundancy of saying chai tea.](https://www.youtube.com/watch?v=oILePLqJXos)  :smile:
