### ISSUE TITLE
Remove capitalization from concepts in PDController

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3534]
As seen in the example below, many concepts in the PDController example have capitalization baked in, instead of letting the sentence constructors handle it.

https://github.com/JacquesCarette/Drasil/blob/1acb8ba1553d16d1c949e3b55049fb2242dfe555/code/drasil-example/pdcontroller/lib/Drasil/PDController/Concepts.hs#L17-L22

This has unwanted side effects; for example:

![image](https://github.com/JacquesCarette/Drasil/assets/35857611/cb5cd660-7dcf-431c-86c7-f9f685cdfb76)

**Comment by daijingz** [comment]
Although I have chosen other issues, can I work on this as well?

**Comment by balacij** [comment]
Hi @daijingz, that is fine since it doesn't look like anyone else is working on it. Try to submit a PR once you have something.

**Comment by daijingz** [comment]
Can you give me some explanations about your mentioned concept of "capitalization"?
I feel this time I may over-simplify the given issue again. I feel "capitalization" is these 6 concepts concepts' parameters have capitalized letters, which should be changed to non-capitalized letters (Since sentence constructors have already worked on this)

**Comment by daijingz** [comment]
This is my draft answer:

> --pdControllerApp = commonIdeaWithDict "pdControllerApp" (pn "PD Controller")                    "PD Controller" []
> pdControllerApp = commonIdeaWithDict "pdcontrollerapp" (pn "pd controller")                    "PD Controller" []
> --pdControllerCI  = commonIdeaWithDict "pdControllerCI"  (pn "Proportional Derivative")          "PD"            []
> pdControllerCI  = commonIdeaWithDict "pdcontrollerci"  (pn "proportional derivative")          "PD"            []
> --proportionalCI  = commonIdeaWithDict "proportionalCI"  (pn "Proportional")                     "P"             []
> proportionalCI  = commonIdeaWithDict "proportionalci"  (pn "proportional")                     "P"             []
> --derivativeCI    = commonIdeaWithDict "derivativeCI"    (pn "Derivative")                       "D"             []
> derivativeCI    = commonIdeaWithDict "derivativeci"    (pn "derivative")                       "D"             []
> --integralCI      = commonIdeaWithDict "integralCI"      (pn "Integral")                         "I"             []
> integralCI      = commonIdeaWithDict "integralci"      (pn "integral")                         "I"             []
> --pidCI           = commonIdeaWithDict "pidCI"           (pn "Proportional Integral Derivative") "PID"           []
> pidCI           = commonIdeaWithDict "pidci"           (pn "proportional integral derivative") "PID"           []

After running the test, it passes. Is this your expected answer?

**Comment by daijingz** [comment]
For the current pull request, I did not understand what is happening, can anyone give me some descriptions about this failure?
Because these days I try to build and run in many conditions, including different versions and different changes. However, it seems like it can work well.
Here is the URL: https://github.com/JacquesCarette/Drasil/actions/runs/5805216939/job/15769260293?pr=3605

**Comment by balacij** [comment]
The PRs workflow run is "failing" because the freshly generated artifacts that it builds are different than those we've deemed "stable" (which we've stored in the `code/stable/` folder). If you feel that your changes appropriately changed the "stable" artifacts, then you should copy the freshly altered artifacts over those stabilized. `make X_stabilize` (where `X` is the name of each example you've checked) and `make stabilize` will be helpful here to copy over the artifacts. I think this is documented in lengthier discussion somewhere on the wiki.

Once the CI tests the code from the originating branch of the PR and finds that it generates the same code as those stabilized, then that particular check should be cleared. :smile:

**Comment by daijingz** [comment]
Yes, I feel my changes appropriately changed the "stable" artifacts

**Comment by samm82** [comment]
[Your PR](https://github.com/JacquesCarette/Drasil/pull/3605/files) only changed one file in `code/drasil-example` - if you "appropriately changed the 'stable' artifacts", then files in the `code/stable` folder would have been changed as well. Running `make stabilize` will update the stable artifacts to match what is generated in the `code/build` folder - it is up to you to determine if this is true.

>Now there is nothing in the log file

After running your code, look in the `code/logs` folder. You should see an entry for PD controller, which will show you where your generated files differ from the stable files (as I've previously mentioned on a PR)

**Comment by balacij** [comment]
Closed in #3651 ? Perhaps with #3650, we could figure out an auto capitalization scheme for initialisms?

**Comment by samm82** [comment]
In future @daijingz, you can add the phrase "closes #3534", etc. to the description of a PR; that way, the linked issue will be closed automatically when the branch is merged into the main one!
