### ISSUE TITLE
Change `abrv` to `programName` for usages that do not cause a stable change

### ISSUE THREAD

**Issue by harmanpreet-sagar** [JacquesCarette/Drasil#3545]
Based on the findings of #3472, `abrv` needs to be changed to `programName` in areas that do not cause any stable changes. 

Background: Most uses of `abrv` come along with `sys`, which essentially holds the name of the examples. There is no difference between `programName` and `abrv` in all examples other than `Game Physics` and `PD Controller`. In the cases of these two examples, the only difference that is created based on the usage of `programName` instead of `abrv` would be the addition of an underscore `(_)` between the two words in its name. More information on this investigation can be found in this Excel sheet [here ](https://mcmasteru365-my.sharepoint.com/:x:/g/personal/sagarh_mcmaster_ca/EYuyx9tXvwhBiRhrO-Ft3UIBOTqIKkipPtl3HGFTG-OOZg?e=i8mQco) or in this comment [here](https://github.com/JacquesCarette/Drasil/issues/3472#issuecomment-1638883175).

**Comment by harmanpreet-sagar** [comment]
@smiths @JacquesCarette Should I have the underscore here or not as in this mention, the name of the example is part of an ongoing sentence.

![image](https://github.com/JacquesCarette/Drasil/assets/110783820/ad34a1a9-f674-49ac-81c0-5d52f3a4b763)

**Comment by JacquesCarette** [comment]
The issue of `_` is completely different and should be discussed in its proper context rather than here. (Which is probably why @smiths has a hard time answering here.)

**Comment by harmanpreet-sagar** [comment]
@smiths I believe it is referring to the Game Physics Library as a program. I can create a new issue to explore this further.

**Comment by smiths** [comment]
@harmanpreet-sagar if the intention is to define what the Game_Physics library does, then the sentence should be reworded.  Something like "Game_Physics is a library for modelling and simulating 2D rigid body physics for use in video games."  In this case, we need the underscore, since the library really has to have a name that is different from the phrase "game physics".  People will have trouble reading the sentence if it is read as the concept of game physics, rather than the library called game physics.  I think we really should come up with a better name for this library.  I don't want to cause additional headaches, so that's something we can talk about in the future.  :smile:

**Comment by smiths** [comment]
Game_Physics is really one of our more neglected examples.  It really requires a thorough review, but I've been waiting until we get our refined theories version in order.  It also would help to find someone that is enthusiastic about physics, since there is some neat physics even in 2D rigid body mechanics.  :smile:
