### ISSUE TITLE
Add citation to original (manual) works from each case study

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3562]
Spawning from #3526.

The majority of the case studies recreate a manually created SRS + code artifacts. For each case study where we haven't already, we should add a citation back to the original artifacts and authors.

As @smiths mentioned in #3526, "in the introduction we should point to the previous manually created case studies, as appropriate."

@smiths maintains [a repo containing the original artifacts](https://github.com/smiths/caseStudies/tree/master/CaseStudies) (with [swhs](https://github.com/smiths/swhs) in a side repo), which we can use for citation.

**Comment by daijingz** [comment]
I want to work on this issue. I am going to have a lot of questions. (Seems like nobody is working on this)

**Comment by daijingz** [comment]
I am confused about how we should cite in this issue. (I cannot imagine what kind of citation work we should add.) What should I do? Can you give me more information?

**Comment by balacij** [comment]
I believe all the case studies are based on manually-created original works, and so we want to add a citation back to the git repo containing the original works. I linked to them in the original post, but you might need to do some digging around for all the links. Naveen's PD Controller is likely from his personal GitHub account, while the rest are from @smiths' account.

**Comment by daijingz** [comment]
Let me do some personal research

**Comment by daijingz** [comment]
**Confusion 1** -- Where are all case studies? The given link is https://github.com/smiths/caseStudies/tree/master/CaseStudies. It is a different repository from this one. All of my updates are on this repo.
**Confusion 2** -- What are the mentioned "citations in the introduction section"? Some case studies have the repository `\ref`, but I do not think these are the right places. I think the introduction part only refers to those `README` files.
So I am going to modify the README files in these folders and here: https://github.com/daijingz/caseStudies/tree/master/CaseStudies#readme

![image](https://github.com/JacquesCarette/Drasil/assets/61481741/817524b9-be1d-4897-a45b-e453179fd3fd)
**Because there is one folder** `swpcm` **whose citations are already complete, I am not going to modify this folder**

**Comment by daijingz** [comment]
@balacij Jason here is my PR, I need your help immediately -> https://github.com/smiths/caseStudies/pull/248

**Comment by smiths** [comment]
@daijingz I think you misunderstood the issue.  I believe it is simpler than you are making it.  In the introduction to the generated SRS for each Drasil example (that doesn't already do this) we want to cite the original work.  The original work is a manually created version of the SRS produced in the Case Study repo.  You are right that this is a separate repo.  This is the repo where the examples were originally created manually.  Drasil has now reached the point where it can regenerate these examples.  In several cases the Drasil version is now better than the original because we stopped maintaining the original (manual) versions.

**Comment by daijingz** [comment]
@balacij Jason, here is my understanding:
Folder `Case Studies` are all original places where we need to cite from, while the folder `Drasil` includes some recreated versions, which requires me to cite them back to the case studies folder project.
Where are the expected location that these citations are supposed to take place?

**Comment by daijingz** [comment]
@balacij @samm82 Jason and Sam, now this issue I have already reached the second step: This is the page including some of my confusion: https://github.com/JacquesCarette/Drasil/pull/3682
Please give me some assistance

**Comment by samm82** [comment]
Not sure what you mean by this/need help with; it looks like #3682 has been resolved?

**Comment by smiths** [comment]
@samm82, the PR only addressed part of the original issue.  It identified the case studies and listed them in a README file, but it didn't modify the SRS to cite those case studies.

**Comment by samm82** [comment]
Ahh, I see. It looks to me like we want to add this link to the Introduction section. For example, for Projectile, something like the following, where the bolded/italicized part is what is added:

> The following section provides an overview of the Software Requirements Specification (SRS) for Projectile _**based on the original, manually-created version of [Projectile](https://github.com/smiths/caseStudies/tree/master/CaseStudies/projectile/projectileSRS)**_. This section explains the purpose of this document, the scope of the requirements, the characteristics of the intended reader, and the organization of the document.

**Comment by daijingz** [comment]
@samm82 No problem!

**Comment by daijingz** [comment]
@smiths @samm82  I found the correct place, however, there is one difficulty: how to add the link inside.
Now my code just adds the text inside. (**SEE the fifth line**)

![VOT0RBJ_BNXVQT6)QZ)5`WE](https://github.com/JacquesCarette/Drasil/assets/61481741/a6cf4b92-f930-4ab2-8f9f-1dd2f12bd331)

Here is the output: 
![FSUV%5 Y14ELRJ KUOR}IP3](https://github.com/JacquesCarette/Drasil/assets/61481741/00128bb0-a2a5-4d54-a006-bd5700e7aa06)

In order to have a link, we need to have a matching with different URL addresses. This is easy for URL addresses. However, the problem is, how to build a link inside. I have already see some system constraint examples, but I cannot use their same format since the program requires a Reference format. (While I do not know how to write the reference format)
(Below is the system constraint example)
![F`YK1L0PUCM607 CR%E{GZJ](https://github.com/JacquesCarette/Drasil/assets/61481741/a6bef33f-d784-49b0-b993-aa8c0d9cb465)

**Comment by smiths** [comment]
@daijingz the case studies should be treated the same as other citations.  You can start by having a look in the examples to see how citations are coded.

**Comment by daijingz** [comment]
@smiths Dr.Smith, I find it very hard to find a reference link example. There are some references in the SRS, however, their formats are quite distinct. Let me review the target link again.

**Comment by balacij** [comment]
@daijingz [Projectile's SRS](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/srs/Projectile_SRS.html) has a "Purpose of Document" section containing an example here (an inlined citation). You might be able to use that as an example. Otherwise, you should be able to use that as a starting point to poke around the Haddock documentation (linked from the Drasil website).

**Comment by daijingz** [comment]
@balacij @smiths I forgot to indicate a difficulty here: link formats are different (in several distinct types):
Example: 
https://github.com/smiths/caseStudies/tree/master/CaseStudies/gamephys
https://github.com/smiths/swhs
https://github.com/Zhang-Zhi-ZZ/CAS741Project

I believe the previous pattern-matching method cannot work well, because all previous citation links have consistent address paths (partial parts of paths). Some folders are from different repositories. I am working on solving this.
