### ISSUE TITLE
Reorganize calculation and output FRs of SWHS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3589]
Currently, SWHS (and NoPCM) are the only two examples (that I've encountered) that group the calculation and output requirement by quantity (i.e., having one requirement for calculating **and** outputting **each** value) instead of by operation (i.e., having one requirement for calculating **all** values and one for outputting **all** values). Not only is this inconsistent and capture multiple functionalities in the same requirement, it also is a roadblock to #3259.

**Comment by samm82** [comment]
The current SWHS includes the following two requirements:

![image](https://github.com/JacquesCarette/Drasil/assets/35857611/1b3214fb-1f07-45de-a82c-5cc56f73a86b)

[Originally](https://github.com/JacquesCarette/Drasil/issues/3259#issuecomment-1636294793), I noticed that these quantities weren't present as outputs of the program:

https://github.com/JacquesCarette/Drasil/blob/cdb28906b50118513c6b5fa3569abad4b066d447/code/drasil-example/swhs/lib/Drasil/SWHS/Unitals.hs#L409-L412

Now, I'm also realizing that (unless I'm missing something), these values are obtained implicitly by the [IM they reference](https://jacquescarette.github.io/Drasil/examples/swhs/SRS/srs/SWHS_SRS.html#IM:eBalanceOnPCM) and are not directly calculated:
![image](https://github.com/JacquesCarette/Drasil/assets/35857611/229761b9-7bf7-40a0-a9f3-e00035e2a309)

Should these values have IMs for explicitly calculating them? This feels like the "right" approach, but I also might be missing some nuance and this feels like yet another thing for me to be sidetracked by. Another workaround would be to (temporarily?) remove these two requirements until we have a better way to implement them? @smiths @JacquesCarette Any thoughts?

**Comment by samm82** [comment]
We decided in #3593 that we should leave these output requirements to be manually for now and revisit them later (#3600), generating the rest of the requirements in the meantime.

**Comment by smiths** [comment]
I think this issue is actually more than one "issue."  The starting point, reproduced below, is fairly straightforward:

> Currently, SWHS (and NoPCM) are the only two examples (that I've encountered) that group the calculation and output requirement by quantity (i.e., having one requirement for calculating **and** outputting **each** value) instead of by operation (i.e., having one requirement for calculating **all** values and one for outputting **all** values). Not only is this inconsistent and capture multiple functionalities in the same requirement, it also is a roadblock to #3259.

Having the requirements for both calculate and output is inconsistent, and not atomic.  However, I don't think we want to have a single calculation requirement for SWHS (and nonPCM).  That wouldn't be atomic either, since multiple calculation requirements would be in the same requirement.  For simple problems that is okay, but for something like SWHS breaking down the calculations into separate requirements makes sense to help the reader understand the process.  Having said I like separate requirements for each calculation, I would also be fine with a single requirement that points to a table that summarizes the quantities calculated and the source IM, like for the [projectile example](https://github.com/JacquesCarette/Drasil/issues/3533#issuecomment-1667131065).

So for the question of splitting calculate and output into separate requirements, this is a good idea.  We should definitely do that, with a table summary if that is the easiest way to do it.

Now the question of t_melt^init, which is really a separate issue.  The IM can't really split solving the ODE from solving for the time when the ODE switches to a new "zone".  Solving the ODE requires event location.  The documentation for [Matlab's ODE Event Location](https://www.mathworks.com/help/matlab/math/ode-event-location.html) gives the following motivation and example:

"Part of the difficulty in solving some systems of ODEs is determining an appropriate time to stop the solution. The final time in the interval of integration might be defined by a specific event and not by a number. An example is an apple falling from a tree. The ODE solver should stop once the apple hits the ground, but you might not know when that event would occur beforehand."

In SWHS we aren't stopping the simulation when the PCM starts melting, but switching to a new ODE.  We switch again when all of the PCM has melted.

We can't really separate the calculation of t_melt^init from the calculation to solve for temperature.

Having said that, the IM above doesn't explicitly mention t_melt^init, so you have found a problem with the current requirements specification.  t_melt^init (and t_melt^final) are not even shown as outputs, even though they are.  The IM should be modified to mention how melt times are found.

@samm82 can you create a separate issue to fix the TM to explicitly mention t_melt^init and t_melt^final as outputs and include a description of what is being calculated?  

Although I could imagine splitting t_melt^init (and t_melt^final) into their own IMs by defining an event function, this would be an artificial split.  The IMs for the event functions and for solving the ODE would have to be solved together.  I think I would rather have an IM with multiple outputs.

@samm82 will this cause a problem for your automation steps?

**Comment by samm82** [comment]
Having an IM with multiple outputs will likely cause difficulties with my current method of automation, but it will also likely cause difficulties with many other areas of our code, based on how baked in the assumption of "one IM, one output" seems to be. I think we can cross that bridge when we get there. Leaving them as explicit, manually written requirements for now I think is the best path forward.

**Comment by smiths** [comment]
@samm82, I agree with your conclusion.
