### ISSUE TITLE
Desired depth of reading

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3654]
I've just finished reading the first paper on the [Generative Programming reading list](https://github.com/JacquesCarette/Drasil/wiki/Generative-Programming), [A Survey of Metaprogramming Languages](https://dl.acm.org/doi/abs/10.1145/3354584). The notes I've taken can be found in [the latest version of my "thesis"](https://github.com/samm82/TestGen-Thesis/blob/7f06aae04fc6d09e902b44c7cc77a377ebc6a7c2/thesis.pdf), from pages 8-16 (for context, the original paper is 40 pages long).

How in-depth should I be going for future readings? I found the note-taking process really helpful for consolidating and understanding information, and having everything linked to its sources (including page numbers) should (hopefully) pay off when writing my thesis. However, I'm worried I did the classic Sam maneuver of "doing too good of a job" and have taken too much time on this. On a scale from "skimming" to "what I'm currently doing", how long should I spend reading these papers? What should I be seeking to gain from them?

**Comment by smiths** [comment]
@samm82 how long you spend on a paper should be proportional to how useful the paper is.  I skimmed through your current summary and it has a lot of information.  My first thought is that maybe you have too much information for the time it would have taken to collect it.  @JacquesCarette is a better judge of how useful the summary will be, but it seems to me that you've covered a lot of definitions and terminology related to metaprogramming.  I think definitions are helpful, but I also think you want to know how to do the things you will need to do.  Would your time be better served by doing metaprogramming exercises, or by writing down the definitions?  My instinct is that doing would be more helpful, but I defer to the judgement of @JacquesCarette since metaprogramming is his area.

In general, I think you want to start with only a quick survey of a paper.  The kind of summary you can write in about 30 minutes.  If the paper keeps coming up in your work, then you want to return to it and invest more time.  I skimmed hundreds of papers for my grad work, but I only read every word of probably less than 20 papers.  

Often it is enough to read the abstract of a paper to know if it is relevant.  If the abstract is promising, then I read the introduction and the conclusion.  I only read the discussion when I really need to know the details.

A paper that is on metaprogramming applied to generating testing code would be really helpful.  That seems like a paper where you would want to read the whole thing.  :smile:

**Comment by samm82** [comment]
Thanks for the valuable feedback! Definitely makes sense to me!

**Comment by samm82** [comment]
Thank you both again for this information! I have added it to the wiki under [Readings](https://github.com/JacquesCarette/Drasil/wiki/Readings) in case it would be helpful to future students.
