### ISSUE TITLE
General Definition Unit Construction?

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/Drasil#369]
I feel like this was already addressed somewhere but I could not find it...
At the moment, General Definitions are created using `RelationConcept`s. However, `RelationConcept`s do not take units which may or may not be present in a General Definition.  Was there a design reason for this or is this simply a place holder?

**Comment by JacquesCarette** [comment]
In theory, it is not needed as units should be inferable from the relation.  That, however, is not yet implemented.

Can you point to specific examples where this is a problem?

**Comment by AKM11** [comment]
Here is a side by side comparison of the General Definition output (left) and what the output should look like (right).
![image](https://user-images.githubusercontent.com/28261578/28944532-daeb7538-7870-11e7-9418-8b669fb80d26.png)
Note that the table might need a SI Unit row (also note that the T placeholder for Number is also signifying that the table is currently being constructed as a Theoretical Model).

**Comment by AKM11** [comment]
@niazim3 brought up an interesting point for Instance Model, which has a similar problem in terms of missing output. In NoPCM, the table employs two rows designated Input and Output while in GlassBr there is only one row labelled equation (essentially making it a RelationConcept and much easier to work with):
![image](https://user-images.githubusercontent.com/28261578/28944950-87d498f0-7872-11e7-87e4-c89ec32a9f6f.png)
Are either of these formats preferred?

**Comment by smiths** [comment]
My preference is for the instance models to all have the same format, and I would like that format to contain explicit mention of the inputs and outputs.  The GlassBR example likely left this information out because it is implicit in the equation.  For instance, the input is NFL, GTF and LSF and the output is LR.  We shouldn't have implicit information in our knowledge base though, we should make it explicit.  If someone decided to write a recipe for displaying the instance model without the input and outputs, that would be their choice, but we should have this knowledge available for those that want to use it.

I believe we should seek standardization between our case studies.  We should only treat the examples differently if there is a compelling reason to do so.  I don't see a compelling reason in this case.  The differences are due to different authors of the documents, not because of anything explicitly planned.

**Comment by niazim3** [comment]
@smiths Would it be beneficial to have an **Inputs** field, an **Outputs** field, _and_ an **Equation** field? Just so the user can see the relationship between the inputs that are used to produce the output(s)? Or would this be considered redundant information?

**Comment by JacquesCarette** [comment]
We need to have "Functional Models" which have explicit **input** and **output** fields.  An instance model may have many different functional models, by choosing different sets of variables to be inputs/outputs.

For convenience, when we have a `QDefinition`, used as a trivial theory, we should automatically infer that all 'free' variables are inputs and the one variable being defined is the sole output.

**Comment by smiths** [comment]
In answer to your question @niazim3 , I think we can remove the Equation field from the instance model.  The output field will hold the equation.  It could be an explicit equation, like the ones in GlassBR, or an implicit specification of the outputs, as in SWHS.

**Comment by JacquesCarette** [comment]
@szymczdm As this is (now) intimately related to getting "theories" working, could you please cross-reference the right issues? This will be relatively easy to fix once that's done [and I understand that the implementation is well on its way].

**Comment by szymczdm** [comment]
The general definitions units were fixed a while ago (commit 91583019f01f99a9586bf5517eac31c73a102608 or possibly earlier). The Instance Models were fixed and tested as of commit e1ae83c94f14426265d150d6cabcd58ec6b3331a.

Smart constructor for instance models from QDefinitions added as of commit d3cd3c36e32622e45dcf7fe16ea3494bade7bc65
