### ISSUE TITLE
Add more static analysis to our Haskell tool chain?

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#3700]
[Stan](https://github.com/kowainik/stan/) is another tool, which does things differently than hlint. Maybe we should use it too?

This issue is basically for us to come up with a yes/no decision; if yes, then this should become a (small) project instead of a long-lived issue.

**Comment by balacij** [comment]
`weeder` is another one that might be useful too.

Are there any conflicts between Stan and hlint?

In either case, I'm a vote for 'yes.'

**Comment by smiths** [comment]
I looked at a sample [report](https://kowainik.github.io/projects/stan/report) that Stan generated for another project.  I can't see any reason, other than the time it will take to do it, to not be interested in a report on Drasil.  We might not need to integrate Stan into our CI process.  Maybe it is just something we do on an ad hoc basis?  The decision will depend on how useful the output is from Stan.  

I looked up [weeder](https://hackage.haskell.org/package/weeder) as well.  The purpose of weeder is to detect dead code.  I'd certainly be interested in knowing if we have dead code.  :smile:  Again, I don't know if we need it as part of our CI process.  I think we should run it on our code base first to see how useful the output is.

**Comment by balacij** [comment]
I used `stan` on `drasil-lang` and was very pleased with the feedback. It output a clear report, providing concrete solutions.

Notes:
* I upgraded the project GHC version to 9.4.8 and used Stan v0.1.1.0. The GHC version change is to include a bugfix for my system, completely irrelevant for everyone else, but will show up in the report.
* `stan` and `weeder` work using [HIE](https://www.haskell.org/ghc/blog/20190626-HIEFiles.html) files, which is great, because they will rely on information from GHC directly.
* `stan` does not appear to enjoy lazy data, so I enabled the `StrictData` language extension on the project, otherwise there is a ton more warnings (at least 1 for each data definition, but can also be an extra 1 for each argument in each constructor!). I don't have any issue with this. @JacquesCarette any thoughts on this one in particular?

Unfortunately, GitHub does not allow uploading HTML files in comments. So, here is [stan.txt](https://github.com/JacquesCarette/Drasil/files/14643081/stan.txt), the same HTML-encoded file except in a .txt file extension. Renaming is all you'll need to do :smile:  

Highlights:
* `foldl` use should be avoided for `foldl'` (agreed)
* finds inefficiencies (`nub`)
* warns about partial functions (`head`, `tail`)
* warns about infix operators defined without a fixity
* warns about catch-all pattern match cases (not sure if I like this)

**Can we run this in the CI?** I believe so! I'll have to demo it.

Overall, it looks like a bit of time investment is worth the effort.

**Comment by smiths** [comment]
Thank you @balacij.  Looks good.  I agree that stan (and weeder) seem to be worth the effort.  I guess we still have to confirm with @JacquesCarette about enabling `StrictData`.  @balacij once this is confirmed, can you please create a newcomer issue for fixing our current code base so that it passes the stan checks.

**Comment by JacquesCarette** [comment]
`StrictData` is fine with me. We don't use laziness anywhere.

**Comment by balacij** [comment]
Steps are in #3710.
