### ISSUE TITLE
Drasil Research Group Meeting, Monday, Apr 1, 3:00 pm, ITB/111

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3702]
1. Discussion of [refining little theories version of projectile](https://github.com/smiths/caseStudies/blob/master/CaseStudies/projectile/projectileSRS_RefinedTheories/RefiningTheories/ProjectileLittleTheories.pdf) with documentation knowledge
  - How to combine theory with the documentation of the theory?  Can the documentation be viewed as another kind of theory?
  - How to bring in context information (typical values, problem specific constraints, etc.)?  Can there be a context theory?
  - Where does the rationale go?  Should it be provided for each theory, or only for the final theory?
2. 'Theories': Shift association with IM/DD/TM/GD terms to 'printing' level #3691
3. Tasks and training for summer students

Regrets: ?

Virtual:

**Comment by samm82** [comment]
## My Takeaways
 - the result of theory product is a theory (can be used to combine theories, like going from 1D to 2D, etc.)
 - "grammar-wielding syntactic" attributes exist, meaning that semantic vs. syntactic is a spectrum, not a binary
 - definitions and units should have the same priority as types, since they are semantically meaningful
 - position won't _necessarily_ be twice-differential; this is _truly_ an axiom for this specific use of the concept
 - we may make theories (e.g., position) richer (e.g., adding world) which may add constraints to "attributes" (e.g., `World w, PhysObj w a`)
   - theories may be curried like functions to apply them to specific instances
     - however, position likely fits better as a method of a `PhysObj` class instead of `PhysObj` being a parameter

## More about Units
- will the unit field be the base unit (e.g., m; SI or similar) or could it be more specific (e.g., mm, km, etc.)?
  - if we go the latter route, how would we deal with conversions? (see GlassBR for example)
- I found the Haskell package [units](https://hackage.haskell.org/package/units) and its related package [units-defs](https://hackage.haskell.org/package/units-defs); would this help us out at all?

**Comment by J1aM1ng** [comment]
![IMG_7117](https://github.com/JacquesCarette/Drasil/assets/57659317/97ab8818-063e-4c16-b678-d4284c6f10e0)
FYI: note of Dr. Carette

**Comment by smiths** [comment]
@samm82 for the unit attribute I think we should use the standard SI unit (m, kg, s, etc.).  Having everything in standard units avoids complications with unit conversions.  At the theory level this isn't a problem.  For display purposes, we might have to introduce modifiers and unit conversions. The packages you suggested might help.  They seem like a good starting point to me.

We haven't devoted much extra thought to units because it is viewed as a "solved" problem.  As you pointed out by linking libraries there are people that have already worked on this problem.  We've prioritized working on things that are new.

**Comment by smiths** [comment]
We concluded the meeting so I'll close this issue.  The agenda items we didn't cover have been moved to #3711.
