### ISSUE TITLE
Question about ghcide version

### ISSUE THREAD

**Issue by B-rando1** [JacquesCarette/Drasil#3723]
I noticed that in any Haskell file I open in Drasil, I get this warning:

```
ghcide compiled against GHC 9.4.7 but currently using 9.2.8 
This is unsupported, ghcide must be compiled with the same GHC version as the project.
```
![image](https://github.com/JacquesCarette/Drasil/assets/97637834/b7524cba-5fbc-4c97-bf43-4d1e864678d9)

What can I do to get the versions synced?

**Comment by balacij** [comment]
This reminds me: we should consider recommending users install Haskell tools via [GHCup](https://www.haskell.org/ghcup/), because I _vaguely remember_ the VS Code Haskell Language Server plugin being able to communicate with GHCup to automatically download the correct version of HLS compiled against the project's used GHC version. Do you want to give that a try?

**Comment by B-rando1** [comment]
I'm on Windows, using WSL.  I installed Haskell with GHCup, but I think the VS Code extension installed the HLS (I might be wrong though).  It doesn't seem like it has an option to automatically download the correct version of HLS, though.  Do you think there's something set up wrong with the extension settings?

And just to be clear, the code compiles fine when I run `make`, it's just the editor that says there's a problem.

**Comment by B-rando1** [comment]
Thanks @balacij for coming over and taking a look.  Opening the `Drasil/code` folder instead of the `Drasil` folder seems to have fixed the issue.

**Comment by balacij** [comment]
No problem!

Would you mind adding it as a note somewhere on the document too? We can add GHCup later, that'll take a bit of re-writing, I think.
