### ISSUE TITLE
Adding Support for 1-Indexed Arrays

### ISSUE THREAD

**Issue by B-rando1** [JacquesCarette/Drasil#3746]
Arrays in both Julia and MATLAB are 1-indexed.  We'll need some way to account for this when translating GOOL to these languages.  As far as I can tell, we have to assume that GOOL's arrays are 0-indexed, since the line of GOOL code 
```haskell
varDecDef (var "e" double) (listAccess (valueOf $ var "a"
    (listType double)) (litInt 1))
```
currently translates to the following line of Python code:
```python
e = a[1]
```
which means that in Julia it should translate to
```julia
e = a[2]
```

If we are assuming that GOOL's arrays are 0-indexed, we'll need to convert indices to 1-indexed (by adding or subtracting 1 in various cases) at some point when generating code for these targets.  I thought of various ways that we could do this, but the only feasible way I could find is to assume that all indices in the generated code are 0-indexed, until they are used with the List API, and only then do we convert.  For example, GOOL code producing the Python code
```python
l = ["a", "b", "c"]
i = 2
print(l[i])
```
would translate to the following Julia code:
```julia
l = ["a", "b", "c"]
i = 2
println(l[i + 1])
```
This isn't always the most idiomatic way to do it (e.g. above setting `i = 3` would have been better), but making the conversion at any other point leads to difficulties because we'd have to keep track of whether or not a variable is storing an index, etc.

I've started implementing it this way for Julia, and I'm trying to think how to do it in a way that is general enough that adding new methods to the List API, as well as adding new languages that are 1-indexed, won't require as much care with when to add or subtract `1`.  Here's a design I've thought of so far:
- Add two new functions to the `InternalListFunc` typeclass: `varToIndexFunc :: SValue r -> SValue r` and `indexToVarFunc :: SValue r -> SValue r`, which would add and subtract `1`, respectively, to the index given for 1-indexed targets, and return the index given for 0-indexed targets.
- Call these two functions within some general functions that are either implemented in every target language, or at least most of them.  One way to do this would be to call them on the index given for the functions defined in `LanguagePolymorphic.hs`, such as `ListAccess` in [LanguagePolymorphic.hs](https://github.com/JacquesCarette/Drasil/blob/21ff3588595f34c3135af6e6db538e16d5318767/code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs#L280-L288).

What are your thoughts?  Does this  seem like a good direction, or do we need to think about this some more?

**Comment by JacquesCarette** [comment]
This feels correct, i.e. that GOOL's arrays are implicitly 0-indexed, so that `+1` needs to be added when generating Julia.

Yes, doing it when a number is used as an index is the current best way to handle this (i.e. what you show above). Anything else would require 'too much reasoning'.

What I don't understand is why you need both directions? I was expecting a single `resolveIndexing :: SValue r -> SValue r` function that is either the identity or adds 1. Why would you need to subtract one?

**Comment by B-rando1** [comment]
There are cases where you get an index from the list API instead of giving it, for example the `indexOf` method of the `List` typeclass, which returns the index of the element you're searching for.  In cases like that, you would need to subtract `1`.

**Comment by bmaclach** [comment]
Just to note, in cases where the index is a literal, as in the first code example at the top of this issue, it would be possible to use GOOL's state objects so that `litInt` knows it is in a `listAccess` context and generates a number one higher than its argument in the Julia renderer, rather than actually generating the `+1`. 

It's a small can of worms, though, as you'd then need `listAccess` to know that the index is a literal, and so it should not generate `+1` (which can again be accomplished using the state objects). So I'm not sure if this would be worth it, but I wanted to highlight the possibility.
