### ISSUE TITLE
Drasil Research Group Meeting, Monday July 8, 3pm, ITB/225

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3834]
1. #3835 (@BilalM04 )
2. #3792 (@B-rando1)
3. #3828 (@NoahCardoso)
4. Ideas for reorganizing the Drasil repo now that we have a Drasil Org

Virtual: @JacquesCarette (possibly), @samm82

**Comment by BilalM04** [comment]
## Weekly Update

- Issue #3748: conducted an experiment on the HTML SRS speeds (https://github.com/JacquesCarette/Drasil/issues/3748#issuecomment-2203518150).
  - @JacquesCarette mentioned that the differences between full TeX and current SRS is noticeable.
  - Majority of the time is from scripting (Mathjax) and rendering (?),
- Issue #3830: created a PR that resolves the issue (#3832).
- Issue #3722 
  - Continued working on #3823, implementing the suggestions.
  - Created `makefile` targets to build and launch mdBook server. 
  - Took a deep dive into rendering assets in mdBook. Findings are detailed in #3835.

## Agenda / Blockers

The only blocker for the mdBook project is the rendering of assets. I spent the week looking into various solutions, testing them out, and having productive discussions with @balacij. My findings and work are detailed in #3835. For the meeting, deciding on a concrete solution to proceed with would be ideal.

**Comment by B-rando1** [comment]
## Weekly Update
- #3817 I got a sorting algorithm for `Interleaved` inputs working the way we want it too.  Now that that's working, I have a better idea of what I'll need to do in order to generate interleaved code.  I'm not exactly sure when I'll have time to do this (there's lots to do with Julia/procedural languages), but at least the way is a bit clearer.
- #3809 I finished fixing `listSlice`, and we got the changes merged.
- #3821 I started implementing a distinction between `local` and `global` scoped variables in GOOL.  I got a decent start creating the necessary data structures, but I ran into a weird type error in the C++ renderer, and I haven't been able to get it working.
- The last couple days I've mainly been working on splitting GOOL into components that are OO-only and shared between OO and Procedural languages, as I've documented [here](https://github.com/JacquesCarette/Drasil/discussions/3792#discussioncomment-9962372).  I created a diagram (viewable [here](https://drive.google.com/file/d/19gW8p70-LajaXSgAMJoZtdrW3GHCKhKc/view?usp=drive_link)) to keep track of which typeclasses belong where, and which ones need to be split up in order to separate things correctly.  So far I've successfully split up a group of 5 or so typeclasses with `TypeSym` as their root.  I think I'll have a PR out by today for that.

## Blockers/Agenda
- I think I might need some help with the error I'm getting in #3821.  This probably isn't an agenda item though, as we can probably figure it out over the week.
- We could discuss #3792.  It's going well so far, but it's a large change and I'm sure there's lots of potential missteps.  I would appreciate any guidance I can get.

**Comment by NoahCardoso** [comment]
### Update
- Finished nounPhraseSP #3831. I only fixed the simple example as @balacij mentioned in the pr the more complex example should be done on a case-by-case basis.  
- I started working on adding `Set`s to Drasil. I also started working on adding back `Set`s as constraints #2655 which has taken up most of my time. 

### Blockers
- For #3761 I am waiting to know what should be done about the `Ord` of `eNames'` #3828

**Comment by JacquesCarette** [comment]
I will try hard to attend.

**Comment by smiths** [comment]
We completed this meeting.  All agenda items were discussed.  We don't have a specific plan for reorganizing the Drasil repo, but candidate folders to move elsewhere in the Org include People, Presentations and notes.
