### ISSUE TITLE
Merges to `main` unexpectedly/randomly don't update Wiki

### ISSUE THREAD

**Issue by BilalM04** [JacquesCarette/Drasil#3873]
PR #3823 made some changes to the Wiki files which did not automatically update the actual Wiki when merged.

The [Wiki files in `main`](https://github.com/JacquesCarette/Drasil/blob/main/wiki/New-Workspace-Setup.md) were merged correctly; however, the [actual Wiki](https://github.com/JacquesCarette/Drasil/wiki/New-Workspace-Setup) is unchanged. Looking at GitHub actions, the Wiki workflow did not run for either the pull request (#3823) or when merged in.

**Comment by balacij** [comment]
Hmm, that's odd! I'm not sure why it wouldn't have worked. Since the workflow didn't trigger at all, it seems like the issue has to do with the [`on` section](https://github.com/JacquesCarette/Drasil/blob/c86e1175eb09ac8a4b53f684ba20ad71c7bc6b83/.github/workflows/Wiki.yaml#L2-L8). I wonder if GH was just having issues on the backend? This looks completely fine to me. The PR targeted main and one of the paths changed in the PR was of the form `wiki/X`. Do you see any issues?

**Comment by BilalM04** [comment]
The Wiki workflow worked for #3664 and seems to be working for #3848.

Looking at the commit history, there were [changes made to the `Wiki.yaml`](https://github.com/JacquesCarette/Drasil/commit/82b61a3d5c38eb4f3e54406968613fc5aaf6ec5c) that were pushed to `main` while #3823 was under development. However, I am pretty sure I merged with `main` at some point after that. Other than that, I do not notice any issues in the workflow files themselves.

**Comment by balacij** [comment]
I think something outside our control is happening, but let's leave the ticket open if we find any more issues like this.

**Comment by BilalM04** [comment]
Just thought I'd add an update here. The changes intended by #3823 have now occurred due to the wiki workflow running when #3848 was merged.

**Comment by balacij** [comment]
Thank you, @BilalM04 :smile:

**Comment by balacij** [comment]
I'm fine with closing it :smile:
