### ISSUE TITLE
Drasil Research Group Meeting, 3pm, Tuesday Aug 6, 2024, ITB/225

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3892]
0. Thoughts on Dr. Angela Zavaleta Bernuy
1. Blockers? (@Xinlu-Y)
2. Feedback on #3878, #356 (@NoahCardoso)
3. How to convert vectors and vector operations into GOOL's representation of them (@BilalM04) (fix redefinition of $t_\text{flight}$ to show a scalar multiple of a vector?)
4. #3821, #3904, #3678, #3508 (good for progress on vectors) (@B-rando1)
5. Posters

regrets: @balacij 
virtual: @smiths, @samm82

**Comment by smiths** [comment]
@TRISHI-L, @NoahCardoso, @BilalM04, @B-rando1, please create your weekly summaries as usual.

**Comment by BilalM04** [comment]
## Weekly Summary

- Worked on some issues in the backlog.
  - #3894 
  - #3896 
  - Proposed a solution for #718 
- Delved deeper into vectors in Drasil.
  - There is currently *some* vector support in `drasil-lang`
    - You can declare vectors: [`vec2D`](https://github.com/JacquesCarette/Drasil/blob/3261db372ce2e9ade85942ab08e83ef834a6ed47/code/drasil-lang/lib/Language/Drasil/Expr/Class.hs#L68-L69), [`rowVec`](https://github.com/JacquesCarette/Drasil/blob/3261db372ce2e9ade85942ab08e83ef834a6ed47/code/drasil-lang/lib/Language/Drasil/Expr/Class.hs#L79-L81), and [`columnVec`](https://github.com/JacquesCarette/Drasil/blob/3261db372ce2e9ade85942ab08e83ef834a6ed47/code/drasil-lang/lib/Language/Drasil/Expr/Class.hs#L83-L85).
    - Support for some vector operations as well: [`dim`](https://github.com/JacquesCarette/Drasil/blob/3261db372ce2e9ade85942ab08e83ef834a6ed47/code/drasil-lang/lib/Language/Drasil/Expr/Class.hs#L163-L164), [`norm`](https://github.com/JacquesCarette/Drasil/blob/3261db372ce2e9ade85942ab08e83ef834a6ed47/code/drasil-lang/lib/Language/Drasil/Expr/Class.hs#L166-L167), [`negVec`](https://github.com/JacquesCarette/Drasil/blob/3261db372ce2e9ade85942ab08e83ef834a6ed47/code/drasil-lang/lib/Language/Drasil/Expr/Class.hs#L169-L170), [`cross`, `vScale`, `vAdd`, `vSub`](https://github.com/JacquesCarette/Drasil/blob/3261db372ce2e9ade85942ab08e83ef834a6ed47/code/drasil-lang/lib/Language/Drasil/Expr/Class.hs#L187-L197), and [`dot product`](https://github.com/JacquesCarette/Drasil/blob/3261db372ce2e9ade85942ab08e83ef834a6ed47/code/drasil-lang/lib/Language/Drasil/Expr/Class.hs#L103-L104).
  - There also seems to be some support for vectors in [GOOL](https://github.com/JacquesCarette/Drasil/blob/main/code/drasil-code/test/GOOL/VectorTest.hs), implementing vectors and their operations.
  - As a start, I changed the [calculation of landing time](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/mdBook/book/SecIMs.html#IM:calOfLandingTime) instance model for projectile to use vectors. I changed it to the following: ![image](https://github.com/user-attachments/assets/dfc26e63-1fe7-4ce5-a847-068e7ad7e4c4)
  - My approach was to use the current vector support and follow the propagation of errors in order to find where it is lacking. I ran into problems at [`convExpr`](https://github.com/JacquesCarette/Drasil/blob/3261db372ce2e9ade85942ab08e83ef834a6ed47/code/drasil-code/lib/Language/Drasil/Code/Imperative/Import.hs#L286-L360), which converts `Expr`s to GOOL values. Here, [column vectors](https://github.com/JacquesCarette/Drasil/blob/3261db372ce2e9ade85942ab08e83ef834a6ed47/code/drasil-code/lib/Language/Drasil/Code/Imperative/Import.hs#L356) and [vector operations](https://github.com/JacquesCarette/Drasil/blob/3261db372ce2e9ade85942ab08e83ef834a6ed47/code/drasil-code/lib/Language/Drasil/Code/Imperative/Import.hs#L460-L472) error out.
    - From speaking with @B-rando1, my understanding is that GOOL (somewhat?) supports vectors; however, we are lacking the support for converting vectors to GOOL. 
    - Additionally `convExpr` converts `Expr`s to `SValue`; however, the [vector operations in GOOL](https://github.com/JacquesCarette/Drasil/blob/3261db372ce2e9ade85942ab08e83ef834a6ed47/code/drasil-gool/lib/Drasil/GOOL/InterfaceCommon.hs#L320-L345) expect vectors to be of type `VSThunk`, which I'm not entirely sure what it is, it has something to do with variables. It doesn't seem to be used for anything in GOOL other than vectors. 

## Agenda / Blockers

How to convert vectors and vector operations into GOOL's representation of them.

**Comment by B-rando1** [comment]
### Weekly Summary
- I spent Wednesday and some of Thursday working on #3821.  I made some good progress, but then I found a problem with our current approach.  The solution could affect any of my branches involving the issue, so I can't make progress until we decide how to solve it.
  - The problem is that it's not enough for `drasil-code` to know what scope it's currently generating when it uses a variable - it also needs to know what scope it was in when it declared that variable.  My thinking is that we could either fix this by adding that functionality in `drasil-code`, or there might be a better fix that would require reworking how `Scope` is used in `drasil-gool`.
- I opened #3904, and did some digging to see what that will involve.  At this point it seems like structs themselves shouldn't be too hard to implement, but integrating them properly into the existing types of `drasil-gool` (and later `drasil-code`) will be a challenge.
- While I waited to hear back on a few issues, I looked through the issue tracker for GOOL-related issues.
  - I started working on a fix for #3678.
  - #3508 also caught my eye.  It seems pretty straightforward, so I'll keep it in mind if I need something to do next week.

**Comment by Xinlu-Y** [comment]
### Weekly Summary

- Worked on transitioning from `Lens` to `Getter` for certain fields in Haskell code && opened a PR (#3907 )
  -  This included making the `HasUID` lens read-only. 
  - Addressed type inference issues related to the Contravariant constraint in `uid` lens definitions, particularly in `DataDefinition.hs` and `ModelKinds.hs`.
-  Worked on adding citation to original (manual) works && opened a PR (#3898 )
### Agenda
- Resolves #702 
  - At present, there are unwanted repetitive prefixes if we add "Figure: " manually. 
  - The challenge is to avoid this conflict by ensuring that the prefix is added only in the HTML version and not in the LaTeX version.
  - Next week, I will investigate in more depth how both the HTML and LaTeX renderers work, and how they differ.
- During the code modifications, I focused on enhancing my understanding of Haskell syntax. Given my current level of familiarity, there may be some issues in the code. I appreciate and welcome any feedback to improve the quality of my contributions.

**Comment by NoahCardoso** [comment]
### Weekly Summary
- I spent most of the week finishing #3878 which set support in Drasil such as
  - Added Sets as a constraint for chunks
  - Added Set operations in drasil.lang (Add, Remove, Union and Contains)
  - Added Sets as a Space
  - Updated physical and software constraints
  - Added Sets in expr and set constructor
  - Changed nomThick back to contained input in glassbr
  - Proper rendering of Sets
  - Added the contains and in operation to GOOL
  - Added litSet, printSet and other Set support in GOOL
  - Added Sets in all generated langs other than Julia
 - Added STAN to makefile #3893
 - Added Weeder to makefile #3897
 - changed ghc version of Drasil from 9.2.8 -> 9.6.6
 
### Blockers
- Waiting on feedback on #3878 so it can get merged and I can start working on #356

**Comment by JacquesCarette** [comment]
I may or may not be able to join. I'm at a conference in Montreal next week, and I don't quite know all the details yet. I've added this to my schedule, and we'll see.

**Comment by smiths** [comment]
@BilalM04, @B-rando1, @NoahCardoso, @Xinlu-Y, @samm82, Sam and I are going to be virtual tomorrow.  @JacquesCarette may also join the meeting.  You can get Mary to let you into ITB/225, or just stay in your regular office.  I think we should have everyone participate virtually tomorrow (Tuesday) for the meeting.

**Comment by smiths** [comment]
All agenda items were covered.
