### ISSUE TITLE
Drasil Research Group Meeting, 3pm, Monday Aug 19, 2024, ITB/225

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#3929]
(Not quite sure who is still around!) For those who will be, please add your weekly summary if you will be @B-rando1 @Xinlu-Y @NoahCardoso @BilalM04 @balacij . I know @smiths is on vacation. I will be there in person.

Virtual: @samm82

**Comment by Xinlu-Y** [comment]
### Weekly Summary
- Worked on #3916 .
  - The `printLO` function was adjusted to utilize the new approach for handling captions. Specifically, a check `checkSpec` was introduced to determine if the caption is empty. If it is, `Nothing` is passed to the `makeFigure` function, preventing the "Figure: " prefix from being added to an empty caption.
  - However, the current implementation still manages the presence or absence of a caption (using `Maybe Caption`) at a relatively low level in the code. Based on the feedback, it's recommended that the core data structure for a `Figure` should inherently know whether it has a caption, rather than deferring this decision to later stages in the code generation process. To address this, I plan to introduce a new data type that will distinguish between figures with and without captions.
- Continuing the work on #1876.
  - I have created a new data type to represent different types of literal values. The next step is to identify other areas where optimizations can be applied to additional types of literal values.
  - I will expand the optimization strategies to other literal types stored in the `litVal`. This includes implementing constant folding and similar optimizations for boolean values, strings, and potentially other literal types like floating-point numbers and characters.

**Comment by B-rando1** [comment]
### Weekly Summary
- For #3821, I implemented a fix for the problems with the current solution we were working on (#3899).
  - This fix isn't perfect as it leads to way too many `global` declarations, but it is a step in the right direction from what we currently have.
- For #3871, I performed another analysis in [this](https://github.com/JacquesCarette/Drasil/discussions/3871#discussioncomment-10352019) comment.  My conclusion is that there are no 'obvious' next steps to remove code duplication.  The issue seems to be that when generating GOOL and GProc code, at almost every turn there is potential for a GOOL- or GProc-specific feature to show up.  My current thinking is that we need to introduce a set of  typeclasses in `drasil-code` so that we can have better polymorphism over GOOL and GProc.
- For #3918, I read some of Dong's report to better understand how ODE solvers work in Drasil.  After that, I learned how Julia's ODE solver library works, and hand-coded an implementation of swhsnopcm ([#251](https://github.com/smiths/caseStudies/pull/251)).  I might have more questions about how to make Drasil aware of the library, but we should be able to do that on the issue tracker.
### Agenda/Blockers
- I would appreciate feedback on #3899.
- If we have time, we could discuss #3871.  I'm not sure if we'll have time to start making the changes now, but it would be helpful to better understand the problem and potential solutions.

**Comment by BilalM04** [comment]
## Weekly Summary

- Created a summary of the current state of vectors in Drasil and my initial approach.
  -  https://github.com/JacquesCarette/Drasil/discussions/3923#discussion-7031363
  - **Very brief summary:** there is some vector support in `drasil-lang` and GOOL; however, converting vectors and vector operations to GOOL is lacking.
- Investigated how an instance model gets converted to a calculation function and summarized the limitations related to vector support.
  - https://github.com/JacquesCarette/Drasil/discussions/3923#discussioncomment-10338475
  - **Very brief summary:** current implementation does not support multi-line operations, which are required for vectors.
- Generated code for declaring a simple column vector (no operations).
  - https://github.com/JacquesCarette/Drasil/discussions/3923#discussioncomment-10338742 
- Continued working on #3910 
- Completed and submitted the research poster 😀
  - #3920

**Comment by NoahCardoso** [comment]
### Weekly Summary
- Created update on STAN and Weeder
  - Looked more into strict data
  - Analyzed Weeder's suggestions
  - Fixed issue stan was having after updating the ghc version #3928
- Completed research poster #3925 
- Completed #3919, waiting on sets to get merged before making pr request
- Looked into #373 
- Completed feedback on Sets

### Blockers
- Waiting on #3878 Feedback

**Comment by samm82** [comment]
If it's a hassle for me to be virtual, just go ahead without me! I've been doing such different stuff (i.e., focused on software testing) that I'll have much less to contribute - if it's straightforward though, I'm happy to attend and see our students off! 🫡
