### ISSUE TITLE
Best way to implement external libraries for codegen?

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/Drasil#394]
@JacquesCarette I've been thinking about the best way to implement external libraries for code generation.  There seems to be 2 choices here:

1.  As an "External Library" data type that encodes a generic interface for a particular library type and given a language, converts it into `AbstractCode` that uses the existing GOOL AST.  This will mean generating a different language-specific `AbstractCode` for each language.  But we get the benefit of not having to modify the GOOL AST or the renderers every time we add a new library type or modify/extend existing libraries.

2.  Adding external library syntax directly into the GOOL AST, keeping the `AbstractCode` the same for all languages.  It seems like this approach will be much more tedious to modify and maintain.

I'm thinking option 1, but this will mean the GOOL `AbstractCode` is no longer "generic" and might add a lot of overhead later on when generating large programs in multiple languages.

**Comment by JacquesCarette** [comment]
I am thinking neither of these options!

External libraries should be treated like pure APIs - like a Foreign Function Interface.  See https://wiki.haskell.org/Foreign_Function_Interface and https://wiki.haskell.org/GHC/Using_the_FFI and https://wiki.haskell.org/FFI_complete_examples.

The [bindings-DSL](http://hackage.haskell.org/package/bindings-DSL-1.0.22) library is worth a look too.

What you need are two levels:
1. declaration of available libraries (collections of functions), with signatures in GOOL
2. for each language, an optional definition of what the library call "really is".  There could be multiple definitions for the same library (i.e. choices of ODE library, for example).

Eventually the second level may need information that will be needed at link time.  So this is likely to force you to generate a specific Makefile, on the fly, for each configuration of each project.  And when there are choices, this becomes an "implementation choice" as well.

**Comment by JacquesCarette** [comment]
@palmerst I notice now that our conversations about this were not noted down. Can you please jot something here? That will be the easiest way to remember.  [Or add a link here to where it is documented.]

**Comment by bmaclach** [comment]
@JacquesCarette Do you recall anything from those conversations from a year and a half ago?

I looked at the FFI-related links above and admit to being very confused by it all. I understand the general purpose of the FFI, but I found it difficult to follow their tutorials/examples. It didn't help that I couldn't grasp the connection to our own issues. Was your suggestion to actually use the FFI, or just that our solution will likely have similarities to the FFI?

In terms of the 2 levels you describe above, the immediate connection I made to our finally tagless GOOL was that level 1 corresponds to our Symantic typeclasses and level 2 to their instances, though I'm not confident that I'm on the right track with that. In particular, that connection doesn't fit with the idea of having multiple definitions of the same library in the same language.

**Comment by JacquesCarette** [comment]
I do have some memories of this. I think I recall the latter: our solution will likely have similarities with FFI (declaring them, setting them up, calling them, etc).

The two levels here are independent of the underlying implementation methodology. What we need are features of GOOL that allow to declare available libraries, and then actual definitions.  Yes, you are completely right that these levels closely correspond to typeclass/instance.

**Comment by bmaclach** [comment]
This issue came up at our last meeting and I've done some more thinking about it. What follows is a summary of what I see as the current options for moving forward with this. For simplicity, I'll focus on ODE solvers, though the ideas should apply to any external library.

I see there being 2 choices that need to be made when using an external library:
1. Which algorithm/method to use?
2. Which library to use?

## Which algorithm/method to use?
I see this variation being represented by different functions in GOOL. So for ODE solving, GOOL might offer a `odeEuler` function for solving an ODE using Euler's method and a `odeRungeKutta` method for solving an ODE using the Runge-Kutta method (and likewise for other methods).

## Which library to use?
At the last meeting, 3 options for handling this variation came up.

__Option 1: Same libraries for all languages__
The idea here was that we would only offer libraries that were compatible with all of the languages we render. All of the languages we currently target have foreign function interfaces to C, so ODE-solving libraries in C would be eligible. The benefit to this approach is that it fits well with the idea of GOOL as a generic language; one line of GOOL could generate valid code in many different languages. The downsides are that this severely limits our choices of libraries and updating each renderer in GOOL to be able to generate code that interfaces with C could get rather complicated and likely require heavy extensions to GOOL.

__Option 2: Fixed library for each language__
The idea here is that we would not offer choices of libraries beyond the choice of which language to use. So we would have one library for Python, one for Java, etc. The benefit here is that we could again have the same line of GOOL render valid code for multiple languages. The downside is that the user can't decide which library to use.

__Option 3: Choice of libraries for each language__
This was the option that @smiths seemed to expect we would do. My worry with this was that each language offers a different choice between libraries, which goes against the idea of GOOL as language-generic. But thinking it through, I have a plan for how we could do this. We could define an enumerated type for all of the different libraries we offer for all languages:
```
data ODELibrary = SciPy | ODEint | Apache | ...
```
The GOOL functions for ODE solving would take an `ODELibrary` as a parameter. In each renderer, the case where the chosen library does not match the language would result in an error. So for example in the python renderer we would have something like:
```
odeEuler SciPy = ... -- Some valid implementation here
odeEuler _ = error "Chosen ODE library is not compatible with Python. Please change ODE library choice
  to one of the following: <List of valid libraries for Python>"
```
The benefit to this option is that the user of Drasil could choose which library they want to use. The downside is that we would only be able to generate one language at a time (which I expect will be the "normal" use case for Drasil anyway), and changing the language would result in an error until the library choice is also changed (with good error messages, the impact of this would be small). I don't see how we could avoid those downsides while also giving users language-specific choices of library.

**Comment by bmaclach** [comment]
@JacquesCarette Just to make sure I understand: Is option 4 basically the same as option 3 except that the user passes an ordered set of choices instead of just one?

**Comment by smiths** [comment]
I like where this is going.  I prefer Options 3 and 4 to the other options.  However, the case where a library does not exist for a given language might be more common than the discussion suggests.  Most ODE solver libraries are going to be written in ONE language.  They aren't going to provide different implementations in different languages.  I think there are some libraries in both C and FORTRAN, like Netlib, but in my experience most scientific libraries are tied to one language choice.  (There are cases, like for Python 2 and 3, where a library is maintained in two versions of the same language.)  This makes me think that Option 3 is what we'll end up when we try Option 4.

**Comment by JacquesCarette** [comment]
@bmaclach Yes, I think so.
@smiths Sure, but I want to, at some level, decouple language choice and external library choice. For things other than ODE solvers, there might be a lot more cross-language things, and we might as well start thinking about this broadly.

**Comment by smiths** [comment]
Sounds good @JacquesCarette.  I'm all for the more general solution, since the case where there is only one implementation of a given library in one language is a subset of your proposal.

**Comment by bmaclach** [comment]
As a first step for this, I want to write manual versions of NoPCM in each of our target languages, so I can learn and compare the ODE solvers for each language. Should I do that in the case studies repo instead of this one (we already have a python implementation in the case studies repo)? @smiths @JacquesCarette

**Comment by JacquesCarette** [comment]
I think the hand-written code does belong in case studies more than in here.

**Comment by smiths** [comment]
I agree with @JacquesCarette.

**Comment by bmaclach** [comment]
I've manually implemented NoPCM in each of our target languages in the caseStudies repo. Based on this, I don't think we will need to do multiple passes, at least not for the simple ODE case like NoPCM's. 

In general, a call to an ODE solver requires:
- some code where the call is made
- sometimes a class or function needs to be added to the program based on the ODE. 

The first part is easy. The second part is what makes ODEs tricky, but since these additional functions/classes can be added at the program-level, we can accomplish this once we've restructured GOOL to use the `State` monad in its underlying types (#1880 ). When an ODE is called, we just store some information about the ODE in the `State`, and then we can add functionality to GOOL's `prog` function to read the `State` and generate any additional classes/functions needed. 

And the choice of which numerical method to use is typically handled by just one line in the generated code, so that should be easy to implement, whether by offering different functions in GOOL for the different methods (`odeEuler`, `odeRungeKutta`, etc.) or by having a generic `ode` function that gets passed a choice for which method to use.

**Comment by JacquesCarette** [comment]
Sounds good!

**Comment by smiths** [comment]
Yes, @bmaclach, this does sound good.  I'm not sure which I prefer with respect to having multiple methods named by the different methods (`odeEuler` etc.) versus on `ode` function with the method passed as a parameter.  I know that Matlab has separate ode solver methods for different families of algorithms (like the a family of Runge Kutta methods).  We might think of an option like that as well.  @bmaclach, what decision do most of the ode solver libraries  use?

What I'm really looking forward to is when the selection of algorithm is automated too.  This is down the road, but I can imagine a day when the algorithm is selected based on the user's nonfunctional requirements, together with some automated benchmark testing.

**Comment by bmaclach** [comment]
Of the 4 ODE solvers I used:
- 2 had the method passed as a parameter (Python and C++)
- 2 had different classes for each method type, so the user must create an object of the right class based on which method they want to use (Java and C#).

The solver for C we've used in the past has the method passed as a parameter, and as you say Matlab has different methods for each numerical method. So there doesn't seem to be a standard here, between the two options.

**Comment by smiths** [comment]
Thank you for the additional information @bmaclach.  You quantified data matches my guess.  I can't, at least off the top of my head, think if a principle that will guide us toward one approach over the other.  I'm almost ready to consider this an arbitrary decision.

We can decide for sure how to handle this once you get to it.  Currently, I think I would prefer the ode solver have one interface, with the method passed as a parameter.  It feels like it would be easier to modify which specific algorithm is being used.  Also, changing the algorithm dynamically seems a bit cleaner with the "method as a parameter" option.

**Comment by JacquesCarette** [comment]
@bmaclach I'm going to assign this to you - I think this is done.

**Comment by bmaclach** [comment]
A lot of this is done on master, but the actual generation of code that interfaces with external libraries is only on the noPCMODE branch, which is dependent on #2014 before a PR can be opened.
