### ISSUE TITLE
Glass-BR Case Issues

### ISSUE THREAD

**Issue by deviprasad135** [JacquesCarette/Drasil#420]
Hello @szymczdm ,
I have couple of problems in this case, please help me in resolving them.

1) In manual version the physical system figure is placed in section 6.1.2  and in stable version it is placed in section 6.2.1. So I am confused. which is better?

2) In section 6.2 and 6.2.1 I think the assumptions mentioned in manual version are better than the one mentioned in stable version. Which one should I consider?

3)  the position of Instance Models in manual and stable versions is different . Will the position matters? If it matters which is better?

4) In section 6.2.5 for data definition Minimum Thickness from Nominal Thickness and data definition Glass Type Factor, I don't know which is better. Which is better stable or manual?

5) In section 9, I think the Traceability matrices and graphs which are mentioned in Manual version is better than stable version. Which one should I consider?

**Comment by smiths** [comment]
@deviprasad135, with respect to your first point, both documents put the reference to the figure and the code for compiling the figure, in the same place.  The generated version has the code in different locations because the documents are different and that was the "best" location for each document, according to LaTeX.  The size of the images is also different (I believe, but I haven't verified).  

Item 1 in your list isn't something that we would modify in the original tex file, or in the stable version.  From the point of view of this exercise, the two examples are the same.

**Comment by szymczdm** [comment]
1) There's a size issue with the figure. We want to set the width in the stable version, so the manual version does not need to be changed.

2) Intro to the assumptions with the sections references from Stable is better. Assumption A4 is better in stable than in the manual version. Also, the lack of IM references in stable is bad, but it is a known issue related to referencing (so, manual is better, no change yet required there).

3) Manual should be updated so the sections are in the same order as the template.

4) Stable is better than manual for "Actual Thickness". For Glass Type Factor, we can return to it if it becomes an issue, but we've agreed it seems fine. The only change necessary is that stable's GTF description will need to be updated to include the definitions of AN, FT, HS.

5) Leave it as is, but stable will eventually need to be updated.

Manual version: Figure 5 caption is incorrect, should say traceability graph instead of matrix. Also, need to include Section 10: Values of Auxiliary Constants, and the "characteristics of intended reader" section. For Section 10, that will involve removing Table 3 from the Data Constraints section in Manual.

Section 4.2 stable is better, but conceptually they are the same.

Section 5.1 & 5.2: Update Manual.

Stable version needs to have LDF as a data definition instead of an auxiliary constant.

Update Manual to use SI Units.

**Comment by smiths** [comment]
Great summary @szymczdm.  Your notes match what I recorded in my notebook.  @deviprasad135, when you address the changes in the manual version that @szymczdm has listed, please add a comment below, including the commit hash that addressed the issue.  As we discussed, going forward, we should have a separate issue for each difference between the manual and stable versions.  Don't worry about creating too many issues.  😄

**Comment by deviprasad135** [comment]
Modified according to the comments mentioned above.

**Comment by smiths** [comment]
Hello Devi.  Please give a pointer to the commit where the modifications have been made.

**Comment by deviprasad135** [comment]
Should I mention the commit number?

**Comment by smiths** [comment]
Yes.

**Comment by deviprasad135** [comment]
Commit 3a5d55f

**Comment by deviprasad135** [comment]
commit 3a5d55f

**Comment by smiths** [comment]
Is the commit in the case studies repo?  That would make sense, but you haven't given enough information for a reader to track it down.  It seems like you are indicating the commit is in this repo.  If the commit is in the case studies repo,  you should go to the web-page for your commit, copy the url, and paste it here.

**Comment by deviprasad135** [comment]
The url of the commit is  https://github.com/smiths/caseStudies/commit/3a5d55fd74739dd95652b5babddcbf5b57faad5f

**Comment by smiths** [comment]
Thank you @deviprasad135.  Unfortunately, the commit shows everything deleted and then everything added back in, with your edits in the second version.  I don't know what tool you used, but it is better if the diff provides helpful information like where the changes were made.  It would time consuming to check the edits, so I'll assume that you made them correctly.  😄

**Comment by deviprasad135** [comment]
I am sorry about that @smiths. Generally what tool do you use?

**Comment by smiths** [comment]
I use an emacs editor (Aquamacs).  You don't need to use emacs, but maybe you should try a different editor?

**Comment by deviprasad135** [comment]
I am using TeXworks.

**Comment by szymczdm** [comment]
@smiths I checked the log on my computer and did a diff between revisions (it makes it clear which sections have changed, I'm not sure why github didn't do the same).

@deviprasad135 , how did you add the file to the repo? Did you commit/push from terminal or through a tool? Or did you upload via the github web interface?

**Comment by deviprasad135** [comment]
@szymczdm I have uploaded via the github web interface.

**Comment by szymczdm** [comment]
Ah, I'm pretty sure that's why we couldn't see the diff. In the future you should use git from the terminal/command line or use a tool (such as TortoiseGit if you're on Windows, as it integrates into the right-click menu).

**Comment by deviprasad135** [comment]
Ok.

**Comment by smiths** [comment]
@szymczdm, thank you for getting to the bottom of this.  Using diff directly is a good idea, but it is more convenient to be able to see the diff directly in GitLab.

**Comment by smiths** [comment]
Yes, this issue can be closed.  Nice to have one less issue.  :smile:
