### ISSUE TITLE
Provide Ability in Documentation Language to Change Appearance of Table of Units

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#426]
The documentation language should allow the document designer to select the format of tables that matches their preferred style.  Different options can be seen by comparing the table of units for the NoPCM example, in the manual version versus the stable version.

Manual version

![units-manual](https://user-images.githubusercontent.com/1422000/32627768-a2a4862c-c561-11e7-8572-7e8fc2e193a5.png)

Stable version

![units-stable](https://user-images.githubusercontent.com/1422000/32627772-a7d8844a-c561-11e7-9fb3-bdc1302bec1f.png)

**Comment by samm82** [comment]
The default now is having a separate "SI Name" column, but I created the following functions:

https://github.com/JacquesCarette/Drasil/blob/a183a747693a1f5707f2dd695cd6a01ca414d442/code/drasil-docLang/Drasil/DocumentLanguage.hs#L122-L125

so that using `tunit'` (passing in the default `[TUIntro]` from `-docLang`) outputs (this example is from Projectile):

![image](https://user-images.githubusercontent.com/35857611/62078233-215abf80-b21a-11e9-8062-3a2ef0ba7932.png)

Should there be an option to be able to not have the "SI Name" column but still use the default `[TUIntro]` (without passing in the default `[TUIntro]` and just using it internally), or this is OK? @smiths

**Comment by JacquesCarette** [comment]
The extra functions are nice. An option to have less information displayed is good too, for the people who prefer conciseness.
