### ISSUE TITLE
Code generation not implemented in the C++, C#, Java renderers

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/Drasil#450]
Re-opened milestone 0.3.1 as the code generation for ode solving is only working for Python right now.  Need to complete the other renderers.

**Comment by bmaclach** [comment]
I can't find any working code generation for ode solving, for python or otherwise, even going back to commits from when this issue was opened. Do you know of something I might be missing @JacquesCarette @smiths?

**Comment by smiths** [comment]
Until I read the text by @palmerst, I would have said we never had the code generation for the ODE solver working.  I don't know where the code would be, but I do know that we weren't aiming for generating code to directly solve an ODE.  We were aiming for code to interface with existing ODE solvers.  There are Python ODE solvers and we were just aiming to generate the code to interface with the existing solver.  We would have been targeting SWHS (and by association noPCM), since that is example that has an ODE that needs solving.

**Comment by JacquesCarette** [comment]
If anywhere, I would have guess under `GOOLCodeGen`. I took a look to see if it might have been in a stale branch - but no, those are all gone.

**Comment by JacquesCarette** [comment]
Does it make sense @bmaclach to keep this issue open, or is this essentially done?

**Comment by bmaclach** [comment]
It is very close to done, but on the noPCMODE branch, which is still dependent on #2014 before a PR can be opened.

**Comment by JacquesCarette** [comment]
Right, I'll try to get to that soon.  Review of writing first.

**Comment by bmaclach** [comment]
As of #2114, code generation for ODE solving works in all languages. Closing.
