### ISSUE TITLE
SWHS - Volume of PCM software constraint

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#451]
Stable contains the following non-sensical constraint:
Physical: 0 < V_P < V_{tank}
Software: V_P >= V_{tank}

so the software constraint and the physical constraint have no overlap.

**Comment by smiths** [comment]
These constraints do not match the information in the original case study (https://github.com/smiths/swhs/blob/master/SRS/PCM_SRS.pdf page 23).  This is another example of a translation error from "manual" to Drasil code.  The Drasil physical constraint matches the case study, but the Drasil software constraint was originally:

V_P >= MINFRACT*V_{tank}, where MINFRACT was set to 10^{-6} in the original case study.  MINFRACT is a symbolic constant in Table 2 (Specification Parameter Values).  To avoid the problem you noticed, we should constrain MINFRACT to be less than 1.

**Comment by JacquesCarette** [comment]
Right - so you've "fixed" the part that needed your expertise to fix. Now there is an issue in the Drasil version of SWHS that should also be fixed.  Have we sort-of assigned some of the projects to our M.Eng. students, so that I could re-assign this?

**Comment by smiths** [comment]
@halonazhao, has been working with the SWHS example; therefore, I will reassign this issue to her.  Yuzhi, please modify the Drasil code for the SWHS example to match the case study example for the V_P constraint.  If you have any questions about the constraint, please ask me.  For questions about the changes to the Drasil code, please ask @szymczdm.

**Comment by halonazhao** [comment]
Hello @szymczdm 
I just updated the version to fix this issue https://github.com/JacquesCarette/Drasil/commit/53f705bc09770d78c1684546d467f85886ea624e. The tex file and html file work. But still there are two ignored errors. I don't know what happened cause there is no detailed information. Those two are not the same errors from the Nopcm case because I commented the SSD section out in Nopcm. Can you please take a look?

**Comment by halonazhao** [comment]
@smiths Could you give me a specific definition, unit and value for variable `minfract`? In manual version now, there is no statement for this variable any more. I guess we put `minfract` in `Values of Auxiliary Constants` table? Since you mentioned that this value should be less than 1 , which is a range, but in `Values of Auxiliary Constants` table, every constant has a specific value. Is that ok I directly put 10^-6 as you ever mentioned?

Thanks!

**Comment by smiths** [comment]
MINFRACT is in the manual (case study) version of SWHS.  Maybe your search is case sensitive?  MINFRACT is a constant, so the typographic convention is used where it is displayed in ALL_CAPS.  As you said, MINFRACT is in the table of Auxiliary Constants and has a value of 1e-6.  MINFRACT is unitless.  In case it isn't clear, MINFRACT is the minimum fraction of the volume of the PCM to the volume of the tank.  Dividing units of volume by  units of volume means that MINFRACT is unitless.

**Comment by halonazhao** [comment]
Issue has been solved in e9a0fffe0913268fd194de8e4b8858e7761898a9
