### ISSUE TITLE
Fix stable changes

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#452]
I've overwritten the stable versions with their previously generated output to make testing changes easier. Now the travis CI will complain if ANY example is produces a different output.

This should be reverted in the future. The commit where things were changed is tagged "stable-break" (commit cc955d04338a4ce468aaae2ec7aa0483df152107). The previous commit (with stable unbroken) was b568b26f21b5b8a524f418de353b7d7f95c10a8a.

**Comment by JacquesCarette** [comment]
But that old commit is probably so old that many things have (correctly!) changed since, making comparisons increasingly difficult as time goes on.

It would be much better to identify the underlying bugs that cause "stable-break" to be incorrect and file them as issues. They could be cross-referenced to here as well.

**Comment by szymczdm** [comment]
#397 is one of them (mostly? due to indexing). I'll double check if other issues have been created and if not, I'll add them.

**Comment by JacquesCarette** [comment]
As expected, the divergence got too big.  Closing this one, as people are looking at the paper version now anyways.
