### ISSUE TITLE
fix `inputHack` in SSP/IMods

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#467]
Better than the hack that was there before... but it's still a hack.

**Comment by balacij** [comment]
I'm not quite sure what our closing criteria is. However, we don't appear to have `inputHack` anywhere in our codebase and considering we don't generate code for SSP, I think that whatever this issue was about will come up again when we bring SSP to up to speed and generate code for it. As such, I think we can close this ticket for now.

**Comment by smiths** [comment]
I agree with closing this issue.  Once we have vectors, hopefully we can get SSP to generate code.
