### ISSUE TITLE
Rendering multicharacter symbols in LaTeX

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#468]
For symbols that consist of multiple characters, like min, max, MINFRACT, etc, when they are rendered in LaTeX equations they would look better in an \mbox.  Rather than LaTeX interpreting min as m times i times n, a \mbox{min} would achieve a more natural spacing.

**Comment by JacquesCarette** [comment]
I thought that if you used `Atomic`, they would get thus rendered (well, not with an mbox, but with mathsf or similar). Perhaps some of these are hacked-in rather than using the correct symbol combinators?

**Comment by smiths** [comment]
We discussed this further in the "all hands meeting" on March 14.  GlassBR has several examples of equations that look odd, for instance LR = NFR GTF LSF.  This would look better with a multiplication symbol.  Maybe we can detect cases like this an automatically add the symbol when rendering?  This isn't a high priority, but something to keep in mind for the future.

**Comment by JacquesCarette** [comment]
This would be quite hard to achieve, at least not without a clear way of understanding what is the root cause of the oddness.  Having multiple multiplication symbols is not hard.  It is the decision criteria to use one versus another which is.

**Comment by smiths** [comment]
Yes, we talked about this a bit at the start of the meeting.  We thought that with some thought we could come up with some rules for when explicit multiplication symbols would look nice.  After all, human being have some implicit rules when they change the formatting of the display of an equation.  This isn't a high priority, but it might be a little project for a future student to tackle.  A simple rule might be that multi-character symbols multiplied together need an explicit multiplication symbol.

**Comment by samm82** [comment]
Related to #1639

**Comment by JacquesCarette** [comment]
Is this still needed?

**Comment by smiths** [comment]
Yes, this is still needed.  I had a quick look at the LaTeX code and some of the equations are spaced very oddly.  I'll attach the example of is_safeProb.  It looks like `is - safeProb`, with LaTeX implicitly multiplying all the symbols.

![is_safeProb](https://user-images.githubusercontent.com/1422000/83712573-115afb80-a5f4-11ea-8c74-8b43e9c33e2c.png)

The solution might just be to use `Atomic` properly?  Not all of the symbols look wrong in the documents.

**Comment by JacquesCarette** [comment]
Yes, I think `Atomic` is the solution.

**Comment by balacij** [comment]
Ah, I think we've given this a small attempt in #2865; 
![image](https://user-images.githubusercontent.com/1627302/144528288-cd1e4bc5-20e6-4bae-97ae-d360b861527a.png)

However, some things are still problematic:
![image](https://user-images.githubusercontent.com/1627302/144528347-071fdcac-1c7a-49d8-9ce1-d0a6e62bb22f.png)

(both are examples from GlassBR)

**Comment by JacquesCarette** [comment]
Definitely still a problem! What is the generated LaTeX for that?

**Comment by balacij** [comment]
For `isSafeLoad = capacity > Load`, we have:
https://github.com/JacquesCarette/Drasil/blob/ad1e157f9ce96046e74787aaf31cb4e0726fe237/code/stable/glassbr/SRS/HTML/GlassBR_SRS.html#L938-L944

For `LR = NFLGTFLSF`, we have:
https://github.com/JacquesCarette/Drasil/blob/ad1e157f9ce96046e74787aaf31cb4e0726fe237/code/stable/glassbr/SRS/HTML/GlassBR_SRS.html#L1894-L1897

It's also weird that the generated HTML here is different between them. They look like they _should_ use the same constructors and have the same code-styled output, and yet they're not.

**Comment by JacquesCarette** [comment]
I think that MathJax wants `\[` for inline math, whereas "standard latex" now prefer `\begin{displaymath}` (over `$`). I think it's ok, and this is controlled via some options that are passed in.

Is there still a problem with `>`? I don't think so?

Anyways, implicit multiplication is definitely a problem. At the very least, we should hand-insert some space (I tend to use `\ `, i.e. backslash-space in my own latex. Although we might want to use `\thinspace` instead as a first experiment. That will definitely be better. We might still need to explore using an explicit multiplication symbol.

**Comment by BilalM04** [comment]
Currently the multiplication operator in the TeX printer is defined as:

https://github.com/JacquesCarette/Drasil/blob/88506c869bc96b81840eafabc69947d81ab50890/code/drasil-printers/lib/Language/Drasil/TeX/Print.hs#L169

The above code inserts a blank space in the TeX code between items being multiplied. When compiled and rendered, the PDF does not have any space between the items being multiplied.

---

The multiplication operator in the HTML printer is defined as:

https://github.com/JacquesCarette/Drasil/blob/88506c869bc96b81840eafabc69947d81ab50890/code/drasil-printers/lib/Language/Drasil/HTML/Print.hs#L233

`&#8239` is a [narrow no-break space](https://www.codetable.net/decimal/8239). The HTML SRS uses HTML syntax for simple expressions, and TeX for the more complicated ones. 

---

The issue here arises when multi-character symbols are being multiplied. Since the `Mul` operator is rendered without a space, it is difficult to distinguish what exactly is being multiplied when there are multi-character symbols. On the side of `drasil-printers`, it is not feasible to come up with rules at the time of rendering as it is very difficult to know whether we are multiplying single character or multicharacter symbols with the current structure, as @JacquesCarette mentioned in https://github.com/JacquesCarette/Drasil/issues/468#issuecomment-373222281.

One possible quick fix solution is rendering the `Mul` operator as a thin space (`\,`). Although this solves the issue for multi-character symbols, it also inserts a thin space between single-character symbols being multiplied. I'm not sure if that is something we want. Here is examples of how it would render:

1. Example with single-character symbols. ([Original](https://jacquescarette.github.io/Drasil/examples/glassbr/SRS/HTML/GlassBR_SRS.html#IM:dimlessLoad))
  ![image](https://github.com/user-attachments/assets/434226bc-1c1e-4e58-a526-2a6f78ead6f3)
2. Example with multi-character symbols. ([Original](https://jacquescarette.github.io/Drasil/examples/glassbr/SRS/HTML/GlassBR_SRS.html#IM:calofCapacity))
  ![image](https://github.com/user-attachments/assets/6c21e5b7-b20a-438b-96c7-2c94138238b1)

This issue is more complicated than it appears, an exact solution does not come to my mind. @balacij what do you think?

**Comment by JacquesCarette** [comment]
The original is "too tight". I think the solution of using `\,` seems quite reasonable.

**Comment by smiths** [comment]
I agree with @JacquesCarette.  This is a nice practical fix @BilalM04.  The equation for LR in GlassBR has bothered me for years.  It looks much better with your fix!
