### ISSUE TITLE
Stable doesn't match Manual Version

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#483]
In manual version of SWHS case, the 4.2.6 Data Constraints section keeps "*, +, #, **" to mark different situations, but in stable, these information is missing, such as some constraints in the table V_p, A_c and so on. Do we still have to keep these information?

Manual version link: https://github.com/smiths/caseStudies/blob/master/CaseStudies/swpcm/Documentation/SRS/PCM_SRS.pdf
@szymczdm @smiths

**Comment by smiths** [comment]
@halonazhao why do you think that the information in the manual version isn't relevant?  If we delete it, then it is gone forever.  The constraints are not obvious and without the footnote information future readers will not know where the constraints came from.  Rather than the simple, but wrong, solution of deleting the information we need to figure out the best way to capture it, and then the best way to document it.  @szymczdm or @JacquesCarette may have ideas on how to capture the information on the derivation of the constraints.  The idea of capturing the rationale for different concepts and ideas is something that we have been trying to include in Drasil, although I don't think it is yet clear how to do this.

**Comment by smiths** [comment]
@halonazhao, I like the questions you are asking.  I don't agree with deleting information, but I like that you are questioning the "manual" reports and the Drasil code.

**Comment by JacquesCarette** [comment]
I think this is what the `Rationale` attribute should help with. It is defined but not really plugged-in right now.

**Comment by halonazhao** [comment]
@smiths, I don't think that we should delete these information either. Because they do mean a lot under that context. But I was thinking that since I am not expert at this. Usually, for some problems, although I am pretty sure that something must be right, there could be a very strong reason out there I didn't come up with before, to prove that my thought was wrong. So I didn't actually mean that we should delete those. I was just attempting to ask.

**Comment by smiths** [comment]
That is a very reasonable explanation.  Thank you @halonazhao.  I'm just sensitive that we don't take the easy solution, since once information is lost, it isn't likely to come back.  Reminding us of the need for ```Rationale``` is a good thing.

**Comment by JacquesCarette** [comment]
It feels to me that things have also moved here - perhaps this is fixed?

**Comment by smiths** [comment]
I've verified that we have restored the "lost" information to stable.  (It isn't pretty how it is formatted, but it is there.)
