### ISSUE TITLE
The Enumeration of the Assumptions

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#485]
Since the Nopcm case and the SWHS case are using some common assumptions, some assumptions should be directly imported from the assumptions of SWHS. The contents are fine, but the number of the same assumption might be different in two cases. Those numbers like "assump1" are hard-coded by using string type to give. So basically, we have to produce a new assumption again in Nopcm. I didn't find any proper enumerating constructor. Is there any thing I can do about it?

Thanks.
@szymczdm

**Comment by smiths** [comment]
@halonazhao I've assigned this issue to @szymczdm.  Issues should be attached to someone, so that someone can take ownership.

**Comment by JacquesCarette** [comment]
Right - this is a referencing issue.

**Comment by szymczdm** [comment]
This is a known issue, #470, which is stopping us from enumerating the assumptions properly. The reason is they're buried too deep into the Drasil Language and should be pulled out into the DocumentLanguage as we've discussed on several occasions.

This is actually resulting in the short-name being used instead of a number (which is also it's referencing name due to the `assump` constructor). If the assumptions are given better short names (ie. instead of `S "assump3"` it were something like `S "FullyMixedA"`) we wouldn't need to worry about the "wrong numbers" since they will no longer exist. This would be the best short-term solution, then we can deal with getting a "good" numbering once #470 is taken care of.

**Comment by szymczdm** [comment]
And I just realized everything I said assumes that you (@halonazhao) are up to date with the master branch, which after taking a look at your branch it appears you're not! We need to merge master into your branch and fix things ASAP.

**Comment by samm82** [comment]
@szymczdm Related to #470, and assumptions have shortnames already in SWHS. Can we close this? @halonazhao

**Comment by halonazhao** [comment]
Yes, I think so. ShortNames make this issue meanless. I'll close this issue for now. If someone thinks this issue is still worthy keeping open, please reopen it.
