### ISSUE TITLE
Merging branches in

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#491]
It is becoming very high priority that the work of @halonazhao and @deviprasad135 be merged into master. That means merging master into their branch first, and then doing an orderly merge back. Then we need a process (Pull Requests and smaller branches?) which we can keep on top of.

**Comment by smiths** [comment]
@JacquesCarette, @szymczdm and @smiths should discuss the process for making changes to Drasil (and maybe the Case Studies as well) during our meeting on Monday (May 7).  We can discuss the plans with the entire group on Tuesday (May 8).  Changes will happen fast and we want to stay on top of them.

**Comment by szymczdm** [comment]
Since I was sick for that meeting, should we discuss this here?

I can think of 2 ways to tackle this. 1) Meet with them and do this in real-time. I can work on other things while they complete the merge, but be in the same room for any questions that arise.
2) Have them merge master into their branches and then create a PR for me to confirm everything's alright.

I think 1 will go smoother, but to my knowledge at least one of their branches has diffs that need to be figured out before the merge can take place. We've gotten pretty far ahead of where they started, so it's going to be a bit tricky.

**Comment by smiths** [comment]
I agree that option 1 would go smoother, but I trust your judgement @szymczdm.

**Comment by niazim3** [comment]
What is the status of getting the [yuzhi branch](https://github.com/JacquesCarette/Drasil/tree/yuzhi) merged into master? Some work that is being put into adding labels in [addLabels](https://github.com/JacquesCarette/Drasil/tree/addLabels) to the examples will need change when it's merged in; the sooner that branch is merged in, less redundant work will be done (e.g. by way of eliminating use of `solChSpecF` in the remaining examples).

**Comment by JacquesCarette** [comment]
There isn't a PR for it. So I'm not sure. @halonazhao ?

**Comment by halonazhao** [comment]
This isn't a PR yet. Maryyam and I are working on adding missing information and matching stable with drasil.

**Comment by niazim3** [comment]
Both branches have been merged into `master` (#530 and #870). This issue can now be closed.
