### ISSUE TITLE
Retain variable type information in the backend

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#496]
Some hacks in the backend are due to the fact that variables "forget their types".  More specifically:
It all really boils down to GOOL not retaining type information.  Types are only used in the variable declaration statements in GOOL, and after that the types of variables are totally lost -- everything is just Var with a label.

Some examples of this:

-  LanguageRenderer.hs:316-323.  At some point, I needed to change GOOL Cast to take a source type in addition to a target type, because some languages needed to know what type is being cast in some instances to do the cast properly.  This made it necessary to hardcode some type (I used Integer) as the source type in some places in the renderers since GOOL didn't retain enough/any type information.

-  Code/Imperative/AST.hs:115.  Taking a slice of a list requires the StateType to be explicitly passed (since we need to create a temporary list to do the slice in some languages).  GOOL doesn't know what type a list is.

**Comment by bmaclach** [comment]
This came up in my discussions of finally tagless GOOL with @JacquesCarette. Another example demonstrating the need for GOOL to have types came up:

In finally tagless GOOL, there is a polymorphic `listType` function which takes a type as a parameter and creates a `Doc` of the type that is a list of the given type. However, it is not always straightforward to generate the corresponding list type given the type it contains. For example an integer in Java is `int`, but a list of integers is `ArrayList<Integer>` (at least, that's one option). So the list type is not a simple matter of plugging in the `Doc` for the contained type somewhere. For this reason, functions like `intListType`, `floatListType`, etc. were created in finally tagless GOOL to handle these situations. But we lose the benefits of having a polymorphic `listType` function that always works. If GOOL stored more type information, the `listType` function could use that information and we would not need these specific `intListType` etc. functions.

The following comment on this issue is directly quoted from @JacquesCarette:

"What this then calls for is to have GOOL have its own types, and each language implementation have a function that takes a GOOL type specification and translates it to the target language type.  And this translation may need to be done differently than the code, as it is 'global' in some sense.

This can still be done in 'finally tagless' style, but the instance can't just have a Doc.  It has to carry more information."

**Comment by JacquesCarette** [comment]
My thinking is that I would first experiment with having the variables carry around both the name of the variable and their type (as a `repr`, not a `Doc`; or at least as something more informative than a `Doc`). Then, at the use-site of a variable, the information needed ought to be available to do the 'sensible' thing, which can be rather complex, as per the examples above.

**Comment by bmaclach** [comment]
@JacquesCarette Did you want to remain assigned to this, or is it okay for me to take it? Also, to represent the type could we just create a new type for types, something like:

`data ValueType = Boolean | Integer | List ValueType | ...`

Which we could easily pattern match on?

**Comment by JacquesCarette** [comment]
Absolutely ok for you to work on it!
Is there no such "type" already? That seems surprising.

**Comment by bmaclach** [comment]
@JacquesCarette We have `CodeType` which seems like exactly what I wanted:
```
data CodeType = Boolean
              | Integer
              | Float
              | Char
              | String
              | File
              | List CodeType
              | Object String
```

We also had a series some types in the old GOOL AST, which offered a few more options:
```
data BaseType = Boolean | Integer | Float | Character | String | FileType Mode
    deriving (Eq, Show)
data StateType = List Permanence StateType | Base BaseType | Type Label | Iterator StateType | EnumType Label
    deriving (Eq, Show)
```

But my feeling is that I should just use `CodeType` and add to it if need be.

**Comment by bmaclach** [comment]
As of the merge of #1610 `Value`s in GOOL retain type information. There is still some resulting clean up that can be done, but that task is captured by #1611 so I think this issue can be closed.
