### ISSUE TITLE
Add information to GD descriptions

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#522]
When updating the GDs (on @halonazhao's branch) the descriptions have changed, but some of that information is still useful. We need to be able to re-introduce the lost information (one example is pictured here):
![gds](https://user-images.githubusercontent.com/235140/39977995-c71bffb2-570b-11e8-835e-f4dcd7aea590.PNG)

Left is build, Right is stable

**Comment by szymczdm** [comment]
This is part of #507

**Comment by halonazhao** [comment]
These missing information has been temporarily added into every case as Note field. Still need a further design.

**Comment by JacquesCarette** [comment]
@smiths it seems the information is no longer lost, but maybe we do indeed want a better way to deal with it.  Since all of this is being actively looked at, it would be a good idea to keep this in mind at the same time.

**Comment by smiths** [comment]
Agreed.  When reviewing issue #523, I will also have to check that manual and Drasil match for this previously missing information.

**Comment by smiths** [comment]
The specific example given in the description of this issue has been fixed.  I am going to close this issue, since the information has been added to GD descriptions.  The Notes field is not entirely satisfying, so we may refine it in the future.  However, this will happen naturally, not through anything mentioned in this issue.
