### ISSUE TITLE
Removal of ConVar

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#524]
As pointed out in issue #514, "it appears `ConVar` and `DefinedQuantityDict` are identical in terms of the class instances they implement. The only difference is in the way they're constructed. If anything it might be worthwhile to remove one of them entirely since they're not really saying anything different."

Since `ConVar` only has `ConceptChunk`, `Symbol`, and `Space` and `DQD` has `Quantity` (which has `unit`, `attribs`, `idea`, `space`, and `symbol`) and `ConceptChunk`, `ConVar` is the type that should be removed.

Other notes for convenience: 
"...we may want to change the way DQD is constructed to avoid the 'double uid' issue mentioned in the comments inside DefinedQuantity.hs.
Also, just to be clear, `ConVar` and `DQD` have exactly the same class instances. While `ConVar` always returns Nothing for the Maybe Unit, whereas `DQD` will sometimes have a non-Nothing value, they are databases of the same types of information.

Working on this issue in [this branch](https://github.com/JacquesCarette/Drasil/tree/remove-convar).

**Comment by JacquesCarette** [comment]
[I've read all the conversation at #514]. I believe I agree.

**However** we should first figure out where `ConVar` is used/defined, and where a defined quantity is instead. There might be differences in intension that are not reflected in the implementations. If we prematurely unify them, we might regret it.

So I'd like to see say 5 different places each (with details!) of use "in context".

**Comment by niazim3** [comment]
It looks like `DefinedQuantityDict` instances are not that common in the current examples: 
![image](https://user-images.githubusercontent.com/28247301/40010679-72c9bec8-5773-11e8-9a7c-e6af20217297.png)

Example of use #1:

Looking in [SSP/Unitals.hs](https://github.com/JacquesCarette/Drasil/blob/adding-attributes/code/Example/Drasil/SSP/Unitals.hs): 
https://github.com/JacquesCarette/Drasil/blob/dbd4b7f149c87c87794d7d9db21a1e0cd05d5972/code/Example/Drasil/SSP/Unitals.hs#L14-L16

, where `sspUnitless` is a list of `convar`s.

https://github.com/JacquesCarette/Drasil/blob/dbd4b7f149c87c87794d7d9db21a1e0cd05d5972/code/Example/Drasil/SSP/Unitals.hs#L390-L396

If anything, I think the `DefinedQuantityDict` type is acting as a wrapper to create the list of symbols for SSP and SWHS/NoPCM. (Is this the type of example being looked for @JacquesCarette?)

**Comment by JacquesCarette** [comment]
Yes, this is exactly the kinds of examples I was looking for.

I would search for the constructors, not just the type itself. Because I think that there are specific slots in `SystemInformation` that expect a `DefinedQuantityDict` and/or `ConVar`.

**Comment by samm82** [comment]
@JacquesCarette In `SystemInformation`:
https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Language/Drasil/SystemInformation.hs#L22-L40

the only slots that could take either a `DQD` or a `ConVar` are `b` and `f`, which correspond to `kind` and `concepts`. A `DQD` could be accepted for `e`, `h`, and `i`, (`quants`, `inputs`, and `outputs`), but not `Convar`, since `ConVar` doesn't have `Attributes`.

**Comment by JacquesCarette** [comment]
Thanks.

**Comment by JacquesCarette** [comment]
It still needs further investigation. I need to look at what you've provided above in more detail.

**Comment by samm82** [comment]
Should I find more examples of the usage of `ConVar`?

**Comment by JacquesCarette** [comment]
All uses preferably.

**Comment by samm82** [comment]
<h1>Language</h1>
`ConVar` is used to generate `UnitalChunk`s, which could also be done via a `DQD`:
https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Language/Drasil/Chunk/Unital.hs#L36-L54

The only notable difference is that `ConVar` doesn't have `Attributes`, but these could be supplied by the `DQD`, unless there would be different `Attributes` for the `UnitalChunk` and the `DQD` it would be made from. All of the `UnitalChunk`'s properties (`uid`, `term`, etc.) could be derived from a `DQD`.

The function `cv` is defined within ConVar.hs:
https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Language/Drasil/Chunk/ConVar.hs#L35-L36

And this is used in the following functions in Unital.hs...
https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Language/Drasil/Chunk/Unital.hs#L64-L82
...and their "empty list" counterparts. I'm pretty sure we could use a function that returns a `DQD` instead of a `ConVar` in all of these cases.

These are the only occurrences of `ConVar` or `cv` in Language, other than in a comment here: 
https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Language/Drasil/Chunk/VarChunk.hs#L47-L49

---
<h1>Data</h1>
`ConVar` is used in the following lines to define constants:

https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Data/Drasil/Quantities/Chemistry.hs#L9-L11
https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Data/Drasil/Quantities/Math.hs#L8-L17
https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Data/Drasil/Quantities/Physics.hs#L8-L9
https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Data/Drasil/Quantities/SolidMechanics.hs#L16-L17

---
<h1>Example</h1>
<h2>Defining Constants</h2>

https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Example/Drasil/GamePhysics/Unitals.hs#L49-L63
https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Example/Drasil/GamePhysics/Unitals.hs#L69-L86
https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Example/Drasil/SSP/Unitals.hs#L390-L441
https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Example/Drasil/SWHS/Unitals.hs#L189-L201
(This example is to be removed: )

https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Example/Drasil/SSP/Unitals.hs#L117-L121

<h2>Generates UnitalChunks</h2>

https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Example/Drasil/GamePhysics/Unitals.hs#L91-L126
https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Example/Drasil/GamePhysics/Unitals.hs#L140-L239

<h2>Forming Sentences</h2>

https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Example/Drasil/NoPCM/Body.hs#L453-L460
https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Example/Drasil/NoPCM/GenDefs.hs#L39-L46
https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Example/Drasil/SWHS/Body.hs#L1040-L1046
https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Example/Drasil/SWHS/Body.hs#L1356-L1368

This was the only thing I could see a potential problem with, but since `ConVar` and `DQD` both have a `ConceptChunk`, and it appears that the `phrase` function is applied to a noun phrase through the `ConceptChunk`, this should be OK.

<h2>Generating a List of Contents</h2>

https://github.com/JacquesCarette/Drasil/blob/340a4de868308be50f62fe84bdfb3a531cb45184/code/Example/Drasil/SWHS/Body.hs#L1265-L1295

---
Sorry for the long comment, but long story short, it seems that merging `ConVar` and `DQD` shouldn't cause any problems, unless there was/were specific reason(s) for originally implementing two separate functions.

**Comment by szymczdm** [comment]
We should begin unifying ConVar and DQD. First we should update DQD to fix the problem of dual `uid`s. What that means is we'll want to DQD constructed in a very similar way to how ConVar is constructed. Essentially, we should have fields in our record of type: 
- `ConceptChunk`
- `Stage -> Symbol`
- `Space`
- `Maybe UnitDefn`

Then we can use the appropriate lenses to keep our class instances.

**Comment by JacquesCarette** [comment]
Another way of saying what @szymczdm said: we want to keep DQD, but want its implementation (which has problems right now) to look more like `ConVar`. And get rid of `ConVar` as a data-type.

However, keep the constructors for `ConVar`, just have them build the (new) DQD instead. 

Then we can take a look at constructor duplication.

**Comment by samm82** [comment]
One thing @szymczdm and @JacquesCarette, `DQD` has a `QuantityDict` and a `ConceptChunk` that both have `IdeaDict`s. Are they the same/is this the duplication problem?

**Comment by JacquesCarette** [comment]
Yes, that duplication is a huge (potential) problem. Which is why this is a great opportunity to fix it. #527 is higher priority, as the results of that will influence the details of the design of this issue.

**Comment by niazim3** [comment]
1. Would `DefinedQuantityDict` remain a good name for this type? I'm asking since it no longer builds off of `QuantityDict`...
2. Also, since it no longer builds from `Quantity`, `DefinedQuantity` no longer is an instance of `HasAttributes`; is that a problem we should be taking into consideration? Taking the following into consideration, 
![image](https://user-images.githubusercontent.com/28247301/40121453-9c332380-58ef-11e8-8a5a-dea57b840d2e.png) would it make sense to just update the current definition for `DefinedQuantityDict` 
to have the same fields (i.e. `Quantity` and `ConceptChunk`), but have `Quantity` updated to have 
- `Maybe Unit`
- `Maybe Attribs` (? Or just Attribs since all the types will eventually be an instance of `HasAttributes`)
- `Maybe Idea`
- `Space`
- `Symbol`

**Comment by szymczdm** [comment]
DefinedQuantityDict is still a good name for it as it's a Quantity with a definition (regardless of the use of QuantityDict).

If `Quantity` has attributes, DefinedQuantityDict should also (probably) have attributes, but we'll know for sure once we've reviewed all the uses of attributes and decided what to do with them.

**Comment by niazim3** [comment]
That makes sense. And how about changing 
```
data QuantityDict = QD { _id' :: IdeaDict
                       , _typ' :: Space
                       , _symb' :: Stage -> Symbol
                       , _unit' :: Maybe UnitDefn
                       , _attribs :: Attributes
                       }
```
to 
```
data QuantityDict = QD { _id' :: **Maybe** IdeaDict
                       , _typ' :: Space
                       , _symb' :: Stage -> Symbol
                       , _unit' :: Maybe UnitDefn
                       , _attribs :: Attributes
                       }
```
?

**Comment by szymczdm** [comment]
Why do you want to make it a `Maybe` in the first place? The `IdeaDict` is the piece of information with the unique id and other important (mandatory) pieces of information.

**Comment by samm82** [comment]
So can we go ahead and start merging the two, and if not, is there something else we could be working on?

**Comment by JacquesCarette** [comment]
Yes, go ahead. As per my last comment, please.

**Comment by niazim3** [comment]
Since we're no longer building off of `QuantityDict`, I think we can add it as a field for `DQD`.

**Comment by JacquesCarette** [comment]
Correct (to both).

**Comment by samm82** [comment]
One thing I noticed, in the definition of `DQD`...

https://github.com/JacquesCarette/Drasil/blob/c9df4cdd06c2b1ce9bb258a0dfa8254a0009ae6b/code/Language/Drasil/Chunk/DefinedQuantity.hs#L22-L27

...we pass a `ConceptChunk` and a `UnitDefn`. The type of a `UnitDefn` is...

https://github.com/JacquesCarette/Drasil/blob/c9df4cdd06c2b1ce9bb258a0dfa8254a0009ae6b/code/Language/Drasil/Unit.hs#L138

...and `FundUnit` has a `ConceptChunk`!

https://github.com/JacquesCarette/Drasil/blob/c9df4cdd06c2b1ce9bb258a0dfa8254a0009ae6b/code/Language/Drasil/Unit.hs#L49

So are we passing two `ConceptChunk`s and is this a problem?

**Comment by JacquesCarette** [comment]
I don't think I understand the question. You either have a `DQD` or `UnitalChunk` in your hands. You ask it for a unit, and it will give you what it has.

**Comment by samm82** [comment]
@JacquesCarette Yes you're right - my bad

**Comment by JacquesCarette** [comment]
So the simplest thing to do was to change `DQD` to `Maybe` have a unit. This isn't the optimal solution (as can be seen from some of the things in the examples), but it works. And it can be fixed piecemeal.
