### ISSUE TITLE
Remove Errors from types that are instances of `HasShortName`

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#549]
As mentioned in the comments of commit d7dedf56b, the types that raise error messages like the one below (i.e. `GenDefn`, `TheoryModel`, `InstanceModel`, and `DataDefn`(i.e. `QDefinition`)) should now be explicitly supplied the shortname since collapsing `RefName` and `ShortName` (being tracked in issue #537) allows for them to be instances of the `HasShortName` class.

```No explicit name given for ___ -- build a custom Ref```
- [x] GenDefn
- [x] Theory
- [x] InstanceModel
- [x] Eq

**Comment by niazim3** [comment]
This issue can be closed with merge of PR #561.

**Comment by JacquesCarette** [comment]
Hmm, except that aren't some of these "" ?

**Comment by niazim3** [comment]
This may need revisiting after it's determined what's happening with `shortname`.

**Comment by niazim3** [comment]
Removing the error for `QDefinitions` is left to close this issue. I've run into what I think may need some design? The following is the current definition of the `ec` constructor: 
https://github.com/JacquesCarette/Drasil/blob/dd3f0f124448c2560d7cc0d140f7bd5f568a9259/code/Language/Drasil/Chunk/Eq.hs#L71-L74

I attempted to update it to the following

```
ec :: (HasShortName c, Quantity c) => c -> Expr -> QDefinition
ec c eqn = EC (qw c) eqn [] [] (shortname c) --hack?
```
, but that resulted in errors since `ChunkDB` (which uses `relToQD` which uses `convertRel` which uses `ec`) is not an instance of the `HasShortName` class.

If `ec` is instead updated to 
```
ec :: (HasShortName c, Quantity c) => c -> Expr -> ShortName -> QDefinition
ec c eqn sn = EC (qw c) eqn [] [] sn
```
, it becomes awkward and difficult to pass in shortnames to the lists that `relToQD` is mapped to https://github.com/JacquesCarette/Drasil/blob/dd3f0f124448c2560d7cc0d140f7bd5f568a9259/code/Example/Drasil/GlassBR/Body.hs#L146-L152.

**Comment by JacquesCarette** [comment]
It should not be needed for `ChunkDB` itself to be an instance of `HasShortName`. The issue is whether `Quantity` should be an instance of `HasShortName`. And that's not unreasonable, but it does appear to be asking to too much.

As far as `relToQD` is concerned, wouldn't it make more sense for `iModels` and `tModels` to have models that contain shortnames, which `relToQD` could extract?

**Comment by JacquesCarette** [comment]
`RelationConcept` is too 'raw' to be the only material for creating models. Or at least, that's my understanding of it.  But I'm not entirely sure I want to augment `RelationConcept` (as it has other flaws, so I'm not so keen on relying on it even more). `relToQD` is a horrible hack too.

I get the feeling that this is another piece that needs just  a bit more design - we need to understand what these various data-structures are used for, i.e. what actual knowledge is being encoded here. To understand if the encoding is adequate. I get the feeling it's not, so that anything local patch we apply now would be a mere band-aid that would need to be fixed again soon.

**Comment by niazim3** [comment]
In that case, can this issue be closed with the merge of a PR for the branch this was worked on, and a new one be opened containing your comments about design being needed for `relToQD` and `RelationConcept` implementation? @JacquesCarette

**Comment by JacquesCarette** [comment]
Yes.
