### ISSUE TITLE
FundUnit was removed?

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#554]
According to the manual version, the table of unit only includes the fundamental units. 

But I just found out the "FundUnit" was removed. Seems that they are replaced by "UnitDefn". I don't know what's the benefit here? If this is the case, then some fundamental units who only occures in a DerUChunk can not be split out.

So whether we have to put both fundamental units and derived units in the table or I think if using exclusive method to exclude units at DerUChunk type, we can get partial fundamental unit types. As I said before if a fundamental units only occures in DerUChunk, the table will not be complete.

There is a "IsUnit class", the current instances for IsUnit class are "UnitDefn" and "DerUChunk". It actually doesn't make more sense to me than having "FundUnit" and "DerUChunk".

So far in "traciProject branch", both derived and fundatmental units are collected in the unit table.

If I didn't miss up any details, based on current structure. We can not parse out all the fundamental units. Any suggestions here?

@szymczdm @JacquesCarette

**Comment by JacquesCarette** [comment]
`FundUnit` was a bad name. `UnitDefn` is its better named replacement.  

I believe that the table of units is supposed to be just the actual SI units that occur in the document. So if there is a velocity, then we'll want meters and seconds in the table of units, but not m/s. Though of course, it would be nice to be able to decide whether to do one or the other.

So the problem boils down to `unitWrapper`: it takes what might have been a `DerUChunk` and makes it into a `UnitDefn`, thus forgetting that it is defined. So you have no straightforward way of knowing whether it is fundamental or not.

This will require a deeper change: I think that `UnitDefn` and `DerUChunk` will have to be merged into a single type, with a `Maybe UDefn` field. And the interface to units will need an extra method to retrieve this new field (which will allow you to tell if the unit is fundamental or not).  This might not be quite enough, but it's a start.  [I have my suspicion that the definition of `UDefn` may have to be changed as well].

But this is good. The reason you encountered this is because of a lack of *traceabiliy* !! `unitWrapper` dropped some information that was important, and we shouldn't have done that.

**Comment by halonazhao** [comment]
Alright. I will try this method. 

There may be another way to get them out is to pattern match the constructors who take fundamental units and produce a derived symbol. I can collect and pattern match all constructors to get FundUnit out. Kind of like getting different units from `USynonym`.

But from the data structure seems better.

**Comment by JacquesCarette** [comment]
I think that `unitWrapper` would end up making the pattern-matching approach not work. Plus we want to be as independent of the actual implementation details as possible, so that's why we use lens instead of explicit data-structures.  So that changes such as these can be done without having to do lots of changes to the examples. We are not 100% there, but getting closer all the time.

**Comment by halonazhao** [comment]
Ok, I see the comments under another issue.

**Comment by JacquesCarette** [comment]
So what needs to be done is now clear?

**Comment by halonazhao** [comment]
I will close this issue because mainly of this issue relating problem is discussed in #555. And this issue itself has been solved. So far all derived units and fundamental units are integrated into new type `UnitDefn`.
