### ISSUE TITLE
Design needed for `relToQD` and `RelationConcept` implementation

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#628]
In issue #549, the errors for certain types that are instance of `HasShortName` have been removed. However, as of fdf90d9, `RelationConcept` now has an error thrown in relation to `HasShortName`.

This was done because https://github.com/JacquesCarette/Drasil/blob/fdf90d90260bb4050c6d5e2b16cdec99d81adaa9/code/Example/Drasil/GlassBR/Body.hs#L146-L148 `imodels` and `tmodels` are lists of `RelationConcept`s and trying to extract shortnames from there led to deduction errors.

It was originally thought that either `RelationConcept` should have a shortname OR `imodels` and `tmodels` should not be `[RelationConcept]` / should be named differently.

@JacquesCarette mentioned that `RelationConcept` is too 'raw' to be the only material for creating models and that perhaps it should not be augmented "as it has other flaws, so I'm not so keen on relying on it even more".

`relToQD` is a horrible hack too.

"I get the feeling that this is another piece that needs just  a bit more design - we need to understand what these various data-structures are used for, i.e. what actual knowledge is being encoded here. To understand if the encoding is adequate. I get the feeling it's not, so that anything local patch we apply now would be a mere band-aid that would need to be fixed again soon."

I'm unsure who to assign this issue to, so I'm assigning @JacquesCarette and myself for now...

**Comment by JacquesCarette** [comment]
I think this issue is going to be important to fix to deal with both #695 and #891 properly.

Roughly speaking, neither instance models nor theory models should use `RelationConcept` at all. Really they should use some type like `QDefinition` or a superset of it. [Eventually, we'll have other kinds of definitions than just equalities, but I'm not sure where they are now.]

**Comment by JacquesCarette** [comment]
This is now half fixed: instance models use a more refined definition that differentiate between equational models, DE models and 'other' models. That type needs to pulled out of there so that theory models can use this too.

Note that `relToQD` itself is already completely gone. `RelationConcept` will stay for quite a while yet, as those models that use it (i.e. DE and other) will stay like that right now.

**Comment by JacquesCarette** [comment]
Just an update: this is partly done, but than it was when I last looked too, but still is not finished.

**Comment by JacquesCarette** [comment]
Hmm, the fixes were on a branch that was never pulled in. `relToQD` is not gone at all.

**Comment by balacij** [comment]
It looks like we only use `relToQD` in GlassBR (for converting IMods) and Projectile (for converting  IMods + GenDefns). In other words, once #2493 and #2388 are complete, we'll be able to remove it completely I believe.

**Comment by JacquesCarette** [comment]
Hurray!

**Comment by balacij** [comment]
Just an update, `relToQD` is removed. RelationConcepts are still currently used as discussed earlier (in ModelKinds/DEModels for example).

**Comment by JacquesCarette** [comment]
Agreed.
