### ISSUE TITLE
WorkFlow for issue #567

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#629]
This is just the workflow @niazim3, @samm82 and I discussed (for issue #567) 

## Label
- [x] Create Label type

## isLabel
- [x] Create isLabel

## LabelledContent
- [x] Create LabelledContent type (MUST have its own uid and shortname separate from the label within it)
- [ ] Create smart constructors for LabelledContent

## Label all the things
- [ ] Add Label to all applicable Chunk types (MUST keep uid and shortname of the chunk type)
- [ ] Create ShortName lens

**Comment by niazim3** [comment]
@szymczdm @JacquesCarette 
Clarification request: It says here that a labelled content "MUST have its own uid and shortname separate from the label within it". Is this true for the shortname?

Since a shortname is something a human will be seeing, must a label have a shortname as well? Or does it make sense to do one of the following instead:

1. label only has a UID and a label type (no shortname); labelled content has a label, its own UID, the actual contents, and maybe a shortname
2. label has a UID, a label type, and a shortname; labelled content has a label, its own UID, and the actual contents

Does it make a difference if either is implemented?

**Comment by JacquesCarette** [comment]
I believe that the shortname for LabelledContent can be the same as for the content. So that option 2 above seems to make most sense to me.

**Comment by szymczdm** [comment]
Option 2 makes the most sense to me as well.

**Comment by niazim3** [comment]
Thanks for the input. Made changes in relation to that in the following commit range: d63663e52a31e0c6807088cc3eda83d6797fe6f6...99366f8156a15ddab3c114f1707f64fdea0b2b4b.

**Comment by niazim3** [comment]
(I will be asking the following in today's upcoming meeting, but it may be useful to have it noted down here as well.)

In [PR #677's review](https://github.com/JacquesCarette/Drasil/pull/677#pullrequestreview-129645822), it was mentioned that the `RefAdd` from the Table (i.e. `Contents`) can most likely be pulled out into the `LabelledContent` constructor.

Such a change will influence anything that depends on the use of the `Referable` class and `HasShortName` class; which means that there needs to be a systematic approach to the remaining bits of this issue to hopefully avoid large PRs.

@szymczdm @JacquesCarette 
Would it be possible to get some feedback on the following workflow for labelled content?

1. create `LabelledContent` to have a label, UID, contents, where label has a UID of its own, a label type, and a maybe shortname (done)
2. leave reference addresses in `Contents` as they are (there will be some duplication in the next few stages)
3. make `LabelledContent` instances of all the classes `Contents` are currently instances of
4. remove `Contents` as instances of all the classes it currently is an instance of
5. slowly update examples and files to use `LabelledContent` instead of `Contents` (probably will be done one `Contents` type at a time as their constructors are built)
6. make `Contents` unavailable outside of defined file (e.g. cannot build a table directly from a case study's body)
7. remove duplicate reference addesses from original `Contents`

**Comment by elwazana** [comment]
@JacquesCarette Hello Dr. Carette, I just have a question for the end goal of creating `Label`, which `uid` will we use for referencing internally the uid of the `LabelledContent` or the uid of the `Label` within the `LabelledContent`

**Comment by szymczdm** [comment]
Labels were created with the end goal of having a label for internal referencing. So the idea is that we're going to use the label uid to look up the relevant referencing information from a database of labels.

**Comment by elwazana** [comment]
@szymczdm Then what is the purpose of the uid in the `LabelledContent`? Is there a purpose more than just to have a unique ID for `labelledContent`?

**Comment by szymczdm** [comment]
@JacquesCarette I think I misunderstood the question honestly. I was thinking in general 'label' terms, not about `LabelledContent` (and by 'internal' I meant within a doc, not internal to Drasil).

**Comment by JacquesCarette** [comment]
No worries - and we'll get to see who actually understood the question as it was meant!

**Comment by elwazana** [comment]
What I meant is that within Drasil, if I'm creating a paragraph, which uid would I use to create a reference to another paragraph?

I thought the purpose of creating `Label` was to replace the method that is used to create references in Drasil. When I continue to replace the `acro-` functions in the future, which uid would I need to create the replacements?

**Comment by szymczdm** [comment]
> I thought the purpose of creating Label was to replace the method that is used to create references in Drasil. 

Yes! I'd consider it more of an augmentation than a complete replacement, regardless, labels are meant for creating references. In your example (paragraph referring to paragraph), we'd have a label attached to each paragraph (ex. paragraph P1 has label L1, P2 has L2), then within P2 you could create a reference to P1 by using *only* L1 (or even just L1's UID if we've got a LabelDB, but that's neither here nor there).

**Comment by JacquesCarette** [comment]
Agreed.

**Comment by niazim3** [comment]
For the task "Create smart constructors for LabelledContent", why is it better to use something like https://github.com/JacquesCarette/Drasil/blob/f1cc1de748f668f51e809fc6de6fb4468b65054f/code/drasil-lang/Language/Drasil/Document.hs#L135-L149
instead of https://github.com/JacquesCarette/Drasil/blob/f1cc1de748f668f51e809fc6de6fb4468b65054f/code/drasil-lang/Language/Drasil/Document.hs#L112-L114?

**Comment by JacquesCarette** [comment]
To me `llcc` is better!  I don't understand your edit question though -- what is `sn'` there?

**Comment by niazim3** [comment]
Whoops, removed it from the function definition. (I forgot to remove it from the current implementation of `mkTableLC` when I copied it over: https://github.com/JacquesCarette/Drasil/blob/fdfa048c771d333fdf0aaeba8877f8228dccd980/code/drasil-lang/Language/Drasil/Document.hs#L135-L137)

Since `llcc` is better, should the "Create smart constructors for LabelledContent" task be one that no longer needs to be done?

**Comment by JacquesCarette** [comment]
For `LabelledContent`, it may well be that there is **currently** no need for a suite of smart/convenient constructors.  Once we start creating them, we might well see usage patterns that arise, and then we'll want to revisit this.

**Comment by elwazana** [comment]
This workflow is obsolete with the implementation of `(Un)LabelledContent`, the new workflow plan can be followed here: #963
