### ISSUE TITLE
Should Label have a Maybe ShortName or just a ShortName?

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#689]
@szymczdm @JacquesCarette Hello Dr. Carette and Dan, I'm just wondering if `Label` should have a `Maybe ShortName` or just a `ShortName`. All chunk types are going to have a `Label` so why not have all of them have some `ShortName` for citing? 

![image](https://user-images.githubusercontent.com/35268928/41665739-aede4936-7476-11e8-9a68-b6fc8a484069.png)

I was working on #629 task number 

3. make `LabelledContent` as instances of all the classes `Contents` are currently instances of) 

in @niazim3 last comment and one of the instances for `Content` is `HasShortName`, while trying to create a `HasShortName` instance for `labelledContent` I realized that `LabelledContent` doesn't have its own shortname. It does however, have a `Label` so I tried to create a `HasShortName` instance for `Label` but I couldn't becuase `Label` has a `Maybe ShortName`. Am I looking at the task incorrectly or should `Label` have a `ShortName` not a `Maybe ShortName`?

**Comment by niazim3** [comment]
The reason why `Maybe Shortname` was used instead of just a short name was because when the design was being discussed, `Contents` had some types that didn't have reference addresses (i.e. `Bib`, `Paragraph`, and `Enumeration`; however, as discussed in yesterday's meeting, these 3 can be updates to also have reference addresses, so the definition of errors for these types will be removed eventually. Since that is the case, I think your point about having a short name for every reference address makes sense, but let's wait for some input from @szymczdm and @JacquesCarette.

**Comment by JacquesCarette** [comment]
Indeed. If we're going to create a Label at all, it makes sense to give it some kind of user-displayable name at the same time.

Excellent thinking (and reasoning it through).

**Comment by JacquesCarette** [comment]
[I closed it because this design question is answered. If you want to reopen it while you implement it, that's fine.]
