### ISSUE TITLE
HTML: Figures should have `Figure X: ` in their `figcaption` and references to figures should be prettier.

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#702]
EDIT: Take [Projectile's SRS](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/srs/Projectile_SRS.html) for example. Specifically, the [System Context Figure](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/srs/Projectile_SRS.html#Figure:sysCtxDiag). We have ~2-3 issues:
1. Figures are missing the `Figure: ` text in their captions.
2. References to figures use the internal HTML IDs! For example, in the [System Context section](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/srs/Projectile_SRS.html#Sec:GenSysDesc), we write `Fig:sysCxtDiag`.
3. Instead of writing the references, we should either use a short-caption (i.e., a short-title where available) OR use a numbering system. 

@smiths Do you have any thoughts on whether this we should use a numbering system or a short-caption?

Original OP:
* LaTeX gets figure prefixes (i.e. "Figure xx: ") for free in captions, whereas HTML does not. This results in either the HTML not having "Figure xx:" prefixed to captions or LaTeX having "Figure xx: Figure xx: " prefixed to its captions.
* ~~HTML is not centering figures. LaTeX encloses figures in a `center` environment. ~~

**Comment by samm82** [comment]
A similar (but different) thing happened with tables (#833), and I think (at least for now) we're OK with it. This came up now because I'm removing a function that created a `LabelledContent` for a figure (because it's only used a couple of times and isn't worth it), and it happened to hardcode these figure numbers.

**Comment by Awurama-N** [comment]
@JacquesCarette I see I'm suppose to review this open issue and report back with what the current state of the problem is...
I started and have already seen an instance of a missing "Fig:xx:" prefixing a caption. Would you like me to make a list of all the places that have an issue with the "Fig:xx:" prefix?

also just to clarify... What i am seeing in the html is "Fig:xx:xx" eg. "Fig:SysCon: System Context" Not "Figure xx:".

**Comment by JacquesCarette** [comment]
Yes, the first step is to report back. A list of all the problems would be excellent.

It seems that, at some point, things might have changed from Figure to Fig in the html. That's probably fine. It's shorter.

**Comment by Awurama-N** [comment]
Okay I'll do that

**Comment by Awurama-N** [comment]
## SWHS_SRS
- under "Specific System Description" > "Physical System Description" there's a missing "Fig:Tank:" before the caption "Solar water heating tank, with heat flux into the water from the coil of qC and heat flux into the PCM from water of qP" (html)

## DblPendulum_SRS
- under "Physical System Description" there's a missing "Fig:pendulum:" before the caption "The physical system"

## GamePhysics_SRS
- under "General System Description" > "System Context" there's a missing "Fig:sysCtxDiag" before the caption "System Context"

## GlassBR_SRS
- under "General System Description" > "System Context" there's a missing "Fig:sysCtxDiag" before the caption "System Context"
- under "Specific System Description" >"Physical System Description" there's a missing "Fig:physSystImage" before the caption "The physical system" 
- under "Appendix" there's a missing "Fig:demandVSsod" and "Fig:dimlessloadVSaspect" beneath their respective graphs.

## NoPCM_SRS
- under "Specific System Description" > "Physical System Description" there's a missing "Fig:Tank:" before the caption "Solar water heating tank, with heat flux from heating coil of qC" (html)

## PDController_SRS
- under "General System Description" > "System Context" there's a missing "Fig:systemContextDiag" before the caption "System Context"
- under "Specific System Description" > "Physical System Description" there's a missing "Fig:pidSysDiagram" before the caption "The physical system"

## Projectile_SRS
- under "Specific System Description" > "Physical System Description" there's a missing "Fig:Launch" before the caption "The physical system"


Should i go ahead and fix these?
from looking at one of the fig:xx:caption that came out the right way i could edit the tex file 

- another inconsistency i see is that in GamePhysics the "system context diagram" is"Fig:sysCtxDiag" but in PDController it is "Fig:systemContextDiag".

@JacquesCarette

**Comment by JacquesCarette** [comment]
You should never edit the tex file - it's generated. Something in the generator is always the real problem.

It is really weird that the html has something in it, that doesn't show up in the tex file.  That would be the next thing to investigate. Maybe start with Projectile (it's the smallest), and let's see what HTML and what LaTeX is generated right around the "Fig:SystemContextDiag".  It would be useful to see the Drasil that generates that too.

The difference in labels between GamePhysics and PDController is not a big deal, as those labels are human-generated. They can be fixed, but it's not a big concern.

**Comment by balacij** [comment]
Small note from our meeting:

On the LaTeX side, this is done for us by the compiler. For the HTML side, since we already use the figure tags, we might look into using the "counter" CSS properties in our SRS stylesheet to do the rest of the work (e.g., [w3schools information](https://www.w3schools.com/cssref/pr_gen_counter-increment.asp), [w3schools specific example](https://www.w3schools.com/cssref/tryit.asp?filename=trycss_counter-reset3)), or, if we prefer Javascript, we can have a little snippet of Javascript code that, when the document is loaded in the web browser, scans the document for sections, subsections, and figures, and adds the numbering as appropriate. I _think_ the better solution is to use CSS because it's a necessity to rendering the page (e.g., the page will show a spinner in the tab favicon in most web browsers until the page has been fully rendered).

**Comment by TRISHI-L** [comment]
Q: When referencing figures in the text and adding captions, should I use a consistent numbering system, such as "Figure 1:" for in-text references and "Figure 1: System Context" for the caption under the figure, to make them clearer and prettier?
![image](https://github.com/user-attachments/assets/d68ccb58-4f4d-4d09-86dc-66d086a24f5b)

**Comment by JacquesCarette** [comment]
The underlying infrastructure should provide the consistent numbers - we just have to provide consistent labels.

**Comment by TRISHI-L** [comment]
- Any suggestions for referencing figures in HTML without using a numbering system? We could use a prefixed caption like 'Figure :' for figures, while LaTeX automatically prefixes captions with 'Figure 1:', 'Figure 2:', etc.
Note: References to figures have been slightly adjusted for clarity.
![image](https://github.com/user-attachments/assets/9b66104e-019d-4b65-bc53-29f760986da7)
- So problem is that LaTeX handles numbering automatically, which can result in repetitive prefixes as shown below.
![image](https://github.com/user-attachments/assets/81c28048-3290-4d06-a320-1df7125d762b)

**Comment by smiths** [comment]
The generator for LaTeX should be different from the html generator.  The word Figure shouldn't be added in the LaTeX version.  @JacquesCarette alluded to the underlying numbering system.  Is there one for the html version?  If there is, you could use it.  If not, maybe we don't need numbers for the html version?  They hyperlinks do the same job.

Do we have hyperlinks in the LaTeX version?  It looks like we do from the screenshots given above.

**Comment by TRISHI-L** [comment]
> The generator for LaTeX should be different from the html generator. The word Figure shouldn't be added in the LaTeX version. @JacquesCarette alluded to the underlying numbering system. Is there one for the html version? If there is, you could use it. If not, maybe we don't need numbers for the html version? They hyperlinks do the same job.
> 
> Do we have hyperlinks in the LaTeX version? It looks like we do from the screenshots given above.

Currently, HTML does not have a numbering system. Adding the prefix "Figure:" could lead to the conflict mentioned earlier.
There are no hyperlinks in the LaTeX version. Maybe I should look into the differences between the generators for each format and figure out why LaTeX automatically prefixes captions.

**Comment by JacquesCarette** [comment]
Yes @TRISHI-L it is a good idea to investigate in more depth how both the HTML and LaTeX renderers work, and how they are different. This isssue is a bit subtle.

I think that we chose to use symbolic links in HTML (rather than numbers) as those tend to be more meaningful for human readers.

**Comment by BilalM04** [comment]
@Xinlu-Y, the relevant package for this issue is `drasil-printers`, which converts Drasil’s representation of the SRS into various render-able formats (HTML, LaTeX, etc.). Specifically, the change to the caption pertains to the function responsible for setting up HTML figures (see below). You can simply append `"Figure:"` to the caption (`c`).

https://github.com/JacquesCarette/Drasil/blob/8ca26be6df6d3f4c24627e76d051637b0ff85b16/code/drasil-printers/lib/Language/Drasil/HTML/Helpers.hs#L141-L150

Similarly, it would probably be nice to add this change to mdBook as well. Here is the function for setting up figures in mdBook:  

https://github.com/JacquesCarette/Drasil/blob/8ca26be6df6d3f4c24627e76d051637b0ff85b16/code/drasil-printers/lib/Language/Drasil/Markdown/Helpers.hs#L63-L67
