### ISSUE TITLE
Add information to README under Running the example(s)

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#726]
The section of the README file for Running the example(s) doesn't actually say what happens when the examples are run.  Please add information to the README to say where the generated documentation ends up.  I thought it went to the build folder, but after some experimentation, I'm not sure I'm right about that.

@niazim3, I'm assigning the issue to you, but feel free to reassign if it is more appropriate for someone else.

**Comment by niazim3** [comment]
It seems that upon running `stack exec Name` like it says in the [README.md](https://github.com/JacquesCarette/Drasil/blob/master/README.md), the html and tex versions of the SRS for the examples corresponding to `NAME` can be found in the SRS and Website directories in code. 

May I ask why we have this option @szymczdm if one can already "...find the generated output in the build folder that appears..."?

**Comment by smiths** [comment]
Good question @niazim3.  I was actually wondering the same thing.  Since build also runs the examples, running them separately will always have the same output.  Also, if I understand correctly, running the examples and creating the output in the code folder means that these examples will not be able to find their figure resources.  Maybe we just take the running option out and clarify that build also runs the examples?  

Should we also point users to where the executables are?  The programs that actually generate the tex and html output?  Some users might want to know this?

**Comment by niazim3** [comment]
I agree that taking out the running option and clarifying that build also runs the examples in the README is a good idea.

Pointing users to the executables (which can be found in `code\dist\build\NAME`) can be done, although isn't that what the `stack exec NAME` command was doing? I may be confusing this with something else but the reason I say this is because (for example) the `NAME` `chipmunkdocs` does not appear anywhere except within the dist folder.

**Comment by niazim3** [comment]
So I should remove the "Running the examples" section and this issue can be closed?

**Comment by smiths** [comment]
Let's wait to see what @szymczdm has to say before making a decision.

**Comment by szymczdm** [comment]
Technically we can run the examples manually using `stack exec` (which runs them from the .stack-work folder after building), but, for our examples, we shouldn't be explicitly running them as our Makefile handles that automatically and running them manually ends up putting the generated docs in the wrong place.

Personally I'd keep the "Running the examples" section, but add a note that if using `make` they'll be run automatically and the generated docs can be found in build, if doing it manually they will appear in the current folder (and will not be subject to our automated tests).

My reasoning for this is if someone tries to create their own example and wants to manually execute it, we should provide instructions. That's more of a long-term goal though, so for the time being (especially since it's still reasonably hard to write new examples in Drasil), we could remove it.

@smiths I'm happy to defer to you for a decision here.

**Comment by niazim3** [comment]
Does b0d1c33 contain all the changes that were requested?

**Comment by szymczdm** [comment]
Looks good to me, except that it doesn't mention the tests. I'd add in to the bit about running them manually that this will not subject the generated versions to automated tests.

**Comment by niazim3** [comment]
This issue can be closed at your discretion @smiths @szymczdm.

**Comment by szymczdm** [comment]
Done and done.

**Comment by smiths** [comment]
Looks good.
