### ISSUE TITLE
Remove multiple occurrences of definition of DD as Data Definition

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#734]
@JacquesCarette @szymczdm Hello Dr. Carette ad Dan, I saw this in the notes directory:
https://github.com/JacquesCarette/Drasil/blob/1e11a50793f7866633d535d8d8f75d6a3464654b/notes/DrasilPotentialTasks.txt#L88

I was wondering if I could get clarification of this potential task?

**Comment by JacquesCarette** [comment]
This is somewhat non-trivial. Surface-wise, it seems straightforward: the `String` "DD" (alone or as a prefix) occurs multiple times in Drasil (whether in Language, Data or Example). It should occur in there at most once.

Fixing that properly may well intersect with the work on `ContentChunk` and `ContentInstance` that @Mornix is doing.  Though the first thing to do would be to find all occurrences of "DD" and figure out why they exist the way they do.

**Comment by niazim3** [comment]
"DD" is used in `getDefName`: 
https://github.com/JacquesCarette/Drasil/blob/8627a38c01c5824c36d48b9df9b4b91c9f582d6d/code/Language/Drasil/Document.hs#L178-L185
***
It can be seen in `makePairs`: 
https://github.com/JacquesCarette/Drasil/blob/8627a38c01c5824c36d48b9df9b4b91c9f582d6d/code/Language/Drasil/HTML/Import.hs#L142-L147
***
And here:
https://github.com/JacquesCarette/Drasil/blob/8627a38c01c5824c36d48b9df9b4b91c9f582d6d/code/Language/Drasil/Reference.hs#L227-L231
***
It is also the acronym for the `dataDefn` `CI`:
https://github.com/JacquesCarette/Drasil/blob/8627a38c01c5824c36d48b9df9b4b91c9f582d6d/code/Data/Drasil/Concepts/Documentation.hs#L18
***
And is hardcoded in `refDD`:
https://github.com/JacquesCarette/Drasil/blob/8627a38c01c5824c36d48b9df9b4b91c9f582d6d/code/Example/Drasil/DocumentLanguage/RefHelpers.hs#L42-L44

**Comment by niazim3** [comment]
## Report on the uses of the above-mentioned functions:
***
### `getDefName`
- used to help define `Contents` as an instance of `HasShortName`
- used to help define `Contents` as an instance of `Referable`

I believe `Contents` will no longer be instances of the `HasShortName` and `Referable` classes once `LabelledContent` is implemented completely. Although, since `LabelledContent` will replace the use of `Contents` for referencing purposes, not sure if this function can be removed or not yet...
***
### `makePairs`
- HTML
    - used in `lay` https://github.com/JacquesCarette/Drasil/blob/8627a38c01c5824c36d48b9df9b4b91c9f582d6d/code/Language/Drasil/HTML/Import.hs#L76-L78
    - which is used in `layout`
https://github.com/JacquesCarette/Drasil/blob/8627a38c01c5824c36d48b9df9b4b91c9f582d6d/code/Language/Drasil/HTML/Import.hs#L60-L61
   - which is not used anywhere at the moment! **so it can be removed...**
- TEX
    - no hardcoded "DD", although used by `layout`, which is used by `sec`, which is used in `createLayout`, which is used by `makeDocument`, which is not used anywhere! **so it can be removed...**
    - Tex uses the `makeDocument` discussed next
- Printing
    - no hardcoded "DD", although used by `layout` --> `sec` --> `createLayout` --> `makeDocument`, which is used by `genTeX` and `genHTML` to produe the docs
***
### `refDD`
- defined in RefHelpers.hs
- used in `modelTraceTable` https://github.com/JacquesCarette/Drasil/blob/8627a38c01c5824c36d48b9df9b4b91c9f582d6d/code/Example/Drasil/DocumentLanguage/TraceabilityMatrix.hs#L7-L12 which is not used anywhere (yet?) so **add a fixme here to remind that `refDD` should probably not be used**
- SSP/DataDefs.hs uses it in its derivation sentences https://github.com/JacquesCarette/Drasil/blob/8627a38c01c5824c36d48b9df9b4b91c9f582d6d/code/Example/Drasil/SSP/DataDefs.hs#L35-L37
- SWHS/DataDefs.hs is used to define `ddRef`, but it is not used anywhere (**so it can be removed?**)
***
### `dataDefn` `CI`
- actually not related to this issue
- used for lists of acronyms for the examples
- used to define the SRS' data defn section
- used in intros for assumptions and general definitions, etc.
***
## Proposal
For now, can I remove the code that is not used in the Tex and HTML "Import" files, linking the work to issue #714? @szymczdm 
Additionally, can the other bolded text above, also be worked on? @JacquesCarette

**Comment by szymczdm** [comment]
@niazim3 Are you sure layout isn't used in HTML import.hs? I did a grep and it shows up on line 73:

**Comment by szymczdm** [comment]
I just realized, if it's the same as the TeX one where it's used in a bunch of places and ultimately not called, then yeah, it can be removed.

**Comment by niazim3** [comment]
With the merge of #754, the only main hardcoded "DD" instance that this issue should continue to track are from `getDefName` and `refDD`.

**Comment by JacquesCarette** [comment]
I just want to double-check that the comment above (regarding the status post-merge of #754) is still accurate?  It seems like things have changed quite a bit around this area.

**Comment by JacquesCarette** [comment]
So I've checked that this is **almost** fixed.  There is still some duplication around this, but all the hard parts have been done.  Seems that there are some silly things that have arisen in the meantime that need to be dealt with.

**Comment by JacquesCarette** [comment]
This remains "almost fixed", but things have gotten a touch worse. There are now 3 occurrences of DD,  where 2 seem to be duplicates, and the third (in `sectionci`) seems just plain wrong:
```
MacBook-Air-2:code carette$ egrep -e "\"DD\"" */*/*.hs */*/*/*.hs */*/*/*/*.hs */*/*/*/*/*.hs */*/*/*/*/*/*.hs
drasil-lang/Data/Drasil/IdeaDicts.hs:dataDefn    = commonIdeaWithDict "dataDefn"    (cn' "data definition")    "DD"   [softEng]
drasil-lang/Language/Drasil/Document.hs:sectionci    = commonIdeaWithDict "sectionci"    (cn' "section")                   "DD"        [documentc]
drasil-data/Data/Drasil/Concepts/Documentation.hs:dataDefn    = commonIdeaWithDict "dataDefn"    (cn' "data definition")                             "DD"        [softEng]
```
@samm82 can you track down the uses of all 3 of the above symbols?
Also, we should do the same with TM, GD and IM too.

**Comment by samm82** [comment]
@JacquesCarette `sectionci` is never used and can be removed without consequences (yay!)

The `dataDefn` in `drasil-lang` is for use in `drasil-theory`, since it can't use the one in `drasil-data` because `-data` is dependent on `-theory`. The simplest fix would be use remove the one in `-data` and replace all instances of it from the one in `-lang` (although it seems weird to me to have a `Data` directory in the `-lang` package.)

**Comment by JacquesCarette** [comment]
Go ahead and delete `sectionci`.

The reason to have `Data.` in the `drasil-lang` package is that part of the Drasil Language is defined as "data" instead of as "code". It's as simple as that. So yes, delete the duplicate information from `drasil-data`.

**Comment by samm82** [comment]
Not a huge deal, but do you prefer `thModel` and `inModel` or `theoryMod` and `instanceMod`? @JacquesCarette

**Comment by samm82** [comment]
Also, the duplicate (that I removed) used "theoretical model" as the definition, while the other used "theory model". For now I'm going to keep it as "theoretical model" to reduce the changes to stable, but I can change it if desired.

**Comment by JacquesCarette** [comment]
I was going to say the opposite BUT I don't feel strongly about it!
