### ISSUE TITLE
GlassBR's LDF representation

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#749]
(Moved from #350)
LDF is no longer a data definition in the generated version of GlassBR, but it is still present in the caseStudies repo
![image](https://user-images.githubusercontent.com/28247301/42283299-0c6e1530-7f77-11e8-9ebf-464ebb22ec5a.png). 

What's currently generated in relation to the content in the above DD:
1. ![image](https://user-images.githubusercontent.com/28247301/42293836-ebfbc00c-7faa-11e8-9be1-e3c6eb25a62f.png) under "Values of Auxiliary Constants".
2. 
![image](https://user-images.githubusercontent.com/28247301/42293858-19df9e9e-7fab-11e8-9fed-7197eb3c62ac.png) under "Assumptions"

@smiths Which one is preferred?

**Comment by smiths** [comment]
I would like the Drasil repo to match the current case study repo for LDF.  That is, there should be a data definition for LDF.  My guess is that the modification was made in the generated version to simplify the problem.  Since LDF currently only depends on constants, LDF is also constant.  However, the constants that LDF depends on could become variables in the future.  (I think this is even listed as a likely change.)  For future maintainability, it is better if we capture this information as a data definition.

The previous version of the SRS also sent mixed messages, since LDF was also listed as a constant.  It was in as a data definition and in the table of constants.  The latest version of the SRS removes LDF from the table of constants.

**Comment by smiths** [comment]
Yes, LDF should be removed from the table of constants.  The assumption that says that LDF is constant should also be simplified.  You'll see in the case study version the formula for calculating LDF and its value are removed.  This information is redundant.

The purpose of the table of constants is to list the constants that are defined when the program starts.  LDF has a formula.  It is calculated.  We know it is constant, but we don't need to impose this information on the documentation.  We can calculate LDF.  The formula will stay the same if the other values aren't constants in the future.  In the future, Drasil will be "smart" enough to deduce when a value is constant and the generated code will take this into account.  We don't have any reason to try to optimize at the specification stage.
