### ISSUE TITLE
Recursively describe symbols that appear in a model/definition

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#751]
(Moved from #350)
The data definition for GlassBR's GTF is missing the descriptions for the elements in the mapped set in the generated version. This is the manual version 
![image](https://user-images.githubusercontent.com/28247301/42283440-7383e308-7f77-11e8-99dc-e7824c1d80de.png) and this is currently generated 
![image](https://user-images.githubusercontent.com/28247301/42283448-7964492a-7f77-11e8-9968-f08c1fd10348.png). I believe this may end up being related to the potential solution of recursively describing the symbols that appear in a model/definition (see smiths/swhs/issues/35 for that discussion).

**Comment by JacquesCarette** [comment]
I think this might be straightforward - whatever currently does the recursive traversal seems to not traverse the lhs of the case construct properly.

**Comment by smiths** [comment]
@niazim3 thank you for highlighting this.  We should definitely consider using a recursive traversal, especially if it is straightforward.  Another option to consider is to manually add a data definition for glass types.  This would give us something that we could explicitly point to for traceability.  Another option is to assume that the reader will consult elsewhere to find the meaning of AN, FT etc.  I don't like this option though because in some cases we might not include this information anywhere else.

**Comment by samm82** [comment]
A possible workaround - we could add it to the Notes section, as it seems like "additional information".

**Comment by smiths** [comment]
Adding to the notes section is a good solution for now.  We might consider the other ideas in the future, but adding to the Notes section would let the generated version match the manual version, so that we can close this issue.
