### ISSUE TITLE
Missing information in SSP from yuzhi branch 

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#756]
The descriptions with the missing information can be found at commit: c3654874044223057570967df051e04ee9e5d95b

**Comment by JacquesCarette** [comment]
Decoding what this means: the commit pointed to above has some text (in red) that disappeared from SSP. We don't want this information to disappear. Some of it is still there, just reformatted. So there is first a need to investigate exactly what disappeared. Then we can figure out which we want to have, and then we'll need to understand how/why it disappeared, before we actually implement anything.

**Comment by Awurama-N** [comment]
I think there have been quite a few changes since this commit was made, so upon investigation i have found where the deleted text is suppose to be (now shifted to different lines than when the commit was made), would you like me to go through all the red text and let you know what is still missing from this file?
and should i also add the missing text along the way or report back here first?
@JacquesCarette

**Comment by JacquesCarette** [comment]
Yes please, on finding what text is still missing. Then report here, we'll see what to do afterwards.

**Comment by Awurama-N** [comment]
There is quite a bit of text that went missing, so to avoid this being lengthy i will be sectioning my findings. This is the first part.  

- I wouldn't classify `Equation & $τ=σ \tan\left(φ'\right)+c'$` as missing because i see something similar has been placed on line 547-8.
```
Equation & \begin{displaymath}
           {τ^{\text{f}}}={σ_{N}}' \tan\left(φ'\right)+c'
```

- The following should start on line 558 but doesn't.
```
Description & For a soil under stress it will exert a shear resistive strength based on the start Coulomb sliding law. The resistive shear is the maximum amount of shear a surface can experience while remaining rigid, analogous to a maximum normal force. In this model the resistive shear stress $τ$ is proportional to the product of the normal stress on the plane $σ$ with it's static friction in the angular form $\tan\left(φ'\right)={U_{t}}$. The $τ$ versus $σ$ relationship is not truly linear, but assuming the effective normal force is strong enough, it can be approximated with a linear fit (A\ref{A:Effective-Norm-Stress-Large}) where the cohesion $c'$ represents the $τ$ intercept of the fitted line.
```
- This should be on line 718
`Equation & $S_{i}=\frac{P_{i}}{FS}=\frac{{N'}_{i} \tan\left({φ'}_{i}\right)+{c'}_{i} b_{i} \sec\left(α_{i}\right)}{FS}$`

- This should start on line 721
 ```
Description & From the definition of the factor of safety in T1, and the new definition of $P$, a new relation for the net mobile shear force of the slice $T$ is found as the resistive shear $P$ (GD3) divided by the factor of safety $FS$.
```
- This should be on line 967
`Equation & $X=λ f G$`

- This should start on line 970
```
Description & The assumption for the Morgenstern Price method (A\ref{A:Interslice-Norm-Shear-Forces-Linear}) that the interslice shear force $x$ is proportional to the interslice normal force $G$ by a proportionality constant $λ$ and a predetermined scaling function $f$, that changes the proportionality as a function of the x-ordinate position of the interslice. $f$ is typically either a half-sine along the slip surface, or a constant.
```

**Comment by JacquesCarette** [comment]
So we're going to have to pull in @smiths here. I have some vague memory that 'shear' as a concept was removed from SSP, so that a number of these things are all shear-related. So it could be that they really were meant to be removed.

For the first case: even though the equations are close, I think they are nevertheless for different quantities, so it still counts as a deletion. But it might all be purposeful deletion!

**Comment by smiths** [comment]
I have gone through the deletions highlighted by @Awurama-N.  The deletions are fine.  It is good that we have verified that we aren't removing anything that we shouldn't have.
