### ISSUE TITLE
Data Types Diagram

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#764]
This issue is similar to issue #704. However, it will involve the creation of a diagram displaying the connections between Data Types instead of Classes

**Comment by JacquesCarette** [comment]
You're going to find that the data-types are not all that 'connected' (overall), as many of them are flattened.  One of the important things to track, for each data-type, is which class they are instances of.  Since classes are transitively closed, you can indicate this via giving only the 'lowest' classes (as per the other diagram) as it implies the rest.

**Comment by JacquesCarette** [comment]
The data diagram looks fine - but is 'too small' to say much beyond that.

For `ConstrConcept`, you should link to both `Concept` and `Quantity` as neither is 'lower' than the other (where 'lower' is defined via inheritance links, not diagram position).

**Comment by elwazana** [comment]
@JacquesCarette Hello Dr. Carette, I've added onto the Data Diagram and connected `ConstrConcept` as you have requested: 
[DataDiagram.pdf](https://github.com/JacquesCarette/Drasil/files/2220328/DataDiagram.pdf)

**Comment by JacquesCarette** [comment]
Can you make the background colour of the classes different than those of the data-structures? Right now it is harder to read than is needed because of that.  For the classes, I think it would be fine to not display any of their methods.

Also, make sure all the boxes are wide enough so that there is no line-wrapping happening. That is confusing too.

**Comment by elwazana** [comment]
@JacquesCarette Is this better?
[DataDiagram.pdf](https://github.com/JacquesCarette/Drasil/files/2220755/DataDiagram.pdf)

**Comment by JacquesCarette** [comment]
Yes!  You should fix the -> (which show up with an inverted ? because of LaTeX oddities).

**Comment by elwazana** [comment]
@JacquesCarette Hello Dr. Carette, I've fixed the arrow issue you mentioned above: 
[DataDiagram.pdf](https://github.com/JacquesCarette/Drasil/files/2298488/DataDiagram.pdf)

There are still Data Types to add so I'll continue to do so, however, I going to commit this one just to have the updated diagram on Drasil.

**Comment by JacquesCarette** [comment]
Nice.  Adding all of the 'has a' links would be good - and what will require some types (such as `RelationConcept`) to be included. That will definitely give a good global picture of what's going on.
