### ISSUE TITLE
Check Symbol Implementation in Drasil

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#797]
Check implementation of Symbols in manual and drasil.  Some relevant discussion can be found in comment of commit https://github.com/JacquesCarette/Drasil/commit/363cb07cbc952e154f65173c9eb5455e4107dc41.

This is the list all the symbols has been removed:
In SWHS case:
q | Heat flux | W/m2

In SSP case:
K_no | Normal Stiffness: residual strength | Pa/m
K_tr | Shear Stiffness: residual strength | Pa/m

In NoPCM case:
C_L | Specific heat capacity of a liquid | J/(kg⋅°C)
q | Heat flux | W/m2
τ | Dummy variable for integration over time | s

In GamePhysics case:

î | Horizontal Unit Vector | m
I_k| Moment of Inertia Of the K-Th Rigid Body | kg⋅m2
J | Impulse (vector) | N⋅s
ĵ | Vertical Unit Vector | m
m_i | Mass Of the I-Th Rigid Body | kg
n | Number of particles in a rigid body
r | Distance | m
rAP | Displacement vector between the centre of mass of rigid body A and contact point P | m
rBP | Displacement vector between the centre of mass of rigid body B and contact point P | m
rkP | Displacement vector between the centre of mass of rigid body k and contact point P | m
t0 | Denotes the initial time | s

**Comment by halonazhao** [comment]
#910 GamePhysics is missing a whole section. That's why there are many symbols missing.

**Comment by JacquesCarette** [comment]
@smiths could you check whether this issue is still of concern?

**Comment by smiths** [comment]
Yes, I have verified that these problems have been fixed.  A few of the symbols, like K_no are not included, but that is because @bmaclach did a major revision to remove the finite element portion of the spec.  The game physics example also does not have all of the symbols, but the game physics example needs major revision, so changes will occur when it is revised.

We no longer need to compare to the manual versions to the generated versions.  Going forward we agreed that we will only be maintaining the Drasil versions.

We can close this issue.
