### ISSUE TITLE
Paragraph Breaks in caseStudies - GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#826]
This is an issue with multiple sections, where there is a paragraph break in caseStudies but not in Drasil.

- [x] 2 Introduction
- [x] 2.1 Purpose
- [x] 2.4 Organization of Document
- [x] ~~10 End of Traceability Matrices~~ The note was removed in Drasil.
---

Example:
![par break](https://user-images.githubusercontent.com/35857611/42580008-8474e7fe-84f7-11e8-84ed-60912ed66cc0.png)

**Comment by elwazana** [comment]
@smiths Hello Dr. Smith, I've been investigating this issue for a while now and I've noticed that the two paragraphs are defined separately, however, they are fed into a function as a `[Contents]`  and then the TeX is automatically generated and somewhere there they get weaved together. 

It is definitely somewhere in the TeX generation because the HTML looks like this: 
![image](https://user-images.githubusercontent.com/35268928/42652705-2f8d3aee-85e1-11e8-8d11-1d3f6709a117.png)

As a note, because the TeX generation is responsible for this changing it would effect all the examples not just GlassBR.

**Comment by smiths** [comment]
@elwazana, you have found a "bug" in the tex generator.  It shouldn't be collapsing paragraphs.  I'm sure you are correct that this is happening in all of the examples.  The html and the tex should have the same paragraphs.  @szymczdm do you know what is going on here?  Should we create an issue in the Drasil repo to deal with this problem?

**Comment by JacquesCarette** [comment]
There is a way to make `Paragraph`s in Drasil. Those should definitely not be collapsed together.

**Comment by samm82** [comment]
This issue has been fixed, it just hasn't been closed yet. 😂
