### ISSUE TITLE
Difference in Size of Figure in GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#836]
The size of the physical system figure is drastically different between Drasil (left) and caseStudies. Which size is preferred/is it arbitrary?

![phys sys](https://user-images.githubusercontent.com/35857611/42584950-5b5af786-8502-11e8-8bfa-040bb4894a56.png)

**Comment by smiths** [comment]
Smaller is better, especially for such a simple figure.  I believe that the Drasil version is bigger because of the need for automation and limited facilities for customization.  If you can easily address the issue so that the Drasil figure is smaller, that would be great, but we are willing to leave this kind of tweaking to the future if it isn't easy.
