### ISSUE TITLE
Input Data Constraints Table | Difference in Row Order

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#864]
- [x] Manually sort the rows in caseStudies (right)
- [x] Add a facility to sort this table in Drasil
  - Possibly add a way to sort a table by any column

![rows](https://user-images.githubusercontent.com/35857611/42646046-b4bdddfe-85cd-11e8-9ee7-a8cad162ec21.png)

**Comment by smiths** [comment]
Agreed.  The rows should be sorted alphabetically by Var symbol.  I don't think Drasil currently does this, but the functionality must be there, since the table of symbols is sorted.  Can you please create an issue in Drasil to provide a facility to sort the table.  It might be even more useful if we had a way to sort any table by selecting the column that we want to sort by.  I don't know if this is an easy request, or a major headache.

For the case study, can you please manually sort the table alphabetically.

**Comment by samm82** [comment]
While working on #886, I found the function `compsy` which sorts symbol - this just needs to be implemented here. To sort by column, a function would just need to be defined for that column and passed in to a `sortBy` function. Should I still create an issue for this? I think we should only implemented sorting functions if we think we'll want to actually have them sorted by that column

**Comment by smiths** [comment]
This sounds like a great idea to me.  Yes, please create an issue.
