### ISSUE TITLE
Data Definition auxiliary functions?

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#917]
@szymczdm @JacquesCarette 
As of issue #747, Data Definitions have there own designated data type `DataDefintion` instead of `QDefinition`.

Should these be changed to take a `DataDefinition`? 
![image](https://user-images.githubusercontent.com/35268928/42958530-c2dace52-8b53-11e8-8601-9a983fdb5182.png)

**Comment by niazim3** [comment]
After a discussion with @elwazana, the reason why this question was brought up was because `makePairs` didn't have a matching-pattern for all the `DType`s (missing `Data'`): https://github.com/JacquesCarette/Drasil/blob/fd0423c7339b6001aabdf56e19dac85803d5f457/code/drasil-lang/Language/Drasil/Document.hs#L53-L63
***
The reason why the current implementation is as follows. `ddefn'` is currently used to transform `DataDefinition`s to `Contents` for rendering
https://github.com/JacquesCarette/Drasil/blob/fd0423c7339b6001aabdf56e19dac85803d5f457/code/drasil-docLang/Drasil/DocumentLanguage/Definitions.hs#L53-L54, which shows that the `DType` that's being used is `DD`, not `Data'` from the kinds of `DType` and shows why the `Contents` being pattern-matched in the `lay` function is actually the `DefnT`, not the `Definition` kind: https://github.com/JacquesCarette/Drasil/blob/fd0423c7339b6001aabdf56e19dac85803d5f457/code/drasil-lang/Language/Drasil/Printing/Import.hs#L298-L299. Since `makePairs` isn't called by the only implementation of `DataDefinition`s (i.e. from GlassBR), no error is thrown since the `Data'` isn't matched in any case; that is, there is no implementation for `Data'`).

Looking at the fixme in line 53 of Document.hs (see permalink above), it seems that this is actually desirable, since `Data` and `Theory` should eventually be removed, which I believe will be removed once `DataDefinition`s replace the use of `QDefinition`s in the examples. (Another to do after #747 implementation).

According to the fixmes it seems that the use of `Defnt DD` instead of `Data' DataDefinition` or `Definition DType` is better. 

```Haskell
--FIXME: Remove Data and Theory from below.
-- | Types of definitions
data DType = Data QDefinition -- ^ QDefinition is the chunk with the defining 
                              -- equation used to generate the Data Definition
           | Data' DataDefinition
....
           | DD
-------------------------------------------------------------------------
-- | Types of layout objects we deal with explicitly
data Contents = ...       | Definition DType
               ...
               ---- FIXME: The above Definition will need to be removed ----
               | Defnt DType [(Identifier, [Contents])] RefAdd
```
***
@elwazana I don't think `buildEqn`/`buildDDDescription` functions for `DataDefinition` are necessary since their used only by `makePairs`, which is used in the pattern for `Definition`, which will eventually be removed.

I think that this issue can be closed. If @JacquesCarette or @szymczdm want to add or correct anything (in case I'm on the wrong track), this issue can be reopened.

**Comment by szymczdm** [comment]
@niazim3 you are entirely correct. `Definition` is archaic and should be removed. `Defnt` is the placeholder for the better way of doing things which (once `Definition` is removed) should be renamed to `Definition`.

It will be a two-step process to fix, since we'll need to ensure the removal of Definition goes smoothly, then the name change should be easy.
