### ISSUE TITLE
Look into use of `assembler`

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#927]
As mentioned in PR https://github.com/JacquesCarette/Drasil/pull/909#discussion_r203926791, GamePhysics is the only case study that relies on `assembler` to produce its sections. 

@szymczdm mentioned that "assembler was, I believe, an ambitious attempt to do things in a generalized way, but I believe using GSDSec is better for consistency".

In order to see what should be done with `assembler` (i.e. removal or propagation to other examples), need to determine the "usefulness" of `assembler`. https://github.com/JacquesCarette/Drasil/blob/6fc9813b0d4055651ab3811bcbc55a3e6d9c4dcd/code/drasil-docLang/Drasil/Sections/SolutionCharacterSpec.hs#L232-L239

**Comment by niazim3** [comment]
Noting here that @JacquesCarette mentioned in issue https://github.com/JacquesCarette/Drasil/issues/321#issuecomment-311482496 that `solChSpecF` is akin to an assembler and that `solChSpecF` will be removed with merge of #913.

**Comment by JacquesCarette** [comment]
Clearing the assignees, as it seems unlikely that they are the ones who will be doing this in the short term. This still needs done though.

**Comment by samm82** [comment]
I'm implementing the goal statements in Projectile right now, and using `assembler` requires a lot more work and more things need to be added to/built in Body. I think we'd be better off doing it through `GSDSec`, since it's consistent with how other sections are built. Unless you disagree, I think I'll implement the goal statements in Projectile without using `assembler`, then self-assign this and look into removing `assembler` in favour of `GSDSec` in GamePhysics later. @JacquesCarette

**Comment by JacquesCarette** [comment]
As far as I can tell, `GSDSec` is likely the better route anyways.

**Comment by samm82** [comment]
Separate issue for removing `assembler` (#1437).
