### ISSUE TITLE
Remove hacks from 5f117c5

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#977]
We need to remove the hacks introduced in 5f117c5ead4329b6994800d28eb07ca61b4f2ca5. As mentioned in the comments of issue #961 we need to create a less fragile method for handling section skipping.

Personally, I think the best approach is to move the extraction code up to the document language level, then we can actually skip sections by construction, as opposed to looking up the name and deciding to skip it. Though I'm not sure if there are any details I'm forgetting which could make this difficult.

A better idea would probably be to (at the docLang level) just grab the list of sections that should be parsed, then send them to the back end extract code. Then we've got reusable code and we're not exposing any additional constructors for pattern matching.

I've assigned myself and @JacquesCarette to help with the design, but I believe this issue should be owned by @halonazhao.

**Comment by halonazhao** [comment]
@szymczdm I guess this problem is the one we mentioned in group meeting. We were talking about the `Expr` or something. And we think `Expr` is kind of hack, which I didn't fully understand. And then @JacquesCarette said I did the similar hack or something to collect `sentence` or `expr`, which is not the right way to do. This part is blurry to me. Can you correct me or give me more information?

So now from my understanding by moving the extraction code up to the `document language` level means that instead of traversing the `Document.hs`, we change to traverse `DocumentLanguage.hs`, which actually means parsing `DocDesc` instead of `Document`? If we do that at Document Language Level would mean that we extract everything before everything is translated into `Document`. If so, I remember last time Dr.Carette said we need more than one `DocumentLanguage`, then once there are new structures added into DocumentLanguage, we need to change the `Extraction` method too. So it that right that either way the `Extraction` should be keeping updated when structure is changed?

**Comment by szymczdm** [comment]
I think having the extraction code work over `Document`-level structures is important for reusability. However, I think we may want to make that very simple code (ie. it does not make any decisions, just grabs the symbols from whatever we send it).

Then at the `DocumentLanguage` level, we have something that will parse the high-level `DocDesc` and ignore sections that would cause loops (AuxConstants and ToS for example). This parse function would then (essentially) need to hand over the parts we keep to the back-end extraction code.

I'm sure the implementation will be a little more complicated than what I'm describing, since it will likely need to convert from `DocDesc` to `Document` at some point, or do the conversion directly to `Section` and the like instead, but the details can be worked out as we go.

Do you see any major problems with this combined approach?

**Comment by halonazhao** [comment]
I don't see big problems. Maybe avoiding converting the same section twice would be a problem. I'll try to implement this idea. If there are any issues, we'll see.

**Comment by JacquesCarette** [comment]
I agree with @szymczdm 's general design.  If our 'input' to the document generation is now uniformly `DocDesc`, we should use that. It would actually be easier, as we won't have to skip generated sections, as they won't be there!

There should be no need to go double-generation.

**Comment by JacquesCarette** [comment]
Actually, as far as 'next' tasks go, I think this one is more important.

**Comment by halonazhao** [comment]
After thinking about this method, I think it's hard to avoid converting `DocDesc = [DocSection]` to `Document` more than once. 

Filtering out some sections at `DocDesc` level is easy, but our output document should have all the sections, which means there is no sections should be filtered out when we generate our document. 

But to get symbols from `sentences` or `expr` needs us to filter out some sections. Say we already filtered out some sections at `DocDesc` level, we eventually have to call `getDoc` to get sentences from `Document`, which needs one mote time converting from a filtered 'DocDesc' to an incomplete 'Document'. Unless we don't us `mkDoc` to convert a `DocDesc` as a whole, instead we use `mkSec` every time and finally put every piece together. But this way is sort of silly. That's the method I can come up now. Is there some ways can help avoiding converting? @JacquesCarette @szymczdm

**Comment by JacquesCarette** [comment]
What I think we meant is that you never call `mkDoc` or `mkSec` while finding symbols. You should not need to.  Yes, symbol-finding and rendering the document will each do a full pass on the `DocDesc`, that's fine.

What I want to know is, why would we need to 'make' the `Document` (or `Section` or ...) to extract the symbols? I do not think it is necessary -- but I am not certain!

**Comment by JacquesCarette** [comment]
Very good summary.

I am not sure about the re-usability of the code wrt extracting from `Document`. I don't know how much analysis we want to do on the "expanded document" (aka `Document`) versus the "document generator" (aka `DocSec`).

If we want to be paranoid (which is not a bad thing in our context), we would want to check consistency between them.

Which brings us to the task at hand: we want an automated way to grab all the symbols that will appear in a document. The reason we have to do weird things over `Document` is that this has already been processed quite a bit, and kind of implicitly assumes that we know what these symbols are (which is why we have to filter out some sections!). I conclude from that that we should grab the needed symbols from `DocSec` **without** rendering it at all. That way we can check the consistency of our rendering (including both of the generated sections).

**Comment by JacquesCarette** [comment]
Yes, I agree that you have to filter out some sections even here - but that makes sense.  Plus, in and of its own, `RefSec` doesn't have many symbols... `TUnits` and`TAandA` are representations of things that will involve lots of symbols, but in their raw form, have none.

For mass_min and mass_max, we need a better story for why they should not appear in the table. Maybe they should be. If you feel that the only way is to do something 'manually', then our explanation is not good enough [and I don't mean just our explanation to you of what we want, I mean the explanation to **ourselves** of what we want].

**Comment by JacquesCarette** [comment]
Reviewing this, it definitely looks like @halonazhao has made a lot of progress on this. I don't think this is quite finished though? [I would like to be wrong here!]

**Comment by halonazhao** [comment]
I believe this hack has been removed since we migrated the extracting structure to `DocDesc` from `Document` and those sections do not have to be manually skipped.

But another problem is that is it necessary to keep the extracting structure for `Document`, that part of codes is not being used anymore. But in case, in future, somehow we may use them. I am not sure. @JacquesCarette

**Comment by JacquesCarette** [comment]
The code for extracting structure from `Document` is obsolete, please delete it. And any support function that was only created for that.  Thanks for checking though.

**Comment by halonazhao** [comment]
This issue can be closed now. The final clean up has been made in #1041.
